### ISSUE TITLE
Question about debugging in IDE，DBLE_HOME is lakcing of configuration isolation

### ISSUE THREAD

**Issue by tankilo** [actiontech/dble#1015]
After executing `mvn clean install`, i found there are no config files such as `schema.xml` in directory `target/claases`. 
This results from the following configuration in  file `pom.xml`
```
<build>
	<!-- finalName>${artifactId}-${version}-${buildNumber}</finalName -->
	<resources>
		<resource>
			<directory>src/main/resources</directory>
			<includes>
				<include>*.dtd</include>
			</includes>
		</resource>
```

This means if  i use local config files instead of zk and i set vm options with `-DDBLE_HOME=XXXX\dble\target\classes`, i won't make the code run.

Then, i plan to decompress the dble-xxxx.tar.gz into a directory like `C:\Coding\CodeEnv\DBLE_HOME` and set vm options with `-DDBLE_HOME=C:\Coding\CodeEnv\DBLE_HOME`.

But i still get erors.
```
com.actiontech.dble.config.util.ConfigException: java.lang.IllegalArgumentException: InputStream cannot be null
	at com.actiontech.dble.config.loader.xml.XMLServerLoader.loadXml(XMLServerLoader.java:87)
	at com.actiontech.dble.config.loader.xml.XMLServerLoader.<init>(XMLServerLoader.java:46)
	at com.actiontech.dble.config.ConfigInitializer.<init>(ConfigInitializer.java:51)
	at com.actiontech.dble.config.ServerConfig.<init>(ServerConfig.java:68)
	at com.actiontech.dble.DbleServer.startup(DbleServer.java:273)
	at com.actiontech.dble.DbleStartup.main(DbleStartup.java:30)
Caused by: java.lang.IllegalArgumentException: InputStream cannot be null
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:117)
	at com.actiontech.dble.config.util.ConfigUtil.getDocument(ConfigUtil.java:93)
	at com.actiontech.dble.config.loader.xml.XMLServerLoader.loadXml(XMLServerLoader.java:83)
	... 5 more
```
I found that even DBLE_HOME is set, some code read config from classpath instead of relative positions under DBLE_HOME.

For example, com.actiontech.dble.config.loader.xml.XMLServerLoader#loadXml
```
ResourceUtil.getResourceAsStream("/server.xml");
```

I don't want to add extra claaspath when debugging code in IDEA.

And it's really annoying that the code fail to distinguish files which are really need to be read from claaspath and those ones which should be read from DBLE_HOME. This makes DBLE_HOME to be lack of isolation.

I fix this problem in my fork(https://github.com/tankilo/dble/issues/1), but it's not a good fix and may lead to some bugs due to lack of time and tests. So i just report this problem and you can determine whether to fix it or not.

**Comment by Baofengqi** [comment]
if your os is windows, you can follow steps in link to copy config files to target.
link: https://github.com/actiontech/dble/blob/master/docs/DeveloperNotice.md

**Comment by tankilo** [comment]
Thx, it works. But if i want to switch between serveral local config file set, then this way still doesn't solve the fundamental problem. If there is an easy-to-use web UI to manage data stored in zk, then the previous problem may be ignored via  switch between config in zk.

**Comment by yanhuqing666** [comment]
> Thx, it works. But if i want to switch between serveral local config file set, then this way still doesn't solve the fundamental problem. If there is an easy-to-use web UI to manage data stored in zk, then the previous problem may be ignored via switch between config in zk.

It's not the dble's core problem, we will not cost time to do this.
