### ISSUE TITLE
For zk mode,  the content of file dnindex.properties is empty after restart dble

### ISSUE THREAD

**Issue by wjl1619** [actiontech/dble#1016]
* **dble version：** 
5.6.29-dble-9.9.9.9-c3445b55c3e57110427b5b0862a56411fd9f96b7-20190221102958 
* **preconditions ：** 
1.execute dble auto_test to start dble in zk mode: 
```bash
behave -Dreinstall=true -Dis_cluster=true features/install_uninstall/install_dble_cluster.feature
```
2.make sure all the zk nodes are online

* **steps：**    
    step1.  ./zkCli.sh
    step2.   
    [zk: localhost:2181(CONNECTED) 2] ls /
    [dble, zookeeper]
    [zk: localhost:2181(CONNECTED) 3] rmr /dble
    [zk: localhost:2181(CONNECTED) 4]
    step3.  restart dble
* **expect result：**  
    1.the dnindex.properties have the correct content
* **real result：**  
    1.the content of file dnindex.properties is empty
* **supplements：**  
    1.the content before rmr /dble and restart dble is like this:
```text
       #
       # Copyright (C) 2016-2019 ActionTech.
       # License: http://www.gnu.org/licenses/gpl.html GPL version 2 or higher.
       #

       #update
       #Mon Feb 13 17:24:37 CST 2017
       localhost2=0
       localhost1=0
```

/label ~BUG

**Comment by yexiaoli88** [comment]
verified on version: 5.6.29-dble-9.9.9.9-5fef501dbaaa747cb78bc6590921455254643965-20190322093714

**Comment by yexiaoli88** [comment]
auto_test position:features/install_uninstall/single_dble_and_zk_cluster.feature #3
