### ISSUE TITLE
Get NP when global table join with nosharding table and sharding table

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#1023]
* **dble version：**  5.6.29-dble-9.9.9.9-3ad1b621f5d5773e3835389f3a66ad09b49e86bc-20190226080316
* **configs：** 

**schema.xml**  

```
<table name="t1" dataNode="dn3"/>
<table name="goods" dataNode="dn1,dn2" type="global"/>
<table name="atest" dataNode="dn3,dn4" rule="sharding-by-hash2" primaryKey="name" autoIncrement="true"/>
```

* **steps：**    
    ```
    create table goods(id int,name varchar(30));
    create table atest(id int,name varchar(30));
    create table t1(id int,name varchar(30));
    ```
    step1.  select a.id,b.id,c.id from goods a,t1 b,atest c order by a.id,c.id ;
* **expect result：**  
   get query result 
* **real result：**  
ERROR 1105 (HY000): java.lang.NullPointerException

/label ~BUG

**Comment by FlyingMao** [comment]
**verified version：** 5.6.29-dble-9.9.9.9-d395c5efe3733f839360964cf9482465e95c7236-20190227063450

**Comment by FlyingMao** [comment]
**for tester**
auto_test postion: dble/behave_dble/sqls/sqls_mixed/bugs/bug.sql(line:245)
