### ISSUE TITLE
DDLChildListener#updateMeta should not refresh meta when ddl result is failured. 

### ISSUE THREAD

**Issue by tankilo** [actiontech/dble#1038]
* **dble version：**  current master branch  Release 2.19.01.0
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```



```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  
```
mysql> create table testpppppp (id int);
Query OK, 0 rows affected (9.91 sec)

mysql> ALTER TABLE `testpppppp` ADD INDEX index_name ( `id` );
Query OK, 0 rows affected (5.95 sec)

mysql> ALTER TABLE `testpppppp` ADD INDEX index_name ( `id` );
ERROR 1061 (42000): Duplicate key name 'index_name
```
* **expect result：**  
    1. When other nodes (not the ddl sql execution node) execute com.actiontech.dble.meta.DDLChildListener#updateMeta , if remote `DDLInfo#status` is `FAILED`, local metaDataLock should be released  but no need to refresh memory metadata.
* **real result：**  
    1. metadata is refreshed when remote DDL sql failed to execute.
![image](https://user-images.githubusercontent.com/10413284/53850943-e69c8480-3ff7-11e9-952a-7889adba14f9.png)
* **supplements：**  
    1.

/label ~BUG

**Comment by yanhuqing666** [comment]
need check logic of ucore @Baofengqi

**Comment by Baofengqi** [comment]
ucore logic ok

**Comment by yexiaoli88** [comment]
tried to reproduce and got following result in 2.19.0.1:
metadata in slave nodes is not refreshed when master node executed CREATE ,DROP or TRUNCATE fail except ALTER.

**Comment by yexiaoli88** [comment]
verified on dble version version: 5.6.29-dble-9.9.9.9-ff5ffeb91d499bc7809e236b670343cfd24d58b4-20190311085428
