### ISSUE TITLE
[improve] optimize global sequence generated by timestamp

### ISSUE THREAD

**Issue by Baofengqi** [actiontech/dble#1040]
global sequence generated by timestamp has following limit:
1. generated from fixed time 2010-10-04 09:42:54
2. loop from scratch again when global sequence has reach to limit

improve:
1. make start time configurable
2. when global sequence has reach to limit, raise error

**Comment by Baofengqi** [comment]
doc updated - https://github.com/actiontech/dble-docs-cn/blob/develop/1.config_file/1.7_global_sequence/1.7.2_timestamp.md

**Comment by Baofengqi** [comment]
时间戳生成全局序列算法：
![image](https://user-images.githubusercontent.com/21034841/54263676-58eb0700-45ac-11e9-96cd-ac590c8b926d.png)

**Comment by Baofengqi** [comment]
dble中提供了一种使用zk生成全局序列的方式，其中也会涉及时间戳，但是该方式只与插入时的时间戳相关，故此种方式不需要 improve。

**Comment by FlyingMao** [comment]
**verified version：** 5.6.29-dble-9.9.9.9-e8d8c8d2b1f60e85524cb806926e8a3e0de529aa-20190320071817
