### ISSUE TITLE
load data block the NIOreactor 

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#1045]
* **dble version：**  2.19.01-release
* **configs：** 
**server.xml**  
```
<property name="processors">1</property>

```
* **steps：**    
   1. use a btrace script to block method end() of com.actiontech.dble.server.handler.ServerLoadDataInfileHandler for more than 1mins
   2. execute a load data query 
   3. open a new client try to login dble server
* **expect result：**  
    new client can login and execute new query
* **real result：**  
    new client login request would block and fail after 15s

/label ~BUG

**Comment by irene-coming** [comment]
verified on dble version:
5.6.29-dble-9.9.9.9-89ec430f46ccadc8d6f126ade4d62ada7cf440ce-20190307084418
