### ISSUE TITLE
Improve background retry policy when xa transaction fail to commit/rollback

### ISSUE THREAD

**Issue by Baofengqi** [actiontech/dble#1052]
* **dble version：**  
  2.19.01.0 or earlier

policy before improvement:

- retry infinitely in the background util commit/rollback successfully

improve:

-  add configuration to define the number of retry in server.xml (xaRetryCount)
        1. number == 0, retry infinitely 
        2. number > 0, retry number times

- when failing to retry, send a alert. Once retrying successfully,  resolve the alert

- when retry to commit/rollback xa transaction in the background
        1. add manager cmd `show @@session.xa` to view xa transtraction detail
        2. add manager cmd `kill @@xa_session id1,id2...` to kill retry

**Comment by FlyingMao** [comment]
#1069 、#1071 、 #1077 、 #1084 、 #1095 、 #1102、 #1106

**Comment by FlyingMao** [comment]
**verified version：**
5.7.13-dble-9.9.9.9-4db692bab7e885f86a5673d107a482db317d62c5-20190408053834
