### ISSUE TITLE
Refactor the cluster related part to support more clustering type

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#1055]
Dble only support ucore/zk type of clustering in old version.And it's hard for user to create a customized support.  
So we refactor the cluster related code and separate the clustering related business and connection related code.After that ,user can use a new type of  clustering just by extends AbstractClusterSender and use it with cluster="className"

**Comment by yexiaoli88** [comment]
zk cluster cases be regressed by ci autotest on dble version: 5.6.23-dble-9.9.9.9-804834f13996ceb825b95c647692dce650d14bea-20190403054824

a new issue be created on gitlab for ucore cases
