### ISSUE TITLE
Need warn，when `start time> insert time` on global sequence generated by timestamp

### ISSUE THREAD

**Issue by FlyingMao** [actiontech/dble#1063]
* **dble version：**  
5.6.29-dble-9.9.9.9-6d9aec3cbe94d2e217b42646dff266ecb7e5dfdb-20190318061530
* **preconditions ：**  
```
create table mytest_auto_test(id bigint,time char(120));
```
* **configs：** 

**schema.xml**  

```
<table name="mytest_auto_test" dataNode="dn1,dn2,dn3,dn4" rule="hash-four" primaryKey="id" autoIncrement="true"/>

```

**rule.xml**  

```


```

**server.xml**  

```


```
**sequence_time_conf.properties**
```
WORKID=01
DATAACENTERID=31
START_TIME=2030-10-01 09:42:54
````
* **steps：**    
    step1.  
```
mysql> insert into mytest_auto_test values(1);
Query OK, 1 row affected (0.02 sec)

mysql> select * from mytest_auto_test;
```
* **expect result：**  
    1. Give an error message about  `start time< insert time`
* **real result：**  
    1. 
```
mysql> select * from mytest_auto_test;
+----------------------+------+
| id                   | time |
+----------------------+------+
| -1527231444026390826 | 1    |
+----------------------+------+
1 row in set (0.01 sec)
```
* **supplements：**  
    1.

/label ~BUG

**Comment by Baofengqi** [comment]
need Confirm rationality: @FlyingMao @yanhuqing666 
1. when startTime format is incorrect, print a warning log and use default startTime 2010-10-04 09:42:54 ?
2. when startTime is over than insert time, raise error and dble can't start ?

**Comment by FlyingMao** [comment]
**verified version:** 5.6.29-dble-9.9.9.9-e8d8c8d2b1f60e85524cb806926e8a3e0de529aa-20190320071817
