### ISSUE TITLE
Now the order by XX is not working in syntax "select XX from noshard_t1 a natural right join schema2.global_4_t1 b order by a.id,b.id"

### ISSUE THREAD

**Issue by wjl1619** [actiontech/dble#1074]
* **dble version：**  
5.6.29-dble-9.9.9.9-4b64ca5325d73acc12633f9094899c5868073005-20190321063506
* **preconditions ：**  
```sql
drop table if exists noshard_t1;
drop table if exists schema2.global_4_t1;
CREATE TABLE noshard_t1(`id` int(10) unsigned NOT NULL,`t_id` int(10) unsigned NOT NULL DEFAULT '0',`name` char(120) NOT NULL DEFAULT '',`pad` int(11) NOT NULL,PRIMARY KEY (`id`),KEY `k_1` (`t_id`))DEFAULT CHARSET=UTF8;
CREATE TABLE schema2.global_4_t1(`id` int(10) unsigned NOT NULL,`o_id` int(10) unsigned NOT NULL DEFAULT '0',`name` char(120) NOT NULL DEFAULT '',`pad` int(11) NOT NULL,PRIMARY KEY (`id`),KEY `k_1` (`o_id`))DEFAULT CHARSET=UTF8;
insert into noshard_t1 values(1,1,'noshard_t1中id为1',1),(2,2,'test_2',2),(3,3,'noshard_t1中id为3',4),(4,4,'$test$4',3),(5,5,'test...5',1),(6,6,'test6',6);
insert into schema2.global_4_t1 values(1,1,'global_4_t1中id为1',1),(2,2,'test_2',2),(3,3,'global_4_t1中id为3',3),(4,4,'$order$4',4),(5,5,'order...5',1),(6,6,'test6',6);
```
* **configs：** 

**schema.xml**  

```xml
<schema name="schema1" sqlMaxLimit="100" dataNode="dn5">
</schema>
<schema name="schema2" sqlMaxLimit="100">
       <table name="global_4_t1" dataNode="dn1,dn2,dn3,dn4" type="global" />
</schema>
<dataNode name="dn1" dataHost="172.100.9.5" database="db1" />
<dataNode name="dn2" dataHost="172.100.9.6" database="db1" />
<dataNode name="dn3" dataHost="172.100.9.5" database="db2" />
<dataNode name="dn4" dataHost="172.100.9.6" database="db2" />
<dataNode name="dn5" dataHost="172.100.9.5" database="db3" />

```

* **steps：**    
    step1.  execute with the sql:
```sql
select a.id,a.t_id,a.name,a.pad,b.id,b.o_id,b.name,b.pad from noshard_t1 a natural right join schema2.global_4_t1 b order by a.id,b.id;
```
* **expect result：**  
mysql> select a.id,a.t_id,a.name,a.pad,b.id,b.o_id,b.name,b.pad from noshard_t1 a natural right join schema2.global_4_t1 b order by a.id,b.id;
+----+------+--------+-----+----+------+----------------------+-----+
| id | t_id | name   | pad | id | o_id | name                 | pad |
+----+------+--------+-----+----+------+----------------------+-----+
| NULL | NULL | NULL   | NULL |  1 |    1 | global_4_t1中id为1   |   1 |
| NULL | NULL | NULL   | NULL |  3 |    3 | global_4_t1中id为3   |   3 |
| NULL | NULL | NULL   | NULL |  4 |    4 | $order$4             |   4 |
| NULL | NULL | NULL   | NULL |  5 |    5 | order...5            |   1 |
|  2 |    2 | test_2 |   2 |  2 |    2 | test_2               |   2 |
|  6 |    6 | test6  |   6 |  6 |    6 | test6                |   6 |
+----+------+--------+-----+----+------+----------------------+-----+
6 rows in set (0.00 sec)
* **real result：**  
mysql> select a.id,a.t_id,a.name,a.pad,b.id,b.o_id,b.name,b.pad from noshard_t1 a natural right join schema2.global_4_t1 b order by a.id,b.id;
+----+------+--------+-----+----+------+----------------------+-----+
| id | t_id | name   | pad | id | o_id | name                 | pad |
+----+------+--------+-----+----+------+----------------------+-----+
| NULL | NULL | NULL   | NULL |  1 |    1 | global_4_t1中id为1   |   1 |
|  2 |    2 | test_2 |   2 |  2 |    2 | test_2               |   2 |
| NULL | NULL | NULL   | NULL |  3 |    3 | global_4_t1中id为3   |   3 |
| NULL | NULL | NULL   | NULL |  4 |    4 | $order$4             |   4 |
| NULL | NULL | NULL   | NULL |  5 |    5 | order...5            |   1 |
|  6 |    6 | test6  |   6 |  6 |    6 | test6                |   6 |
+----+------+--------+-----+----+------+----------------------+-----+
6 rows in set (0.00 sec)

* **supplements：**  
mysql> explain select a.id,a.t_id,a.name,a.pad,b.id,b.o_id,b.name,b.pad from noshard_t1 a natural right join schema2.global_4_t1 b order by a.id,b.id;
+-----------------+---------------+----------------------------------------------------------------------------------------------------------------------------+
| DATA_NODE       | TYPE          | SQL/REF                                                                                                                    |
+-----------------+---------------+----------------------------------------------------------------------------------------------------------------------------+
| dn2_0           | BASE SQL      | select `b`.`id`,`b`.`o_id`,`b`.`name`,`b`.`pad` from  `global_4_t1` `b` order by `b`.`id` ASC,`b`.`name` ASC,`b`.`pad` ASC |
| merge_1         | MERGE         | dn2_0                                                                                                                      |
| dn5_0           | BASE SQL      | select `a`.`id`,`a`.`t_id`,`a`.`name`,`a`.`pad` from  `noshard_t1` `a` order by `a`.`id` ASC,`a`.`name` ASC,`a`.`pad` ASC  |
| merge_2         | MERGE         | dn5_0                                                                                                                      |
| join_1          | JOIN          | merge_1; merge_2                                                                                                           |
| shuffle_field_1 | SHUFFLE_FIELD | join_1                                                                                                                     |
+-----------------+---------------+----------------------------------------------------------------------------------------------------------------------------+
6 rows in set (0.00 sec)

/label ~BUG
autotest located: behave_dble/sqls/sqls_mixed/select/join_global_nosharding.sql: line69

**Comment by yexiaoli88** [comment]
verified on version: 5.6.29-dble-9.9.9.9-8cd6b0feb42f7fbb72867fe9fda7f8b3da7aaa34-20190325065504
