### ISSUE TITLE
improve dble config template

### ISSUE THREAD

**Issue by Baofengqi** [actiontech/dble#1078]
* **dble version：**  
before 2.19.03.0 release
* **before improve:**  
The configuration template can only partially display the usage of the configuration.

* **improve:**  
The configuration template completely shows the usage of the configuration.

**Comment by yexiaoli88** [comment]
<alarm /> should be removed from server_template.xml

**Comment by yexiaoli88** [comment]
<table / > contains incrementColumn should be added into schema_template.xml

**Comment by yexiaoli88** [comment]
in schema_template.xml, since 1+ writeHosts are not allowed when switchType="-1", standby writeHosts should exist with Comment

**Comment by yexiaoli88** [comment]
the value of verison  in xxx_template.xml should be the same as dble' version，so 2.19.05.0 is more accurate than 2.19.03.0 during this milestone

**Comment by yexiaoli88** [comment]
verified on  version: 5.6.29-dble-9.9.9.9-f6f28409940f880019ea6c4406b65634b38d628f-20190523042605
