### ISSUE TITLE
 The network interrupt between dble and MySQL node before xa commit, the transaction lock in mysql will always exist

### ISSUE THREAD

**Issue by FlyingMao** [actiontech/dble#1084]
* **dble version：** 
 5.6.29-dble-9.9.9.9-da140223c0f8caa02b686963c5f138778a058169-20190327072228
* **preconditions ：**  
dble ip:10.186.65.63
mysql ip:10.186.65.64
```
create table sharding_4_t1(id int);
```
* **configs：** 

**schema.xml**  

```
<table name="sharding_4_t1" dataNode="dn1,dn2,dn3,dn4" rule="hash-four" />
```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  start xa
```
mysql> set xa=1;
Query OK, 0 rows affected (0.01 sec)

mysql> begin;
Query OK, 0 rows affected (0.00 sec)

mysql> insert into sharding_4_t1 values(1),(2),(3),(4);
Query OK, 4 rows affected (0.03 sec)
```
step2.  Simulate network interruption between dble and MySQL nodes
```
iptables -A INPUT -s 10.186.65.63 -j DROP
iptables -A OUTPUT -d 10.186.65.63 -j DROP
```
step3.  execute `commit` in dble
```
mysql> commit;
ERROR 2013 (HY000): Lost connection to MySQL server during query
```
step4. Recovery network
```
iptables -F
```
step5. Query whether there are outstanding transactions on the MySQL node
```
select * from information_schema.innodb_trx \G
```
* **expect result：**  
    1. There are no outstanding transactions on the mysql node
* **real result：**  
    1.
```
mysql> select * from information_schema.innodb_trx \G
*************************** 1. row ***************************
                    trx_id: 123264
                 trx_state: RUNNING
               trx_started: 2019-03-28 03:15:13
     trx_requested_lock_id: NULL
          trx_wait_started: NULL
                trx_weight: 2
       trx_mysql_thread_id: 256
                 trx_query: NULL
       trx_operation_state: NULL
         trx_tables_in_use: 0
         trx_tables_locked: 1
          trx_lock_structs: 1
     trx_lock_memory_bytes: 1136
           trx_rows_locked: 0
         trx_rows_modified: 1
   trx_concurrency_tickets: 0
       trx_isolation_level: REPEATABLE READ
         trx_unique_checks: 1
    trx_foreign_key_checks: 1
trx_last_foreign_key_error: NULL
 trx_adaptive_hash_latched: 0
 trx_adaptive_hash_timeout: 0
          trx_is_read_only: 0
trx_autocommit_non_locking: 0
*************************** 2. row ***************************
                    trx_id: 123262
                 trx_state: RUNNING
               trx_started: 2019-03-28 03:15:13
     trx_requested_lock_id: NULL
          trx_wait_started: NULL
                trx_weight: 2
       trx_mysql_thread_id: 253
                 trx_query: NULL
       trx_operation_state: NULL
         trx_tables_in_use: 0
         trx_tables_locked: 1
          trx_lock_structs: 1
     trx_lock_memory_bytes: 1136
           trx_rows_locked: 0
         trx_rows_modified: 1
   trx_concurrency_tickets: 0
       trx_isolation_level: REPEATABLE READ
         trx_unique_checks: 1
    trx_foreign_key_checks: 1
trx_last_foreign_key_error: NULL
 trx_adaptive_hash_latched: 0
 trx_adaptive_hash_timeout: 0
          trx_is_read_only: 0
trx_autocommit_non_locking: 0
2 rows in set (0.00 sec)
```
* **supplements：**  
    1.dble log：
[dble.log](https://github.com/actiontech/dble/files/3016410/dble.log)
2.Network capture results, you need to remove the .log suffix name
[target.cap.log](https://github.com/actiontech/dble/files/3016413/target.cap.log)
3. the processlist on mysql
```

mysql> show processlist;
+-----+------+--------------------+------+---------+------+----------+------------------+
| Id  | User | Host               | db   | Command | Time | State    | Info             |
+-----+------+--------------------+------+---------+------+----------+------------------+
| 272 | test | 10.186.65.63:37354 | NULL | Sleep   |   40 |          | NULL             |
| 274 | test | 10.186.65.63:37358 | db1  | Sleep   |   40 |          | NULL             |
| 275 | test | 10.186.65.63:37360 | db3  | Sleep   |   40 |          | NULL             |
| 276 | test | 10.186.65.63:37362 | db2  | Sleep   |  494 |          | NULL             |
| 277 | test | 10.186.65.63:37366 | db1  | Sleep   |   40 |          | NULL             |
| 278 | test | 10.186.65.63:37364 | db2  | Sleep   |   40 |          | NULL             |
| 279 | test | 10.186.65.63:37368 | db3  | Sleep   |   40 |          | NULL             |
| 280 | test | 10.186.65.63:37370 | db3  | Sleep   |   40 |          | NULL             |
| 281 | test | 10.186.65.63:37372 | db1  | Sleep   |  494 |          | NULL             |
| 282 | test | 127.0.0.1:48320    | NULL | Query   |    0 | starting | show processlist |
| 283 | test | 10.186.65.63:37378 | db2  | Sleep   |   40 |          | NULL             |
+-----+------+--------------------+------+---------+------+----------+------------------+
11 rows in set (0.00 sec)
```

/label ~BUG

**Comment by tankilo** [comment]
# Remaining Unfixed Problmes
I noticed that in method `com.actiontech.dble.backend.mysql.nio.handler.transaction.xa.XACommitNodesHandler#errorResponse`, the problems described in this issue have already been fixed.

![image](https://user-images.githubusercontent.com/10413284/58220354-23e3f900-7d41-11e9-8e9f-a5627ff38e61.png)

> if mysql connection holding xa transaction wasn't released, may result in ER_XAER_NOTA, so we need check xid here

But in method `com.actiontech.dble.backend.mysql.nio.handler.transaction.xa.XARollbackNodesHandler#errorResponse`, it doesn't deal with the similar scenes.
![image](https://user-images.githubusercontent.com/10413284/58220409-5130a700-7d41-11e9-97aa-3b43b375edb5.png)

When you directly execute the follwing sql through mysql in two terminals, the problem described in the issue will happen, so i think this a same problem. 
![image](https://user-images.githubusercontent.com/10413284/58220430-6dccdf00-7d41-11e9-8448-8ecc71c8834e.png)

# And it seems to be there will be more scenarios that this problem could happen
If `xa start xid` is executed and network borken with currently executing transaction in mysql not released,  other new connection to mysql will get error like `ERROR 1440 (XAE08): XAER_DUPID: The XID already exists`.  This would be a serious problems since server connection will continue to use the same xid untill you disable and enable xa transaction through 'set xa=1'.

**Comment by Baofengqi** [comment]
Dble rollback doesn't contains prepare phase, so if dble connects mysql to recover xa, there are no record.

**Comment by FlyingMao** [comment]
#1240

**Comment by FlyingMao** [comment]
**verified version：**dble-9.9.9.9-bd2c51f6d1eb7dcae815babae1378193c8966e74-20190613103752
