### ISSUE TITLE
Load data error,when `local-infile=0` in the mysql node

### ISSUE THREAD

**Issue by FlyingMao** [actiontech/dble#1085]
* **dble version：**  
5.7.13-dble-9.9.9.9-da140223c0f8caa02b686963c5f138778a058169-20190327072228
* **preconditions ：**  
1、
```
create table test(id int,c int);
```
2、Need to set `local-infile=0` in the mysql node
* **configs：** 

**schema.xml**  

```
<table name="test" dataNode="dn1,dn2,dn3,dn4"  type="global" />
```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  create test.txt in the dble directory
```
1,1
2,2
3,3
```
 step2.  execute `load data` in dble
```
load data infile "./test.txt" into table test fields terminated by ',' lines terminated by '\n';
```
* **expect result：**  
    1. executed succeed
* **real result：**  
    1.
```
mysql> load data infile "./test.txt" into table test fields terminated by ',' lines terminated by '\n';
ERROR 1148 (42000): The used command is not allowed with this MySQL version
```
* **supplements：**  
    1.mysql general log
```
2019-03-28T07:24:13.336307Z  324 Query	LOAD DATA LOCAL INFILE './test.txt' INTO TABLE test COLUMNS TERMINATED BY ',' LINES TERMINATED BY '
'
```

/label ~BUG

**Comment by yanhuqing666** [comment]
see doc https://github.com/actiontech/dble-docs-cn/blob/master/3.SQL_Syntax/3.2_DML/3.2.09_LOAD_DATA.md
