### ISSUE TITLE
Need support `' `in the `kill @@ddl_lock where schema=? and table=?`

### ISSUE THREAD

**Issue by FlyingMao** [actiontech/dble#1086]
* **dble version：**  
5.7.13-dble-9.9.9.9-da140223c0f8caa02b686963c5f138778a058169-20190327072228
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  
```
kill @@ddl_lock where schema='testdb' and table='test';
```
* **expect result：**  
    1. supported
* **real result：**  
    1.
```
mysql> kill @@ddl_lock where schema='testdb' and table='test';
ERROR 1003 (HY000): Unsupported statement
```
* **supplements：**  
    1.

/label ~BUG

**Comment by Baofengqi** [comment]
The affected statement and compatible with no apostrophe:
- show @@datanodes where schema='?' and table='?'
- show @@Algorithm where schema='?' and table='?'
- kill @@ddl_lock where schema='?' and table='?'

**Comment by FlyingMao** [comment]
**verified version：** 5.6.29-dble-9.9.9.9-4db692bab7e885f86a5673d107a482db317d62c5-20190408053834
