### ISSUE TITLE
correlated subquery in the SELECT clause will raise an error

### ISSUE THREAD

**Issue by tankilo** [actiontech/dble#1087]
* **dble version：**  
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```
<table name="TK_TEST" dataNode="dn1,dn2" rule="sharding-by-mod2" primaryKey="SUBS_ID"/>

```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
step1.  create table 
```
CREATE TABLE `TK_TEST` (
  `SUBS_ID` bigint(19) NOT NULL,
  `SENDING_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (SUBS_ID)
);
```
step2.  query
```
SELECT COUNT(*) AS TEMP2,
       (SELECT COUNT(*)
          FROM TK_TEST S
         WHERE MONTH(s.SENDING_DATE) = MONTH(t.SENDING_DATE)
       ) AS TEMP1
  FROM TK_TEST t
```

* **expect result：**  
    1. 
* **real result：**  
```
mysql> SELECT COUNT(*) AS TEMP2,
    -> (SELECT COUNT(*)
    -> FROM TK_TEST S
    -> WHERE MONTH(s.SENDING_DATE) = MONTH(t.SENDING_DATE)
    -> ) AS TEMP1
    -> FROM TK_TEST t;
ERROR 4004 (42S22): column t.SENDING_DATE not found
```
* **supplements：**  
    1.

/label ~BUG

**Comment by tankilo** [comment]
It seems that Correlated SubQuery is expected to not be supported.   
![image](https://user-images.githubusercontent.com/10413284/55323220-0b79ff80-54b1-11e9-9409-dff5ac1eb4b9.png)

![image](https://user-images.githubusercontent.com/10413284/55323256-2b112800-54b1-11e9-8d9c-891d976653d2.png)

But code only deal with scenes of `WHERE clause` and  `HAVING clause example`, but missing `SELECT clause`.

**Comment by tankilo** [comment]
I may post an PR to fix it.

**Comment by FlyingMao** [comment]
**verified version：** 5.6.29-dble-9.9.9.9-8cca170a075e66e92a06fb8d5c2fd0cfb551498c-20190402055219
