### ISSUE TITLE
tableStructureCheckTask does not work properly

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#1098]
* **dble version：**  2.19.01.0/rel
* **preconditions ：**  
no
* **configs：** 
**schema.xml**  
```
    <schema name="TESTDB" sqlMaxLimit="100" dataNode="dn1">
    	  <table name="testxxx" dataNode="dn3"/>
        <table name="test1" dataNode="dn1,dn2,dn3,dn4" rule="hash-four"/>
    </schema>
```
* **steps：**    
    + start dble with config 
    + change test1 in one of the backend node in mysql
    + tableStructureCheckTask can not find the diff of dataNodes
* **expect result：**  
     + Table [" + tableName + "] structure are not consistent in different data node!
* **real result：**  
    + Table [" + tableMeta.getTableName() + "] are modified by other,Please Check IT!

/label ~BUG

**Comment by FlyingMao** [comment]
**verified version：** dble-9.9.9.9-884bcad81c600041536445b1a068208635992813-20190415062755
