### ISSUE TITLE
Load data will skip lines which start with ‘#’

### ISSUE THREAD

**Issue by yanhuqing666** [actiontech/dble#1101]
* **dble version：**  dble-9.9.9.9-4db692bab7e885f86a5673d107a482db317d62c5-20190408053834
* **preconditions ：**  

drop table if exists sharding_two_node;
CREATE TABLE `sharding_two_node` (
  `name` varchar(15) DEFAULT NULL,
  `id` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

file： data.txt
```
#1,1
2,2
```

file： data2.txt
```
#3,3
#4,4
```

* **configs：** 

**schema.xml**  

```
<schema name="testdb" sqlMaxLimit="100">
<table name="sharding_two_node" dataNode="dn1,dn2" rule="two_node_hash"/>
</schema>
```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1. load data infile '/tmp/data.txt' into table sharding_two_node fields terminated by ',';
    step2.  load data infile '/tmp/data2.txt' into table sharding_two_node fields terminated by ',';
* **expect result：**  
    1.load two rows
    2.load two rows
* **real result：**  
    1.load only one row,skip first line
    2.load no row,skip all lines (in dble2.18.12.0,client may hang)
* **supplements：**  
    1.

/label ~BUG

**Comment by FlyingMao** [comment]
**verified version:** dble-9.9.9.9-9aa9cc36c3fe9dfa3bca49ba13dd8d55a17f18ab-20190410033617
