### ISSUE TITLE
error message should be more meaningful when dble instances are doing DDL simultaneously in one cluster

### ISSUE THREAD

**Issue by yexiaoli88** [actiontech/dble#1105]
* **dble version：2.19.01.0**
* **preconditions ：**  
```
1.two dble instances are in ucore cluster

2.btrace script on dble master instance server is as follows:

 @OnMethod(
            clazz = "com.actiontech.dble.btrace.provider.ClusterDelayProvider",
            method = "delayBeforeDdlNoticeDeleted"
    )
    public static void delayBeforeDdlNoticeDeleted(@ProbeClassName String probeClass, @ProbeMethodName String probeMethod) throws Exception {
        BTraceUtils.print("get into delayBeforeDdlNoticeDeleted ");
        BTraceUtils.print(" for order __________________________ ");
        Thread.sleep(60000l);
    }
```
**schema.xml**  
```
  <table name="test" type="global" dataNode="dn1,dn2,dn3,dn4"></table>
```

* **steps：**    
1. execute btrace script  on dble master instance server

2.execute ddl in dble master instance --hang
```
create table test (id int);
```
3.execute ddl in dble slave instance even step 2 hangs
```
mysql> alter table test add column age int;
ERROR 1064 (HY000): java.lang.Exception: The syncMeta.lock or metaLock about testdb.test in universe/dble/ushard-group/ddl/testdb.testis Exists,sql:alter table test add column age int

```
* **expect result：**  
    1.error message from step3 should change to like"schema[].table[] is doing ddl"
* **real result：**  
    1.error message from step3 is diffcult to understand
* **supplements：**  
    1.

/label ~BUG

**Comment by wjl1619** [comment]
verified on version: 5.6.29-dble-9.9.9.9-bd2c51f6d1eb7dcae815babae1378193c8966e74-20190613103752

Now the message in dble cluster is like this: 
ERROR 1064 (HY000): java.lang.Exception: The metaLock about ``schema1`.`test`` is exists. It means other instance is doing DDL.,sql:ALTER TABLE test
	ADD COLUMN age int AFTER id
