### ISSUE TITLE
table attribute type value "default" in schema.xml is illegal now

### ISSUE THREAD

**Issue by wjl1619** [actiontech/dble#1109]
* **dble version：**  
2.19.01.0-303221e9e77e00d7741629e15f8053e4fa196de3-20190228085303
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```xml
<schema name="testdb" sqlMaxLimit="100">
        <table name="test" type="default" primaryKey="id" needAddLimit="true" rule="test_database__test" dataNode="dn1,dn2"></table>
    </schema>

```

* **steps：**    
    step1.  execute the management conmmand "dryrun"
* **expect result：**  
    1.dryrun success with no warning for that
* **real result：**  
    1.WARNING | Table[test] attribute type sharding in schema.xml is illegal, use sharding replaced
-- | --

* **supplements：**  
    1.

/label ~BUG

**Comment by FlyingMao** [comment]
**verified version：** dble-9.9.9.9-2bb2c0f06a08fcf065600542f3bc39d2bba987c4-20190410054801
