### ISSUE TITLE
When the mysql node configures `local_infile = 0`, the client connects dble to execute ` load data` error.

### ISSUE THREAD

**Issue by FlyingMao** [actiontech/dble#1111]
* **dble version：**  
dble-9.9.9.9-4db692bab7e885f86a5673d107a482db317d62c5-20190408053834
* **preconditions ：**  
```
drop table if exists sharding_4_t1;
CREATE TABLE sharding_4_t1 (
name varchar(15) DEFAULT NULL,
id int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```
set global local_infile=0 on mysql nodes 
* **configs：** 

**schema.xml**  

```
<table name="sharding_4_t1" dataNode="dn1,dn2,dn3,dn4" rule="hash-four" />
```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  load data infile 'data.txt' into table sharding_4_t1 fields terminated by ',';
* **expect result：**  
    1.success
* **real result：**  
    1.
```
mysql> load data infile 'data.txt' into table sharding_4_t1 fields terminated by ',';
ERROR 1148 (42000): The used command is not allowed with this MySQL version
```
* **supplements：**  
    1. The statement actually issued by dble
```
LOAD DATA LOCAL INFILE './data.txt' INTO TABLE sharding_4_t1 COLUMNS TERMINATED BY ','
```

/label ~BUG

**Comment by yanhuqing666** [comment]
@Baofengqi need add doc

**Comment by Baofengqi** [comment]
https://github.com/actiontech/dble-docs-cn/blob/master/5.Limit/5.2_other_limit.md

**Comment by FlyingMao** [comment]
**verified version:** dble-2.19.01.0-303221e9e77e00d7741629e15f8053e4fa196de3-20190228085303
