### ISSUE TITLE
when running sysbench oltp test ,XA transaction can't restore correctly after restarting dble

### ISSUE THREAD

**Issue by kaikai2000** [actiontech/dble#1114]
* **dble version：**  
     2.19.01.0
* **preconditions ：**  
    - 1、 sudo yum install sysbench
   - 2、edit   $SYSBENCH_SCRIPT_HOME/lua-tests/db/oltp.lua ,add `db_query("set xa=1")`  below ` db_query(begin_query)`
  - 3、edit   $SYSBENCH_SCRIPT_HOME/oltp.sh， add `--mysql-ignore-errors=1205,2013,1213,1003,1062`
 - 4、edit  $SYSBENCH_SCRIPT_HOME/conf.sh, configure the correct database information

* **configs：** 

**schema.xml**  

```

<schema name="dbtest">
		<table dataNode="dn1,dn2" name="sbtest1" rule="mod2" />
   </schema>

	<dataNode name="dn1" dataHost="localhost1" database="sysbench_0" />
	<dataNode name="dn2" dataHost="localhost1" database="sysbench_1" />
```

**rule.xml**  

```
<tableRule name="mod2">
		<rule>
			<columns>id</columns>
			<algorithm>hashmod2</algorithm>
		</rule>
	</tableRule>
	<function name="hashmod2" class="Hash">
		<property name="partitionCount">2</property>
		<property name="partitionLength">1</property>
	</function>

```

**server.xml**  

```


```

* **steps：**    
    step1.   execute shell `sh oltp.sh`  on the installed sysbench machine
    step2.  restart dble when sysbench is running
    step3.  stop sysbench
    step4.  execute `xa recover` on the mysql which is used by dble 
* **expect result：**  
    1. empty result, dble can restore all not completed xa transactions.
* **real result：**  
    1. There are still some transactions that have not been released
* **supplements：**  
    1.

/label ~BUG

**Comment by kaikai2000** [comment]
### reason:

- One of the xa logs without normal restore
`{"id":"'Dble_Server.1.194'","state":"12","participants":[{"host":"10.45.61.34","port":"32305","p_state":"2","expires":0,"schema":"sysbench_0"},{"host":"10.45.61.34","port":"32305","p_state":" 3","expires":0,"schema":"sysbench_1"}]}` 

 the transation with  p_state":"3" state will be rolled back, the transation with "p_state":"2" will be ignored, but  the transation with "p_state":" 2"  is already 3  on mysql , just because dble has no time to write correct state to disk.

**Comment by Baofengqi** [comment]
In my opinion, state of participants are written to file when dble has received mysql response. Now, when you restart dble, dble miss mysql response partly,so state of  part participants are not entirely written to file.

**Comment by yanhuqing666** [comment]
@Baofengqi #1154

**Comment by kaikai2000** [comment]
@Baofengqi  @yanhuqing666  102515a With this change, there is no problem with the logic, but the performance has a big impact. If the transaction involves 10 nodes, you need to refresh 10 disks, only refresh once before modification.
