### ISSUE TITLE
Some of the SQL Method param in complexQuery must be uppercase

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#1132]
* **dble version：**  2.19.01.0/rel
* **configs：** 
**schema.xml**  
```
    	  <table name="test_a" dataNode="dn1"/>
    	  <table name="test_b" dataNode="dn2"/>
    	  <table name="test_c" dataNode="dn3"/>
```

* **steps：**    
    + execute : select  timestampdiff(hour,a.id,now()) from test_a a,test_b b where a.id = b.id ;
* **expect result：**  
    return result
* **real result：**  
    ERROR 1105 (HY000): No enum constant com.alibaba.druid.sql.ast.expr.SQLIntervalUnit.hour
* **supplements：**  
    select  timestampdiff(HOUR,a.id,now()) from test_a a,test_b b where a.id = b.id ;
     would be ok

/label ~BUG

**Comment by yexiaoli88** [comment]
verified on dble version  5.6.29-dble-9.9.9.9-2d18ed6c8dae540e4becc2ba03472b2284238f58-20190429070246

**Comment by yexiaoli88** [comment]
auto_test position: sqls/special_sharding/select/select_sharding.sql line 258-267
