### ISSUE TITLE
the dble has an error "java.io.IOException: Can't get variables from data node" When install mysql8.0

### ISSUE THREAD

**Issue by yinyanghuafa** [actiontech/dble#1134]
* **dble version：**  
dble-9.9.9.9-884fc6b612d64cc22101226536f8fd1d24580857-20190221182143
* **preconditions ：**  
```
create table if not exists company (id bigint not null auto_increment,name varchar(20) not null,address varchar(250) not null,create_time timestamp not null,owner varchar(20) not null,employees integer not null default 50,primary key(id))engine=innodb charset=utf8;
insert into company values(2,'lisi','2','2011-01-01 00:00:00','4','5');
```
* **configs：** 

**schema.xml**  

```
    <dataHost name="localhost" maxCon="1000" minCon="10" balance="0" switchType="1" slaveThreshold="100">
      <heartbeat>show slave status</heartbeat>
	  <writeHost host="hostM1" url="127.0.0.1:3306" user="root"
				 password="******">
	  </writeHost>
    </dataHost>

```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1. docker pull krutpong/mysql8.0
    step2. docker run -p 3306:3306 --name mymysql -v $PWD/conf:/etc/mysql/conf.d -v $PWD/logs:/logs 
                -v $PWD/data:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=****** -d mysql:8.0
    step3. start dble.

* **expect result：**  
    1. Server startup successfully.
* real result：  
    1. java.io.IOException: Can't get variables from data node.
    2. here are some datasource connection failed, pls check these datasource.
* **supplements：**  
    

/label ~BUG

**Comment by FlyingMao** [comment]
**verified version** dble-9.9.9.9-42aeaab7fc3d719a8e918dce18176909ed35b340-20190610120741
