### ISSUE TITLE
[improve] optimize global sequence generated by distributed timestamp

### ISSUE THREAD

**Issue by Baofengqi** [actiontech/dble#1138]
* dble version：
  2.19.03.0 or earlier
* limit：
global sequence generated by distributed timestamp generated from current time, so global sequence can use 17 years.

* improve

1. make start time configurable
2. when global sequence has reach to limit, raise error

**Comment by Baofengqi** [comment]
algorithm of global sequence generated by distributed timestamp：
![image](https://user-images.githubusercontent.com/21034841/56547307-95e4e900-65af-11e9-9472-66a15392f389.png)

**Comment by Baofengqi** [comment]
doc-it:
https://github.com/actiontech/dble-docs-cn/blob/develop/1.config_file/1.7_global_sequence/1.7.3_distribute_timestamp.md

**Comment by FlyingMao** [comment]
**verified version：** dble-9.9.9.9-8ee3c85960e48f9e6b5af5f34b26e197d87486e5-20190527034228
