### ISSUE TITLE
Global sequence error when generated by distributed timestamps

### ISSUE THREAD

**Issue by FlyingMao** [actiontech/dble#1153]
* **dble version：**  
dble-9.9.9.9-9779b4e725815cf799600bb322f29c6e9c852a1d-20190429023717
* **preconditions ：**  
```
create table mytest_auto_test(id bigint,time char(120));
```
* **configs：** 

**schema.xml**  

```
<table name="mytest_auto_test" dataNode="dn1,dn2,dn3,dn4" rule="hash-four" primaryKey="id" autoIncrement="true"/>
```

**rule.xml**  

```


```

**server.xml**  

```


```
**sequence_distributed_conf.properties**
```
INSTANCEID=zk
CLUSTERID=01
#START_TIME=2003-04-24 09:42:54
```

* **steps：**    
    step1.  
```
datestr=`date +%Y%m%d`
mysql -utest -ptest -h127.0.0.1 -P8066 -D schema1 -e"insert mytest_auto_test values('${datestr}');"
```
step2.
```
mysql> select * from mytest_auto_test;
+---------------------+----------+
| id                  | time     |
+---------------------+----------+
| 1122651967227691299 | 20190429 |
+---------------------+----------+
1 row in set (0.03 sec)
```
* **expect result：**  
    1. The time obtained by calculating the id is inconsistent with the time of insertion
* **real result：**  
    1.The time obtained by calculating the id is consistent with the insertion time
* **supplements：**  

/label ~BUG

**Comment by FlyingMao** [comment]
#1138

**Comment by Baofengqi** [comment]
need config as follows:
```
<property name="sequnceHandlerType">3</property>
```
