### ISSUE TITLE
XA Transaction failed to commit due to the previous one's remaining error message((XACommitNodesHandler)MultiNodeHandler#isFailed).

### ISSUE THREAD

**Issue by tankilo** [actiontech/dble#1156]
* **dble version：**  
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```
<table name="xa_test" dataNode="dn1,dn2" rule="sharding-by-mod2" primaryKey="ID"/>

```

**rule.xml**  

```
	<tableRule name="sharding-by-mod2">
        <rule>
            <columns>id</columns>
            <algorithm>hashmod2</algorithm>
        </rule>
    </tableRule>
    <function name="hashmod2" class="Hash">
        <property name="partitionCount">2</property>
        <property name="partitionLength">1</property>
    </function>

```

**server.xml**  

```


```
create table if not exists xa_test(id int primary key);

* **steps：**    
step1.  
```
mysql> set xa = 1;
Query OK, 0 rows affected (0.17 sec)

mysql> begin;
Query OK, 0 rows affected (0.01 sec)

mysql> INSERT INTO xa_test (id) VALUES(1),(2),(3);
Query OK, 3 rows affected (0.13 sec)

// during this step, you should kill the backend connection(for example, MySQLConnection#quit)  
// before method `XACommitNodesHandler#preparePhase` send command `XA Prepare`
mysql> commit;
ERROR 1105 (HY000): err:java.nio.channels.ClosedChannelException

mysql> rollback;
Query OK, 0 rows affected (31.72 sec)

mysql> begin;
Query OK, 0 rows affected (0.00 sec)

mysql> INSERT INTO xa_test (id) VALUES(1),(2),(3);
Query OK, 3 rows affected (0.01 sec)

mysql> commit;
Query OK, 0 rows affected (4.28 sec)

mysql> select * from xa_test;
ERROR 1003 (HY000): Transaction error, need to rollback.Reason:[err:java.nio.channels.ClosedChannelException]
```

* **expect result：**  
    1. the latter XA transaction should commit successfully.
* **real result：**  
    1. the latter XA transaction failed to commit.
* **supplements：**  
The previous XA transaction set `(XACommitNodesHandler)MultiNodeHandler#isFailed` to `true` when the connection is broken and the following XA transaction failed to reset `(XACommitNodesHandler)MultiNodeHandler#isFailed` to `false` in method `AbstractCommitNodesHandler#reset`.

`AbstractCommitNodesHandler#reset` override `MultiNodeHandler#reset`
* com.actiontech.dble.backend.mysql.nio.handler.transaction.AbstractCommitNodesHandler#reset
![image](https://user-images.githubusercontent.com/10413284/56944073-b2a39280-6b54-11e9-8abf-c190c8a52b36.png)
* com.actiontech.dble.backend.mysql.nio.handler.MultiNodeHandler#reset
![image](https://user-images.githubusercontent.com/10413284/56942473-86d0de80-6b4d-11e9-8914-354d0094d591.png)

Method `AbstractCommitNodesHandler#reset` is redundant and should be removed.   

/label ~BUG

**Comment by tankilo** [comment]
This issue is used to track the problem found in PR https://github.com/actiontech/dble/pull/1154

**Comment by FlyingMao** [comment]
**verified version：** dble-9.9.9.9-8d9e851726324cb759338b5a5ccfe75693505571-20190514084301
