### ISSUE TITLE
XACheckHandler#checkXid pass wrong parameters to SQLJob's constructor

### ISSUE THREAD

**Issue by tankilo** [actiontech/dble#1160]
* **dble version：**  
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  
![image](https://user-images.githubusercontent.com/10413284/57187618-5a89d900-6f24-11e9-9e18-28d5548c1719.png)

* **expect result：**  
    1.
* **real result：**  
    1.
* **supplements：**  
    1.

/label ~BUG

**Comment by wjl1619** [comment]
will observe on the later version continuously
