### ISSUE TITLE
When MultiNodeQueryHandler send multiple sql statements to mysql, if the middle part failed to execute,  frontend session will hang

### ISSUE THREAD

**Issue by tankilo** [actiontech/dble#1164]
* **dble version：**  
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```
<table name="xa_test" dataNode="dn1,dn2" rule="sharding-by-mod2" primaryKey="ID"/>
```

**rule.xml**  

```
<tableRule name="sharding-by-mod2">
       <rule>
           <columns>id</columns>
           <algorithm>hashmod2</algorithm>
       </rule>
</tableRule>
<function name="hashmod2" class="Hash">
       <property name="partitionCount">2</property>
       <property name="partitionLength">1</property>
</function>
```

**server.xml**  

```


```

* **steps：**    
**step1. edit com.actiontech.dble.backend.mysql.nio.MySQLConnection#synAndDoExecuteMultiNode**
![image](https://user-images.githubusercontent.com/10413284/57219392-87281880-702a-11e9-8629-a3340532615a.png)
add following code
```
xaCmd = xaCmd.replace("'", "\\'");
xaCmd = "MOCK ERROR '" + xaCmd + "'";
```
**step2. execute sql**
```
set xa = 1;
delete from xa_test;
```

* **expect result：**  
    1. sql execution returns the exepcted syntax error response
* **real result：**  
    1. cmd hang!!! 
![image](https://user-images.githubusercontent.com/10413284/57219549-03baf700-702b-11e9-919c-07921beb6c5b.png)

* **supplements：**  
    1.

/label ~BUG

**Comment by tankilo** [comment]
```

**Comment by tankilo** [comment]
In the above, i repalce `xa start` with syntax error and get wrong result, this is because mysql mix the third sql and the fourth sql. So there was only three response.

But when i replace `xa start` with [delete nonexistent table],   the above problem did happen again, session still hang.
![image](https://user-images.githubusercontent.com/10413284/57266788-17f50780-70b0-11e9-8cea-99f091709cfc.png)
![image](https://user-images.githubusercontent.com/10413284/57266809-22af9c80-70b0-11e9-9026-57367b27df07.png)

![image](https://user-images.githubusercontent.com/10413284/57266802-1e837f00-70b0-11e9-8677-00db71784e28.png)

**Comment by Baofengqi** [comment]
So the problem is known, we are going to find a good way to fix it.

**Comment by tankilo** [comment]
> So the problem is known, we are going to find a good way to fix it.

I have searched through issues yesterday and didn't find any related information. You should record problem in time next time.

**Comment by Baofengqi** [comment]
OK, thx for issue and pr. The problem is also related to https://github.com/actiontech/dble/issues/1144.

**Comment by FlyingMao** [comment]
**verified version:** dble-9.9.9.9-787ba3e240b63f85506f6d66a1d2821dbad091ae-20190531093226
