### ISSUE TITLE
MultiNodeQueryHandler#errorResponse add only one connection to errConnection list

### ISSUE THREAD

**Issue by tankilo** [actiontech/dble#1166]
* **dble version：**  
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```
<table name="xa_test" dataNode="dn1,dn2" rule="sharding-by-mod2" primaryKey="ID"/>
```

**rule.xml**  

```
<tableRule name="sharding-by-mod2">
       <rule>
           <columns>id</columns>
           <algorithm>hashmod2</algorithm>
       </rule>
</tableRule>
<function name="hashmod2" class="Hash">
       <property name="partitionCount">2</property>
       <property name="partitionLength">1</property>
</function>
```

**server.xml**  

```


```

* **steps：**    
    step1.  execute sql in mysql shell via server port
```
set xa = 1;
delete from xa_test where dbac;
```
* **expect result：**  
    1. Both datanode's corresponding backend connections are added to com.actiontech.dble.backend.mysql.nio.handler.MultiNodeQueryHandler#errConnection
* **real result：**  
    1. only one connection is added to com.actiontech.dble.backend.mysql.nio.handler.MultiNodeQueryHandler#errConnection
![image](https://user-images.githubusercontent.com/10413284/57277326-82b93980-70d6-11e9-90be-818246fbc786.png)
![image](https://user-images.githubusercontent.com/10413284/57277283-6ae1b580-70d6-11e9-9c80-8be08a1a65bd.png)
![image](https://user-images.githubusercontent.com/10413284/57277292-6f0dd300-70d6-11e9-866c-8afeeb3eebdc.png)

* **supplements：**  
    1.

/label ~BUG

**Comment by FlyingMao** [comment]
**verified version：** dble-9.9.9.9-787ba3e240b63f85506f6d66a1d2821dbad091ae-20190531093226

**Comment by FlyingMao** [comment]
### verified steps from tester：
* **dble version：**  
dble-9.9.9.9-787ba3e240b63f85506f6d66a1d2821dbad091ae-20190531093226
* **preconditions ：**  
```
create table sharding_4_t1(id int,name char);
```
* **configs：** 

**schema.xml**  

```
<schema name="schema1" sqlMaxLimit="100">
<table name="sharding_4_t1" dataNode="dn1,dn2,dn3,dn4" rule="hash-four" />
</schema>
    <dataNode name="dn1" dataHost="10.186.65.64" database="db1"/>
    <dataNode name="dn2" dataHost="10.186.65.65" database="db1"/>
    <dataNode name="dn3" dataHost="10.186.65.64" database="db2"/>
    <dataNode name="dn4" dataHost="10.186.65.65" database="db2"/>
```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
     step1. start btrace to trace the dble, BtraceXaDelay.java download here
[BtraceXaDelay.java.txt](https://github.com/actiontech/dble/files/3251584/BtraceXaDelay.java.txt)
(remove the postfix .txt by yourself)

setp2. execute xa in dble
```
mysql> set autocommit=0;
mysql> set xa=on;
mysql> insert into sharding_4_t1 values(1,1),(2,2),(3,3),(4,4);
```
step3. create xa_id with the same name in dble in two mysql nodes when btrace prints "before xa start..." 

step4. execute sql in dble on the same session as step 2 after 'insert' returning the result
```
rollback
```
step5. check the general log about mysql nodes
* **expect result：**  
    1. there are two quits in mysql general log
* **real result：**  
    1. 
* **supplements：**  
    1.


/label ~BUG
