### ISSUE TITLE
When implicit XA transaction fail to commit and is automatically rollbacked, the real error should be returned to the user instead of OK packet.

### ISSUE THREAD

**Issue by tankilo** [actiontech/dble#1170]
* **dble version：**  
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```
<table name="xa_test" dataNode="dn1,dn2" rule="sharding-by-mod2" primaryKey="ID"/>
```

**rule.xml**  

```
<tableRule name="sharding-by-mod2">
        <rule>
            <columns>id</columns>
            <algorithm>hashmod2</algorithm>
        </rule>
    </tableRule>
    <function name="hashmod2" class="Hash">
        <property name="partitionCount">2</property>
        <property name="partitionLength">1</property>
    </function>
```

**server.xml**  

```


```

# **steps：**    
## **step1.   executing following command**
```
delete from xa_test;
INSERT INTO xa_test (id) VALUES(1),(2),(3);
set xa=1;
delete from xa_test;
```

Before you execute `delete from xa_test;` the second time, set a break point in method `com.actiontech.dble.backend.mysql.nio.handler.transaction.xa.XACommitNodesHandler#preparePhase`
![image](https://user-images.githubusercontent.com/10413284/57439999-c26c5680-7279-11e9-95a1-3982c4136a88.png)

## **step2. kill connection manually to imitate the network failure**
![image](https://user-images.githubusercontent.com/10413284/57440117-ffd0e400-7279-11e9-8def-34c8ef432189.png)

## **step3 check result of the second delete statement**
![image](https://user-images.githubusercontent.com/10413284/57440261-44f51600-727a-11e9-9041-cfa339cbb89f.png)

* **expect result：**  
    1. If the implicit transaction failed to commit and is rollbacked automatically  
 (DML executed sucessfully but xa prepare run into network failure) , then error message that 【indicate the fact of auto-rollback behaviour】 and 【the real error message】 should be returned to the user.
* **real result：**  
    1. It's OK Packet...
* **supplements：**  
    1.

/label ~BUG

**Comment by tankilo** [comment]
# The cause of the problem
`XAAutoRollbackNodesHandler` extends `XARollbackNodesHandler`, in `XAAutoRollbackNodesHandler`'s constructor, the error that leads to `automatic rollback operation` is passed to `XARollbackNodesHandler#sendData`.

In `XARollbackNodesHandler#cleanAndFeedback`, when rollback opertaion executed successfully, the following logic doesn't consider the automatic rollback scene, it simplely return OK packet. In explicit transaction scene, this is reasonable, users get OK packet from their rollback statement. But in automatic rollback scene of implicit transaction scene, the error that passed via XAAutoRollbackNodesHandler's constructor should be used. l think the error bytes should be decoded using the orginal charset and words that such as 'auto rollback happend, reason: ' should be added to the beginning of `XARollbackNodesHandler#sendData`
![image](https://user-images.githubusercontent.com/10413284/57496190-39e6c800-7304-11e9-8f68-6eac8e8f5552.png)

**Comment by FlyingMao** [comment]
**verified version：** dble-9.9.9.9-3e92f5e5fde9cb9fb5b328c1d4fd2132e6232a7c-20190524070519
