### ISSUE TITLE
Discussion about the the logic of MySQLConnection#quit

### ISSUE THREAD

**Issue by tankilo** [actiontech/dble#1171]
In method `com.actiontech.dble.backend.mysql.nio.MySQLConnection#quit`, backend connection that passed through `connection-phase` will send a `QUIT` packet to mysql `asynchronouslly`. 
![image](https://user-images.githubusercontent.com/10413284/57496829-8bdd1d00-7307-11e9-8572-22d25bd5e0ae.png)
Because of `NIO` , current thread will not block and continue to close socket. If this is done before 
receiving the reponse of the `QUIT` packet, then when the latter arrvies, `java.nio.channels.ClosedChannelException` is raised.

```
java.nio.channels.ClosedChannelException
  at sun.nio.ch.SocketChannelImpl.ensureReadOpen(SocketChannelImpl.java:257)
  at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:300)
  at com.actiontech.dble.net.NIOSocketWR.asyncRead(NIOSocketWR.java:170)
  at com.actiontech.dble.net.AbstractConnection.asyncRead(AbstractConnection.java:272)
  at com.actiontech.dble.net.NIOReactor$RW.executeKeys(NIOReactor.java:119)
  at com.actiontech.dble.net.NIOReactor$RW.run(NIOReactor.java:90)
  at java.lang.Thread.run(Thread.java:748)
```

What is more serious is that `ResponseHandler#connectionError` will be invoked since `MySQLConnection#quit` doesn't clean `MySQLConnection#respHandler`.  When combined with XA transaction, in method such as `XACommitNodesHandler#errorResponse`，program will 【manually quit backend connection】 by calling `MySQLConnection#quit`. If the above asynchronous problem happend, `XACommitNodesHandler#connectionError` and `XACommitNodesHandler#connectionClose` may be invoked before the response of other datanodes' XA control statement. program will feel there is 【unexpected network failure】happened when executing XA control statement. This will cause concurrent modification of error response message and transaction state, it may lead to problems in latter XA judgement logic.
![image](https://user-images.githubusercontent.com/10413284/57497440-440bc500-730a-11e9-92be-2b06dd7b36ef.png)

![image](https://user-images.githubusercontent.com/10413284/57497955-73bbcc80-730c-11e9-90d5-62e8b415e357.png)

![image](https://user-images.githubusercontent.com/10413284/57497474-69003800-730a-11e9-82bf-2245a6e36122.png)

***
The orginal message i sent in DBLE QQ group.     
![image](https://user-images.githubusercontent.com/10413284/57497529-a95fb600-730a-11e9-8664-6bc646dcec33.png)
![image](https://user-images.githubusercontent.com/10413284/57497558-c09ea380-730a-11e9-8720-8c672907da2d.png)

**Comment by tankilo** [comment]
# Some ideas about the solution of this problem
In `com.actiontech.dble.backend.mysql.nio.MySQLConnection#quit`, I think before sending quit packet, `the previous ResponseHandler that set by users` must be cleared. Because sending quit packet is an internal phase of connection lifecycle, it should be cared only by the connection iteself instead of user's ResponseHandler.

And whether simply set ResponseHandler to null or switch to a dedicated ResponseHandler that dealing with QUIT packet, i prefer the former. Since in most cases, Quit packet will be sent successfully and we will also continue to close the socket if it's failed，i think sending quit packet should be a oneway operation.

**Comment by tankilo** [comment]
# Other risks
In method `com.actiontech.dble.backend.mysql.nio.handler.transaction.xa.XARollbackNodesHandler#rollback`, before executing `XARollbackNodesHandler#executeRollback`,    `conn.setResponseHandler(this);` will be called. This may be risky if the backend connection is manually quit before.  If simply setting ResponseHandler to `XARollbackNodesHandler`,   the reponse of the quit packet may invoked `XARollbackNodesHandler` related callbacks. 
I think a judgement condition should be added.
![image](https://user-images.githubusercontent.com/10413284/57499195-52a9aa80-7311-11e9-9d76-6ea3f2700304.png)

**Comment by sunsun314** [comment]
Need to be verified by CI & stability test

**Comment by kaikai2000** [comment]
Personal point of view, the close method can be changed to mycat native practice, without sending the quit command, directly close the socket. A lot of quit is called in XA, because the above feedback problem can be directly changed to the close method. The final result of quit and close can close the connection, the difference is that quit is elegant. I don't know if I understand it right?

**Comment by sunsun314** [comment]
The QUIT_PACKET should be sent because of https://github.com/actiontech/dble/issues/607  
Mysql would record tcp connection lost as a error .  
When the dble server need to be running in stable operation for a long time it's important not to create much error log in Mysql,especially when the backends Mysql number is quite large

**Comment by sunsun314** [comment]
reapet steps:
+ dble start with on timed jobs and  a unshard table qtest in dn4 -> db4
+ create qtest with id int,name varchar(50)
+ use a Btrace script to trace com.actiontech.dble.backend.mysql.nio.handler.SingleNodeHandler#backConnectionErr
to print the trace log  
and another trace into com.actiontech.dble.backend.mysql.nio.MySQLConnection#quit line 604
delay the thread for more than 60s
+ drop database db4 from MySQL ,and kill all the connections connected to db4 in MySQL
+ exec select * from qtest in dble
+ find log in dble execute sql err : errNo:1049 Unknown database... find the connection detail "threadId"
+ kill MySQL connction threadId in MySQL
+ see the Btrace log ,the backConnectionErr has been called  twice

**Comment by wjl1619** [comment]
will observe on the later version continuously
