### ISSUE TITLE
The way the alarm should be customized

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#1174]
Now the dble can only alarm with two ways,one for ucore(inner cluster only),other for log file.
We try to let the use can customize more ways to send the alarm message with whatever user wants.  
So we try to create a config to let the user load alarmSender,and finally finish the alarm

**Comment by sunsun314** [comment]
https://github.com/actiontech/dble-docs-cn/blob/develop/1.config_file/1.11_customized_alert/1.11_customized_alert.md

**Comment by wjl1619** [comment]
verified on version:  5.6.29-dble-9.9.9.9-67d04aa94d912fb01583096c6d8cba52f513996e-20190619021040
verified sending the alarm message by email
