### ISSUE TITLE
Imporve SetTestJob errorMsg

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#1177]
* **dble version：**  19.03/rel
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```
    <dataHost name="localhost1" maxCon="8" minCon="0" balance="0" switchType="1" slaveThreshold="100">

```

* **steps：**    
    use Mysql transaction to use all the backend MysqlConnections  
    create new client and execute set @x = 1
* **expect result：**  
    error message
* **real result：**  
    Connection close

/label ~BUG

**Comment by sunsun314** [comment]
Use a Btrace script to delay the SetTestJob#okResponse and kill the MysqlConnection would also close the frontEndConnection

**Comment by FlyingMao** [comment]
**verified version：** dble-2.19.03.0-bbc1097eae1f4e037d1aaf6bbe3d5f77de7d7c87-20190418142931
