### ISSUE TITLE
Load data will cause exception when the column content only has one '"' at the begining

### ISSUE THREAD

**Issue by ssxlulu** [actiontech/dble#1182]
* **dble version：**  2.19.03.0
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```
<?xml version="1.0"?>
<!--
  ~ Copyright (C) 2016-2019 ActionTech.
  ~ License: http://www.gnu.org/licenses/gpl.html GPL version 2 or higher.
  -->

<!DOCTYPE dble:schema SYSTEM "schema.dtd">
<dble:schema xmlns:dble="http://dble.cloud/" version="2.19.03.0">

    <schema name="TESTDB" dataNode="dn1">
        <table name="test" dataNode="dn1" type="single"/>
    </schema>
    <!-- <dataNode name="dn1$0-743" dataHost="localhost1" database="db$0-743"
        /> -->
    <dataNode name="dn1" dataHost="localhost1" database="db1"/>
    <dataHost name="localhost1" maxCon="1000" minCon="10" balance="0" switchType="1" slaveThreshold="100">
        <heartbeat>show slave status</heartbeat>
        <!-- can have multi write hosts -->
        <writeHost host="hostM1" url="localhost:3306" user="root"
                   password="123">

        </writeHost>
        <!-- <writeHost host="hostM2" url="localhost:3316" user="root" password="123456"/> -->
    </dataHost>
</dble:schema>

```

**rule.xml**  

```


```

**server.xml**  

```

<property name="maxCharsPerColumn">10</property>
```

* **steps：**    
    step1.  create table test (id int, name varchar(20));
    step2.  generate your csv file.
[csv.txt](https://github.com/actiontech/dble/files/3186748/csv.txt)
    step3. execute the command 
`load data local infile 'csv.txt' into table test character SET 'utf8' fields terminated by '|' lines terminated by '\n';`

* **expect result：**  
    1. load the data successfully
* **real result：**  
    1. cause the following exception:

![image](https://user-images.githubusercontent.com/14773179/57849286-8141ec80-780d-11e9-8b88-15cf2a758e0a.png)
    2. following is the stack:

> Hint: Number of characters processed may have exceeded limit of 10 characters per column. Use settings.setMaxCharsPerColumn(int) to define the maximum number of characters a column can have
Ensure your configuration is correct, with delimiters, quotes and escape sequences that match the input format you are trying to parse
Parser Configuration: CsvParserSettings:
	Auto configuration enabled=true
	Autodetect column delimiter=false
	Autodetect quotes=false
	Column reordering enabled=true
	Empty value=null
	Escape unquoted values=false
	Header extraction enabled=null
	Headers=null
	Ignore leading whitespaces=false
	Ignore trailing whitespaces=false
	Input buffer size=1048576
	Input reading on separate thread=true
	Keep escape sequences=false
	Keep quotes=false
	Length of content displayed on error=-1
	Line separator detection enabled=false
	Maximum number of characters per column=10
	Maximum number of columns=1017
	Normalize escaped line separators=true
	Null value=null
	Number of records to read=all
	Processor=none
	Restricting data in exceptions=false
	RowProcessor error handler=null
	Selected fields=none
	Skip empty lines=false
	Unescaped quote handling=nullFormat configuration:
	CsvFormat:
		Comment character=\0
		Field delimiter=|
		Line separator (normalized)=\n
		Line separator sequence=\n
		Quote character="
		Quote escape character=\
		Quote escape escape character=null
Internal state when error was thrown: line=2, column=1, record=0, charIndex=14, content parsed=ab
2|cde
3
	at com.univocity.parsers.common.AbstractParser.handleException(AbstractParser.java:339)
	at com.univocity.parsers.common.AbstractParser.parseNext(AbstractParser.java:475)
	at com.actiontech.dble.server.handler.ServerLoadDataInfileHandler.end(ServerLoadDataInfileHandler.java:600)
	at com.actiontech.dble.net.FrontendConnection.loadDataInfileEnd(FrontendConnection.java:293)
	at com.actiontech.dble.net.FrontendConnection$1.run(FrontendConnection.java:482)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 10
	at com.univocity.parsers.common.input.DefaultCharAppender.appendUntil(DefaultCharAppender.java:223)
	at com.univocity.parsers.csv.CsvParser.parseQuotedValue(CsvParser.java:268)
	at com.univocity.parsers.csv.CsvParser.parseRecord(CsvParser.java:119)
	at com.univocity.parsers.common.AbstractParser.parseNext(AbstractParser.java:444)
	... 6 more
 (com.actiontech.dble.net.FrontendConnection:FrontendConnection.java:295) 

* **supplements：**  
    1. when the column content only has one '"' at the begining, like the following picture shows, dble's csvpaser will process all of the content after the '"' and ignore the character '|' and '\n', so will cause the maximum number of characters exception.
![image](https://user-images.githubusercontent.com/14773179/57849510-0a592380-780e-11e9-915f-5765481a6b39.png)

/label ~BUG

**Comment by ssxlulu** [comment]
**In summary**, what causes the issue is the dble's csv parser will set the `enclosed by` character to `"` by default if we are not specified the `enclosed by` character explicitly. The commit above will resolve the problem.

**Comment by yexiaoli88** [comment]
verified on version: 5.6.29-dble-9.9.9.9-3e92f5e5fde9cb9fb5b328c1d4fd2132e6232a7c-20190524070519
