### ISSUE TITLE
 Global sequences generated by distributed timestamps may have duplicate values

### ISSUE THREAD

**Issue by FlyingMao** [actiontech/dble#1184]
* **dble version：**  
dble-9.9.9.9-04e3d94aea4a5599593604325c30e9cf21dfcf0d-20190516054617
* **preconditions ：**  
zk manages 3 dble（dble1、dble2、dble3） to form a cluster
* **configs：** 

**schema.xml**  

```
<table name="mytest_auto_test" dataNode="dn1,dn2,dn3,dn4" rule="hash-four" primaryKey="id" autoIncrement="true"/>
```

**rule.xml**  

```


```

**server.xml**  

```
<property name="sequnceHandlerType">3</property>
```
**sequence_distributed_conf.properties**
```
#
# Copyright (C) 2016-2019 ActionTech.
# License: http://www.gnu.org/licenses/gpl.html GPL version 2 or higher.
#

INSTANCEID=zk
CLUSTERID=01
#START_TIME=2010-11-04 09:42:54
```

* **steps：**    
    step1.  The time difference between the environment where dble1 and dble2 are located
    step2.  insert number into mytest_auto_test from dble1
    step3.  Convert the leader from dble1 to dble2 by restarting dble.
    step4.  insert number into mytest_auto_test from dble2
* **expect result：**  
    1. Values ​​inserted twice will not cause duplicates
* **real result：**  
    1.Two inserted values ​​may produce duplicates
* **supplements：**  
    1. The INSTANCEID of the leader in the cluster will be the same
/label ~BUG

**Comment by Baofengqi** [comment]
update doc : https://github.com/actiontech/dble-docs-cn/blob/develop/2.Function/2.2_global_sequence/2.2.3_distribute_timestamp.md

**Comment by FlyingMao** [comment]
**verified version：** dble-9.9.9.9-77a301ab1dd9a58dbf8fad345dfb2d563a54ebc8-20190905021744
