### ISSUE TITLE
Fail to recover XA Transaction on startup when xa log is not flushed and server is down

### ISSUE THREAD

**Issue by tankilo** [actiontech/dble#1192]
* **dble version：**  
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```
<table name="xa_test" dataNode="dn1,dn2" rule="sharding-by-mod2" primaryKey="ID"/>
```

**rule.xml**  

```
<tableRule name="sharding-by-mod2">
        <rule>
            <columns>id</columns>
            <algorithm>hashmod2</algorithm>
        </rule>
    </tableRule>
    <function name="hashmod2" class="Hash">
        <property name="partitionCount">2</property>
        <property name="partitionLength">1</property>
    </function>
```

**server.xml**  

```


```

* **steps：**    
## step1.  set breakpoint in method `com.actiontech.dble.backend.mysql.nio.handler.transaction.xa.XACommitNodesHandler#executeCommit`
![image](https://user-images.githubusercontent.com/10413284/58019614-84ecb080-7b38-11e9-99ce-08d9d02d7aab.png)

## step 2. executing following command via mysql shell
```
set xa=1;
delete from xa_test;
```
## step 3. when program stops at the above breakpoint, kill program 
![image](https://user-images.githubusercontent.com/10413284/58019846-1b20d680-7b39-11e9-8a90-1c13c99d745e.png)
![image](https://user-images.githubusercontent.com/10413284/58019885-2bd14c80-7b39-11e9-9f01-7da38c6f4bef.png)

```
{"id":"'Dble_Server.server_01.786'","state":"12","participants":[{"host":"localhost","port":"3306","p_state":"2","expires":0,"schema":"db2"},{"host":"localhost","port":"3306","p_state":"2","expires":0,"schema":"db1"}]}
```
## step 4. restart dble server, dble failed to recover this prepared transaction.
![image](https://user-images.githubusercontent.com/10413284/58019756-d9902b80-7b38-11e9-99bb-9c9d39e1786d.png)
![image](https://user-images.githubusercontent.com/10413284/58019984-6dfa8e00-7b39-11e9-9ebb-74239be12f91.png)

* **expect result：**  
    1. transaction should be rollback
* **real result：**  
    1. transaction is not rollbacked.

* **supplements：**  
    1.

/label ~BUG

**Comment by FlyingMao** [comment]
### Recurring steps from tester：
* **dble version：**  
dble-2.19.03.0-bbc1097eae1f4e037d1aaf6bbe3d5f77de7d7c87-20190418142931
* **preconditions ：**  
```
create table sharding_4_t1(id int,name char);
```
* **configs：** 

**schema.xml**  

```
<schema name="schema1" sqlMaxLimit="100">
<table name="sharding_4_t1" dataNode="dn1,dn2,dn3,dn4" rule="hash-four" />
</schema>
    <dataNode name="dn1" dataHost="10.186.65.64" database="db1"/>
    <dataNode name="dn2" dataHost="10.186.65.65" database="db1"/>
    <dataNode name="dn3" dataHost="10.186.65.64" database="db2"/>
    <dataNode name="dn4" dataHost="10.186.65.65" database="db2"/>
```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
     step1. start btrace to trace the dble, BtraceXaDelay.java download here
[BtraceXaDelay.java.txt](https://github.com/actiontech/dble/files/3239905/BtraceXaDelay.java.txt)
(remove the postfix .txt by yourself)

setp2. execute xa in dble
```
mysql> set autocommit=0;
mysql> set xa=on;
mysql> insert into sharding_4_t1 values(1,1),(2,2),(3,3),(4,4);
mysql> commit;
```
step3. restart dble when btrace prints "before xa prepare..." at the second time 

step4. execute sql in dble 
```
use schema1;
delete from sharding_4_t1;
```
* **expect result：**  
    1.
```
mysql> delete from sharding_4_t1;
Query OK, 0 rows affected (0.06 sec)
```
* **real result：**  
    1. hang when execute `delete from sharding_4_t1` in dble
* **supplements：**  
    1.


/label ~BUG

**Comment by FlyingMao** [comment]
**verified version：** dble-9.9.9.9-c5a6bb17a1c8cd191894a01046c0d7c13c6740e4-20190531030545
