### ISSUE TITLE
？？？？？？？？？？？？？

### ISSUE THREAD

**Issue by daweifly1** [actiontech/dble#1201]
root@node2 logs]# tail -100f wrapper.log 
STATUS | wrapper  | 2019/05/23 15:01:26 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2019/05/23 15:01:26 | Launching a JVM...
INFO   | jvm 1    | 2019/05/23 15:01:31 | Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
INFO   | jvm 1    | 2019/05/23 15:01:31 |   Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.
INFO   | jvm 1    | 2019/05/23 15:01:31 | 
ERROR  | wrapper  | 2019/05/23 15:01:43 | JVM exited unexpectedly.
STATUS | wrapper  | 2019/05/23 15:01:44 | JVM exited in response to signal SIGKILL (9).
STATUS | wrapper  | 2019/05/23 15:01:48 | Launching a JVM...
INFO   | jvm 2    | 2019/05/23 15:01:58 | Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
INFO   | jvm 2    | 2019/05/23 15:01:58 |   Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.
INFO   | jvm 2    | 2019/05/23 15:01:58 | 
ERROR  | wrapper  | 2019/05/23 15:02:03 | JVM exited unexpectedly.
STATUS | wrapper  | 2019/05/23 15:02:03 | JVM exited in response to signal SIGKILL (9).
STATUS | wrapper  | 2019/05/23 15:02:08 | Launching a JVM...
INFO   | jvm 3    | 2019/05/23 15:02:20 | Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
INFO   | jvm 3    | 2019/05/23 15:02:20 |   Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.
INFO   | jvm 3    | 2019/05/23 15:02:20 | 
ERROR  | wrapper  | 2019/05/23 15:02:24 | JVM exited unexpectedly.
STATUS | wrapper  | 2019/05/23 15:02:24 | JVM exited in response to signal SIGKILL (9).
STATUS | wrapper  | 2019/05/23 15:02:28 | Launching a JVM...
INFO   | jvm 4    | 2019/05/23 15:02:47 | Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
INFO   | jvm 4    | 2019/05/23 15:02:47 |   Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.
INFO   | jvm 4    | 2019/05/23 15:02:47 | 
ERROR  | wrapper  | 2019/05/23 15:03:01 | JVM exited unexpectedly.
STATUS | wrapper  | 2019/05/23 15:03:03 | JVM exited in response to signal SIGKILL (9).
STATUS | wrapper  | 2019/05/23 15:03:07 | Launching a JVM...
INFO   | jvm 5    | 2019/05/23 15:03:17 | Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
INFO   | jvm 5    | 2019/05/23 15:03:17 |   Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.
INFO   | jvm 5    | 2019/05/23 15:03:17 | 
ERROR  | wrapper  | 2019/05/23 15:03:26 | JVM exited unexpectedly.
STATUS | wrapper  | 2019/05/23 15:03:28 | JVM exited in response to signal SIGKILL (9).
FATAL  | wrapper  | 2019/05/23 15:03:28 | There were 5 failed launches in a row, each lasting less than 300 seconds.  Giving up.
FATAL  | wrapper  | 2019/05/23 15:03:28 |   There may be a configuration problem: please check the logs.
STATUS | wrapper  | 2019/05/23 15:03:28 | <-- Wrapper Stopped

**Comment by yanhuqing666** [comment]
Close it for Invalid title until @daweifly1  change it。
