### ISSUE TITLE
[Improve]dble don't limit the number of user frontend connection by default

### ISSUE THREAD

**Issue by Baofengqi** [actiontech/dble#1218]
* **2.19.03.0 or earlier version：** 
dble limit the number of user frontend connection to 1024 by default
* **inprove：** 
dble don't limit the number of user frontend connection by default
* **config：** 
server.xml
```
<property name="maxCon">0</property>
```

**Comment by Baofengqi** [comment]
doc-it:
https://github.com/actiontech/dble-docs-cn/blob/develop/1.config_file/1.03_server.xml.md

**Comment by wjl1619** [comment]
verified on version: 5.6.29-dble-9.9.9.9-bd2c51f6d1eb7dcae815babae1378193c8966e74-20190613103752
