### ISSUE TITLE
  When there is a case in the field, Join returns null, missing result set

### ISSUE THREAD

**Issue by kaikai2000** [actiontech/dble#1229]
* **dble version：*dble-9.9.9.9-2bafab5013f4caaf8d8d76622eafe9f155a89aac-20190610085314*  
* **preconditions ：**  
MYSQL fields are not case sensitive
![image](https://user-images.githubusercontent.com/73138/59250293-74bc8280-8c59-11e9-9778-d20cd9836db8.png)

* **configs：** 

**schema.xml**  

```
        <table name="uos_page_ret_inst" dataNode="dn4" />
        <table name="uos_tache_def" dataNode="dn3" />

```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  create table and import data by executing [sql.zip](https://github.com/actiontech/dble/files/3275088/sql.zip)

  step2. on the navicat, execute sql:
   

> select 
> INST.TACHE_CODE,
> def.TACHE_CODE
> from uos_page_ret_inst INST
>  JOIN uos_tache_def def
> ON  def.TACHE_CODE=INST.TACHE_CODE

* **expect result：**  
    1.
![image](https://user-images.githubusercontent.com/73138/59250168-11325500-8c59-11e9-9ecb-30cf4eb75ef2.png)

* **real result：**  
    1.
![image](https://user-images.githubusercontent.com/73138/59250136-fc55c180-8c58-11e9-9bce-e087d231ada8.png)

* **supplements：**  
    1.

**Comment by kaikai2000** [comment]
The cause of the problem, mysql is not case sensitive, the order by join field lowercase letters will appear in front of the uppercase letters, but the cross-database query uses the ASCII comparison of characters, these two logics are a bit not right。
- join code location:rc\main\java\com\actiontech\dble\backend\mysql\nio\handler\query\impl\join\JoinHandler.java
` protected void ownThreadJob(Object... objects) `
- compare value code:
 ` private static class CompareBinaryString implements ArgCmpFunc {

        @Override
        public int compare(ArgComparator ac) {
            String res1, res2;
            if ((res1 = ac.a.valStr()) != null) {
                if ((res2 = ac.b.valStr()) != null) {
                    if (ac.setNull && ac.owner != null)
                        ac.owner.setNullValue((false));
                    byte[] res1b = res1.getBytes();
                    byte[] res2b = res2.getBytes();
                    int res1Len = res1b.length;
                    int res2Len = res2b.length;
                    int cmp = MySQLcom.memcmp(res1b, res2b, Math.min(res1Len, res2Len));
                    return cmp != 0 ? cmp : res1Len - res2Len;
                }`

**Comment by sunsun314** [comment]
This case may more complex than what it looks like  
"mysql is not case sensitive" this word is not accurate，because when the COLLATE of CHARACTER  changes the behave of mysql would change as well.  
e. g.  
 CHARACTER SET utf8 COLLATE utf8_general_ci is not case sensitive  
 CHARACTER SET utf8 COLLATE utf8_bin is case sensitive

**Comment by irene-coming** [comment]
to fix:
- [ ] in the compare function, lack judgement for case_sensitive setting
- [ ] collation choice effects join result. Collation logic in MySQL is hardcode, if dble wants to support original MySQL collation, the workload is very heavy, in thinking...

**Comment by wjl1619** [comment]
verified on version: 5.6.29-dble-9.9.9.9-03f8bc17bae75327030bfc67d0ab359e8e01ff55-20190902092338
