### ISSUE TITLE
pma can not connect to dble

### ISSUE THREAD

**Issue by lirulei** [actiontech/dble#1239]
* **dble version：all
* **preconditions ：**  
phpMyAdmin all versions
* **configs：** 

**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.   pma config add dble connections
    step2.   through pma to search dble's resultset
* **expect result：**  
    1.
* **real result：**  
    1.
* **supplements：**  
    1.dble logs as follow:
2019-06-17 10:45:18.401  INFO [BusinessExecutor6] (com.actiontech.dble.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:62)) - There is an error you may need know.
java.lang.RuntimeException: schema information_schema is not exists!

**Comment by yanhuqing666** [comment]
Can you use PMA to connect MySQL which setting with Query "set global general_log =on;"?
Paste the MySQL  general_log  will easy for us to find the unsupported query from PMA.

**Comment by wjl1619** [comment]
This is the general log to connect MySQL: 
[mysql.log](https://github.com/actiontech/dble/files/3445627/mysql.log)
In this log, I found dble got error for executing the statement below:
mysql> SELECT 1 FROM (SELECT `GRANTEE`, `IS_GRANTABLE` FROM `INFORMATION_SCHEMA`.`COLUMN_PRIVILEGES` UNION SELECT `GRANTEE`, `IS_GRANTABLE` FROM `INFORMATION_SCHEMA`.`TABLE_PRIVILEGES` UNION SELECT `GRANTEE`, `IS_GRANTABLE` FROM `INFORMATION_SCHEMA`.`SCHEMA_PRIVILEGES` UNION SELECT `GRANTEE`, `IS_GRANTABLE` FROM `INFORMATION_SCHEMA`.`USER_PRIVILEGES`) t WHERE `IS_GRANTABLE` = 'YES' AND '''test''@''%''' LIKE `GRANTEE` LIMIT 1;
ERROR 1105 (HY000): schema INFORMATION_SCHEMA doesn't exist!
mysql> explain SELECT 1 FROM (SELECT `GRANTEE`, `IS_GRANTABLE` FROM `INFORMATION_SCHEMA`.`COLUMN_PRIVILEGES` UNION SELECT `GRANTEE`, `IS_GRANTABLE` FROM `INFORMATION_SCHEMMA`.`TABLE_PRIVILEGES` UNION SELECT `GRANTEE`, `IS_GRANTABLE` FROM `INFORMATION_SCHEMA`.`SCHEMA_PRIVILEGES` UNION SELECT `GRANTEE`, `IS_GRANTABLE` FROM `INFORMATION_SCHEMAA`.`USER_PRIVILEGES`) t WHERE `IS_GRANTABLE` = 'YES' AND '''test''@''%''' LIKE `GRANTEE` LIMIT 1;
ERROR 1105 (HY000): schema INFORMATION_SCHEMA doesn't exist!

**Comment by yanhuqing666** [comment]
delay to next version

**Comment by Baofengqi** [comment]
pma get schema infos by mysql information_schema, but dble fake empty result of information_schema info:
1. SELECT `SCHEMA_NAME` FROM `INFORMATION_SCHEMA`.`SCHEMATA`;
2. SELECT *,CAST(BIN_NAME AS CHAR CHARACTER SET utf8) AS SCHEMA_NAME FROM (SELECT BINARY s.SCHEMA_NAME AS BIN_NAME,s.DEFAULT_COLLATION_NAME FROM `information_schema`.SCHEMATA s GROUP BY BINARY s.SCHEMA_NAME, s.DEFAULT_COLLATION_NAME ORDER BY BINARY `SCHEMA_NAME` ASC) a;

**Comment by wjl1619** [comment]
verified on version: 5.6.29-dble-9.9.9.9-4a1798f8927fa77cef643523b5451807fe469989-20191008111520
