### ISSUE TITLE
`Explain` the child table in the er table, the statement is actually executed

### ISSUE THREAD

**Issue by FlyingMao** [actiontech/dble#1251]
* **dble version：**  
dble-9.9.9.9-16ae8083a9edeb67ab102cded51446e27d7ee2f5-20190628070902
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```
<table name="tb_parent" dataNode="dn1,dn2" rule="hash-two">
<childTable name="tb_child1" joinKey="child1_id" parentKey="pad"/>
</table>
```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  
```
mysql> create table tb_parent(id int,pad int);
Query OK, 0 rows affected (0.33 sec)

mysql> create table tb_child1(id int,child1_id int);
Query OK, 0 rows affected (0.02 sec)

mysql> insert into tb_parent values(1,1);
Query OK, 1 row affected (0.01 sec)

mysql> explain insert into tb_child1 values(1,1);
Query OK, 1 row affected (0.06 sec)

mysql> select * from tb_child1;
+------+-----------+
| id   | child1_id |
+------+-----------+
|    1 |         1 |
+------+-----------+
1 row in set (0.01 sec)
```
* **expect result：**  
    1. `tb_child1` table contents are empty
* **real result：**  
    1. The data was successfully inserted into the `tb_child1`
* **supplements：**  
    1.

**Comment by wjl1619** [comment]
verified on version: 5.6.29-dble-9.9.9.9-3973be7c76d1c0fc2f285a75c4218c27e57febe2-20190725053413
