### ISSUE TITLE
Error when execute ‘select test1.id,test1.id+1 as `rpda_0` from test1 order by `rpda_0` ASC’

### ISSUE THREAD

**Issue by newskyddm** [actiontech/dble#1256]
* **dble version：**  2.19.05.0
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  
    <schema name="TESTDB" dataNode="dn1">

        <table name="test1" dataNode="dn1,dn2,dn3,dn4" rule="sharding-by-mod4"/>
```


```

**rule.xml**  

```
    <tableRule name="sharding-by-mod4">
        <rule>
            <columns>id</columns>
            <algorithm>hashmod4</algorithm>
        </rule>
    </tableRule>
    <function name="hashmod4" class="Hash">
        <property name="partitionCount">4</property>
        <property name="partitionLength">1</property>
    </function>

```

**server.xml**  

```


```

* **steps：**    
    step1.  execute sql using mysql client

select test1.id,test1.id+1 as `rpda_0` from test1 order by `rpda_0` ASC

* **expect result：**  
    1. successfully

* **real result：**  
    1.
mysql> select test1.id,test1.id+1 as `rpda_0` from test1 order by `rpda_0` ASC;
ERROR 4004 (42S22): column rpda_0 not found

* **supplements：**  
    1. explain result
mysql> explain select test1.id,test1.id+1 as `rpda_0` from test1 order by `rpda_0` ASC;
ERROR 1105 (HY000): column rpda_0 not found
mysql> 

2、dble log
dble log file has no error info

**Comment by wjl1619** [comment]
verified on version: 5.6.29-dble-9.9.9.9-3973be7c76d1c0fc2f285a75c4218c27e57febe2-20190725053413
