### ISSUE TITLE
Refactoring attribute  'version' in xml config

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#1260]
We add `version` attribute in both rule/schema/server.xml to clearly configuration version, but the `version` it self is not fit for the actual scenes to be used.  
So we decide to change the version into a more actual rule:  
+ change version into a case of ```X.Y``` the ```XY``` as a integer (e.g.  1.16)
+ X change only when the xml structure has changed.Such as delete some part of the config from dtd,add/delete/update some required field of the config in dtd.
+ Y change only when the xml structure changed with part compatibility.Such as add/delete/update none required field of the config in dtd or delete/update some properties

The ```X.Y``` will be started with ```1.0``` it may cause compatibility problem .  
Dry-run will check the version of the xml,and return ERROR/WARNING/NOTICE by rule below:
+ X not fit - WARNNING - the config may outdate and cause some problem
+ Y not fit - NOTICE - the config may outdate but is't OK

**Comment by Lordess** [comment]
Frankly, I DO NOT want `version`.

I work on providing technical support of MySQL and its related stuff including dble. And I find it difficult to explain why they should pay attention to `version` to my end users.

The `version` is no more than a self declaration. Careless users would make their XMLs incorrect( e.g. a misspelled attribute or property ), even if they give the right `version` in it. Besides, dble itself could not rely on `version` completely. Both DTD based checking and element checking during loading xml are necessary as well as nowadays.

Overall, for my role, `version` is not useful, but will increase my comminucation cost. Hope you guys WON'T add it.

**Comment by sunsun314** [comment]
Well,after a long discussion,we decide to change the version attribute into totally optional object.  
Just check the version when user set it into the xml.If not dble will ignore the version check

**Comment by FlyingMao** [comment]
**verified version：** dble-9.9.9.9-0d3c776cbd7993a4287108af0ac140be4693ca58-20190820021310
