### ISSUE TITLE
got error while checking multi-query functionality by using c_api

### ISSUE THREAD

**Issue by wjl1619** [actiontech/dble#1269]
* **dble version：**  
5.6.29-dble-9.9.9.9-8fb726b120caf25a44f7c9d8d2b7cd0dab249dc0-20190717054448
* **preconditions ：**  
1.change the file "c_mysql_api.cpp" to run with the below two api cases only:
```
#include "c_mysql_api.h"
#include "prepare_util.h"
//usage:
//c_mysql_api.o {centos6|centos7}
//c_mysql_api.o {centos6|centos7} debug

int main(int argc, char *argv[]) {
//	IS_DEBUG = argc==1 && strcmp(argv[1],"debug")==0;
	printf("IS_DEBUG: %d, argc:%d, argv[1]:%s\n", IS_DEBUG, argc, argv[2]);

//    config("../../sys.config", sys);
    MYSQL* conn = getConn();


    case_mysql_real_query(conn);
    case_mysql_row_seek(conn); 

    cout << "!!!Test Over!!!" << endl;
    return 0;
}
```

https://github.com/actiontech/dble-test-suite/blob/master/drivers/c_mysql_api/src/mysql_real_query.cpp
https://github.com/actiontech/dble-test-suite/blob/master/drivers/c_mysql_api/src/mysql_row_seek.cpp

* **configs：** 

**schema.xml**  

```xml
       <schema name="schema1" sqlMaxLimit="100" dataNode="dn5">
                <table name="sharding_4_t1" dataNode="dn1,dn2,dn3,dn4" rule="hash-four" />
        </schema>
```

* **steps：**    
    step1.  execute with the command "bash c_mysql_api.sh" 
    step2. check the output file “curr.output”
* **expect result：**  
    1.excute success with no error
* **real result：**  
    1.excute failed with the error message "SCHEMA[schema1], TABLE[sharding_4_t1] is doing DDL" in file curr.output
* **supplements：**  
    1.

**Comment by wjl1619** [comment]
The following two files were captured by using tcpdump, please rename the file c_api_dble.log to c_api_dble.cap and the file c_api_mysql.log to c_api_mysql.cap:
[c_api_dble.log](https://github.com/actiontech/dble/files/3415721/c_api_dble.log)
[c_api_mysql.log](https://github.com/actiontech/dble/files/3415723/c_api_mysql.log)

**Comment by sunsun314** [comment]
The packet shows that the real TCP packet is not like the code shows  
The client creates 2 connections and sends different queries at the same time

**Comment by wjl1619** [comment]
verified on version: 5.6.29-dble-9.9.9.9-049081ded5dd499363390bcefac071394afa9f9a-20191009092028

amend the case of testing mysql_real_query()
