### ISSUE TITLE
 The information of `useOldMetaInit` is missing in `show @@ sysparam`

### ISSUE THREAD

**Issue by FlyingMao** [actiontech/dble#1272]
* **dble version：**  
dble-9.9.9.9-a2bd0212a1ae83f36d88d4775b1ad8321dc51075-20190719082946
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  execute `show @@sysparam;` in dble manager port
```
mysql> show @@sysparam;
```
* **expect result：**  
    1. Has the information about `useOldMetaInit`
* **real result：**  
    1.Missing information about `useOldMetaInit`
* **supplements：**  
    1.

**Comment by yanhuqing666** [comment]
removed

**Comment by FlyingMao** [comment]
**verified version：** dble-9.9.9.9-c48f02a2b60ed1e192657368bddc1fe1629b4a59-20190829074556
