### ISSUE TITLE
manager user can login server port 

### ISSUE THREAD

**Issue by CrookedPotato** [actiontech/dble#1277]
* **dble version：**  
Server version: 5.6.29-dble-2.19.03.0-bbc1097eae1f4e037d1aaf6bbe3d5f77de7d7c87-20190418142931 dble Server (ActionTech)
* **preconditions ：**  
no
* **configs：** 
**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```
<!DOCTYPE dble:server SYSTEM "server.dtd">
<dble:server xmlns:dble="http://dble.cloud/" version="2.19.03.0">
    <system>
        <property name="serverPort">8666</property>
        <property name="managerPort">9666</property>
        <property name="sequnceHandlerType">2</property>
        <property name="serverBacklog">2048</property>
        <property name="checkTableConsistency">0</property>
        <property name="checkTableConsistencyPeriod">60000</property>
        <property name="useGlobleTableCheck">1</property>
        <property name="glableTableCheckPeriod">86400000</property>
        <property name="dataNodeIdleCheckPeriod">300000</property>
        <property name="dataNodeHeartbeatPeriod">10000</property>
        <property name="processorCheckPeriod">1000</property>
        <property name="sqlExecuteTimeout">300</property>
        <property name="idleTimeout">1800000</property>
        <property name="recordTxn">0</property>
        <property name="xaSessionCheckPeriod">1000</property>
        <property name="xaLogCleanPeriod">1000</property>
        <property name="useJoinStrategy">true</property>
        <property name="nestLoopConnSize">4</property>
        <property name="nestLoopRowsSize">2000</property>
        <property name="otherMemSize">4</property>
        <property name="orderMemSize">4</property>
        <property name="joinMemSize">4</property>
        <property name="bufferPoolChunkSize">4096</property>
        <property name="bufferPoolPageNumber">512</property>
        <property name="bufferPoolPageSize">2097152</property>
        <property name="useSqlStat">0</property>
        <property name="enableSlowLog">1</property>
        <property name="slowLogBaseDir">./slowlogs</property>
        <property name="slowLogBaseName">slow-query</property>
        <property name="flushSlowLogPeriod">1</property>
        <property name="flushSlowLogSize">1000</property>
        <property name="sqlSlowTime">3000</property>
    </system>
    <firewall/>
    <user name="root_">
        <property name="password">654321</property>
        <property name="manager">true</property>
    </user>
    <user name="root">
        <property name="password">123456</property>
        <property name="schemas">ppp,xa_test</property>
    </user>
</dble:server>
```

* **steps：**    
    step1.  
[root@mysql-ecs conf]#  mysql -u root_ -p654321 -P 8666 -h 172.17.170.69
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 6604556
Server version: 5.6.29-dble-2.19.03.0-bbc1097eae1f4e037d1aaf6bbe3d5f77de7d7c87-20190418142931 dble Server (ActionTech)

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MySQL [(none)]> show databases;
+-----------------+
| DATABASE        |
+-----------------+
| ppp |
| xa_test         |
+-----------------+
2 rows in set (0.00 sec)

MySQL [(none)]> use moka_production;
Database changed
MySQL [ppp]> show tables;
ERROR 1044 (42000): Access denied for user 'root_' to database 'ppp'
MySQL [ppp]> show tables;
ERROR 1044 (42000): Access denied for user 'root_' to database 'ppp'
* **expect result：**  
    1.
* **real result：**  
    1.As above
manager user can login server port;

* **supplements：**  
    1.

**Comment by wjl1619** [comment]
verified on version: 5.7.13-dble-9.9.9.9-6292d58e0be9e6867efa84b8159371d27e1fe1b3-20190925075738
