### ISSUE TITLE
For sharding table, "select id from test1 union SELECT ROW_COUNT()" will return an unstable ResultSet

### ISSUE THREAD

**Issue by wjl1619** [actiontech/dble#1287]
* **dble version：**  
5.6.29-dble-9.9.9.9-3973be7c76d1c0fc2f285a75c4218c27e57febe2-20190725053413
* **preconditions ：**  
```sql
drop table if exists  test1;
CREATE TABLE  test1(`id` int(10) unsigned NOT NULL,`k` int(10) unsigned NOT NULL DEFAULT '0',`c` char(120),`pad` int(11) NOT NULL,PRIMARY KEY (`id`),UNIQUE KEY (`k`))DEFAULT CHARSET=UTF8;
insert into  test1 values(1,1,'id1',1),(2,2,'id2',2),(3,3,'id3',3),(4,4,'id4',4),(5,5,'id5',1),(6,6,'id6',2),(7,7,'id7',3),(8,8,'$id8$',4),(9,9,'test',3),(10,10,'中',3),(11,11,'i_',4),(12,12,'_g',5),(13,13,'y_u',6),(14,14,'20%',14),(15,15,'a_1',15),(16,16,16,-1),(0,0,0,0),(17,17,'new*\n*line',17),(18,18,'a',18);
insert into  test1(id,k,pad) values(19,19,19);
select id from  test1 union SELECT USER();
select id from  test1 union SELECT LAST_INSERT_id();
```
* **configs：** 

**schema.xml**  

```xml
<schema name="schema1" sqlMaxLimit="100" dataNode="dn5">
		<table name="test1" dataNode="dn1,dn2,dn3,dn4" rule="hash-four" />
</schema>

```

* **steps：**    
    step1.  execute the sql:
```sql
select id from  test1 union SELECT ROW_COUNT();
```
* **expect result：**  
    1.mysql> select id from  test1 union SELECT ROW_COUNT();
+----+
| id |
+----+
|  0 |
|  1 |
|  2 |
|  3 |
|  4 |
|  5 |
|  6 |
|  7 |
|  8 |
|  9 |
| 10 |
| 11 |
| 12 |
| 13 |
| 14 |
| 15 |
| 16 |
| 17 |
| 18 |
| 19 |
+----+
20 rows in set (0.00 sec)

* **real result：**  
    1.mysql> select id from  test1 union SELECT ROW_COUNT();
+----+
| id |
+----+
| -1 |
|  0 |
|  1 |
|  2 |
|  3 |
|  4 |
|  5 |
|  6 |
|  7 |
|  8 |
|  9 |
| 10 |
| 11 |
| 12 |
| 13 |
| 14 |
| 15 |
| 16 |
| 17 |
| 18 |
| 19 |
+----+
21 rows in set (0.01 sec)

* **supplements：**  
    1. explain two times:
mysql> explain select id from  test1 union SELECT ROW_COUNT();
+-----------------+---------------+-----------------------------------+
| DATA_NODE       | TYPE          | SQL/REF                           |
+-----------------+---------------+-----------------------------------+
| dn1_0           | BASE SQL      | select `test1`.`id` from  `test1` |
| dn2_0           | BASE SQL      | select `test1`.`id` from  `test1` |
| dn3_0           | BASE SQL      | select `test1`.`id` from  `test1` |
| dn4_0           | BASE SQL      | select `test1`.`id` from  `test1` |
| merge_1         | MERGE         | dn1_0; dn2_0; dn3_0; dn4_0        |
| shuffle_field_1 | SHUFFLE_FIELD | merge_1                           |
| dn1_1           | BASE SQL      | select ROW_COUNT() as `id`        |
| merge_2         | MERGE         | dn1_1                             |
| union_all_1     | UNION_ALL     | shuffle_field_1; merge_2          |
| distinct_1      | DISTINCT      | union_all_1                       |
| shuffle_field_2 | SHUFFLE_FIELD | distinct_1                        |
+-----------------+---------------+-----------------------------------+
11 rows in set (0.01 sec)

    mysql> explain select id from  test1 union SELECT ROW_COUNT();
+-----------------+---------------+-----------------------------------+
| DATA_NODE       | TYPE          | SQL/REF                           |
+-----------------+---------------+-----------------------------------+
| dn1_0           | BASE SQL      | select `test1`.`id` from  `test1` |
| dn2_0           | BASE SQL      | select `test1`.`id` from  `test1` |
| dn3_0           | BASE SQL      | select `test1`.`id` from  `test1` |
| dn4_0           | BASE SQL      | select `test1`.`id` from  `test1` |
| merge_1         | MERGE         | dn1_0; dn2_0; dn3_0; dn4_0        |
| shuffle_field_1 | SHUFFLE_FIELD | merge_1                           |
| dn5_0           | BASE SQL      | select ROW_COUNT() as `id`        |
| merge_2         | MERGE         | dn5_0                             |
| union_all_1     | UNION_ALL     | shuffle_field_1; merge_2          |
| distinct_1      | DISTINCT      | union_all_1                       |
| shuffle_field_2 | SHUFFLE_FIELD | distinct_1                        |
+-----------------+---------------+-----------------------------------+
11 rows in set (0.00 sec)

2.Sometimes dble will return the same result as expect result:
mysql> select id from  test1 union SELECT ROW_COUNT();
+----+
| id |
+----+
|  0 |
|  1 |
|  2 |
|  3 |
|  4 |
|  5 |
|  6 |
|  7 |
|  8 |
|  9 |
| 10 |
| 11 |
| 12 |
| 13 |
| 14 |
| 15 |
| 16 |
| 17 |
| 18 |
| 19 |
+----+
20 rows in set (0.00 sec)

**Comment by FlyingMao** [comment]
https://github.com/actiontech/dble/issues/1747

**Comment by sunsun314** [comment]
#952 releated, in MySQL-5.7.13 the ```select ... union select row_count()``` the row_count() result is 0. But in latest MySQL version(both 8.0.19 or 5.7.30) the result is -1

**Comment by sunsun314** [comment]
https://dev.mysql.com/doc/refman/8.0/en/information-functions.html#function_row-count

**Comment by FlyingMao** [comment]
need check ddl

**Comment by FlyingMao** [comment]
**verified version：** dble-9.9.9.9-7b169880e5635ca1654e61d846818ac18585091c-20200331061144
