### ISSUE TITLE
建议在.net core平台重写dble，以提高运行时性能

### ISSUE THREAD

**Issue by mfjiang** [actiontech/dble#1309]
你们好，看了dble的资料，以及一些实用案例，感到非常好，希望你们在.net core平台上重写dble，以提高运行时性能，这样做的一大收益是：在docker容器中取得更好的性能。因为.net core对docker容器的支持比java更全面，优化得更好。

DBLE is good, I hope you can rewrite DBLE on the .net core platform to improve runtime performance. One of the big gains is: get better performance in the docker container.Because the .net core supports the docker container more comprehensively than Java.

**Comment by alexinea** [comment]
I don't think this is a good idea. If you think you can rewrite an implementation with .net core, then you can do it. If you have successfully rewritten, you can try to join NCC or even apply to join the .NET Foundation.

Implementing dble with the .NET Core technology stack is not the job of the dble team. If you think you can contribute to the .NET community, we welcome you to implement it into .NET Core.

**Comment by yanhuqing666** [comment]
> get better performance in the docker container. Because the .net core supports the docker container more comprehensively than Java.

Although this is not a suggestion that can be implemented，I also want to know more detail about `performance in the docker` and `more comprehensively`.  Can you show us more documents about it？

**Comment by yanhuqing666** [comment]
no response and close
