### ISSUE TITLE
maxPacketSize in server.xml does not work

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#1317]
* **dble version：**  
5.6.29-dble-9.9.9.9-e2603d1945eec66ed3fd11f2608027ab324ca483-20190802031757

* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  
* **expect result：**  
    1.
* **real result：**  
    1.
* **supplements：**  
    1.there is no way to know the max packet size dble can support

**Comment by wjl1619** [comment]
Now we only support maxPacketSize<16M
verified on version:  5.6.29-dble-9.9.9.9-4bbbb80e84bf6dcbdbacf4e9e3643e4b7fdd050f-20191113024033
