### ISSUE TITLE
Check  different dataNodes with same dataHost and  same database

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#1322]
Dble sharding table based on sharding table into multi-dataNodes. But when the different dataNodes have the same dataHost and the same database. The SQL witch expected to be executed in multi-database would be executed in one database which can cause strange errors.  
So we decide to ban this type of config by checking it in both start-up & dry-run

**Comment by FlyingMao** [comment]
**verified version：** dble-9.9.9.9-1fcd7adf1b8233d6050245297593240b79eef1e7-20190823072726
