### ISSUE TITLE
The table name in the query will be scanned globally.  If add backquotes  `table_name`

### ISSUE THREAD

**Issue by CrookedPotato** [actiontech/dble#1324]
* **dble version：**  
Server version: 5.6.29-dble-2.19.03.0-bbc1097eae1f4e037d1aaf6bbe3d5f77de7d7c87-20190418142931 dble Server (ActionTech)
* **preconditions ：**  
query 中库名表名添加反引号\`table_name\`
* **configs：** 

**schema.xml**  

```
<table name="users" dataNode="dn$1-120" rule="customized" primaryKey="id"/>

```

**rule.xml**  

```
[](url)

```

**server.xml**  

```


```

* **steps：**    
    step1

.  
* **expect result：**  
    1.
MySQL [production]> explain SELECT * FROM users where org_id='zxinui';
+-----------+----------+-------------------------------------------------------+
| DATA_NODE | TYPE     | SQL/REF                                               |
+-----------+----------+-------------------------------------------------------+
| dn44      | BASE SQL | SELECT * FROM users WHERE org_id = 'zxinui' LIMIT 100 |
+-----------+----------+-------------------------------------------------------+
1 row in set (0.00 sec)

MySQL [production]> explain SELECT * FROM \`users\` where org_id='zxinui';
+-----------+----------+---------------------------------------------------------+
| DATA_NODE | TYPE     | SQL/REF                                                 |
+-----------+----------+---------------------------------------------------------+
| dn44      | BASE SQL | SELECT * FROM \`users\` WHERE org_id = 'zxinui' LIMIT 100 |
+-----------+----------+---------------------------------------------------------+
1 row in set (0.00 sec)

MySQL [production]> explain SELECT * FROM \`production\`.\`users\` where org_id='zxinui';
+-----------+----------+---------------------------------------------------------+
| DATA_NODE | TYPE     | SQL/REF                                                 |
+-----------+----------+---------------------------------------------------------+
| dn1       | BASE SQL | SELECT * FROM `users` WHERE org_id = 'zxinui' LIMIT 100 |
| dn10      | BASE SQL | SELECT * FROM `users` WHERE org_id = 'zxinui' LIMIT 100 |
| dn100     | BASE SQL | SELECT * FROM `users` WHERE org_id = 'zxinui' LIMIT 100 |
| dn101     | BASE SQL | SELECT * FROM `users` WHERE org_id = 'zxinui' LIMIT 100 |
| dn102     | BASE SQL | SELECT * FROM `users` WHERE org_id = 'zxinui' LIMIT 100 |
| dn103     | BASE SQL | SELECT * FROM `users` WHERE org_id = 'zxinui' LIMIT 100 |
| dn104     | BASE SQL | SELECT * FROM `users` WHERE org_id = 'zxinui' LIMIT 100 |
| dn105     | BASE SQL | SELECT * FROM `users` WHERE org_id = 'zxinui' LIMIT 100 |
.........

MySQL [production]> explain SELECT * FROM production.\`users\` where org_id='zxinui';
+-----------+----------+---------------------------------------------------------+
| DATA_NODE | TYPE     | SQL/REF                                                 |
+-----------+----------+---------------------------------------------------------+
| dn44      | BASE SQL | SELECT * FROM `users` WHERE org_id = 'zxinui' LIMIT 100 |
+-----------+----------+---------------------------------------------------------+

* **real result：**  
  +-----------+----------+---------------------------------------------------------+
| DATA_NODE | TYPE     | SQL/REF                                                 |
+-----------+----------+---------------------------------------------------------+
| dn44      | BASE SQL | SELECT * FROM \`users\` WHERE org_id = 'zxinui' LIMIT 100 |
+-----------+----------+---------------------------------------------------------+

* **supplements：**  
    1.
添加反引号后执行计划选择错误。

**Comment by wjl1619** [comment]
verified on version: 5.6.29-dble-9.9.9.9-02cef4c18ca820fe4401a62c6e6c8053f689b467-20190926091030
