### ISSUE TITLE
how to know the max_allowed_packet size of dble can support?

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#1325]
dble version: 5.6.23-dble-9.9.9.9-e2603d1945eec66ed3fd11f2608027ab324ca483-20190802031757

supplement:
maxPacketSize in config server.xml does not work at present, it does not control max_allowed_packet of backend connection

**Comment by wjl1619** [comment]
verified on version: 5.6.29-dble-9.9.9.9-4bbbb80e84bf6dcbdbacf4e9e3643e4b7fdd050f-20191113024033
