### ISSUE TITLE
join query with ambiguous columns success but expect not

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#1330]
* **dble version：** 
5.6.23-dble-9.9.9.9-f13a30c4c1af980ecdbda904700c45e166257166-20190819050701
 
* **preconditions ：**  
prepare queries
```mysql
create table sharding_3(id int, name char(20), age int);
create table sharding_2(id int);
insert into sharding_2 values(1),(5),(3);
insert into sharding_3 values(1,null,1),(2,'',2),(3,'a',3);
```
* **configs：** 

**schema.xml**  

```
<table name="sharding_2" dataNode="dn01,dn02" rule="hash_two" />
<table name="sharding_3" dataNode="dn01,dn02,dn03" rule="hash_three" />
```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  query directly to mysql
```mysql
mysql> select id, name from sharding_3 a, sharding_2 b where a.id > b.id;
ERROR 1052 (23000): Column 'id' in field list is ambiguous
```
  step2. query to dble
```mysql
mysql> select id, name from sharding_3 a, sharding_2 b where a.id > b.id;
+------+------+
| id   | name |
+------+------+
|    3 | a    |
|    2 |      |
+------+------+
2 rows in set (0.01 sec)
```
* **expect result：**  
    1. step2 query failed as step1
* **real result：**  
    1. step2 success
* **supplements：**  
    1.

**Comment by wjl1619** [comment]
**dble version:**
5.6.29-dble-9.9.9.9-ca5a30a333655ab595a9663ecea9ce6c2998b7e0-20191021065158
**preconditions:**
```sql
drop table if exists sharding_2_t1;
drop table if exists sharding_4_t1;
create table sharding_2_t1(id int);
create table sharding_4_t1(id int);
insert into sharding_2_t1 values(1),(3);
insert into sharding_4_t1 values(1),(2);
```
**expect result:**
mysql> select id from (select * from sharding_2_t1 a inner join sharding_4_t1 b on a.id=b.id) x;
ERROR 1060 (42S21): Duplicate column name 'id'
mysql> select id from (select * from sharding_2_t1 a inner join sharding_4_t1 b on a.id>b.id) x;
ERROR 1060 (42S21): Duplicate column name 'id'

**real result:**
mysql> select id from (select * from sharding_2_t1 a inner join sharding_4_t1 b on a.id=b.id) x;
+------+
| id   |
+------+
|    1 |
+------+
1 row in set (0.02 sec)

mysql> select id from (select * from sharding_2_t1 a inner join sharding_4_t1 b on a.id>b.id) x;
+------+
| id   |
+------+
|    2 |
|    1 |
+------+
2 rows in set (0.01 sec)

**Comment by wjl1619** [comment]
verified on version: 5.6.29-dble-9.9.9.9-6f54f427d25b89a820752e2354eaefd01f21acde-20191025035141
