### ISSUE TITLE
Support create FUNCTION just like create PROCEDURE 

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#1332]
dble support creates PROCEDURE with a hint in 2.19.05.0 but the FUNCTION still not support well.
So we decide to add create FUNCTION support just like support create PROCEDURE  
User can use a hint to create & call a Stored Routine Function/UDF

**Comment by FlyingMao** [comment]
**verified version：** dble-9.9.9.9-20fc63b93ed597f30fdfee25c1862da63df16a9e-20190903060850
