### ISSUE TITLE
gap time between queries during a transaction is calculated as  part of sqlExecuteTimeout 

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#1335]
* **dble version：**  
5.7.21-dble-9.9.9.9-f13a30c4c1af980ecdbda904700c45e166257166-20190819050701

* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```
        <property name="sqlExecuteTimeout">5</property>
```

* **steps：**    
    step1.  query to dble:
```mysql
set autocommit=0; -- success
select * from sharding_2; -- success
-- wait >5s
select * from sharding_2; -- fail
```
* **expect result：**  
    1.query success, gap time should not calculated in sqlExecuteTimeOut
* **real result：**  
    1.get error like:
ERROR 1152 (HY000): Connection {DataHost[172.100.9.6:3306],Schema[db05],threadID[4233]} was closed ,reason is [Connection {DataHost[172.100.9.6:3306],Schema[db05],threadID[4233]} was closed ]

* **supplements：**  
    1.

**Comment by wjl1619** [comment]
verified on version: 5.6.29-dble-9.9.9.9-641d14832fd4b53f9f534191d43d0fa2ac814d69-20191108094031
