### ISSUE TITLE
Got error "Lost connection to MySQL server at 'reading authorization packet'" when login hang

### ISSUE THREAD

**Issue by wjl1619** [actiontech/dble#1337]
* **dble version：**  
5.6.29-dble-9.9.9.9-0d3c776cbd7993a4287108af0ac140be4693ca58-20190820021310
* **preconditions ：**  
no
* **configs：** 

**server.xml**  

```xml
<property name="processors">1</property>
```

* **steps：**    
    step1. login dble with port 8066 success
    setp2. add a break point by running btrace(com.actiontech.dble.net.handler.FrontendAuthenticator#success) 
    step3. login dble
* **expect result：**  
    1.login success after hang finished
* **real result：**  
    1.login failed and return error "ERROR 2013 (HY000): Lost connection to MySQL server at 'reading authorization packet', system error: 0"
* **supplements：**  
    1.[dble.log](https://github.com/actiontech/dble/files/3523298/dble.log)

**Comment by kaikai2000** [comment]
The reason for this error is that the client sent the login username and password, and the timeout did not receive the return packet.

**Comment by yanhuqing666** [comment]
delay

**Comment by sunsun314** [comment]
The reason is that there is a hidden config in ServerConnection set the default AUTH_TIMEOUT = 15000ms. When a serverconnection can not be authenticated in 15s, idleTimeOut function would treat the connection as idle and kill the connection

**Comment by sunsun314** [comment]
Change the processorCheckPeriod into a large one and add param --connect_timeout=50000 into MySQL command can help to see the phenomenon

**Comment by wjl1619** [comment]
As per comment by @sunsun314, we do not change the current logic, so close it.
