### ISSUE TITLE
ChildTable has no config "incrementColumn"

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#1364]
* **dble version：**  2.19.05.0  
table config has "incrementColumn"  and the increment column can be different from primaryKey
but we forget to add this param into childTable config. So the childTable still use the primaryKey as the increment column

**Comment by sunsun314** [comment]
needAddLimit parameter is lost as well

**Comment by wjl1619** [comment]
verified on version: 5.6.29-dble-9.9.9.9-97b9e4cee24afeae57e7890aa5ebba36afcd225b-20191104052741
please doc-it
