### ISSUE TITLE
reload @@config_all failed may lead to connections for new added datahost in config leaking 

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#1383]
* **dble version：**  
5.6.29-dble-9.9.9.9-d8a5c79cc4efda58659d7990340fde23777a1558-20190903023556

* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  start a trx to a sharding table, eg:
```mysql
begin;
select * from sharding_2_t1 limit 2;
```
  step2. alter the sharding table in another session gets blocked:
```mysql
alter table sharding_2_t1 add column c int; -- blocked here
```
  step3. modify the config schema.xml, to add a new datahost, and add table to use datanode in it

  step4. query "reload @@config_all" to dble manager port, get failed for:
ERROR 1003 (HY000): Reload config failure.The reason is There is other session is doing DDL

  step5. netstat -pent | grep {new added datahost ip} , there will be connections leaving there at "ESTABLISHED" state

* **expect result：**  
    1. if reload @@config_all failed, the new added connections should be recyled
* **real result：**  
    1.reload @@config_all failed may lead to connections leaking as example above
* **supplements：**  
    1. to consider other possible reasons lead to reload failed

**Comment by yexiaoli88** [comment]
verified on version: 5.6.29-dble-9.9.9.9-77a301ab1dd9a58dbf8fad345dfb2d563a54ebc8-20190905021744
