### ISSUE TITLE
Query result is incorrect when the regexp  is used in where condition

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#1385]
* **dble version：**  2.19.5.0
* **schema.xml**   
```
 <schema name="schema1" sqlMaxLimit="100" dataNode="dn1">
    </schema>
    <schema name="schema3" sqlMaxLimit="100" dataNode="dn2">
    </schema>
     <schema name="schema2" sqlMaxLimit="100" dataNode="dn3">
    </schema>
```
* **steps：**    
 **schema1**  
create table table_a(id int,goods_id varchar(40),city varchar(40));
insert into table_a values(1,"goods","city");

**schema2**
create table table_b(id int,goods_id varchar(40));

insert into table_b values(2,"goods");

create table table_c(id int,city varchar(50),wid int);
  
 insert into table_c values(3,"city",4);
 
 **schema3**
 
 create table table_d(id int,name varchar(100));
 insert into table_d values(4,"12345AAA") ;
  
  
* **expect result：**  
select 
       dg.id aaaa,
       dgw.id bbbb,
       ew.id cccc 
from schema1.table_a dgw
         inner join schema2.table_b dg
                    on dgw.goods_id = dg.goods_id 
         left join schema2.table_c dwp
                   on dgw.city = dwp.city
         left join schema3.table_d ew
                   on ew.id = dwp.wid 
where dgw.id = 1
  and ew.name regexp 'AAA';
 has result
* **real result：**  
Empty set (0.89 sec)

**Comment by wjl1619** [comment]
verified on version: 5.6.29-dble-9.9.9.9-02cef4c18ca820fe4401a62c6e6c8053f689b467-20190926091030
