### ISSUE TITLE
Execute sql  error when the database name in MySQL has ’.’

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#1386]
* **dble version：**  2.19.05.0/rel
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```
    <dataNode name="dn1" dataHost="localhost1" database="db.1"/>
    <dataNode name="dn2" dataHost="localhost1" database="db.2"/>

```
* **steps：**    
    step1.  start with dataNode has database db.1/db.2
* **expect result：**  
    dble can provide normal service
* **real result：**  
    even select 1 can't be execute in dn1

**Comment by Baofengqi** [comment]
After fixing this, user still can use the following command to create datenode
create database @@dataNode ='dn......'

**Comment by wjl1619** [comment]
verfied on version: 5.6.29-dble-9.9.9.9-02cef4c18ca820fe4401a62c6e6c8053f689b467-20190926091030
