### ISSUE TITLE
[commit] may got strange resultset when there is datahost can not be reached

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#1392]
* **dble version：**  
5.6.29-dble-9.9.9.9-eaf04a0f6428f81c692fb0d52a9349d5805bbb37-20190916022621
* **preconditions ：**  
table account is a not-sharding table
* **configs：** 
use template config in autotest
**schema.xml**  

```

```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  execute sqls with dble as session1
```mysql
mysql> begin;
Query OK, 0 rows affected (0.01 sec)

mysql> select * from account;
+------+------------+-----------+--------+---------------------+
| id   | customerid | accountno | amount | ts                  |
+------+------------+-----------+--------+---------------------+
|    1 |          1 | a0301     |   0.00 | 2019-09-17 10:17:24 |
|    2 |          2 | a0601     |   0.00 | 2019-09-17 10:17:24 |
|    3 |          3 | a0301     |   0.00 | 2019-09-17 10:17:24 |
|    4 |        601 | a0601     |   0.00 | 2019-09-17 10:17:24 |
+------+------------+-----------+--------+---------------------+
4 rows in set (0.07 sec)
```
step2. stop one of the dataHosts service
kill -9 {mysql-service-pid}

step3. go on query with session1
```mysql
mysql> commit;
+------+------------+-----------+--------+---------------------+
| id   | customerid | accountno | amount | ts                  |
+------+------------+-----------+--------+---------------------+
|    1 |          1 | a0301     |   0.00 | 2019-09-17 10:17:24 |
|    2 |          2 | a0601     |   0.00 | 2019-09-17 10:17:24 |
|    3 |          3 | a0301     |   0.00 | 2019-09-17 10:17:24 |
|    4 |        601 | a0601     |   0.00 | 2019-09-17 10:17:24 |
+------+------------+-----------+--------+---------------------+
4 rows in set (0.00 sec)
```
* **expect result：**  
    1.ERROR 3009 (HY000): the data source[172.100.9.5:3306] can't reached, please check the dataHost
* **real result：**  
    1. commit may get last query resultset or lost connection... as above example:

* **supplements：**  
    1.
[dble.log](https://github.com/actiontech/dble/files/3619103/dble.log)

**Comment by yanhuqing666** [comment]
may be related to #1336

**Comment by sunsun314** [comment]
the phenomenon  is the same as #1336

**Comment by wjl1619** [comment]
verified on version: 5.6.29-dble-9.9.9.9-732ab7b0d51bb13b0650606093ef8ae5f32d6e45-20191114053702
