### ISSUE TITLE
Wrong Packet Id of MySQL Protocol Packet If Error Happens In Process of Loading Data 

### ISSUE THREAD

**Issue by ssxlulu** [actiontech/dble#1397]
I think the packet id is wrong when error hanpens in process of loading data.

> The sequence-id is incremented with each packet and may wrap around. It starts at 0 and is reset to 0 when a new command begins in the Command Phase.

Above is the [MySQL offical document](https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_basic_packets.html) about the sequence-id (is same as 'packet id' in this issue).So if the client use 'load data local' synax, and send more than one packet(the packet id will increment one by one), and dble happens error in process of parsing, the err packet dble send will be wrong because the err packet id as i think.

Below is the code in ServerLoadDataInfileHandler#parseFileByLine:
```
try {
                        parseOneLine(row, true);
                    } catch (Exception e) {
                        clear();
                        serverConnection.writeErrMessage(ErrorCode.ER_WRONG_VALUE_COUNT_ON_ROW, "row data can't not calculate a sharding value," + e.getMessage());
                        return false;
                    }
```
As the code show, when error happens the error packet id will be 1. Does it right?

**Comment by ssxlulu** [comment]
The phenomenon when the error happens may be 'Lost connection to MySQL server during query'.

**Comment by wjl1619** [comment]
verified on version: 5.6.29-dble-9.9.9.9-4a1798f8927fa77cef643523b5451807fe469989-20191008111520
