### ISSUE TITLE
 Use `--default-auth = sha256_password` and the wrong password when connecting dble, return the error: `lost connected`

### ISSUE THREAD

**Issue by FlyingMao** [actiontech/dble#1398]
* **dble version：**  
dble-9.9.9.9-eaf04a0f6428f81c692fb0d52a9349d5805bbb37-20190916022621
* **preconditions ：**  
The right way to connect dble：
MySQL -utest -ptest -h127.0.0.1 -P8066
* **configs：** 

**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1. Use `--default-auth = sha256_password` and the wrong password when connecting dble
```
mysql -utest -p123 -h127.0.0.1 -P8066 --default-auth=sha256_password
``` 
* **expect result：**  
    1. return error :Access denied for user 'root', because password is incorrect
* **real result：**  
    1. 
```
[root@localhost logs]# mysql -uroot -p1234 -h10.186.65.63 -P8066 --default-auth=sha256_password
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading final connect information', system error: 2
```
* **supplements：**  
    1.

**Comment by wjl1619** [comment]
verified on version: 5.7.13-dble-9.9.9.9-6292d58e0be9e6867efa84b8159371d27e1fe1b3-20190925075738
