### ISSUE TITLE
Both Dbleserver&Dbleserver#startup too large

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#1405]
Dbleserver is the main class of the dble, as the server-level function continuously be  added into the Dbleserver the class contains too much function objects that can be independent from the main class.     
As a result, a new server-level feature can hardly be added into dble. So we decided to refactor the Dbleserver and its startup function. The refactor details as below:
+ remove all the server-level feature(XA recovery/binlog_pause except) into a package called 'singleton'
+ change all server-level feature init into a singleton class. So they can be found without Dbleserver
+ change the startup function more readable
+ add clear stages logs in the startup function

We a expect to refactor Dbleserver into a more readable and change it into a clear structure

**Comment by irene-coming** [comment]
no way to verify,just close issue
