### ISSUE TITLE
The columnType returned by DBLE is inconsistent with the MYSQL database.

### ISSUE THREAD

**Issue by zhangjig** [actiontech/dble#1417]
* **dble version：*commit 03908423acd9ed656d57f34e1fad6db7c2a64993 (HEAD -> master, origin/master, origin/HEAD)*  
* **preconditions ：**  
CREATE TABLE `tmp_stmt` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `table_id` int(11) DEFAULT NULL,
  `out_biz_no` decimal(64,0) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
* **configs：** 

**schema.xml**  

```
<schema name="testdb">
        <table name="tmp_stmt" dataNode="dn1,dn2,dn3" rule="tmp_stmt"/>
        <table name="stmt_loan" dataNode="dn1,dn2,dn3" rule="stmt_loan"/>
    </schema>
    <schema name="testdb1">
        <table name="tmp_stmt" dataNode="dn1" />
        <table name="stmt_loan" dataNode="dn1" />
    </schema>

    <dataNode name="dn1" dataHost="localhost1" database="db1"/>
    <dataNode name="dn2" dataHost="localhost1" database="db2"/>
    <dataNode name="dn3" dataHost="localhost1" database="db3"/>

    <dataHost name="localhost1" maxCon="500" minCon="10" balance="0">
        <heartbeat>select user()</heartbeat>
        <writeHost host="hostM1" url="localhost:3308" user="root" password="123456">
        </writeHost>
    </dataHost>

```

**rule.xml**  

```
<tableRule name="stmt_loan">
        <rule>
            <columns>contract_no</columns>
            <algorithm>func_tmp</algorithm>
        </rule>
    </tableRule>

    <tableRule name="tmp_stmt">
        <rule>
            <columns>out_biz_no</columns>
            <algorithm>func_tmp</algorithm>
        </rule>
    </tableRule>

```

**server.xml**  

```
<user name="root">
        <property name="password">123456</property>
        <property name="schemas">testdb,testdb1</property>
    </user>

```

* **steps：**    
    step1.  create table tmp_stmt in db1 and db2 
    step2. insert 1 row
    step3. write the test code: see attached

[testColumnType.zip](https://github.com/actiontech/dble/files/3656848/testColumnType.zip)

* **expect result：**  
    1. the function Coalesce returned columnTypeName is Decimal
* **real result：**  
    1.the function Coalesce returned columnTypeName is Double
* **supplements：**  
    1.Please verify the return type of other functions together, keep the same as the database type

**Comment by zhangjig** [comment]
Round函数存在同样的问题。能否有效解决已实现的函数的数据类型与数据库类型保持一致呢？

**Comment by yanhuqing666** [comment]
![image](https://user-images.githubusercontent.com/16715575/68924421-c4c8e380-07bb-11ea-9252-1cc7e0443581.png)

**Comment by irene-coming** [comment]
dble version: 5.6.29-dble-9.9.9.9-96c130230a2ef9268bdb3605e190d559b0439625-20200203081515
for sql [select count(out_biz_no) from tmp_stmt ] the returned type is not consistent with mysql
dble return type: int
mysql return type: bigint

test using java code of the above attachment zip, to dble's log:
columnName:[ COUNT(out_biz_no) ],columnTypeName:[ INT] ,columnValueType:[ class java.lang.Integer ]

to mysql's log:
columnName:[ count(out_biz_no) ],columnTypeName:[ BIGINT] ,columnValueType:[ class java.lang.Long ]

**Comment by wjl1619** [comment]
verified on version: 5.6.29-dble-2.19.11.0-a8b6cf2daf30fd1dedb6e91294d8b6839e730386-20200211092945
