### ISSUE TITLE
manager cmd “pause @@dataNode=...” return ok ,even if the service is not stopped in fact

### ISSUE THREAD

**Issue by yexiaoli88** [actiontech/dble#1432]
* **dble version：2.19.07.1 b86a4faa297e7ac06be7a7172d50fcbdc64dba7a**  

* **steps：**    
 
1.postman call the interface “/v3/ushard/sharding_scale_out_task/turn_off_traffic” which involved “pause @@dataNode=...”  and return ok

2,execute "show @@pause" in the dble manager port to check if service is stopped,
then find no dataNode's service is stopped

* **supplements：**  
  
[dble.log](https://github.com/actiontech/dble/files/3723327/dble.log)

**Comment by sunsun314** [comment]
By browsing the code some mistakes have been found, but the true reason for return OK and not pause the dataNode is still unresolved

**Comment by wjl1619** [comment]
verified on version: 5.7.21-dble-9.9.9.9-efa89e4c6e7fbe899b9159c984a05fb048ba345b-20191112033427
improvement: now when all instances are both move out the ucore cluster, it will return error excute pause command.
This issue happened on occasion, now add corresponding log and observer in later version.
