### ISSUE TITLE
[set sql_select_limit] failed on session A may effect  session B result

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#1434]
* **dble version：**  
5.6.29-dble-2.19.03.1-26ebd16ef40f5175d07699689661b75d8b15e240-20190927115244
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```
<schema name="schema1" sqlMaxLimit="10000">
<table name="sharding_2_t1" rule="hash-two" dataNode="dn$1-2"></table>
</schema>
<schema name="schema2" sqlMaxLimit="10000">
<table name="sharding_1_t1" dataNode="dn2"></table>
</schema>
<dataNode name="dn1" dataHost="dh1" database="db1"></dataNode>
<dataNode name="dn2" dataHost="dh2" database="db2"></dataNode>
```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  in dble session A login with schema1
```mysql
mysql> set sql_select_limit=3;
Query OK, 0 rows affected (0.01 sec)
```
   step2. in dble session B login with schema2
```mysql
mysql> set sql_select_limit=3;
Query OK, 0 rows affected (0.01 sec)
```
  step3. stop mysql service in datahost dh1
  step4. in dble session A
```mysql
mysql> set sql_select_limit=3;
ERROR 2013 (HY000): Lost connection to MySQL server during query
```
  step5.in dble session B
```mysql
mysql> set sql_select_limit=3;
ERROR 2013 (HY000): Lost connection to MySQL server during query
```
* **expect result：**  
    1.step4, step5 should receive success, because there exists alive datanode 
* **real result：**  
    1.step4, step5 got failed
* **supplements：**  
    1.set xxx route to the first alive datanode to check grammer success, then wait the real query to restore the 'set xx' to the connection

**Comment by wjl1619** [comment]
verified on version: 5.6.29-dble-9.9.9.9-6f54f427d25b89a820752e2354eaefd01f21acde-20191025035141
