### ISSUE TITLE
Optimization implements of manager command thread_used

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#1440]
The executor now try to get the self ThreadWorkUsage from a global TreeMap and set latest value into. But let the executor holding the ThreadWorkUsage can get the same result and cause  less cost

**Comment by wjl1619** [comment]
can not reproduce on version: 5.6.29-dble-9.9.9.9-d1df782b87a62ede3e1c1a3f42583303ddbf72b7-20191115021019, and will observe on later version continuously
