### ISSUE TITLE
loaddata return  error “stream closed”

### ISSUE THREAD

**Issue by yexiaoli88** [actiontech/dble#1450]
* **dble version： 5.6.23-dble-2.19.03.1-161ba1d05a0ecca0633ca0f463704149b16fdef7-20191012125422**  
* **preconditions ：**  
create table test(id char(10),name char(10),k char(10),p char(10));
[test4.txt](https://github.com/actiontech/dble/files/3777350/test4.txt)

* **configs：** 

**schema.xml**  

```
    <schema name="testdb" dataNode="dn1">
        <table name="test" rule="hash-4" dataNode="dn1,dn2,dn3,dn4"></table>
    </schema>

```
  
**two scenarios haven been test**

scenarios 1:
1. produce a file bigger than 4G 
2.execute loaddata in dble server port,
```
 load data infile "/opt/test2.txt" into table test character set 'utf8' fields terminated by ',' lines terminated by '\n';
```
3.load data will hang 

4.error message like "stream closed" would appeare in dble.log after hang about 20min

scenarios 2:
1. use btrace script as bellow:
```
package com.actiontech.dble.btrace.script;

import com.sun.btrace.BTraceUtils;
import com.sun.btrace.annotations.BTrace;
import com.sun.btrace.annotations.OnMethod;
import com.sun.btrace.annotations.ProbeClassName;
import com.sun.btrace.annotations.ProbeMethodName;
import com.sun.btrace.annotations.*;


@BTrace(unsafe = true)
public final class BtraceClusterDelay{

    private BtraceClusterDelay() {

    }

   @OnMethod(
            clazz = "com.actiontech.dble.backend.mysql.LoadDataUtil",
            location= @Location(value=Kind.LINE,line=62)
    )
    public static void delayLoadData(@ProbeClassName String probeClass, @ProbeMethodName String probeMethod) throws Exception {
        BTraceUtils.print("get into delayLoadData");
        BTraceUtils.print(" for order __________________________ ");
        Thread.sleep(50000L);
    }
}

```
2. execute "btrace ${dble_pid} BtraceClusterDelay"

3execute load data  with file 'test4' which have been provided
```
load data infile "/opt/test4.txt" into table test character set 'utf8' fields terminated by ',' lines terminated by '\n';
```
4.load data return error after about 4min
```
mysql> load data infile "/opt/test4.txt" into table test character set 'utf8' fields terminated by ',' lines terminated by '\n';
ERROR 1152 (HY000): Connection {DataHost[172.20.134.4:3306],Schema[db2],threadID[14070]} was closed ,reason is [stream closed]

```
* **expect result：**  
    1. load data should not return error or hang

* **supplements：**  
    1.[1.log](https://github.com/actiontech/dble/files/3777382/1.log)

**Comment by yanhuqing666** [comment]
delay

**Comment by sunsun314** [comment]
phenomenon 2 can be interpreted as in MySQL load data use a synchronized network wait to wait for the file data. But if the next network packet can't get in net_read_timeout, the MySQL would close the socket and end this load data

**Comment by sunsun314** [comment]
phenomenon 1 because we try to send the load-data-end packet in the end. But when the file is big enough dble would wait for file close for a long time. This can cause the MySQL Server load data net_read_timeout, and finally, cause the connection close

**Comment by sunsun314** [comment]
delay because of can't be reproduce
