### ISSUE TITLE
[load data infile 'xxx' into table t (@colA,@colB)] get wrong resultset

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#1454]
* **dble version：** 
5.6.29-dble-9.9.9.9-78a278906811927e31ad0cdc0cc19c2379963992-20191012125722 
* **preconditions ：**  
create table sharding_2_t1(id int(4), B float(8,2)) ;
* **configs：** 

**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  prepare a test.txt filled with 
```
5,5
3,3
```
    step2  query in dble
```mysql
mysql> load data infile '/root/test.txt' into table sharding_2_t1 (@id_str, @B_str);
Query OK, 4 rows affected (0.07 sec)
Records: 4  Deleted: 0  Skipped: 0  Warnings: 0
mysql> select * from sharding_2_t1;
+------+--------+
| id   | B      |
+------+--------+
| NULL |   NULL |
| NULL |   NULL |
| NULL |   NULL |
| NULL |   NULL |
+------+--------+
4 rows in set (0.01 sec)
```
@id_str, @B_str are not explicitly assigned
* **expect result：**  
    1.after load data, select from sharding_2_t1 get resultset :
```
| NULL |   NULL |
| NULL |   NULL |
```
* **real result：**  
    1.resultset seems to be doubled
* **supplements：**  
    1.

**Comment by irene-coming** [comment]
在step2同一个session中执行
```mysql
mysql> select @id_str, @B_str;
+---------+--------+
| @id_str | @B_str |
+---------+--------+
| NULL    | NULL   |
+---------+--------+
1 row in set (0.00 sec)
```
mysql下的执行结果为：
```mysql
mysql> select @id_str, @B_str;
+---------+--------+
| @id_str | @B_str |
+---------+--------+
| 3       | 3      |
+---------+--------+
1 row in set (0.00 sec)
```
**expect:**
after load data, user variables in dble consistent with mysql

**Comment by Baofengqi** [comment]
delay

**Comment by Baofengqi** [comment]
1. In case 1, for sharding table, if columns don't contain sharding column, dble will report error.

**Comment by FlyingMao** [comment]
**case1 verified version:** dble-9.9.9.9-14e43f2e85d2b29aea766d8836f6f799bee2fb2d-20200401051400
case2  :  #1761
