### ISSUE TITLE
[load data ... fields terminated by "x"...] x can only be char, expect x can be string

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#1456]
* **dble version：**  
5.6.29-dble-9.9.9.9-78a278906811927e31ad0cdc0cc19c2379963992-20191012125722
* **preconditions ：**  
create table sharding_2_t1(id int(4), B float(8,2)) ;
prepare /tmp/test3.txt, filled with:
```
1||2
3||4
```
* **configs：** 

**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  query in dble
```mysql
mysql> load data infile '/tmp/test3.txt' into table sharding_2_t1 FIELDS TERMINATED BY '||';
Query OK, 2 rows affected, 4 warnings (0.01 sec)

mysql> select * from sharding_2_t1;
+------+------+
| id   | B    |
+------+------+
|    1 | 0.00 |
|    3 | 0.00 |
+------+------+
2 rows in set (0.00 sec)
``` 
* **expect result：**  
    1. step1 after load data, the data in table is :
```mysql
+------+------+
| id   | B    |
+------+------+
|    1 | 2.00 |
|    3 | 4.00 |
+------+------+
```
* **real result：**  
    1.
* **supplements：**  
tester should verify other fields terminated strings, of which "|||" is a must

**Comment by Baofengqi** [comment]
Fix the issue from dble 2.19.03.1

**Comment by wjl1619** [comment]
verified on version:
5.6.29-dble-2.19.03.2-b1cb453bf052b6dc34d160b0e1daa8dc9814c387-20191030095427
5.6.29-dble-2.19.05.2-14700a8a98c7f8d8081a78942b804bf65abdb5e5-20191030095612
5.6.29-dble-2.19.07.2-c06b12f3a81a12cb64af59d743c1fb5e1becb794-20191030095800

**Comment by wjl1619** [comment]
verified on version: 5.6.29-dble-9.9.9.9-1dc8981d64a9d3930088109f57d5cbd1336863de-20191111090514
