### ISSUE TITLE
主键采用分布式时间戳⽅式在非分片表上不生效

### ISSUE THREAD

**Issue by liuxinwang** [actiontech/dble#1459]
* **dble version：**  MavenVersion 2.19.07.0
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```
<table name="riding_order" primaryKey="id" autoIncrement="true" dataNode="ermdn1"  />

```

**rule.xml**  

```
无

```

**server.xml**  

```
<property name="sequnceHandlerType">2</property>

```
**sequence_time_conf.properties**  

```
dble为双节点负载
dble1:
WORKID=01
DATAACENTERID=01
dble2:
WORKID=01
DATAACENTERID=02

```

* **steps：**    
    step1.  
对 riding_order表 执行插入，主键id生成连续，并没有采用分布式主键方式生成
* **expect result：**  
    1.id生成非连续
* **real result：**  
    1.id生成连续
* **supplements：**  
    1.对riding_order表增加rule规则，也就是采用分片表，分布式主键生成非连续。

**Comment by wjl1619** [comment]
verified on version: 5.6.29-dble-2.19.11.0-14d0361ecc08d84098a04090b8db7d66aa4801f1-20200211074123
