### ISSUE TITLE
schema.xml datanode sums of attributes values of name and database should equal

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#1465]
* **dble version：**  
5.6.29-dble-9.9.9.9-78a278906811927e31ad0cdc0cc19c2379963992-20191012125722
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```
```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1. config schema.xml for dble as:
```xml
<dataNode name="dn1"  database="db1,db2"  dataHost="172.100.9.5"/>
```  
start dble
* **expect result：**  
    1. start dble failed with error log in wrapper.log, for sums of attributes values of name and database are not equal,  that is: count_sum(dn1)=1, count_sum(db1,db2)=2
  2.optimize doc description for attribute database in https://actiontech.github.io/dble-docs-cn/1.config_file/1.02_schema.xml.html
![image](https://user-images.githubusercontent.com/6801133/68014409-794a0c00-fcca-11e9-8fd9-d9e4008c680c.png)

* **real result：**  
    1.start dble success
* **supplements：**  
    1.

**Comment by wjl1619** [comment]
verified on version: 5.6.29-dble-2.19.11.0-3924537e81390ba76656e3c5071c194c7be7923b-20200210030705
