### ISSUE TITLE
complex query with view in view got column not found error

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#1489]
* **dble version：**  
5.6.29-dble-9.9.9.9-641d14832fd4b53f9f534191d43d0fa2ac814d69-20191108094031

* **preconditions ：**  
all tables are no-sharding ones:
create table test1(id int,code varchar(10));
create table test2(id int,code varchar(10));
* **configs：** 

**schema.xml**  

```
 <schema name="schema1" dataNode="dn1">
 </schema>
```

* **steps：**    
    step1.  create view in dble
```
create view test_view(id,name) AS select id,code from test1 union select id,code from test2;
```
step2.  execute following sql
```
mysql> select name from test_view;
```
* **expect result：**  
    1. query success
* **real result：**  
    1.ERROR 5318 (HY000): column name not found
* **supplements：**

**Comment by wjl1619** [comment]
verified on version：5.6.29-dble-9.9.9.9-4a68a4ed0a47b3975cd9b4aedd4631281766987a-20191226093803
