### ISSUE TITLE
同样的语句与mycat对比，性能差(left join 实现不同)，且结果不准确（与mysql比较后是mycat错了）

### ISSUE THREAD

**Issue by Kevy123** [actiontech/dble#1490]
* **dble version：2.19.07.0**  
* **mycat version：1.6.7.3**  
user_info表主键consumer_id，data_now表主键consumer_id，两表都是按照同一字段cid进行的分库。
即mycat的io.mycat.route.function.PartitionByFileMap分库策略，保证相同cid的两个表的数据都在同一节点。两表数据都是大约10~20w，不存在大表join小表。dble与mycat的其余配置都是默认。

## sql 语句
`SELECT SUBSTR(hi.consumer_id,1,14) as cid,avg(hdn.heat) from data_now as hdn
LEFT JOIN user_info as hi 
ON hdn.consumer_id = hi.consumer_id and hdn.company_id = '00019'
GROUP BY SUBSTR(hi.consumer_id,1,14)
LIMIT 1000`

## 对比表现

mycat结果
![image](https://user-images.githubusercontent.com/19991653/68569718-cb90e700-0499-11ea-8dab-7d6c464bfc6e.png)

dble结果
![image](https://user-images.githubusercontent.com/19991653/68569784-fa0ec200-0499-11ea-918e-6eec1310b3e1.png)

目前的系统使用的是mycat，有大量类似于上述的sql语句，想要平移到dble。

**Comment by sunsun314** [comment]
Well, the case you provide may have a bug in dble, but the performance of the case is limited by your scenes.  
As dble can not tell the *SUBSTR(hi.consumer_id,1,14)* would not duplicate in different dataNodes, this query is not supposed to be simply broadcast into backend Mysql.  
Hint in dble may help you to come over these problems  
https://github.com/actiontech/dble-docs-cn/blob/master/2.Function/2.04_hint.md

**Comment by Kevy123** [comment]
就是以company_id 这个字段来分的库
![image](https://user-images.githubusercontent.com/19991653/68574188-537bee80-04a4-11ea-9f79-a1103cbfe3e5.png)

上述sql中已经明确指定company_id='00019'，应该会路由到1号节点啊
![image](https://user-images.githubusercontent.com/19991653/68574360-9e960180-04a4-11ea-9bce-be7ea2e19f4f.png)

**Comment by Kevy123** [comment]
> Well, the case you provide may have a bug in dble, but the performance of the case is limited by your scenes.
> As dble can not tell the _SUBSTR(hi.consumer_id,1,14)_ would not duplicate in different dataNodes, this query is not supposed to be simply broadcast into backend Mysql.
> Hint in dble may help you to come over these problems
> https://github.com/actiontech/dble-docs-cn/blob/master/2.Function/2.04_hint.md

就是以company_id 这个字段来分的库
![image](https://user-images.githubusercontent.com/19991653/68574188-537bee80-04a4-11ea-9f79-a1103cbfe3e5.png)

上述sql中已经明确指定company_id='00019'，应该会路由到1号节点啊
![image](https://user-images.githubusercontent.com/19991653/68574360-9e960180-04a4-11ea-9bce-be7ea2e19f4f.png)

**Comment by sunsun314** [comment]
* LEFT JOIN user_info as hi ON hdn.consumer_id = hi.consumer_id and hdn.company_id = '00019' *  
just look this part of the SQL, dble can not sure that there was no *user_info* data out of dataNode 1
unless you define the relationship of table  data_now & user_info as ER table by explicit

**Comment by yanhuqing666** [comment]
can you dump all your data to mysql and get the correct result? If the value of the right table is null for  `left join`, the query can not send to one node, unless you use `inner join` .

**Comment by Kevy123** [comment]
> *LEFT JOIN user_info as hi ON hdn.consumer_id = hi.consumer_id and hdn.company_id = '00019' *
> just look this part of the SQL, dble can not sure that there was no _user_info_ data out of dataNode 1
> unless you define the relationship of table data_now & user_info as ER table by explicit

两个表都明确的指定分库字段。表现如下：
![image](https://user-images.githubusercontent.com/19991653/68575874-f97d2800-04a7-11ea-89cc-d82496a054b0.png)

**Comment by Kevy123** [comment]
> can you dump all your data to mysql and get the correct result? If the value of the right table is null for `left join`, the query can not send to one node, unless you use `inner join` .
修改为inner join
![image](https://user-images.githubusercontent.com/19991653/68576282-c4bda080-04a8-11ea-8852-6114662b3131.png)

两个表指定分库字段
![image](https://user-images.githubusercontent.com/19991653/68576392-f6366c00-04a8-11ea-982b-ef53b4c26795.png)

**Comment by Kevy123** [comment]
> can you dump all your data to mysql and get the correct result? If the value of the right table is null for `left join`, the query can not send to one node, unless you use `inner join` .

修改为inner join
![image](https://user-images.githubusercontent.com/19991653/68576282-c4bda080-04a8-11ea-8852-6114662b3131.png)

两个表指定分库字段
![image](https://user-images.githubusercontent.com/19991653/68576392-f6366c00-04a8-11ea-982b-ef53b4c26795.png)

**Comment by Kevy123** [comment]
> can you dump all your data to mysql and get the correct result? If the value of the right table is null for `left join`, the query can not send to one node, unless you use `inner join` .

修改为inner join
![image](https://user-images.githubusercontent.com/19991653/68576282-c4bda080-04a8-11ea-8852-6114662b3131.png)

两个表指定分库字段
![image](https://user-images.githubusercontent.com/19991653/68576392-f6366c00-04a8-11ea-982b-ef53b4c26795.png)

**Comment by Kevy123** [comment]
dble同库（确保相同节点）内的所有表进行join操作，都要指定 ‘company_id’(分库字段)？，但是在mycat中,只需指定其中一个表的分库字段就能路由到指定DataNode上吗

**Comment by yanhuqing666** [comment]
> dble同库（确保相同节点）内的所有表进行join操作，都要指定 ‘company_id’(分库字段)？，但是在mycat中,只需指定其中一个表的分库字段就能路由到指定DataNode上
> 
> 对于sql的编写，已经避免了跨库join的前提下。即单库内任意表join、单库内任意表jion和global表join

no need add ‘company_id’，your first `inner join` case is a little strange，can you send your data and dble.log to my email or QQ(from QQ group 669663113)

**Comment by Kevy123** [comment]
> > dble同库（确保相同节点）内的所有表进行join操作，都要指定 ‘company_id’(分库字段)？，但是在mycat中,只需指定其中一个表的分库字段就能路由到指定DataNode上
> > 对于sql的编写，已经避免了跨库join的前提下。即单库内任意表join、单库内任意表jion和global表join
> 
> no need add ‘company_id’，your first `inner join` case is a little strange，can you send your data and dble.log to my email or QQ(from QQ group 669663113)

![image](https://user-images.githubusercontent.com/19991653/68643674-57178000-054d-11ea-9af8-2f4faab4c090.png)

**Comment by yanhuqing666** [comment]
1. left join mysql result:
```
+----------------+---------------+
| cid            | AVG(hdn.heat) |
+----------------+---------------+
| NULL           |  33589.474233 |
| 00019000080250 |  21897.314800 |
| 00019000080280 |  21097.576087 |
| 00019000080290 |  18146.886154 |
| 00019000080310 |   1021.788571 |
| 00019000080320 |  11990.951333 |
| 00019000080330 |     12.482857 |
| 00019000080340 |   2668.644000 |
| 00019000080350 |  16306.882424 |
```
It is same to dble but Not same with dble.
but dble treat the first column as char not varchar,need to fix

2. all inner join results are right :
dble explain paln :
```
mysql> explain SELECT SUBSTR(hi.consumer_id,1,14) as cid,avg(hdn.heat) from data
_now as hdn
    -> inner JOIN user_info as hi
    -> ON hdn.consumer_id = hi.consumer_id and hdn.company_id = '00019' and hi.c
ompany_id = '00019'
    -> GROUP BY SUBSTR(hi.consumer_id,1,14)
    -> LIMIT 100;
+-----------+----------+--------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------+
| DATA_NODE | TYPE     | SQL/REF


                                |
+-----------+----------+--------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------+
| dn2       | BASE SQL | SELECT SUBSTR(hi.consumer_id,1,14) as cid,avg(hdn.heat)
 from data_now as hdn  inner JOIN user_info as hi  ON hdn.consumer_id = hi.consu
mer_id and hdn.company_id = '00019' and hi.company_id = '00019' GROUP BY SUBSTR(
hi.consumer_id,1,14)  LIMIT 100 |
+-----------+----------+--------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------+
1 row in set (0.00 sec)
```

**Comment by yanhuqing666** [comment]
inner join error because of https://actiontech.github.io/dble-docs-cn/A.Faq/ErrorCode/Content/NestLoopParametersLeadToTemptableException.html

**Comment by yanhuqing666** [comment]
It still has two problems, one is that SQL `SELECT SUBSTR(hi.consumer_id,1,14) as cid,avg(hdn.heat) from data_now as hdn inner JOIN user_info as hi ON hdn.consumer_id = hi.consumer_id and hdn.company_id = '00019' GROUP BY SUBSTR(hi.consumer_id,1,14) LIMIT 1000`  route to complex query. the second is the dataType, if may same with the issue #1417

**Comment by sunsun314** [comment]
The explain result is correct, just need to verify the dataType

**Comment by irene-coming** [comment]
reorganize the issue:
**schema.xml:**
```xml
        <table name="user_info" dataNode="dn1,dn2" rule="hash-two"/>
        <table name="data_now" dataNode="dn1,dn2" rule="hash-two"/>
```
**steps**
step1. prepare table in dble:
```mysql
CREATE TABLE `data_now` (
  `meter_id` varchar(32) NOT NULL,
  `consumer_id` varchar(32) NOT NULL,
  `heat` decimal(18,2) DEFAULT NULL,
  `id` varchar(32) NOT NULL,
  PRIMARY KEY (`meter_id`),
  KEY `meter_id` (`meter_id`) USING BTREE,
  KEY `id` (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `user_info` (
  `consumer_id` varchar(32) NOT NULL,
  `id` varchar(32) NOT NULL,
  PRIMARY KEY (`consumer_id`),
  KEY `consumer_id` (`consumer_id`) USING BTREE,
  KEY `id` (`id`) USING BTREE,
  KEY `cc` (`consumer_id`,`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `data_now` VALUES ('01005961000100101010101', '0059610001001010101', '41243.46', '00596');
INSERT INTO `data_now` VALUES ('01000190000802501001东01', '000190000802501001东', '22499.41', '00019');
INSERT INTO `user_info` VALUES ('0059610001001010101', '00596');
INSERT INTO `user_info` VALUES ('000190000802501001东', '00019');
```
step2. query with python cmd line to dble master
```python
>>> import MySQLdb
>>> conn1=MySQLdb.connect('172.100.9.1','test','111111','schema1',8066)
>>> cur1=conn1.cursor()
>>> cur1.execute("select substr(ui.consumer_id,1,14) as uid,avg(dn.heat) from data_now as dn left join user_info as ui on dn.consumer_id=ui.consumer_id and dn.id='00019' and ui.id='00019' group by substr(ui.consumer_id,1,14) limit 1000")
2L
>>> cur1.description
(('uid', 253, 14, 0, 0, 31, 0), ('AVG(dn.heat)', 246, 12, 40, 40, 2, 1))
```
step3. query with python cmd line to dble 2.19.09.1
```python
>>> conn2=MySQLdb.connect('172.100.9.2','test','111111','schema1',8066)
>>> cur2=conn2.cursor()
>>> cur2.execute("select substr(ui.consumer_id,1,14) as uid,avg(dn.heat) from data_now as dn left join user_info as ui on dn.consumer_id=ui.consumer_id and dn.id='00019' and ui.id='00019' group by substr(ui.consumer_id,1,14) limit 1000")
2L
>>> cur2.description
(('uid', 254, 14, 0, 0, 31, 0), ('AVG(dn.heat)', 0, 12, 40, 40, 2, 1))
```
step4. query with python cmd line to mysql
```python
>>> conn3=MySQLdb.connect('172.100.9.4','test','111111','zhj',3306)
>>> cur3=conn3.cursor()
>>> cur3.execute("select substr(ui.consumer_id,1,14) as uid,avg(dn.heat) from data_now as dn left join user_info as ui on dn.consumer_id=ui.consumer_id and dn.id='00019' and ui.id='00019' group by substr(ui.consumer_id,1,14) limit 1000")
2L
>>> cur3.description
(('uid', 253, 14, 14, 14, 0, 1), ('avg(dn.heat)', 246, 12, 24, 24, 6, 1))
```

**expect:** 
step2, dble's cur1.description are same with mysql's in step4

**real:**
the early dble version eg dble-2.19.09.1(in step3) make resultset column type as 254 when expect 253

**ps:** 
the second element of curX.description stands for data type of the resultset column

VAR_STRING = 253
STRING = 254

python MySQLdb resultset column type ref:
https://github.com/PyMySQL/mysqlclient-python/blob/master/MySQLdb/constants/FIELD_TYPE.py
https://github.com/PyMySQL/mysqlclient-python/blob/master/MySQLdb/cursors.py
https://www.python.org/dev/peps/pep-0249/#description

verified on dble: 5.6.29-dble-9.9.9.9-96c130230a2ef9268bdb3605e190d559b0439625-20200203081515
