### ISSUE TITLE
DDL separate from general queries

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#1524]
Now the DDL executes with two query-handlers (SingleNodeHandler/MultiNodeQueryHandler) and general queries are also use these handlers. As a result, both SingleNodeHandler & MultiNodeQueryHandler has lots of extra logic for DDL SQL.  When sometime DDL can hang the meta lock of the table, these handlers can not provide enough log for problem identification. 
  In summary, we thought that it is time to separate DDL handlers form general-query-handlers. we try to separate the handlers into MultiNodeDDLHandler & SingleNodeDDLHandler and add a log trace system for DDL only.

**Comment by irene-coming** [comment]
verified on dble: 5.6.29-dble-9.9.9.9-96c130230a2ef9268bdb3605e190d559b0439625-20200203081515
