### ISSUE TITLE
synax 'limit 0' will return all rows

### ISSUE THREAD

**Issue by ssxlulu** [actiontech/dble#1525]
A simple configuration of sharding table will cause such exception.

Here are the configurations:

schema.xml:
```
<table name="test" dataNode="dn1,dn2" rule="rule_test"/>
```
rule.xml:
```
<tableRule name="rule_test">
        <rule>
            <columns>id</columns>
            <algorithm>func1</algorithm>
        </rule>
    </tableRule>

<function name="func1" class="com.actiontech.dble.route.function.PartitionByLong">
        <property name="partitionCount">2</property>
        <property name="partitionLength">512</property>
    </function>
```

When I execute the sql ` select * from (select * from test) b limit 0;`, dble will return all rows of the tables.

![image](https://user-images.githubusercontent.com/14773179/70045673-73b05080-15ff-11ea-99ac-61304123f329.png)

Following is the explanation of the sql:

![image](https://user-images.githubusercontent.com/14773179/70046031-28e30880-1600-11ea-825e-f3d470df1d0a.png)

**Comment by gaopengpeng123456** [comment]
Code has been submitted

**Comment by irene-coming** [comment]
verified on dble: 5.6.29-dble-9.9.9.9-96c130230a2ef9268bdb3605e190d559b0439625-20200203081515
