### ISSUE TITLE
sysbench prepare  db_bulk_insert_done() failed

### ISSUE THREAD

**Issue by ppsoula** [actiontech/dble#1537]
* **dble version：**  
dble-2.19.09.0
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  
```xml
<dble:schema xmlns:dble="http://dble.cloud/" version="1.0">

    <schema name="mytest">
        <table name="sbtest1" primaryKey="ID" dataNode="dn$1-6" rule="hash-sysbench"/>
    </schema>


    <!-- <dataNode name="dn1$0-743" dataHost="dataHost1" database="db$0-743" /> -->
    <dataNode name="dn1" dataHost="mysql_1" database="db_1"/>
    <dataNode name="dn2" dataHost="mysql_1" database="db_2"/>
    <dataNode name="dn3" dataHost="mysql_1" database="db_3"/>
    <dataNode name="dn4" dataHost="mysql_2" database="db_4"/>
    <dataNode name="dn5" dataHost="mysql_2" database="db_5"/>
    <dataNode name="dn6" dataHost="mysql_2" database="db_6"/>

    <dataHost name="mysql_1" maxCon="1000" minCon="10" balance="0" switchType="-1" slaveThreshold="100">
        <heartbeat>select user()</heartbeat>
        <!-- can have multi write hosts -->
        <writeHost host="hostM1" url="192.168.3.40:33061" user="root" password="123456"></writeHost>
    </dataHost>

    <dataHost name="mysql_2" maxCon="1000" minCon="10" balance="0" switchType="-1" slaveThreshold="100">
        <heartbeat>select user()</heartbeat>
        <!-- can have multi write hosts -->
        <writeHost host="hostM2" url="192.168.3.40:33062" user="root" password="123456"></writeHost>
    </dataHost>
</dble:schema>
```
**rule.xml**  
```xml
<dble:rule xmlns:dble="http://dble.cloud/" version="1.0">
    <tableRule name="hash-sysbench">
        <rule>
            <columns>id</columns>
            <algorithm>hash-sysbench</algorithm>
        </rule>
    </tableRule>

    <!-- hash-sysbench -->
    <function name="hash-sysbench" class="Hash">
        <property name="partitionCount">6</property>
        <property name="partitionLength">1</property>
    </function>
</dble:rule>
```
**server.xml**  
```xml
<dble:server xmlns:dble="http://dble.cloud/">
    <system>
        <property name="processors">10</property>
        <property name="backendProcessors">10</property>
        <property name="processorExecutor">8</property>
        <property name="backendProcessorExecutor">6</property>
        <property name="sqlExecuteTimeout">3000000</property>
    </system>
    <user name="test">
        <property name="password">111111</property>
        <property name="schemas">mytest</property>
        <property name="maxCon">1000000</property>
    </user>
     <user name="root">
         <property name="password">123456</property>
         <property name="manager">true</property>
      </user>
</dble:server>
```
* **steps：**    
    step1. dble status 
* **expect result：**  
   [root@mysqldb dble]# ./bin/dble status
dble-server is running (15688).
 step2.  mysql status
* **expect result：**  
[root@mysqldb dble]# ps -ef |grep mysql
root      6952     1  0 Dec05 ?        00:00:00 /bin/sh /usr/local/mysql_1/bin/mysqld_safe --defaults-file=/etc/33061.cnf
mysql     8284  6952  0 Dec05 ?        00:06:10 /usr/local/mysql_1/bin/mysqld --defaults-file=/etc/33061.cnf --basedir=/usr/local/mysql_1 --datadir=/app/mysql_1 --plugin-dir=/usr/local/mysql_1/lib/plugin --use
r=mysql --log-error=/app/mysql_1/error.log --open-files-limit=65535 --pid-file=mysql_1.pid --socket=/app/mysql_1/mysql.sock --port=33061root     10088     1  0 Dec05 ?        00:00:00 /bin/sh /usr/local/mysql_1/bin/mysqld_safe --defaults-file=/etc/33062.cnf
mysql    11374 10088  0 Dec05 ?        00:06:08 /usr/local/mysql_1/bin/mysqld --defaults-file=/etc/33062.cnf --basedir=/usr/local/mysql_1 --datadir=/app/mysql_2 --plugin-dir=/usr/local/mysql_1/lib/plugin --use
r=mysql --log-error=/app/mysql_2/error.log --open-files-limit=65535 --pid-file=mysql_2.pid --socket=/app/mysql_2/mysql.sock --port=33062root     12012 23722  0 18:33 pts/4    00:00:00 grep --color=auto mysql
 step3. systench prepare data
* **Error result：**  
[root@mysqldb ~]# sysbench --mysql-host=192.168.3.40 --mysql_port=8066 --mysql-db=mytest --mysql-user=test --mysql-password=111111 --table-size=100 oltp_read_only prepare
sysbench 1.0.17 (using system LuaJIT 2.0.4)

Creating table 'sbtest1'...
Inserting 100 records into 'sbtest1'
FATAL: mysql_drv_query() returned error 1064 (bad insert sql, sharding column/joinKey:ID not provided,INSERT INTO sbtest1 (k, c, pad)
VALUES (50, '83868641912-28773972837-60736120486-75162659906-27563526494-20381887404-41576422241-93426793964-56405065102-33518432330', '67847967377-48000963322-62604785301-91415491898-96926520291'),
	(51, '38014276128-25250245652-62722561801-27818678124-24890218270-18312424692-92565570600-36243745486-21199862476-38576014630', '23183251411-36241541236-31706421314-92007079971-60663066966'),
	(51, '33973744704-80540844748-) for query 'INSERT INTO sbtest1(k, c, pad) VALUES(50, '83868641912-28773972837-60736120486-75162659906-27563526494-20381887404-41576422241-93426793964-56405065102-3351843
2330', '67847967377-48000963322-62604785301-91415491898-96926520291'),(51, '38014276128-25250245652-62722561801-27818678124-24890218270-18312424692-92565570600-36243745486-21199862476-38576014630', '23183251411-36241541236-31706421314-92007079971-60663066966'),(51, '33973744704-80540844748-72700647445-87330233173-87249600839-07301471459-22846777364-58808996678-64607045326-48799346817', '38615512647-91458489257-90681424432-95014675832-60408598704'),(51, '37002370280-58842166667-00026392672-77506866252-09658311935-56926959306-83464667271-94685475868-28264244556-14550208498', '63947013338-98809887124-59806726763-79831528812-45582457048'),(50, '44257470806-17967007152-32809666989-26174672567-29883439075-95767161284-94957565003-35708767253-53935174705-16168070783', '34551750492-67990399350-81179284955-79299808058-21257255869'),(51, '37216201353-39109531021-11197415756-87798784755-02463049870-83329763120-57551308766-61100580113-80090253566-30971527105', '05161542529-00085727016-35134775864-52531204064-98744439797'),(51, '33071042495-29920376648-91343430102-79082003121-73317691963-02846712788-88069761578-14885283975-44409837760-90760298045', '91798303270-64988107984-08161247972-12116454627-22996445111'),(50, '73754818686-04889373966-18668178968-56957589012-31352882173-91882653509-59577900152-88962682169-52981807259-62646890059', '76460662325-41613089656-42706083314-81833284991-17063140920'),(53, '26482547570-00155460224-12388481921-23289186371-78242522654-77998886134-73270876420-50821093220-31442690639-11588920653', '30508501104-50823269125-88107014550-70202920684-95842308929'),(51, '05677017559-47107518969-97509137401-28934334557-14497052050-61906823704-44077628507-24840441785-05187301456-27797851637', '29489382504-13697582598-09964978366-26554639515-36136545002'),(55, '69916792160-36263343577-60040896157-93749675091-85349848150-51324584648-99894376828-35106327881-24322876464-85736660000', '87387995487-76363627904-22109071019-39590329504-09541621871'),(49, '06636928111-91412549319-87017689961-79500497523-29051692073-64380774874-78643769852-73373361096-34215043106-34370178281', '89292458800-98111883088-45119613990-18776802947-72334127545'),(45, '66692787527-64669315176-31954384866-40167063199-20714065413-78429761915-37156169484-48536455204-68184091915-53509501438', '38086179531-74613680033-74030836539-16618852001-68255032383'),(50, '03057970397-76844598219-57919615042-40446066254-53006176529-07928677880-76521527831-33188464243-14751964794-48299542958', '58289547349-70221859996-98108169071-42919560989-03199891667'),(50, '46727919633-45146044920-86415428832-97681745441-41127226689-79274197453-43262911115-03302568793-24793907254-41889251160', '16558229746-31933003433-90307278632-58399899267-20471559033'),(62, '66674934079-61932070973-59260913966-95805894865-93643781508-42542760387-65244531372-94908882784-73015194138-09444593269', '57753529930-52222322149-80867581160-08150406969-39000857332'),(50, '42863854528-01081829164-15763552981-12403743290-73250276677-11227646213-34508938444-96091116410-30361051807-02401305678', '30113872711-60560384806-74864932945-57589062046-96056547221'),(50, '82991834540-27107960725-55255797929-15631102224-93218976341-02587259718-39218801679-60059023868-06269782489-88220383890', '22351958118-81193937039-05255492720-04288594638-80971142475'),(50, '50775217476-73338282083-95609959533-46458517058-432FATAL: `sysbench.cmdline.call_command' function failed: /usr/share/sysbench/oltp_common.lua:233: db_bulk_insert_done() failed

**Comment by langkaixin** [comment]
Reason for error：
id does not have value because no configuration "autoIncrement='true'" in schema.xml

fix:
way 1: add --auto_inc=off（the parameter before sysbench1.0.0 is: --oltp_auto_inc=off） to the sysbench command to not use mysql's auto_increment.
way 2: if you really want to use the auto inc:
2.1, if the table is not sharded, then correct the lua, change insert into sbtest1 values(xxxx...) to insert into sbtest1(col-name,xx, xx) values(xxxx...)
2.2, the table is sharded, then use dble's global sequence( the performance may out of your expect)
