### ISSUE TITLE
change dataHost from disabled to enabled, the heartbeat does not recover

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#1538]
* **dble version：**  
5.6.29-dble-9.9.9.9-00e50d172cecce23053131a37b11955d6a776dcb-20191209144118
* **preconditions ：**  
dataHost at disabled state
* **configs：** 

**schema.xml**  

```
	<dataHost balance="0" maxCon="1000" minCon="10" name="host1" slaveThreshold="100" switchType="1">
		<heartbeat>select user()</heartbeat>
		<writeHost host="hostM1" password="111111" url="xx.xx.xx.xx:xxxx" user="test">
		</writeHost>
	</dataHost>

	<dataHost balance="0" maxCon="1000" minCon="10" name="host2" slaveThreshold="100" switchType="1">
		<heartbeat>select user()</heartbeat>
		<writeHost host="hostM2" password="111111" url="xx.xx.xx.xx:xxxx" user="test">
		</writeHost>
	</dataHost>

```

**rule.xml**  

```


```

**server.xml**  

```
<property name="useOuterHa">true</property>

```

* **steps：**    
    step1.  start dble at host1 at disabled state
    step2. connect dble and do query:
```mysql
mysql> show tables;
ERROR 1064 (HY000): java.io.IOException: the dataHost[host1] is disabled, please check it
```
  step3. execute manager cmd to enable the disabled host
```mysql
mysql> dataHost @@enable name='host1';
Query OK, 0 rows affected (0.01 sec)
```
  step4. do query:
```mysql
mysql> show tables;
ERROR 1064 (HY000): java.io.IOException: the data source[10.186.63.134:7145] can't reached, please check the dataHost
```
* **expect result：**  
    1. step4 execute success
* **real result：**  
    1. step4 failed
* **supplements：**  
    1. if disabled dataHost online, the problem can not be reproduced

**Comment by yanhuqing666** [comment]
may need added to 2.19.09.1

**Comment by irene-coming** [comment]
verified on dble: 5.6.29-dble-9.9.9.9-96c130230a2ef9268bdb3605e190d559b0439625-20200203081515
