### ISSUE TITLE
need compatible with all mysql versions for system variable "transaction_isolation(>=5.7.20)" and "tx_isolation(<5.7.20)" 

### ISSUE THREAD

**Issue by wjl1619** [actiontech/dble#1542]
* **dble version：**  
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  
* **expect result：**  
    1.
* **real result：**  
    1.
* **supplements：**  
    1.

**Comment by yanhuqing666** [comment]
delay

**Comment by yanhuqing666** [comment]
DBLE WILL accept  "transaction_isolation(>=5.7.20)" and "tx_isolation(<5.7.20)" and "transaction_read_only(>=5.7.20)" and "tx__read_only(<5.7.20)".
AND use `tx` to send to MySQL(<8.0 ) AND use  `transaction` to send to MySQL(>=8.0 )
