### ISSUE TITLE
loosen the check of the "show database " statement

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#1550]
PhyMyAdmin can use a config like "$cfg['Servers'][$i]['DisableIS'] = true;" to connect to dble, but the database list use "show databases xxx" has some problem in dble. So we decide to loosen the check of the statement to let the phpMyAdmin work normally. Specifically, loosen show database statement let the statement to be returned normally with whatever added in tail

**Comment by wjl1619** [comment]
verified on version: 5.6.29-dble-2.19.11.0-a8b6cf2daf30fd1dedb6e91294d8b6839e730386-20200211092945
