### ISSUE TITLE
请问dble可以和mysql数据保持主从同步吗

### ISSUE THREAD

**Issue by czxin788** [actiontech/dble#1568]
我们正在调研dble。
我们的现状是主库mysql上有几张大表，我们想把这几张大表通过dble做水平拆分到几个实例中。
我想问的是我怎么样在不停服务的状态下，把mysql主库上的业务在线切换到dble上。
可以做mysql---->dble的主从同步吗。
如果能做到mysql---->dble---->mysql的主从同步就更好了，这样如果不想用dble了，还可以回滚到mysql单实例方案。

请问，这样的主从复制，dble支持吗

**Comment by sunsun314** [comment]
Some tools maybe have some help, research for [dtle](https://github.com/actiontech/dtle), please
