### ISSUE TITLE
[Discuss]关于DBLE的嵌套使用场景

### ISSUE THREAD

**Issue by zhaoshan86** [actiontech/dble#1583]
今日在群里有朋友询问DBLE嵌套使用的需求，我们也接到一个类似的需求:

有几个客户他们想把下属单位的所有数据库的数据都统一管理和审计，然后能够做数据共享。开始我们给的建议是用数据仓库把数据收上去，但是客户觉得实时性不好，也太重。他们想要一个类似数据联邦的方案，请求都是只读，且对请求的性能要求不高。

我们考虑了一下，可以用dble干这个事，每个datanode对应一个schema，用一个账户一个连接地址就可以查所有的库。而且dble里有连接池，可以降低对下游数据库的连接负载。

唯一的问题就是，下游数据库有的可能已经用了mycat或者dble做分库分表（或者未来想用），这就产生了中间件嵌套使用的场景，希望能够一同讨论下这个方案的可行性。

**Comment by irene-coming** [comment]
GitVersion 0bd119f7d9169b81808a54722958838718303940
BuildTime  20200205035800
MavenVersion 9.9.9.9

with conf in schema.xml
```xml
<!DOCTYPE dble:schema SYSTEM "schema.dtd">
<dble:schema xmlns:dble="http://dble.cloud/">
    <schema name="schema1" sqlMaxLimit="100">
        <table name="sharding_1_t1" dataNode="dn1"/>
    </schema>
    <schema name="schema2" sqlMaxLimit="100" >
        <table name="sharding_2_t1" dataNode="dn2" />
    </schema>
    <dataNode name="dn1" dataHost="ha_group1" database="schema1"/>
    <dataNode name="dn2" dataHost="ha_group1" database="schema2"/>
    <dataHost balance="0" maxCon="1000" minCon="10" name="ha_group1" switchType="1" slaveThreshold="100">
        <heartbeat>select user()</heartbeat>
        <writeHost host="hostM1" url="172.100.9.2:8066" password="111111" user="test" disabled="false" id="hostM1" weight="0"/>
    </dataHost>
</dble:schema>
```
172.100.9.2:8066 is another dble instance in running

connect to dble hang:
![image](https://user-images.githubusercontent.com/6801133/73834844-63a72e00-4847-11ea-8409-f839ee5073af.png)

**Comment by irene-coming** [comment]
verified on dble:5.6.29-dble-9.9.9.9-0bd119f7d9169b81808a54722958838718303940-20200205035800

both the parent and child embeded dble version should greater then or equal 2.19.11.0

**Comment by irene-coming** [comment]
verified on dble: 5.6.29-dble-2.19.11.0-2d7c4911b7a4fecaa9eb0299f49c32ec11e97c42-20200220121659
