### ISSUE TITLE
Compound SQL statement returned package error

### ISSUE THREAD

**Issue by gaopengpeng123456** [actiontech/dble#1618]
* **dble version：**  
5.6.29-dble-9.9.9.9-39f7dce0882288cad7fdc38ce4b509be58f27006-20200107103915
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  
```
<schema name="testdb">
        <table name="tb_enum_sharding" primaryKey="ID" dataNode="dn1"/>            
 </schema>

 <dataNode name="dn1" dataHost="dataHost1" database="db_1"/>

<dataHost name="dataHost1" maxCon="1000" minCon="10" balance="0" switchType="-1" slaveThreshold="100">
        <heartbeat>show slave status</heartbeat>
        <writeHost host="hostM1" url="localhost:3306" user="root" password="123456">           
        </writeHost>
    </dataHost>

```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    mysql> delimiter //
    mysql> SET autocommit=1;show databases//
* **expect result：**  
     Query OK, 0 rows affected (0.00 sec)

    +----------+
     | DATABASE |
    +----------+
     | testdb     |
    +----------+
    1 row in set (0.00 sec)
* **real result：**  

     Query OK, 0 rows affected (0.00 sec)
* **supplements：**  
    1.#1583

**Comment by irene-coming** [comment]
verified on dble: 5.6.29-dble-9.9.9.9-96c130230a2ef9268bdb3605e190d559b0439625-20200203081515
