### ISSUE TITLE
Fail to insert or update emoji/uncommon character without jdbc param "characterEncoding=utf8"

### ISSUE THREAD

**Issue by feixuefubing** [actiontech/dble#1625]
* **dble version：**  
2.19.09.0
* **preconditions ：**  
1.my.cnf on every mysql node, with "character_set_server=utf8mb4"
2.all mysql tables, CHARSET=utf8mb4
3.default server.xml [system] config
4.success with single mysql node but fail with dble
* **configs：** 

**server.xml**   default

* **steps：**    
    step1.  
* **expect result：**  
     execute successful
* **real result：**  
     java.sql.SQLException: Incorrect string value: '\xF0\xA0\x82\x86\xE8\xB5...'...
* **supplements：**  
    1.fail either use druid or simple jdbc.
    2.also fail either use Statement or PreparedStatement.

**Comment by FlyingMao** [comment]
**verified version：** dble-9.9.9.9-36e137ef5a193ed7494eb59317ac3630182de606-20200410030249
