### ISSUE TITLE
execute sql "show warnings" causing error : lost connection to MySQL server during query

### ISSUE THREAD

**Issue by langkaixin** [actiontech/dble#1634]
* **dble version：**  5.6.29-dble-9.9.9.9-801996f3a36d6e062a49cb9b8afa7a3b179ebbae-20200114090626 
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```

```

**rule.xml**  

```
 
```

**server.xml**  

```

```

* **steps：**  
  
step1.
mysql -utest -p111111 -P8066
mysql> show warnings;
ERROR 2013 (HY000): Lost connection to MySQL server during query

  
* **expect result：**  
    1.no error
* **real result：**  
    1.ERROR 2013 (HY000): Lost connection to MySQL server during query
* **supplements：**  
    1.

**Comment by yanhuqing666** [comment]
https://github.com/actiontech/dble/commit/ddb1c090d0ec600948dcffebca1fc9fa028badcb

**Comment by langkaixin** [comment]
dble-version:
5.6.29-dble-9.9.9.9-3bc0fd1498a4e28065918507d64ee63ca440d386-20200210030514
