### ISSUE TITLE
restart mysql node causing sql err: the data source[172.100.9.5:3306] can't reached. Please check the dataHost status

### ISSUE THREAD

**Issue by langkaixin** [actiontech/dble#1638]
* **dble version：**  5.6.29-dble-9.9.9.9-ddb1c090d0ec600948dcffebca1fc9fa028badcb-20200115071303
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    

### step1.  
mysql -utest -p111111 -P8066
mysql> use schema1;
mysql> select * from sharding_4_t1;
Empty set (0.04 sec)

### step2.
[root@mysql-master1 opt]# /usr/local/mysql/support-files/mysql.server stop   
Shutting down MySQL.... SUCCESS! 
[root@mysql-master1 opt]# /usr/local/mysql/support-files/mysql.server start
Starting MySQL. SUCCESS! 

### step3.
wait a minute

### step4.
mysql -utest -p111111 -P8066
mysql> use schema1;
mysql> select * from sharding_4_t1;
ERROR 3009 (HY000): java.io.IOException: the data source[172.100.9.5:3306] can't reached. Please check the dataHost status

* **expect result：**  
    1.no error in step3
* **real result：**  
    1.report error : the data source[172.100.9.5:3306] can't reached. Please check the dataHost status
* **supplements：**  
    1.

**Comment by irene-coming** [comment]
verified on dble: 5.6.29-dble-9.9.9.9-1dac35e8f0c5b8cd09b13c2a027aaf0d32113306-20200117021241
