### ISSUE TITLE
有个想法：3个配置文件能否从远程加载，并实现热刷新

### ISSUE THREAD

**Issue by youbeiwuhuan** [actiontech/dble#1641]
我希望的：
1. 3个xml配置文件从配置中心加载，并可以在管理后台系统修改后被指定的dble实例感知生效。
2. dble实例能够注册到注册中心，通过管理后台系统实现dble实例的回收和再次部署，这些都可以在管理后台完成
3. 实现了1和2，基本实现了dble的自动化部署。dble能否开源出配套的监控后台

**Comment by yanhuqing666** [comment]
see  https://actiontech.github.io/dble-docs-cn/2.Function/2.08_cluster.html

**Comment by yanhuqing666** [comment]
And For 3， you can contact our sales team:
Global Sales: 400-820-6580
North China: 86-13718877200, Mr.Wang
South China: 86-18503063188, Mr.Cao
East China: 86-18930110869, Mr.Liang
South-West China: 86-13540040119, Mr.Hong
