### ISSUE TITLE
drop table in one of the backend sharding, check full @@metadata's result of consistent_in_data_nodes is 1,expect 0

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#1642]
* **dble version：**  
5.6.29-dble-9.9.9.9-02991f71759b437db3a6fc93343e2c9cd3c62c50-20200116025018
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```
      <table name="test4" dataNode="dn1,dn2,dn3,dn4" rule="hash-four" cacheKey="id"/>
```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  drop table at backend,eg dn1
```mysql
drop table if exists test4
```
    step2. reload @@metadata
    step3. check full @@metadata
```mysql
+
| schema  | table | reload_time         | table_structure                                                                                                                                 | consistent_in_data_nodes | consistent_in_memory |
+---------+-------+---------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------+----------------------+
| schema1 | test4 | 2020/01/17 11:01:29 | CREATE TABLE `test4` (
	`id` int(11) DEFAULT NULL,
	`name` char(1) DEFAULT NULL
) ENGINE = InnoDB CHARSET = latin1                              |                        1 |                    1 |
```
* **expect result：**  
    1.step3, consistent_in_data_nodes value expect 0
* **real result：**  
    1.
* **supplements：**  
    1.found from autotest check_full_metadata.feature Scenario#5

**Comment by wjl1619** [comment]
verified on version: 5.6.29-dble-9.9.9.9-0bd119f7d9169b81808a54722958838718303940-20200205035800
