### ISSUE TITLE
open xa transaction and insert data, then stop datanode causing "commit" hangs

### ISSUE THREAD

**Issue by langkaixin** [actiontech/dble#1644]
* **dble version：**  5.6.29-dble-9.9.9.9-1dac35e8f0c5b8cd09b13c2a027aaf0d32113306-20200117021241
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**
    
### step1.  
mysql> drop table if exists sharding_4_t1;
Query OK, 0 rows affected (0.03 sec)
mysql> create table sharding_4_t1 (id int,customerid int,accountno varchar(20),amount decimal(10,2));
Query OK, 0 rows affected (0.01 sec)
mysql> set autocommit = 0;
Query OK, 0 rows affected (0.00 sec)
mysql> set xa=1;
Query OK, 0 rows affected (0.00 sec)
mysql> begin;
Query OK, 0 rows affected (0.00 sec)
mysql> insert into sharding_4_t1 (id, customerid, accountno, amount) values (1, 1,'a0301',0),(2,2,'a0601',0), (3,3,'a0301',0),(4,601,'a0601',0);
Query OK, 4 rows affected (0.01 sec)
mysql> select * from sharding_4_t1 order by id;
+------+------------+-----------+--------+
| id   | customerid | accountno | amount |
+------+------------+-----------+--------+
|    1 |          1 | a0301     |   0.00 |
|    2 |          2 | a0601     |   0.00 |
|    3 |          3 | a0301     |   0.00 |
|    4 |        601 | a0601     |   0.00 |
+------+------------+-----------+--------+
4 rows in set (0.01 sec)

### step2.
stop mysql-master1:
/usr/local/mysql/support-files/mysql.server stop

### step3.
mysql> commit;

* **expect result：**  
    1.ERROR 1105 (HY000): Connection {DataHost[172.100.9.5:3306],Schema[db1],threadID[184]} was closed
* **real result：**  
    1.commit hangs
* **supplements：**  
    1.

**Comment by Baofengqi** [comment]
can't reproduce, pls choose lateset version to confirm again.

**Comment by yanhuqing666** [comment]
Close if it can't be reproduced until 2.20.04.0

**Comment by Baofengqi** [comment]
It still can't be reproduced.
