### ISSUE TITLE
need support sql [SELECT * FROM t1 a left join t2 c on a.id=c.id and a.id=@id_a;] when don't set a value for variable "@id_a"

### ISSUE THREAD

**Issue by wjl1619** [actiontech/dble#1650]
* **dble version：**  
5.6.29-dble-2.19.11.0-3924537e81390ba76656e3c5071c194c7be7923b-20200210030705
* **preconditions ：**  
```sql
drop table if exists sharding_2_t1;
drop table if exists schema2.sharding_3_t1;
create table sharding_2_t1(id int(4), B float(8,2)) ;
insert into sharding_2_t1 values(1,234.25),(2,67.29),(3,1.25),(12,1),(1,234.25) ;
create table schema2.sharding_3_t1(id int(4), B int(4)) ;
insert into schema2.sharding_3_t1 values (10, 1),(11, 2),(10,2) ;
```
* **configs：** 

* **steps：**    
    step1. **DO NOT** set variable "@id_a" a value in dble
    step2. query in dble:
```sql
SELECT * FROM sharding_2_t1 a left join schema2.sharding_3_t1 c  on a.id=c.id and a.id=@id_a;
```
* **expect result：**  
    1.mysql> SELECT * FROM sharding_2_t1 a left join schema2.sharding_3_t1 c  on a.id=c.id and a.id=@id_a;
+------+--------+------+------+
| id   | B      | id   | B    |
+------+--------+------+------+
|    1 | 234.25 | NULL | NULL |
|    2 |  67.29 | NULL | NULL |
|    3 |   1.25 | NULL | NULL |
|   12 |   1.00 | NULL | NULL |
|    1 | 234.25 | NULL | NULL |
+------+--------+------+------+
5 rows in set (0.00 sec)

* **real result：**  
    1.mysql> SELECT * FROM sharding_2_t1 a left join schema2.sharding_3_t1 c  on a.id=c.id and a.id=@id_a;
ERROR 1003 (HY000): field not found:@id_a

* **supplements：**  
    1.

**Comment by FlyingMao** [comment]
**verified version:** dble-9.9.9.9-14e43f2e85d2b29aea766d8836f6f799bee2fb2d-20200401051400
