### ISSUE TITLE
template_table.sql   这个sql文件运行不起来。。。

### ISSUE THREAD

**Issue by aihuaiyang** [actiontech/dble#1651]
* **dble version：**  
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  
* **expect result：**  
    1.
* **real result：**  
    1.
* **supplements：**  
    1.

**Comment by yanhuqing666** [comment]
need more detail

**Comment by yanhuqing666** [comment]
no more information
