### ISSUE TITLE
er table: when insert values into child table, if the connection of checking parent table have the value was killed, it should be feedfack a resonable error message

### ISSUE THREAD

**Issue by wjl1619** [actiontech/dble#1655]
* **dble version：**  
5.6.29-dble-2.19.11.0-a8b6cf2daf30fd1dedb6e91294d8b6839e730386-20200211092945
* **preconditions ：**  
```sql
drop table if exists table_b;
drop table if exists table_c;
create table table_b(id int,name varchar(40));
create table table_c(name varchar(40),id int);
insert into table_b set id = 1,name = "xx";
```
* **configs：** 

**schema.xml**  

```xml
 <schema name="schema1" sqlMaxLimit="100">
        <table name="table_b" dataNode="dn1,dn2" rule="hash-two">
        <childTable name="table_c" joinKey="name" parentKey="name">
        </childTable>
        </table>
    </schema>
    <dataNode dataHost="ha_group1" database="db1" name="dn1" />
    <dataNode dataHost="ha_group2" database="db1" name="dn2" />
```

* **steps：**    
    step1.  lock tables in dn2 for response delay. in dn2 backend mysql server execute:
    ```sql
    lock tables table_b write;
    ```
    step2. in dble query:
    ```sql
    insert into table_c set id = 5,name = "xx";
    ```
    step3. kill backend conn for searching parent sharding in dn2 backend mysql. execute: kill         thread of {SELECT table_b.NAME FROM table_b WHERE table_b.NAME='xx'}
    then unlock tables on dn2
* **expect result：**  
    1.step2: insert into table_c set id = 5,name = "xx"; got error and the error message need easy to tell what really happened.
* **real result：**  
    1.step2 feedback: mysql> insert into table_c set id = 5,name = "xx";
ERROR 1105 (HY000): can't find (root) parent sharding node for sql:INSERT INTO table_c (id, name)
VALUES (5, 'xx')

* **supplements：**  
    1.

**Comment by leixia2018** [comment]
verified on version : 5.6.29-dble-9.9.9.9-7144885389c9e27df61996d0de5408c7a3a57b0e-20200424071334
now result  as follows:
```
mysql> insert into table_c set id = 5,name = "xx";
ERROR 1105 (HY000): ConnectionException [code=1105, msg=Find (root) parent sharding node occur error: {[dn2:connection closed ,mysql id:113],}]
```
