### ISSUE TITLE
tempReadHostAvailable="1",<heartbeat>show slave status</heartbeat>    not work 

### ISSUE THREAD

**Issue by dairight** [actiontech/dble#1658]
一.Version
GitVersion 83bcd35b0a53c717a7fd8838ff1dcdf5fbb31353
BuildTime  20190702053754
MavenVersion 2.19.05.0

二.Demand:Same group dataHost,writeHost down,readHost can continue to work

三.Configuration
`
<dataHost name="dataHost1" maxCon="1000" minCon="10" balance="3" switchType="-1" slaveThreshold="100" tempReadHostAvailable="1">
        <heartbeat>show slave status</heartbeat>
        <writeHost host="hostM1" url="192.168.1.41:3306" user="root" password="123456">
         <readHost host="hostS1" url="192.168.1.42:3306" user="root" password="123456"/>
        </writeHost>
</dataHost>
`
四.Parameter test
`
1.tempReadHostAvailable="1",<heartbeat>show slave status</heartbeat>    not work    X
2.tempReadHostAvailable="1",<heartbeat>select 1</heartbeat>                 work    √
3.tempReadHostAvailable="1",<heartbeat>select user()</heartbeat>            work    √
`
五.Question:
`<heartbeat>show slave status</heartbeat>  why not work`

**Comment by LUAgam** [comment]
We know from the [documentation ](https://actiontech.github.io/dble-docs-cn/1.config_file/1.02_schema.xml.html)that `slaveThreshold `depends on the heartbeat as `show slave status`, which means that only slaveThreshold is greater than 0 And the delay detection will take effect only when the heartbeat is `show slave status`.
From your configuration (`slaveThreshold="100"`), you can understand that you want dble to detect mysql master-slave delay, and the delay threshold is 100.
If the heartbeat is `show slave status`, the delay detection will be turned on, but at this time, the master and slave are not synchronized (`writeHost down`), and the delay detection cannot be performed, so the read library will not accept the request
If the heartbeat is not show slave status (`select 1`, `select user()`), the delay detection will not be turned on, so there is no need to judge whether the master and slave are synchronized, and the read library can accept the request.
If you do not want to perform master-slave delay detection, you can set `slaveThreshold="-1"`, then even if writeHost down, read the library can also accept the request

**Comment by quepangpang** [comment]
verified on 5.7.11-dble-3.20.07.99-d60211583dbf41b0ce30bf3c8b90c90a9432bf00-20200810060830
