### ISSUE TITLE
When processing "dataHost @@ disable", only open the configuration file once. If it fails, it will not try to reopen the file in the future.

### ISSUE THREAD

**Issue by langkaixin** [actiontech/dble#1659]
* **dble version：**  5.6.29-dble-2.19.09.0-fd62e7a27a561169acabc11df32b2f0d13a0b922-20191121135714
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```

```

**rule.xml**  

```


```

**server.xml**  

```
<system>
	<property name="processors">1</property>
        <property name="processorExecutor">1</property>
	<property name="useOuterHa">true</property>
</system>
```

* **steps：**    
**step1.**  
[root@dble-1 conf]# chattr +i schema.xml
**step2.**
mysql> dataHost @@disable name='ha_group2';
ERROR 1003 (HY000): disable dataHost with error, use show @@dataSource to check latest status. Error:java.nio.file.AccessDeniedException: /opt/dble/conf/schema.xml
**step3.**
[root@dble-1 conf]# chattr -i schema.xml
**step4.**
mysql> reload @@config_all;
Query OK, 1 row affected (0.05 sec)
Reload config success
**step5.**
mysql> dataHost @@disable name='ha_group2';
ERROR 1003 (HY000): disable dataHost with error, use show @@dataSource to check latest status. Error:java.nio.file.AccessDeniedException: /opt/dble/conf/schema.xml
mysql> dataHost @@disable name='ha_group2';
ERROR 1003 (HY000): disable dataHost with error, use show @@dataSource to check latest status. Error:java.nio.file.AccessDeniedException: /opt/dble/conf/schema.xml
mysql> dataHost @@disable name='ha_group2';
ERROR 1003 (HY000): disable dataHost with error, use show @@dataSource to check latest status. Error:java.nio.file.AccessDeniedException: /opt/dble/conf/schema.xml

* **expect result：**  
    1.execute "dataHost @@disable……" should succeed in step5
* **real result：**  
    1.execute "dataHost @@disable……"  failed in step5
* **supplements：**  
    1.

**Comment by sunsun314** [comment]
Change the logic of the file write, when dble in single mod change the dataSource only when write file success & write file with two steps 'dble.safe ->mv to schema.xml'

**Comment by sunsun314** [comment]
Need be verify with issue https://github.com/actiontech/dble/issues/1729

**Comment by FlyingMao** [comment]
**verified version：** dble-9.9.9.9-57b1020709a649ab58fd6e2596c448c559d322cc-20200404140658
