### ISSUE TITLE
when system time less than start time ,expect insert sql failed, but successed

### ISSUE THREAD

**Issue by langkaixin** [actiontech/dble#1665]
* **dble version：**   5.6.29-dble-9.9.9.9-08db8e2966b520086cee64e9d43be7fcf73f587a-20200220121602 
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```
<schema dataNode="dn5" name="schema1" sqlMaxLimit="100">
                <table name="mytest_auto_test" dataNode="dn1,dn2,dn3,dn4" rule="hash-four" incrementColumn="id"/>
</schema>
```

**rule.xml**  

```


```

**server.xml**  

```
<property name="sequnceHandlerType">2</property>
```

* **steps：**    
**step1.**
mysql> create table mytest_auto_test(id bigint,time char(120));
**step2.**
[root@dble-1 opt]# date -s 2000/01/01
**step3.**
mysql> insert into mytest_auto_test values(1);
Query OK, 1 row affected (0.01 sec)
mysql> select * from mytest_auto_test;
+----------------------+------+
| id                   | time |
+----------------------+------+
| -1435202491506489713 | 1    |
+----------------------+------+
1 row in set (0.01 sec)

* **expect result：**  
    1. insert sql should failed in step3
* **real result：**  
    1. insert sql successed
* **supplements：**  
    1.

**Comment by wjl1619** [comment]
verified on version: 5.6.29-dble-9.9.9.9-4b07433c31db6ec41625b5422884fc8b3799b342-20200228123417
