### ISSUE TITLE
after run btrace "BtraceXaDelay.java",  execute "mysql -uroot -p111111 -P9066" was hangs 

### ISSUE THREAD

**Issue by langkaixin** [actiontech/dble#1667]
* **dble version：**  5.6.29-dble-9.9.9.9-08db8e2966b520086cee64e9d43be7fcf73f587a-20200220121602
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```

```

**rule.xml**  

```

```

**server.xml**  

```

```

* **steps：**    

**step1.**  
change sleep time of method 'delayBeforeXaEnd' to 60s :

[root@dble-1 dble]# sed -i -e 's/Thread.sleep([0-9]*L)/Thread.sleep(100L)/' -e '/delayBeforeXaEnd/{:a;n;s/Thread.sleep([0-9]*L)/Thread.sleep(60000L)/;/\}/!ba}' BtraceXaDelay.java

**step2.**
mysql> drop table if exists sharding_4_t1;
Query OK, 0 rows affected (0.06 sec)

mysql> create table sharding_4_t1(id int,name char);
Query OK, 0 rows affected (0.09 sec)

mysql> set autocommit=0;
Query OK, 0 rows affected (0.00 sec)

mysql> set xa=on;
Query OK, 0 rows affected (0.00 sec)

mysql> insert into sharding_4_t1 values(1,1),(2,2),(3,3),(4,4);
Query OK, 4 rows affected (0.01 sec)

**step3.**
run btrace:
[root@dble-1 dble]# btrace 27633 BtraceXaDelay.java

**step4.**
mysql> commit;

**step5.**
mysql -uroot -p111111 -P9066

* **expect result：**  
    1. expect connect mysql success in step5
* **real result：**  
    1.connect mysql is hang in step5
* **supplements：**  
    1.

**Comment by Baofengqi** [comment]
can't reproduce in test env
