### ISSUE TITLE
Do not catch OutOfMemoryError in dble

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#1672]
**D**ble have some places try to catch Throwable object to avoid processes collapse. But we find it can cause problems more than we expect, such as we can not explain why the OutOfMemoryError happens and can not tell the uses whether the OutOfMemoryError is caused by a program BUG or lack of configured memory.
  **S**o we decide to allow OutOfMemoryError collapse processes and dump the heap when it happens. To achieve this behavior below would be changed:
+ when OOM happens, do not catch the Exception and just let the process collapse
+ add default JVM configuration into wrapper.conf to dump the heap when OOM occurs

**Comment by Lordess** [comment]
It is said we would let the dble collapse, but the merge #1704 decided to let the dble survived in the end. I wonder the reason of reversing. Otherwise, what will the dble end up with after a severe OOM?
