### ISSUE TITLE
[Improve]fastJson 1.2.60 has some safe problem, so upgrade to 1.2.62 

### ISSUE THREAD

**Issue by yanhuqing666** [actiontech/dble#1674]
fastJson 1.2.60 has some safe problem, so upgrade to 1.2.62

**Comment by wjl1619** [comment]
verified on version:
2.19.07.3 444e69bd7a771d996a042bd732030451c1fbb8b5
2.19.09.99 b6975871c1de92df5bd82823b699a5b744799275
2.19.11.99 9f85a3fd2db1c70eec3b53109d0208d99fa011f6
master 20366a65995c57f23a4f32257037acffaad8d655
