### ISSUE TITLE
code change for connection leak makes feature of autocommit setting at first startup or reload invalid

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#1686]
* **dble version：**  
5.6.29-dble-9.9.9.9-26da2a0733b3f17a54aa2a3a7a747b6e6c966449-20200304091656 including 2.19.11.0
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  todo:wait append
* **expect result：**  
    1.
* **real result：**  
    1.
* **supplements：**  
    1.

**Comment by FlyingMao** [comment]
verified version：dble-2.19.11.99-d4ff003692996886fee1206ddfde76fe4abb53f9-20200429033631
