### ISSUE TITLE
expect the default xa log name and xa log directoty name contain 'xa'

### ISSUE THREAD

**Issue by wjl1619** [actiontech/dble#1701]
* **dble version：**  
5.6.29-dble-9.9.9.9-d8bced4aa2c21a4dd2636fb8d3a620443b5df146-20200313131148
* **preconditions ：**  
no
* **configs：** 
**server.xml**  

```xml
        <system>
                <property name="processors">1</property>
                <property name="processorExecutor">1</property>
                <property name="useSerializableMode">1</property>
        </system>
```

* **steps：**    
    step1.  
* **expect result：**  
    1.default xa log name and xa log directoty name contain 'xa'
* **real result：**  
    1.[root@dble-1 dble]# 
ll dble/tmlogs/
total 4
-rw-r--r-- 1 root root 369 Mar 16 13:43 tmlog-1.log
* **supplements：**  
    1.

**Comment by quepangpang** [comment]
verified version：5.6.29-dble-9.9.9.9-408315372f0fa426939009fd58a701630a19a629-20200730054246
[root@dble-1 xalogs]# ll
total 4
-rw-r--r-- 1 root root 135 Jul 31 14:41 xalog-1.log
