### ISSUE TITLE
sysbench run into Duplicate entry '504979248' for key 'PRIMARY' after run 2days

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#1713]
* **dble version：**  
5.7.21-dble-2.19.09.1-8ff42f602a9957d4bd94be7a4becb9bc1b25960f-20200228124219

* **preconditions ：**  
sysbench version: 1.0.17

* **configs：** 

**schema.xml**  

```
        <table name="sbtest1" rule="hash-thirty" dataNode="dn$1-30"></table>
        <table name="sbtest2" rule="hash-thirty" dataNode="dn$1-30"></table>
```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  sysbench cmd line:
/usr/bin/sysbench --table_size=1000000000 --tables=2 --max-requests=0 --report-interval=3 --db-driver=mysql --mysql-host=xx.xx.xx.xx --mysql-port=8066 --mysql-user=test --mysql-password=test --mysql-db=schema1 --skip-trx=off --sum_ranges=0 --order_ranges=0 --point_selects=0 --threads=40 --time=604800 --db-ps-mode=disable  --auto_inc=off /usr/share/sysbench/oltp_read_write.lua cleanup|prepare|run
* **expect result：**  
  
* **real result：**  
    1.sysbench stopped at about 3days later for: FATAL: `thread_run' function failed: /usr/share/sysbench/oltp_common.lua:488: SQL error, errno = 1062, state = '23000': Duplicate entry '504979248' for key 'PRIMARY'

* **supplements：**  
    1.key segment of oltp_read_write.lua
```lua
function event()
   if not sysbench.opt.skip_trx then
      begin()
   end

   execute_point_selects()

   if sysbench.opt.range_selects then
      execute_simple_ranges()
      execute_sum_ranges()
      execute_order_ranges()
      execute_distinct_ranges()
   end

   execute_index_updates()
   execute_non_index_updates()
   execute_delete_inserts()

   if not sysbench.opt.skip_trx then
      commit()
   end
end
```
2.dble related logs before and after the error: 
[duplicate_primary_key_err.log](https://github.com/actiontech/dble/files/4348124/duplicate_primary_key_err.log)

3.other sqls route under "autocommit=false", but the err sqls was route under "autocommit=true" which expect not

**Comment by PanternBao** [comment]
执行sysbench时加上参数“--mysql-ignore-errors=1062” 规避，参考：
- https://github.com/akopytov/sysbench/issues/253
- https://github.com/actiontech/dble/issues/458#issuecomment-541559078

**Comment by quepangpang** [comment]
Verified on :5.6.29-dble-3.20.07.99-d8ba50a17a15183a06c8b784be004790aec36c81-20200811110913
