### ISSUE TITLE
Complex query get error when select same column with different alias

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#1716]
* **dble version：**  2.19.11.0/rel
* **configs：** 
```
config table ftest & lotest as sharding tables with whaterver tableRule
```

* **steps：**    
 execute sql below:
```
select * from (
 select a.id aid,
        b.id bid,
        a.id xid,
        3 mark
        from ftest a left join lotest b on a.id= b.id
) t
```
* **expect result：**  
   select success
* **real result：**  
    [Err] 1003 - field not found:t.xid

**Comment by sunsun314** [comment]
issue #1268 releated 
When the outer select need pushdown, there should be a reasonable way to avoid the duplicate name

**Comment by FlyingMao** [comment]
**verified version：** dble-9.9.9.9-ea79fc3429ce9752ab18d81732d2e9093a6f21d6-20200408075848
