### ISSUE TITLE
当查询表记录数量的时候如果查询语句的表名称包含大写字母发生错误

### ISSUE THREAD

**Issue by wang1980** [actiontech/dble#1723]
* **dble version：*2.19.11.0*  
select count(*) from table1 这种语法可以正常执行，
如果将表名称改成Table1
select count(*) from Table1
则查询出错
 table node buildOwn exception! Error:Index: 0, Size: 0
单表和全局表没有此问题，只有分片表才会出现问题。

**Comment by yanhuqing666** [comment]
see https://github.com/actiontech/dble/issues/1749
