### ISSUE TITLE
还是dble的查询性能问题

### ISSUE THREAD

**Issue by Kevy123** [actiontech/dble#1724]
* **dble version：actiontech-dble-2.19.11.0  
[同样的语句与mycat对比，性能差(left join 实现不同)，且结果不准确（与mysql比较后是mycat错了）](https://github.com/actiontech/dble/issues/1490)
还是有问题啊。

![1111](https://user-images.githubusercontent.com/19991653/77216962-98521900-6b59-11ea-8f9f-b07ac0f3b32b.png)

实例sql：
`mysql> SELECT SUBSTR(hi.consumer_id, 1, 14) AS cid,avg(hdn.heat)  from data_now as hdn
    left JOIN user_info as hi
    ON hdn.consumer_id = hi.consumer_id 
    WHERE hi.company_id = '00019'
    GROUP BY SUBSTR(hi.consumer_id, 1, 14)
    LIMIT 10;`

**Comment by sunsun314** [comment]
https://github.com/actiontech/dble-docs-cn/blob/master/2.Function/2.21_query_trace.md
This function may help you to point out which stage cost the most of the time 
You may show us the result of trace or join the QQ group to get some realtime-support

**Comment by Kevy123** [comment]
`mysql> SELECT SUBSTR(hi.consumer_id, 1, 14) AS cid,avg(hdn.heat)  from data_now as hdn
    -> left JOIN user_info as hi
    -> ON hdn.consumer_id = hi.consumer_id 
    -> WHERE hi.company_id = '00019'
    -> GROUP BY SUBSTR(hi.consumer_id, 1, 14)
    -> LIMIT 10;`
![image](https://user-images.githubusercontent.com/19991653/77377090-1b1ee200-6dad-11ea-86c5-091a29ebaf27.png)

两个关联表都指定 相关的分库策略，即company_id
`mysql> SELECT SUBSTR(hi.consumer_id, 1, 14) AS cid,avg(hdn.heat)  from data_now as hdn left JOIN user_info as hi ON hdn.consumer_id = hi.consumer_id  WHERE hi.company_id = '00019' and hdn.company_id='00019' GROUP BY SUBSTR(hi.consumer_id, 1, 14) LIMIT 10;`
![image](https://user-images.githubusercontent.com/19991653/77377247-823c9680-6dad-11ea-8794-1d0ec58992db.png)

分库策略
` <function name="hash-company" class="Enum">
                <property name="mapFile">company-id-hash.txt</property>
  </function>`
![image](https://user-images.githubusercontent.com/19991653/77377370-e0697980-6dad-11ea-9466-d69cadb70eb3.png)

而mycat只需要指定一个表的company_id就可以路由到指定的db上

**Comment by yanhuqing666** [comment]
You can see `http://edu.itpub.net/course/10225.html` to understand why `left join` or `on condition is not sharding column ` can not be sent to MySQL directly.  It may return the wrong result。
Correctness is more important than performance
