### ISSUE TITLE
insert error after selecting from global table more times in xa transaction

### ISSUE THREAD

**Issue by Baofengqi** [actiontech/dble#1725]
* **dble version：**  
2.19.11.0
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```
    <schema name="schema2" sqlMaxLimit="100" dataNode="dn5">
        <table name="global_4_t2" dataNode="dn1,dn2,dn3,dn4" type="global" />
    </schema>
```

* **steps：** 
    step1.  use schema2;CREATE TABLE \`global_4_t2\` (\`id\` int(11) DEFAULT NULL);
    step2. set autocommit=0;set xa=1;delete from global_4_t2;commit;
    step3. select * from global_4_t2;(execute more times)
    step4. insert into global_4_t2 values (1);
* **expect result：**  
    1. Query OK, 1 row affected
* **real result：**  
    1. ERROR 1440 (XAE08): XAER_DUPID: The XID already exists
* **supplements：**  
    1.

**Comment by FlyingMao** [comment]
**verified version:** dble-9.9.9.9-14e43f2e85d2b29aea766d8836f6f799bee2fb2d-20200401051400

**Comment by sunsun314** [comment]
Add new case for this issue:
begin;
select * from test1; (test1 was a global table with more than five nodes in dble)
commit;
+ expect result：
execute success
+ real result:
dble may hang when commit

**Comment by wjl1619** [comment]
verified on version: 5.6.29-dble-9.9.9.9-7144885389c9e27df61996d0de5408c7a3a57b0e-20200424071334
