### ISSUE TITLE
all mysql set insensitive, and query with uppercase table name will return error "table node buildOwn exception!"

### ISSUE THREAD

**Issue by wjl1619** [actiontech/dble#1749]
* **dble version：** 
 5.6.29-dble-2.19.11.0-2d7c4911b7a4fecaa9eb0299f49c32ec11e97c42-20200228124218
* **preconditions ：**  
```sql
drop table if exists sharding_4_t1;
create table sharding_4_t1(id int);
```
* **configs：** 

**schema.xml**  

```xml
<schema dataNode="dn5" name="schema1" sqlMaxLimit="100">
                <table name="Sharding_4_T1" dataNode="dn1,dn2,dn3,dn4" rule="hash-four" />
</schema>
```
* **steps：**    
    step1.  execute sql:
```sql
select count(*) from Sharding_4_T1;
```
* **expect result：**  
    1.select success
* **real result：**  
    1.mysql> select count(*) from Sharding_4_T1;
ERROR 4005 (HY000): table node buildOwn exception! Error:Index: 0, Size: 0
* **supplements：**  
    1.

**Comment by sunsun314** [comment]
This issue is same as #1723

**Comment by FlyingMao** [comment]
**verified version：** dble-9.9.9.9-379e72c0b4b6e8689ffebe3632f6226bb43f9a67-20200403060243
