### ISSUE TITLE
[Improvement] server.xml  spelling mistakes property compatible

### ISSUE THREAD

**Issue by gaopengpeng123456** [actiontech/dble#1755]
* **dble version：**  
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  
* **expect result：**  
    1.
* **real result：**  
    1.
* **supplements：**  
    1.

**Comment by yanhuqing666** [comment]
doc: https://github.com/actiontech/dble-docs-cn/blob/develop/1.config_file/1.03_server.xml.md
