### ISSUE TITLE
Contaminate mysql connection pool when doing ddl in xa transaction

### ISSUE THREAD

**Issue by PanternBao** [actiontech/dble#1760]
* **dble version：** 
2.19.11.0
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```
    <schema name="testdb" sqlMaxLimit="100" dataNode="dn1">
        <table name="sharding_4_t2" dataNode="dn1,dn2,dn3,dn4" rule="hash-four" />
    </schema>

```

**rule.xml**  

```
    <tableRule name="hash-four">
        <rule>
            <columns>id</columns>
            <algorithm>four-long</algorithm>
        </rule>
    </tableRule>
    <function name="four-long" class="Hash">
        <property name="partitionCount">4</property>
        <property name="partitionLength">1</property>
    </function>

```

* **steps：**    
    step1.  use schema2;set autocommit=0;set xa=1;
    step2. show full table;
    step3. create table sharding_4_t2(id int); 
    step4. the statement in step3 must execute error : ERROR 1399 (XAE07): XAER_RMFAIL: The command cannot be executed when global transaction is in the  ACTIVE state.
    step5. rollback
    step6. insert into Sharding_4_t2 values(1); (execute more times)
* **expect result：**  
    1. step6 execute successfully
* **real result：**  
    1. ERROR 1400 (XAE09): XAER_OUTSIDE: Some work is done outside global transaction
* **supplements：**  
    1.

**Comment by Baofengqi** [comment]
import from https://github.com/actiontech/dble/issues/1458

**Comment by Baofengqi** [comment]
can‘t support ddl in xa transaction

**Comment by quepangpang** [comment]
verified version：5.6.29-dble-9.9.9.9-408315372f0fa426939009fd58a701630a19a629-20200730054246

`mysql> set xa=1;
Query OK, 0 rows affected (0.00 sec)

mysql>  create table sharding_4_t2(id int);
ERROR 1046 (HY000): DDL is not allowed to be executed in xa transaction.`
