### ISSUE TITLE
The value of @var is error when it in [load data infile 'xxx' into table t (@colA,@colB)]

### ISSUE THREAD

**Issue by FlyingMao** [actiontech/dble#1761]
* **dble version：**  
dble-9.9.9.9-14e43f2e85d2b29aea766d8836f6f799bee2fb2d-20200401051400
* **preconditions ：**  
create table test(id int(4), B float(8,2)) ; //test is no sharding table
* **configs：** 

**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  prepare a test.txt filled with 
```
5,5
3,3
```
    step2  query in dble
```mysql
mysql> load data infile '/root/test.txt' into table test (@id_str, @B_str);
Query OK, 2 rows affected (0.07 sec)
```
   step3 execute select in dble
```
mysql> select @id_str, @B_str;
```
@id_str, @B_str are not explicitly assigned
* **expect result：**  
    1.
```mysql> select @id_str, @B_str;
+---------+--------+
| @id_str | @B_str |
+---------+--------+
| 3       | 3      |
+---------+--------+
1 row in set (0.00 sec)
```
* **real result：**  
    1.r
```
mysql> select @id_str, @B_str;
+---------+--------+
| @id_str | @B_str |
+---------+--------+
| NULL    | NULL   |
+---------+--------+
1 row in set (0.01 sec)
```
* **supplements：**  
    1.

**Comment by Baofengqi** [comment]
doc : https://github.com/actiontech/dble-docs-cn/blob/develop/3.SQL_Syntax/3.2_DML/3.2.09_LOAD_DATA.md
