### ISSUE TITLE
Whether to add support for macOS development binaries.

### ISSUE THREAD

**Issue by tiansin** [actiontech/dble#1768]

**Comment by yanhuqing666** [comment]
Need more details to describe your problem.

**Comment by tiansin** [comment]
@yanhuqing666 I need to run dble on a macos computer for development testing. But the current release can only run on linux.

**Comment by Baofengqi** [comment]
You can install jdk and intellj idea in macos so you can develop and test. That's what I do.

**Comment by tiansin** [comment]
@Baofengqi 

>   …/Downloads/dble  ./bin/dble -h                                                                    ✔  15:22:36 
> Unable to locate any of the following operational binaries:
>   /Users/johnny/Downloads/dble/bin/./wrapper-macosx-universal-64
>   /Users/johnny/Downloads/dble/bin/./wrapper-macosx-universal-32
>   /Users/johnny/Downloads/dble/bin/./wrapper

**Comment by Baofengqi** [comment]
If you want to run dble binaries in macos directly,  you need to custom and rebuild dble. You can try installing docker to run dble.

**Comment by tiansin** [comment]
@Baofengqi I currently use docker, but I don't really want to use docker because it consumes a lot of memory.

**Comment by Baofengqi** [comment]
You need to custom and rebuild dble, it's a bit of a hassle. But you can limit memory of dble container.

https://cizixs.com/2017/08/04/docker-resources-limit/

**Comment by tiansin** [comment]
@Baofengqi Is it possible to add macos binaries to the new release?Thank you!

**Comment by Baofengqi** [comment]
The users does not have this demand in production environment . You can build a development environment by https://github.com/actiontech/dble/blob/master/docs/CONTRIBUTING.md.
