### ISSUE TITLE
get NPE when execute union sql in dual without database choose

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#1782]
* **dble version：**  2.19.11.0/rel
* **configs：** 
Any config let the dble work is OK
* **steps：**    
   + connection dble without database
   + execute 'select 1 union select CURRENT_DATE();'
* **expect result：**  
    1. get right result
* **real result：**  
    1.ERROR 1064 (HY000): NullPointerException

**Comment by FlyingMao** [comment]
**verified version：** dble-9.9.9.9-f8ec63ed44389c79258c2157744b497fc66e4945-20200408081426
