### ISSUE TITLE
set multi-user-variables & user variables are dependent result not correct

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#1806]
* **dble version：**  2.19.11.0/rel
* **preconditions ：**  
* **steps：**    
    step1.  set @a=1;select @a ;set @b=@a+1;select @b
* **expect result：**  
  result b = 2
* **real result：**  
   b = null

**Comment by yanhuqing666** [comment]
delay

**Comment by wjl1619** [comment]
verified on version: drivers/c_mysql_api/multi-queries/mysql_multi_queries.cpp
