### ISSUE TITLE
Commit/rollback  may get ok but the result is not 

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#1808]
* **dble version：**  dble-9.9.9.9-42f0b54a0c0e272404fab2c10b8b5d7b799108c5
* **preconditions ：**  
create a global table config for table name test1 for 4 nodes
* **steps：**    
    step1.  begin;insert into test1 set id = 1;
    step2.  add trace in com.actiontech.dble.backend.mysql.nio.MySQLConnection#commit for 30s each
    step3.  execute commit in dble
    step4.  kill mysqld after the first connection commited
* **expect result：**  
    1. commit in dble fail
* **real result：**  
    1. return ok

**Comment by wjl1619** [comment]
verified on version: 5.6.29-dble-2.20.04.99-af3a38859c2e9d4b5c3b8091174dbfa74e386307-20200426034147
