### ISSUE TITLE
when `load data` failed,the file:temp was left behind

### ISSUE THREAD

**Issue by FlyingMao** [actiontech/dble#1814]
* **dble version：**  
dble-9.9.9.9-c14b4959f4168217881ae504b6b094eaf4dd0794-20200415140406
* **preconditions ：**  
1.just 11G free disk space

mysql> create table sharding_4_t1(id int primary key,c1 char(5),c2 char(5),c3 char(5));

* **configs：** 

**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```
<property name="bufferPoolChunkSize">256</property>
```

* **steps：**    
    step1.  
```
MySQL [schema1]> load data local infile "/opt/test.txt" into table sharding_4_t1 fields terminated by ',' lines terminated by '\n';
ERROR 1114 (HY000): The table 'sharding_4_t1' is full
```
  step2.
```
cd /opt/dble
du -sh *
```

* **expect result：**  
    1.There is no folder named temp
* **real result：**  
    1.
```
[root@localhost dble]# du -sh *
0	algorithm
868K	bin
128K	conf
4.0K	dble.pid
41M	lib
3.9M	logs
12G	temp
0	tmlogs
8.0K	version.txt
0	viewConf
```
* **supplements：**  
    1.use python create test.txt
```
with open('test.txt', 'w') as fp:
   col1 = 1
   col2 = col1 + 1
   col3 = "abcd111111hgugjhhjhjhuihiuhihuihhuhuuh111111111111111111111111111111111111111111111"
   col4 = "12341111111fgughkhiulnupoilmkokpoyfytgyttfhgyhgyjgygtygg111111111111111111111111111111111111111111111"
   for i in xrange(30000000):
      data = str(col1) + ',' + str(col2) + ',' + str(col3) + ',' + str(col4)
      fp.write(data + '\n')
      col1 = col1 + 1
      col2 = col2 + 1
```

**Comment by Baofengqi** [comment]
The error is reported by mysql : https://dev.mysql.com/doc/refman/5.7/en/full-table.html.  Please check free disk of mysql.

**Comment by quepangpang** [comment]
verified version：5.6.29-dble-9.9.9.9-408315372f0fa426939009fd58a701630a19a629-20200730054246
