### ISSUE TITLE
JDBC has problems saving pictures via setblob or setBinaryStream

### ISSUE THREAD

**Issue by z3093964447** [actiontech/dble#1820]
The database successfully saved the picture, but the picture became larger and could not be viewed

**Comment by z3093964447** [comment]
test code：

   PreparedStatement pstmt = connection.prepareStatement("insert into blobtest(id, file) values(?, ?)");
        FileInputStream fis = new FileInputStream(new File("D:\\test.jpg"));
        pstmt.setInt(1, 1);
        pstmt.setBlob(2, new FileInputStream(new File("D:\\test.jpg")));
        pstmt.executeUpdate();

**Comment by Baofengqi** [comment]
jdbc send following statement to dble : insert into blobtest(id, file) values(1, _binary'图片的二进制')

**Comment by yanhuqing666** [comment]
you can add useServerPrepStmts=true for the URL: 

```
Connection connection = DriverManager.getConnection("jdbc:mysql://127.0.0.1:8066?useServerPrepStmts=true", "root", "123456");
```
to escape the limitation  after #1906 finished or #1907 was merged

**Comment by quepangpang** [comment]
verified  on 5.7.11-dble-3.20.07.99-d60211583dbf41b0ce30bf3c8b90c90a9432bf00-20200810060830
