### ISSUE TITLE
Management cmd ”resume“  return ‘1’ when there's no paused  dataNode in dble cluster

### ISSUE THREAD

**Issue by yexiaoli88** [actiontech/dble#1823]
* **dble version：version: 5.6.23-dble-2.19.11.0-2d7c4911b7a4fecaa9eb0299f49c32ec11e97c42-20200228124218**  
* **preconditions ：**  
dble cluster
* **configs：** 

**schema.xml**  

```
  <schema name="testdb" sqlMaxLimit="-1" dataNode="dn_01">
        <table name="test" needAddLimit="false" rule="default_mod_two-id" dataNode="dn_04,dn_03,dn_02,dn_01"></table>
    </schema>
    <dataNode name="dn_03" dataHost="dh-mysql-1" database="dh_dn_03"></dataNode>
    <dataNode name="dn_02" dataHost="dh-mysql-1" database="dh_dn_02"></dataNode>
    <dataNode name="dn_01" dataHost="test" database="dh_dn_01"></dataNode>
    <dataNode name="dn_04" dataHost="dh-mysql-1" database="dh_dn_04"></dataNode>
    <dataHost name="dh-mysql-1" maxCon="100" minCon="10" balance="0" switchType="-1" slaveThreshold="-1" tempReadHostAvailable="0" keepOrig="0">
        <heartbeat timeout="0" errorRetryCount="0">show slave status</heartbeat>
        <writeHost host="172.20.134.2-3306-dh-2" url="172.20.134.2:3306" user="test" password="Ussx8JvtdWkB/qDAOtC+mjNuB8ePi9sUT5hesZjkenIDrpvJf+1iDwTKhTMR5NHnvzdgHfK+cHuBkzZnA5U0lg==" weight="-1" id="mysql-jkwqay" usingDecrypt="1">
            <readHost host="172.20.134.3-3306-dh-1" url="172.20.134.3:3306" user="test" password="VRlYSV/Hofa2qvX9mRddZsoob2doT1I4sUqEcp7FpgDLS2PhHrb/ka4HzEwLGRY2KXvMjj4BGpNY4cZuJc+XMA==" weight="-1" id="mysql-cr8lky" usingDecrypt="1"></readHost>
        </writeHost>
    </dataHost>

```

* **steps：**    
1.connect to 9066 port,execute "pause @@dataNode='dn_01'",
![image](https://user-images.githubusercontent.com/39580715/80180571-a18d4480-8635-11ea-8ba1-fff30e29a881.png)

2.then execute 'resume' twice in 9066 port,and return "1" in the second time
![image](https://user-images.githubusercontent.com/39580715/80180744-0183eb00-8636-11ea-9210-c218864aa423.png)

* **expect result：**  
    1. resume should return error message when there's no paused dataNode
* **real result：**  
    1. reumw return 1
* **supplements：**  
    1.

**Comment by wjl1619** [comment]
The preconditions to reproduce the issue is:  the cluster is first installed.

**Comment by wjl1619** [comment]
verified on version: 5.7.25-dble-9.9.9.9-f34ec4c43f0cc39b92af1b67882321b1c636c116-20200428052341

**Comment by wjl1619** [comment]
help message verified on version: 
5.6.29-dble-2.20.04.99-8d0f4d97076b32ad3edef600a5ea2f5a83d57e4a-20200428102632
5.6.29-dble-9.9.9.9-e490e33952c8d22ef0f2d4809a17ef337c0058f4-20200428093835
