### ISSUE TITLE
Navicat15 connection dble error

### ISSUE THREAD

**Issue by lcg72** [actiontech/dble#1855]
* **dble version：**  
2.19.11.0
operating system： manjaro
navicat premium version: 15.0.14

MySQL command line can connect correctly
![2020-05-13_09-46](https://user-images.githubusercontent.com/1832626/81762229-b8b9a680-94fe-11ea-8414-205b2555e04a.png)

Navicat15 connection error
![2020-05-13_09-40](https://user-images.githubusercontent.com/1832626/81762274-d1c25780-94fe-11ea-9000-38f85d23a429.png)

**Comment by yanhuqing666** [comment]
dble not support：  SELECT COUNT(*) AS support_ndb FROM information_schema.ENGINES WHERE Engine = 'ndbcluster'

**Comment by wenyh1** [comment]
use **dble 2.19.11.0**
in mysql protocol capture package，as shown in figure（three of them are issued in the same request package）：
![image](https://user-images.githubusercontent.com/44251917/90217448-f4cd1200-de33-11ea-8af2-d42d348f6f15.png)
these three SQL:
```
1.SHOW VARIABLES LIKE 'lower_case_%'; 
2.SHOW VARIABLES LIKE 'sql_mode'; 
3.SELECT COUNT(*) AS support_ndb FROM information_schema.ENGINES WHERE Engine = 'ndbcluster'
```
**expect**:  packets numbers of the corresponding three return packets should be continuous
**real**: as shown in figure (The third packet return packet number starts at 1)：
![image](https://user-images.githubusercontent.com/44251917/90217892-f945fa80-de34-11ea-9228-89ba21c22a68.png)

So，the cause of the issue：multiple SQL statements are issued in the same request package，returns the packet Number discontinuity in the packet；
This causes exposure when connecting with the **Navicat Premium 15.0.14** tool；
However, you can try Navicat Premium greater than version 15.0.14, and connection is normal

Other：
dble 2.19.11.0 support：SELECT COUNT(*) AS support_ndb FROM information_schema.ENGINES WHERE Engine = 'ndbcluster'

**Comment by quexiuping** [comment]
verified on 5.7.21-dble-9.9.9.9-72e69d58c5d468198631b487ecc7f29301e24de6-20201021020509
