### ISSUE TITLE
ERROR 1064 (HY000): The DDL is not supported, sql:ALTER TABLE O_ORG 	COMMENT =

### ISSUE THREAD

**Issue by 13611582598** [actiontech/dble#1924]
ERROR 1064 (HY000): The DDL is not supported, sql:ALTER TABLE O_ORG
	COMMENT ='aaaa' ;

**Comment by yanhuqing666** [comment]
> ERROR 1064 (HY000): The DDL is not supported, sql:ALTER TABLE O_ORG
> COMMENT ='aaaa' ;

Also need config（schema.xml） and table structure about O_ORG .

**Comment by 13611582598** [comment]
create table O_ORG
(
&nbsp; &nbsp;ORG_NO&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;varchar(16) not null comment '供电单位编号',
&nbsp; &nbsp;ORG_NAME&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;varchar(256) comment '供电单位名称',
&nbsp; &nbsp;P_ORG_NO&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;varchar(16) comment '上级供电单位编号
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 直接上级供电单位编号。',
&nbsp; &nbsp;ORG_TYPE&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;varchar(8) comment '供电单位类别
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 01 国网公司、02 省公司、03 地市公司 、04 区县公司、05 分公司、06 供电所。',
&nbsp; &nbsp;SORT_NO&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; numeric(5,0) comment '排序序号
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 在同级中的排列顺序的序号，用自然数标识，如，1、2、3。',
&nbsp; &nbsp;primary key (ORG_NO)
);


alter table O_ORG comment '供电单位
国网标准化设计表
1) 供电单位的基本信息，供电单位为独立的考核单位，如：地市局、分局';


create index IND_O_ORG_PORGNO on O_ORG (P_ORG_NO);














------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"tiger.yan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月8日(星期三) 下午4:35
收件人:&nbsp;"actiontech/dble"<dble@noreply.github.com&gt;;
抄送:&nbsp;"多情剑客"<317935463@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [actiontech/dble] ERROR 1064 (HY000): The DDL is not supported, sql:ALTER TABLE O_ORG  COMMENT = (#1924)





  
ERROR 1064 (HY000): The DDL is not supported, sql:ALTER TABLE O_ORG
 COMMENT ='aaaa' ;
  
Also need config（schema.xml） and table structure about O_ORG .

**Comment by quexiuping** [comment]
verified on 5.7.21-dble-9.9.9.9-45370bcf2493a1881e4f9544d4f51697c3d3ff5c-20201020052916
