### ISSUE TITLE
 "show database " statement need stricter inspection

### ISSUE THREAD

**Issue by Dinosauria** [actiontech/dble#1961]
* **dble version：**  
5.6.29-dble-9.9.9.9-7137fbf0aacb6ec2d6a4e45fe861660a34cfc76a-20200721065157
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  login with port 8066 and execute SQL “show databasesl；” with wrong spelling
* **expect result：**  
    1. Throw errors just as the errors on MySQL
* **real result：**  
    1. Return correct result of "show databases;"
![image](https://user-images.githubusercontent.com/17309012/88148048-9fd11e00-cc30-11ea-962b-593eb2ed1e58.png)

* **supplements：**  
    1. dble should support SQL "show database where..." in the future
    2. It caused by phpMyAdmin #1550 loosen the check of the "show database " statement

**Comment by quepangpang** [comment]
Verified on 5.7.11-dble-9.9.9.9-72a97a116018f5ba1808c3fc8dc2b48713c04f65-20200824053520

**Comment by quepangpang** [comment]
9066
```
MySQL [(none)]> show databasesl;
ERROR 1003 (HY000): Unsupported statement
```
8066
```
MySQL [(none)]> show databasesl;
ERROR 1064 (HY000): TODO pos 15, line 1, column 5, token IDENTIFIER databasesl
```
