### ISSUE TITLE
父子表中parentKey如何选择

### ISSUE THREAD

**Issue by wybrono** [actiontech/dble#1985]
1、parentKey在父子表中要求在⽗表中该字段必须与其拆分规则/拆分键有对等关系，可以理解为该parentKey最好为父表的拆分键吗？
2、若parentKey不是父表的拆分键，那性能与拆分键有多大差距呢？

**Comment by yanhuqing666** [comment]
You can ask questions in the official QQ group  669663113. Issues used for bugs or features.
