### ISSUE TITLE
dble作为kettle的表输出时会导致错误处理步骤失效直接中断kettle转换而mycat则正常

### ISSUE THREAD

**Issue by sunshinecb** [actiontech/dble#2004]
* **dble version：*2.20.04.0*  
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```
<schema name="kfxt" sqlMaxLimit="1000">
	<table name="ods_dfs_gantry_transaction" dataNode="dn1" />
        .......
</schema>

```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  
* **expect result：**  
    1.
* **real result：**  
    1.
* **supplements：**  
    1.

**Comment by yanhuqing666** [comment]
need config ，table structure and so on

**Comment by sunshinecb** [comment]
<schema name="kfxt" sqlMaxLimit="1000">
	<table name="ods_dfs_gantry_transaction" dataNode="dn1" />
        .......
</schema>
没做分库，就单库用于测试，当kettle表输出为mysql或者mycat时遇到插入错误都可以继续，但是使用dble时则直接中断

**Comment by yanhuqing666** [comment]
also need config, table structure and  need dble.log

**Comment by sunshinecb** [comment]
表结构
CREATE TABLE `ods_dfs_gantry_transaction` (
  `id` bigint(10) NOT NULL AUTO_INCREMENT,
  `en_station_id` int(6) DEFAULT NULL COMMENT '',
  `en_station_name` varchar(30) DEFAULT NULL COMMENT '',
  `exit_station_id` int(6) DEFAULT NULL COMMENT '',
  `exit_station_name` varchar(30) DEFAULT NULL COMMENT '',
  `ex_date` date DEFAULT NULL COMMENT '',
  `ex_time` int(2) DEFAULT NULL COMMENT '',
  `avg_time` varchar(20) DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='';
错误信息：主键冲突
execute sql err : errNo:1062 Duplicate entry '1' for key 'PRIMARY' con:MySQLConnection [backendId=4, lastTime=1596697276522, user=root, schema=test, old schema=test, borrowed=true, fromSlaveDB=false, mysqlId=479,character_set_client=utf8mb4,character_set_results=NULL,collation_connection=utf8mb4_general_ci, txIsolation=3, autocommit=false, attachment=dn_test{INSERT INTO ods_dfs_gantry_transaction(id, en_station_id, en_station_name, exit_station_id, exit_station_name, ex_date, ex_time, avg_time) VALUES ( 1,  1035,  null,  1034,  null,  '2020-04-11 00:00:00',  2,  '126129.1')}.0, respHandler=SingleNodeHandler [node=dn_test{INSERT INTO t_trip_time (id, en_station_id, en_station_name, exit_station_id, exit_station_name, ex_date, ex_time, avg_time) VALUES ( 1,  1035,  null,  1034,  null,  '2020-04-11 00:00:00',  2,  '126129.1')}.0, packetId=1], host=192.168.211.11, port=3306, statusSync=null, writeQueue=0, xaStatus=0] frontend host:192.168.211.1/57275/root

**Comment by sunshinecb** [comment]
预期kettle抽取1000条数据，有一条主键冲突，则进入错误处理跳过该条，最终999条会插入，单使用dble时遇到错误直接中断整个kettle转换脚本无法进入错误处理步骤，而mysql和mycat则不会

**Comment by yanhuqing666** [comment]
dble version?

**Comment by sunshinecb** [comment]
2.20.04.0

**Comment by sunshinecb** [comment]
跟踪kettle执行源码发现是由于调用jbdc批处理引起，下面时候bug还原测试
public static void main(String[] args) {
//		String URL = "jdbc:mysql://localhost:8066/kfxt?characterEncoding=utf-8";//测试用dble数据库
		String URL = "jdbc:mysql://localhost:3306/test?characterEncoding=utf-8";//测试用MySQL数据库
		String USER = "root";
		String PASSWORD = "root";
		PreparedStatement ps;
		// 1.加载驱动程序
		try {
			Class.forName("com.mysql.jdbc.Driver");
			// 2.获得数据库链接
			Connection con = DriverManager.getConnection(URL, USER, PASSWORD);
			con.setAutoCommit(false);
		    String sql = "insert into t_trip_time (id) values(?)";
		    ps = con.prepareStatement(sql);
		    ps.setInt(1, 1);//数据库中已存在id为1的数据
		    ps.addBatch();
		    ps.setInt(1, 2);//数据库中不存在ID为2的数据
		    ps.addBatch();
		    try {
		    	ps.executeBatch();//批量插入，此时由于id为1的数据主键冲突导致插入失败
		    	 con.commit();
		        ps.clearBatch();
		    }catch(Exception e) {
		    	ps.clearBatch();//第一次批量插入失败，执行clearBatch方法
		    	con.commit();//fixme 当数据库为mysql或者mycat时调用clearBatch方法后再次commit可成功插入数据，但是dble则继续报错
		    }
		    ps.close();
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

希望楼主解决此bug，这个bug的存在导致一些情况下无法用etl（kettle）抽取数据到dble

**Comment by yanhuqing666** [comment]
same with #2024 ？

**Comment by sunshinecb** [comment]
yes

**Comment by yanhuqing666** [comment]
same with #2024 ，so close this
