### ISSUE TITLE
jdbc batch insert error  because use PreparedStatement.clearBatch() and conn.commit()

### ISSUE THREAD

**Issue by sunshinecb** [actiontech/dble#2024]
* **dble version：*2.20.04.0*  
* **preconditions ：**  
clearBatch and commit
* **configs：** 

**schema.xml**  

```
<schema name="testdb" sqlMaxLimit="1000">
	<table name="t_trip_time" dataNode="dn1" />
        .......
</schema>

```

**rule.xml**  

```
no

```

**server.xml**  

```


```

* **steps：**    
    public static void main(String[] args) {
//	String URL = "jdbc:mysql://localhost:8066/kfxt?characterEncoding=utf-8";//测试用dble数据库
String URL = "jdbc:mysql://localhost:3306/test?characterEncoding=utf-8";//测试用MySQL数据库
String USER = "root";
String PASSWORD = "root";
PreparedStatement ps;
// 1.加载驱动程序
try {
Class.forName("com.mysql.jdbc.Driver");
// 2.获得数据库链接
Connection con = DriverManager.getConnection(URL, USER, PASSWORD);
con.setAutoCommit(false);
String sql = "insert into t_trip_time (id) values(?)";
ps = con.prepareStatement(sql);
ps.setInt(1, 1);//数据库中已存在id为1的数据
ps.addBatch();
ps.setInt(1, 2);//数据库中不存在ID为2的数据
ps.addBatch();
try {
ps.executeBatch();//批量插入，此时由于id为1的数据主键冲突导致插入失败
con.commit();
ps.clearBatch();
}catch(Exception e) {
ps.clearBatch();//第一次批量插入失败，执行clearBatch方法
con.commit();//fixme 当数据库为mysql或者mycat时调用clearBatch方法后再次commit可成功插入数据，但是dble则继续报错
}
ps.close();
} catch (ClassNotFoundException e) {
e.printStackTrace();
} catch (SQLException e) {
e.printStackTrace();
}
}
* **expect result：**  
    1.executeBatch fail （errorNo 1062: Duplicate entry '1' for key 'PRIMARY'）
    2.clearBatch and commit success
* **real result：**  
   1.executeBatch fail （errorNo 1062: Duplicate entry '1' for key 'PRIMARY'）
   2.clearBatch and commit fail （errorNo 1062: Duplicate entry '1' for key 'PRIMARY'）
* **supplements：**  
    CREATE TABLE t_trip_time (
id bigint(10) NOT NULL AUTO_INCREMENT,
PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='';

**Comment by quexiuping** [comment]
verified on 5.7.21-dble-3.20.10.99-1383d023542119c702f56f71877b6c568703c779-20201023094428
