### ISSUE TITLE
occur error "Union field merge error, field not found:W.SCANNUM"

### ISSUE THREAD

**Issue by ClippedWings-renzy** [actiontech/dble#2034]
* **dble version：**
2.19.03.1-134a132261217d26dc8bdfa832958081da3c030c
* **preconditions ：** 
execute sql
This is an exception "Union field merge error, field not found:W.SCANNUM" when execute sql.
sql:
 SELECT 
      'CAMA' appName,
	  W.BRANCHID branchId,
	  W.SCANOPER scanOper,
	  '' IP,
	  W.SCAN_MODE scan_Mode,
	  '2' busiType,
	  '0' authFlag,
	  DATE_PORMAT(DATE_SUB(NOW(), INTERVAL 1 DAY), '%Y%M%D') busiDate,
	  '' busiTime,
	  DATE_FORMAT(NOW(), '%Y%m%d') rptDate,
	  SUM(CASE WHEN W.SCANNUM IS NULL THEN 0 WHEN W.SCANNUM = '' THEN 0 ELSE W.SCANNUM END) num
FROM (
	     SELECT 
            T.SCANMODE,
            T.BRANCHID,
            T.SCANOPE,
            T.SCANNUM,
            U.NAME OPERNAME,
            (CASE WHEN T.SCANMODE = '2' THEN 'AC000000000000000002' ELSE 'AC0000000000000000001' END ) SCAN_MODE
        FROM
            BAMS_SCAN_PRE_DAY T, CTP_USER_NLS U
	    WHERE
	        T.RPTDATE = '20200809'
	    AND
	        T.SCANOPER = U.ID
UNION ALL
         SELECT
	        T.SCANMODE,
            T.BRANCHID,
            T.SCANOPE,
            T.SCANNUM,
            V.TELLERNM OPERNAME,
            (CASE WHEN T.SCANMODE = '2' THEN 'AC000000000000000002' ELSE 'AC0000000000000000001' END) SCAN_MODE
        FROM
            BAMS_SCAN_PRE_DAY T, BAMS_TELLNO V, CTP_BRANCH CB
        WHERE
            T.RPTDATE = '20200809'
        AND
            T.SCANOPER = V.TELLNO 
        AND
            T.BRANCHID = CB.ID
        AND
            V.ZONENO = CB.REGION_ID
        AND
            V.BRNO = CB.NET_TERMINAL
) W

GROUP BY W.BRANCHID, W.SCANOPER, W.SCAN_MODE
LIMIT1 1500;

* **steps：**    
 1、exectue "EXPLAIN SQL"，i find “W.SCANNUM” is not found after spliting in dble.  
* **expect result：**  
return data.
* **real result：**  
    1. exception with "Union field merge error, field not found:W.SCANNUM

   

![缺失SCANNUM](https://user-images.githubusercontent.com/69563979/89972820-64ef6280-dc91-11ea-989b-50b12d8d9cd4.jpg)

**Comment by ClippedWings-renzy** [comment]
* **supplements：**  
    table：
![bamsScan](https://user-images.githubusercontent.com/69563979/89994993-75b4ce00-dcbb-11ea-9808-f6818478e6cb.jpg)
![branch](https://user-images.githubusercontent.com/69563979/89994996-78172800-dcbb-11ea-96e9-9aea83fd1292.jpg)
![tellNo](https://user-images.githubusercontent.com/69563979/89994999-79485500-dcbb-11ea-8ad6-04ca1a1ce2ac.jpg)

**Comment by quexiuping** [comment]
验证版本：5.7.21-dble-9.9.9.9-be474ab1afc6e03be32d8bb7991f25d7a7f11a10-20201204093700

```
    <schema shardingNode="dn5" name="schema1" sqlMaxLimit="100">
        <shardingTable name="BAMS_SCAN_PRE_DAY" shardingNode="dn1,dn2,dn3,dn4" function="hash-four" shardingColumn="ID"/>
        <shardingTable name="CTP_USER_NLS" shardingNode="dn1,dn2,dn3,dn4" function="hash-four" shardingColumn="ID"/>
        <shardingTable name="BAMS_TELLNO" shardingNode="dn1,dn2,dn3,dn4" function="hash-four" shardingColumn="ZONENO"/>
        <shardingTable name="CTP_BRANCH" shardingNode="dn1,dn2,dn3,dn4" function="hash-four" shardingColumn="ID"/>
    </schema>
```
