### ISSUE TITLE
when the subquery is listed as * and is a union query, create view exceptions

### ISSUE THREAD

**Issue by wenyh1** [actiontech/dble#2063]
* **dble version：<= 3.20.10.99**  
* **preconditions ：**  
all tables are sharding:
create table test1(id int,code varchar(10));
create table test2(id int,code varchar(10));
* **configs：** 

**sharding.xml**  

```
 <schema name="testdb">
    <shardingTable name="test1" shardingNode="dn1,dn2" function="func_jumpHash" shardingColumn="id"/>
    <shardingTable name="test2" shardingNode="dn1,dn2" function="func_jumpHash" shardingColumn="id"/>
</schema>
```

* **steps：**    
    step1.  create view test_view(id,name) AS select * from test1 union select * from test2;
* **expect result：** 
    1. success
* **real result：**  
    1. ERROR 1222 (HY000): The Column_list Size and Select_statement Size Not Match
* **supplements：**  
    1.

**Comment by quexiuping** [comment]
verified on 5.7.21-dble-9.9.9.9-2bbff7bb74414298df4df40951a5ef4c9d466e0a-20201020015009

**Comment by quexiuping** [comment]
verified on 3.20.07.99
