### ISSUE TITLE
UPDATE test SET type = '1;2;3' WHERE id = 1   Perform Parse  error

### ISSUE THREAD

**Issue by BecomeWyd** [actiontech/dble#2093]
* **dble version：**  
2.19.05.0
* **preconditions ：**  
after issue 1225, 1228
* **configs：** 

**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  执行 SQL
UPDATE test SET type = '1;2;3' WHERE id = 1
* **expect result：**  
    1.update success.
* **real result：**  
    1.1064 - unclosed str.  pos 111 , line 11,  column 11, token EQ
* **supplements：**  
    1.Follow up code，After ParseUtil#findNextBreak()，sql is：
UPDATE test SET type = '1;2
The rest is ignored

**Comment by yanhuqing666** [comment]
need also config and table structure

**Comment by BecomeWyd** [comment]
> need more information，config and table structure

Can't reproduce?

**Comment by yanhuqing666** [comment]
> > need more information，config and table structure
> 
> Can't reproduce?

If we have not enough information， we will not waste time to try to start to reproduce

**Comment by BecomeWyd** [comment]
> need more information，config and table structure and version commit

table struct
CREATE TABLE test （
   id int(11) NOT NULL AUTO_INCREMENT,
   type varchar(255) CHARACTER SET utf8mb4,
  PRIMARY KEY('id') USING BTREE
)

config is dble project quick start configuration.

**Comment by quepangpang** [comment]
verivied on dble-2.19.07.0 ,that issue was be fixed
```
Server version: 5.6.29-dble-2.19.07.0-dd160d6138a16228617b75a20d284dd117f5b138-20190919114227 dble Server (ActionTech)

mysql> use schema1;
mysql> drop table if exists test;
mysql> CREATE TABLE test ( id int(11) NOT NULL AUTO_INCREMENT, type varchar(255) CHARACTER SET utf8mb4, PRIMARY KEY(id) USING BTREE );

mysql> UPDATE test SET type = '1;2;3' WHERE id = 1;
Query OK, 0 rows affected (0.03 sec)
```
