### ISSUE TITLE
3.20.07.0 Using Navicat to connect the library can not display the table bug

### ISSUE THREAD

**Issue by 314926481** [actiontech/dble#2105]
Table information cannot be displayed when using Navicat connection

Using Navicat
show table status is not tables
![image](https://user-images.githubusercontent.com/48713296/92991289-87390200-f515-11ea-963a-e98910a3d836.png)

using show tables
![image](https://user-images.githubusercontent.com/48713296/92991441-5dcca600-f516-11ea-8fe2-a8af8d505d42.png)

**Comment by yanhuqing666** [comment]
Can't reproduce， you should upload your configs, describe your operation and show your Navicat version。

**Comment by 314926481** [comment]
dble2：2.19.09.0
dble3：3.20.07.0

After I started dble, I used Navicat to view the list of tables. I couldn't see any tables, but I was querying select * from table_name; can query the data.
Similarly, when using the version of dble2, there is no above problem. The configuration file of dble3 is automatically generated by upgrading.
By querying the debug log. When dble2's show table status is found, the table data information can be queried, and no table data information can be found in dble3

show table status 
dble2：
![image](https://user-images.githubusercontent.com/48713296/93283419-150d3980-f803-11ea-8bed-e6155dc61b32.png)
dble3：
![image](https://user-images.githubusercontent.com/48713296/93283441-1dfe0b00-f803-11ea-9539-06acb470ddbd.png)


My version of Navicat is 12.0.9,
The configuration file is as follows, the rest are the default values
db.xml:
    <dbGroup name="icitytest" rwSplitMode="2" delayThreshold="100">
        <heartbeat>show slave status</heartbeat>
        <dbInstance name="instanceM1" url="127.0.0.1:3406" user="icity" password="mysql!QAZ2wsx!@#" maxCon="1000" minCon="10"
                    primary="true" readWeight="1" id="xx1">
            <property name="testOnCreate">true</property>
        </dbInstance>
    </dbGroup>

user.xml:
<dble:user xmlns:dble="http://dble.cloud/" version="4.0">
    <managerUser name="sky" password="123456" maxCon="100"/>

    <shardingUser name="app_user" password="123456" schemas="icity" readOnly="false" maxCon="20"/>

</dble:user>

sharding.xml:
    <schema name="icity" sqlMaxLimit="1000" shardingNode="dn2"></schema>
    <shardingNode name="dn2" dbGroup="icitytest" database="icity"></shardingNode>

**Comment by 314926481** [comment]
When using the command line to connect to dble3, you cannot query any data by using show table status

**Comment by quexiuping** [comment]
verified on：5.7.21-dble-9.9.9.9-c3b350b31c51b682429c44506b430847bce98e22-20201207061432
Can't reproduce
