### ISSUE TITLE
when connectionTimeout=30 and managercmd execute ,the time more than 5min

### ISSUE THREAD

**Issue by quexiuping** [actiontech/dble#2112]
* **dble version：**  
```
5.6.29-dble-9.9.9.9-12d14d7ed27731358f76889a371a4847b87a6423-20200915064531
```
* **preconditions ：**  
more than connectionTimeout ,the managercmd hang
* **configs：** 

**sharding.xml**  

```
    <schema shardingNode="dn5" name="schema1" sqlMaxLimit="100">
        <globalTable name="g1" shardingNode="dn1,dn2" cron="/5 * * * * ? *" checkClass="CHECKSUM" />
        <globalTable name="g2" shardingNode="dn1,dn3" />
    </schema>

```

* **steps：**    
    step1.  dble in 8066
```
create table schema1.g1(id int,name int)
insert into schema1.g1 values (1,1),(2,2)
```
    step2.  stop mysql server

    step3.  dble in 9066
```
check @@global schema='schema1' and table = 'g1'
```

* **expect result：**  
    1.when connectionTimeout=30 and managercmd execute ,the time more than 30s and less than 31s
* **real result：**  
    1.when connectionTimeout=30 and managercmd execute ,the time more than 5min
* **supplements：**  
    1.

**Comment by PanternBao** [comment]
It's not a bug. The default value of connectionTimeout is 5min in this commit;
