### ISSUE TITLE
SQL:select a.* from gtest a where 1=1 and a.id in (select b.id from test b) order by a.id; could not parse subquery first

### ISSUE THREAD

**Issue by LavieZhou** [actiontech/dble#2130]
* **dble version：**  
dble-2.19.03/lts  30ccce72b3f92b217c4cf6491d601513c13963dd
* **preconditions ：**  
no
* **configs：** 
+-------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+ 
| Table | Create Table                                                                                                                                                      | 
+-------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+ 
| test  | CREATE TABLE `test` ( 
  `id` int(11) DEFAULT NULL, 
  `name` char(20) COLLATE utf8mb4_bin DEFAULT NULL 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin | 
+-------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+ 
+-------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+ 
| Table | Create Table                                                                                                                                                      | 
+-------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+ 
| test  | CREATE TABLE `gtest` ( 
  `id` int(11) DEFAULT NULL, 
  `name` char(20) COLLATE utf8mb4_bin DEFAULT NULL 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin | 
+-------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+ 
**schema.xml**  
```
<schema name="mytest" sqlMaxLimit="1000"> 
<table name="test" rule="hash-two" dataNode="dn01,dn02"></table> 
<table name="gtest" rule="hash-two" dataNode="dn01,dn02"></table> 
</schema> 
```
**rule.xml**  
```
<tableRule name="hash-two"> 
<rule> 
<columns>id</columns> 
<algorithm>two-long</algorithm> 
</rule> 
</tableRule> 
<function class="Hash" name="two-long"> 
<property name="partitionCount">2</property> 
<property name="partitionLength">1</property> 
</function>
```
**server.xml**  

```


```

* **steps：**    
    step1.  
Execute SQL
explain select a.* from gtest a where 1=1 and a.id in (select b.id from test b) order by a.id; 
* **expect result：**  
    1.mysql> explain select a.* from gtest a where 1=1 and a.id in (select b.id from test b) order by a.id; 
+--------------------+-----------------------+-----------------------------------------------------------------------------------------------------------------------------+ 
| DATA_NODE          | TYPE                  | SQL/REF                                                                                                                     | 
+--------------------+-----------------------+-----------------------------------------------------------------------------------------------------------------------------+ 
| dn01_0             | BASE SQL              | select `b`.`id` as `autoalias_scalar` from  `test` `b` LIMIT 2                                                              | 
| dn02_0             | BASE SQL              | select `b`.`id` as `autoalias_scalar` from  `test` `b` LIMIT 2                                                              | 
| merge_1            | MERGE                 | dn01_0; dn02_0                                                                                                              | 
| limit_1            | LIMIT                 | merge_1                                                                                                                     | 
| shuffle_field_1   | SHUFFLE_FIELD         | limit_1                                                                                                                     | 
| scalar_sub_query_1 | SCALAR_SUB_QUERY      | shuffle_field_1                                                                                                             | 
| dn01_1             | BASE SQL(May No Need) | scalar_sub_query_1; select `a`.`id`,`a`.`name` from  `gtest` `a` where `a`.`id` in '{NEED_TO_REPLACE}' ORDER BY `a`.`id` ASC | 
| dn02_1             | BASE SQL(May No Need) | scalar_sub_query_1; select `a`.`id`,`a`.`name` from  `gtest` `a` where `a`.`id` in '{NEED_TO_REPLACE}' ORDER BY `a`.`id` ASC | 
| merge_2            | MERGE                 | dn01_1; dn02_1                                                                                                              | 
| shuffle_field_2   | SHUFFLE_FIELD         | merge_2                                                                                                                     | 
+--------------------+-----------------------+-----------------------------------------------------------------------------------------------------------------------------+ 
10 rows in set (0.02 sec) 
* **real result：**  
    1.mysql> explain select a.* from gtest a where 1=1 and a.id in (select b.id from test b) order by a.id; 
+----------------------------+--------------------------+-----------------------------------------------------------------------------------------------+ 
| DATA_NODE                  | TYPE                     | SQL/REF                                                                                       | 
+----------------------------+--------------------------+-----------------------------------------------------------------------------------------------+ 
| dn01_0                     | BASE SQL                 | select `a`.`id`,`a`.`name` from  `gtest` `a` ORDER BY `a`.`id` ASC                            | 
| dn02_0                     | BASE SQL                 | select `a`.`id`,`a`.`name` from  `gtest` `a` ORDER BY `a`.`id` ASC                            | 
| merge_1                    | MERGE                    | dn01_0; dn02_0                                                                                | 
| shuffle_field_1            | SHUFFLE_FIELD            | merge_1                                                                                       | 
| dn01_1                     | BASE SQL                 | select DISTINCT `b`.`id` as `autoalias_scalar` from  `test` `b` ORDER BY autoalias_scalar ASC | 
| dn02_1                     | BASE SQL                 | select DISTINCT `b`.`id` as `autoalias_scalar` from  `test` `b` ORDER BY autoalias_scalar ASC | 
| merge_2                    | MERGE                    | dn01_1; dn02_1                                                                                | 
| distinct_1                 | DISTINCT                 | merge_2                                                                                       | 
| shuffle_field_3            | SHUFFLE_FIELD            | distinct_1                                                                                    | 
| rename_derived_sub_query_1 | RENAME_DERIVED_SUB_QUERY | shuffle_field_3                                                                               | 
| shuffle_field_4            | SHUFFLE_FIELD            | rename_derived_sub_query_1                                                                    | 
| join_1                     | JOIN                     | shuffle_field_1; shuffle_field_4                                                             | 
| shuffle_field_2            | SHUFFLE_FIELD            | join_1                                                                                        | 
+----------------------------+--------------------------+-----------------------------------------------------------------------------------------------+ 
13 rows in set (0.00 sec)
* **supplements：**  
    1.

**Comment by yanhuqing666** [comment]
in subquery will transfrom to join

**Comment by yanhuqing666** [comment]
delay to next version

**Comment by yanhuqing666** [comment]
https://github.com/actiontech/dble-docs-cn/blob/develop/A.Faq/ErrorCode/Content/inSubQueryTransformToJoin.md
