### ISSUE TITLE
drop view failed if view name contains schema name

### ISSUE THREAD

**Issue by wjl1619** [actiontech/dble#2135]
* **dble version：**  
5.6.29-dble-3.20.07.99-74e9b9ce4526e9c6742d208875e0f86df187b191-20200908030219
* **preconditions ：**  
DO NOT execute "use schema1" before drop view

* **steps：**    
    step1.  login dble with 8066 port and execute sql:
```sql
               drop view if exists schema1.view_tt; 
```
* **expect result：**  
    1.drop view success
* **real result：**  
 ```sql
mysql> drop view if exists schema1.view_tt;
ERROR 1046 (3D000): No database selected
mysql> drop view  schema1.view_tt;
ERROR 1046 (3D000): No database selected
```
* **supplements：**  
    1.

**Comment by quexiuping** [comment]
verified on 5.7.21-dble-9.9.9.9-2bbff7bb74414298df4df40951a5ef4c9d466e0a-20201020015009
