### ISSUE TITLE
simple query, find no Route

### ISSUE THREAD

**Issue by wenyh1** [actiontech/dble#2158]
* **dble version：3.20.07.99**  
* **preconditions ：**  
sharding table：
create table sharding_2_t2(id int,normal_col_1 varchar(30),normal_col_2 varchar(30));
* **configs：** 

**cluster.cnf**  

```


```

**bootstrap.cnf**  

```


```
**db.xml**  

```


```

**user.xml**  

```


```

**sharding.xml**  

```
<shardingTable name="sharding_2_t2" shardingNode="dn1,dn2" function="func_jumpHash" shardingColumn="id"/>

```

* **steps：**    
    step1.  select * from sharding_2_t2 where id = '12' and (normal_col_1 = '0' or normal_col_2 = '1');
* **expect result：**  
    1. success
* **real result：**  
    1. find no Route:select * from sharding_2_t2 where id = '12' and (normal_col_1 = '0' or normal_col_2 = '1')
* **supplements：**  
    1.

**Comment by quexiuping** [comment]
verified on 5.6.29-dble-3.20.07.99-6fb67e20b96f67d8b81632a66bba758a3126d749-20201021023100 and 5.7.21-dble-9.9.9.9-72e69d58c5d468198631b487ecc7f29301e24de6-20201021020509
