### ISSUE TITLE
不支持 WITH PARSER ngram

### ISSUE THREAD

**Issue by gudong** [actiontech/dble#2206]
版本：3.20.07.0

mysql> ALTER TABLE `data` ADD FULLTEXT INDEX idx_data_keyword (`title`, `sub_title`, `cn_title`, `volume`, `author`, `series_title`, `thesaurus`, `tag`)  WITH PARSER ngram;
ERROR 1064 (HY000): sql syntax error, no terminated. IDENTIFIER

不支持 WITH PARSER ngram

mysql> ALTER TABLE `data` ADD FULLTEXT INDEX idx_data_keyword (`title`, `sub_title`, `cn_title`, `volume`, `author`, `series_title`, `thesaurus`, `tag`);
这样是正常的

**Comment by yanhuqing666** [comment]
we will not support Full-text index
