### ISSUE TITLE
 expect send statement 'select ... from table for update' to master

### ISSUE THREAD

**Issue by wjl1619** [actiontech/dble#2225]
* **dble version：**  
5.6.29-dble-2.19.11.99-ff2ccd2e839bfa0f2ea5b1668a909dd86b0bce2a-20201026074503
* **preconditions ：**  
1.
···sql
drop table if exists sharding_4_t1;
create table sharding_4_t1(id int);
insert into sharding_4_t1 values(1),(2),(3),(4);
···
2.set hostS1 as read_only mode, excute sql in hostS1:
```sql
set global super_read_only=on;
```
* **configs：** 

**schema.xml**  

```xml
        <schema dataNode="dn5" name="schema1" sqlMaxLimit="100">
                <table name="sharding_4_t1" dataNode="dn1,dn2,dn3,dn4" rule="hash-four" />
        </schema>

        <dataNode dataHost="ha_group1" database="db1" name="dn1" />
        <dataNode dataHost="ha_group2" database="db1" name="dn2" />
        <dataNode dataHost="ha_group1" database="db2" name="dn3" />
        <dataNode dataHost="ha_group2" database="db2" name="dn4" />
        <dataNode dataHost="ha_group1" database="db3" name="dn5" />

        <dataHost balance="0" maxCon="1000" minCon="10" name="ha_group1" slaveThreshold="100" switchType="1">
                <heartbeat>select user()</heartbeat>
                <writeHost host="hostM1" password="111111" url="172.100.9.5:3306" user="test">
                </writeHost>
        </dataHost>

        <dataHost balance="3" maxCon="1000" minCon="10" name="ha_group2" slaveThreshold="100" switchType="1">
                <heartbeat>select user()</heartbeat>
                <writeHost host="hostM2" password="111111" url="172.100.9.6:3306" user="test">
                 <readHost host="hostS1" password="111111" url="172.100.9.2:3306" user="test"/>
                </writeHost>
        </dataHost>
```

* **steps：**    
    step1.  exec sql :
```sql
select * from sharding_4_t1 where id=1 for update;
```
* **expect result：**  
    1.set to master 
* **real result：**  
    1.set to slave and return error:
```sql
mysql> select * from sharding_4_t1 where id=1 for update;
ERROR 1290 (HY000): The MySQL server is running with the --super-read-only option so it cannot execute this statement
```
* **supplements：**  
    1.

**Comment by wenyh1** [comment]
In addition, 'select ... lock in share mode' also has this problem, need to verify;

**Comment by wjl1619** [comment]
verified on version: 5.7.21-dble-9.9.9.9-60d726b625c288e1d5715d41c90fbab06ab758ce-20201111094506

**Comment by wjl1619** [comment]
verified on version: 5.7.21-dble-3.20.10.99-25f6c6c0ecf47b2a554b0f6934cf5e9b62591029-20201116015929 also.

**Comment by wenyh1** [comment]
Optimized: 
   'select ... for update' and 'select ... lock in share mode' sqls are sent to the master mysql instance in both transaction and non-transaction scenarios

**Comment by wjl1619** [comment]
verified on version: 5.7.21-dble-3.20.10.99-9cbd98516c440ba65641c4d0652c02fe17900e2d-20201125110801，5.7.21-dble-9.9.9.9-7567e1ce91ef5e61caef799a2531bf763b65b4f3-20201125110606

**Comment by dcy10000** [comment]
> In addition, 'select ... lock in share mode' also has this problem, need to verify;

no problem.
