### ISSUE TITLE
inner-726 kill return OK.But doesn't get any effect.

### ISSUE THREAD

**Issue by dcy10000** [actiontech/dble#2340]
* **dble version：**  5.7.21-dble-3.20.10.99-9a609b54f5ae71d5f7aeb892a0ecdc33a359ac87-20201127074744
* **preconditions ：**  
drop table if exists sharding_4_t1;
create table sharding_4_t1(id int,name varchar(20));

* **configs：** 

**sharding.xml**  

```
 <schema shardingNode="dn5" name="schema1" sqlMaxLimit="100">
        <shardingTable name="sharding_4_t1" shardingNode="dn1,dn2,dn3,dn4" function="hash-four" shardingColumn="id"/>
    </schema>

```

* **steps：**    
    step1.  create a normal session `A1`. Run command as follows. 
```
use schema1;
begin;
insert into sharding_4_t1 values(1,1),(2,2),(3,3),(4,4);
```
     step2.  create a manager session. Run command as follows. 
```
mysql> show @@processlist;
+----------+--------------+---------+------+-----------------+------+---------+------+-------+------+
| Front_Id | shardingNode | MysqlId | User | Front_Host      | db   | Command | Time | State | Info |
+----------+--------------+---------+------+-----------------+------+---------+------+-------+------+
|        8 | dn3          | 736     | test | 127.0.0.1:47688 | db2  | Sleep   | 48   |       | NULL |
|        8 | dn2          | 543     | test | 127.0.0.1:47688 | db1  | Sleep   | 48   |       | NULL |
|        8 | dn4          | 536     | test | 127.0.0.1:47688 | db2  | Sleep   | 48   |       | NULL |
|        8 | dn1          | 730     | test | 127.0.0.1:47688 | db1  | Sleep   | 48   |       | NULL |
|        9 | NULL         | NULL    | root | 127.0.0.1:39332 | NULL | NULL    | 0    |       | NULL |
|       10 | NULL         | NULL    | test | 127.0.0.1:47726 | NULL | NULL    | 0    |       | NULL |
+----------+--------------+---------+------+-----------------+------+---------+------+-------+------+



```
   step3.  create another normal session `A2`. Run command as follows. 
```
mysql> kill 8;
Query OK, 0 rows affected (0.00 sec)
```

   step4.  .go to manager session run `show @@processlist;` to check connection 8 is already killed.

* **expect result：**  
    1. connection is killed successfully.
* **real result：**  
    1.connection still alived.

**Comment by wjl1619** [comment]
verified on version: 5.7.21-dble-9.9.9.9-ae91d59367a4493bb445a5942994264db3dd4706-20201130134008，5.7.21-dble-3.20.10.99-de10cf245089409a78a5d7824107a5eca566ac15-20201201073955
