### ISSUE TITLE
schema sqlMaxLimit problem

### ISSUE THREAD

**Issue by lenovore** [actiontech/dble#2362]
* **dble version：**  3.20.07.1
* **preconditions ：**  
no
* **configs：** 

**cluster.cnf**  

```


```

**bootstrap.cnf**  

```


```
**db.xml**  

```


```

**user.xml**  

```


```

**sharding.xml**  

```
<schema name="testdb" shardingNode="dn1">
        <shardingTable name="user_hash2" shardingNode="dn$1-2" sqlMaxLimit="200" function="func_common_hash" shardingColumn="id" incrementColumn="id"/>
</schema>

```

* **steps：**    
    step1.   select * from user_hash2
* **expect result：**  
    1. select * from user_hash2 limit 200
* **real result：**  
    1. select * from user_hash2 limit -1
![QQ截图20201203105146](https://user-images.githubusercontent.com/29646774/100957509-8da7aa80-3555-11eb-9fd3-020bdf371eee.png)

* **supplements：**  
    1.

**Comment by yanhuqing666** [comment]
fixed in 3.20.07.2
