### ISSUE TITLE
使用Navicat数据库工具连接dble3.0版本无法连接

### ISSUE THREAD

**Issue by Neil-Zhou** [actiontech/dble#2389]
* **dble version：dble-3.20.10.0-b29c7c91ac638509dbc4f2c146aea41c3f9f0b83-20201203053354 **  
* **Navicat version：11.1.13(64-bit) Premium **  
* **preconditions ：**  
```
  docker部署dble3.20.10版本，本地测试连接；

```
* **configs：** 

**user.xml**  

```
  <managerUser name="mysql1" usingDecrypt="false" whiteIPs="172.29.95.138,172.29.95.188,172.17.0.%,127.0.0.1,0:0:0:0:0:0:0:1" readOnly="true" password="123456" />
	<managerUser name="user" password="123456" maxCon="100" whiteIPs="172.29.95.138,172.29.95.188,172.17.0.%,127.0.0.1,0:0:0:0:0:0:0:1" readOnly="true"/>
	
    <shardingUser name="mysql" password="123456" schemas="testdb,testdb2" readOnly="false"  maxCon="20"/>

```

![image](https://user-images.githubusercontent.com/16349117/103393237-aad39700-4b5c-11eb-8a20-7857db839e3c.png)

* **steps：**    
    step1.  使用docker部署dble；
    step2.  配置user.xml账号,并配置ip白名单；
    step3.  本地测试连接；
    step4.  客户端测试连接；
* **expect result：**  
    1. 都应该连接成功！
* **real result：**  
    1. 通过同机器docker的mysql客户端，测试shardingUser账号连接，连接失败！
![Uploading image.png…](shardingUser账号)
    2. 通过同机器docker的mysql客户端，测试managerUser账号连接，连接成功！
    3. 通过其他机器navicat连接，测试shardingUser、managerUser账号均失败！
![image](https://user-images.githubusercontent.com/16349117/103393643-b3c56800-4b5e-11eb-8381-2913e55da20e.png)

    4.通过其他机器mysqld client连接，测试shardingUser、managerUser账号均成功！ 

* **supplements：**  
    1.

**Comment by hsiangbinhua** [comment]
![图片](https://user-images.githubusercontent.com/3953400/105833014-97a0d380-6003-11eb-9652-bc691beba1cc.png)
+1，相同配置，也使用navicat连接失败，如上图

**Comment by LUAgam** [comment]
auth plugin is empty when Navicat 11 is connected，you can update the Navicat version(12) or wait for the dble to be fixed

**Comment by quexiuping** [comment]
verified on：5.7.21-dble-9.9.9.9-043d54d3246b80c0f403a38d43bf072f8a3a46eb-20210222033734
use navicat version ：11.1.13  and 15.0.20
