### ISSUE TITLE
sharding routing cannot correctly route to the correct sharding database at "left join" and "union all"

### ISSUE THREAD

**Issue by prostranger** [actiontech/dble#2408]
* **dble version：**  
* 5.6.29-dble-3.20.07.1-70086407f81463c0d7acefdfd2f4f58fe885d1b9-20201021103611
* **preconditions ：**  
no
* **configs：** 
drop table if exists shard_table_a;
create table shard_table_a(
id bigint not null,
shard_key varchar(4) not null,
filed_a varchar(10),
primary key(id)
);

drop table if exists shard_table_b;
create table shard_table_b(
id bigint not null,
shard_key varchar(4) not null,
filed_b varchar(10),
primary key(id)
);

sharding enum：
partition-enum.txt
0000=0
5104=0
5107=1
5101=2
5108=3
5132=4
5109=5
5103=6
5114=7
7178=7
5118=8
5120=9
5113=10
5100=11
5133=12
5111=13
5117=14
5119=15
5116=16
5115=17
5106=18
5110=19
5134=20
5105=21

**cluster.cnf**  

```


```

**bootstrap.cnf**  

```


```
**db.xml**  

```
<dble:db xmlns:dble="http://dble.cloud/">
    <dbGroup name="Hostname1" rwSplitMode="0" delayThreshold="100">
        <heartbeat>show slave status</heartbeat>
        <dbInstance name="hostM1" url="192.168.0.99:3306" user="test_dc" password="xxx" maxCon="1000" minCon="100" primary="true" usingDecrypt="0">
            <property name="heartbeatPeriodMillis">10000</property>
            <property name="timeBetweenEvictionRunsMillis">300000</property>
            <property name="idleTimeout">1800000</property>
        </dbInstance>
        <dbInstance name="hostR1" url="192.168.0.196:3306" user="test_dc" password="xxx" maxCon="1000" minCon="100" usingDecrypt="0">
            <property name="heartbeatPeriodMillis">10000</property>
            <property name="timeBetweenEvictionRunsMillis">300000</property>
            <property name="idleTimeout">1800000</property>
        </dbInstance>
    </dbGroup>
    <dbGroup name="Hostname2" rwSplitMode="0" delayThreshold="100">
        <heartbeat>show slave status</heartbeat>
        <dbInstance name="hostM1" url="192.168.0.78:3306" user="test_dc" password="xxx" maxCon="1000" minCon="100" primary="true" usingDecrypt="0">
            <property name="heartbeatPeriodMillis">10000</property>
            <property name="timeBetweenEvictionRunsMillis">300000</property>
            <property name="idleTimeout">1800000</property>
        </dbInstance>
        <dbInstance name="hostR1" url="192.168.0.164:3306" user="test_dc" password="xxx" maxCon="1000" minCon="100" usingDecrypt="0">
            <property name="heartbeatPeriodMillis">10000</property>
            <property name="timeBetweenEvictionRunsMillis">300000</property>
            <property name="idleTimeout">1800000</property>
        </dbInstance>
    </dbGroup>
    <dbGroup name="Hostname3" rwSplitMode="0" delayThreshold="100">
        <heartbeat>show slave status</heartbeat>
        <dbInstance name="hostM1" url="192.168.0.126:3306" user="test_dc" password="xxx" maxCon="1000" minCon="100" primary="true" usingDecrypt="0">
            <property name="heartbeatPeriodMillis">10000</property>
            <property name="timeBetweenEvictionRunsMillis">300000</property>
            <property name="idleTimeout">1800000</property>
        </dbInstance>
        <dbInstance name="hostR1" url="192.168.0.23:3306" user="test_dc" password="xxx" maxCon="1000" minCon="100" usingDecrypt="0">
            <property name="heartbeatPeriodMillis">10000</property>
            <property name="timeBetweenEvictionRunsMillis">300000</property>
            <property name="idleTimeout">1800000</property>
        </dbInstance>
    </dbGroup>
</dble:db>
```

**user.xml**  
```
<dble:user xmlns:dble="http://dble.cloud/">
    <shardingUser name="test_dc" schemas="test_dc" password="123456" usingDecrypt="false"></shardingUser>
</dble:user>
```

**sharding.xml**  
```
<dble:sharding xmlns:dble="http://dble.cloud/">
    <schema name="test_dc">
	    <shardingTable name="shard_table_a" shardingNode="an1,an2,an3,an4,an5,an6,an7,an8,an9,an10,an11,an12,an13,an14,an15,an16,an17,an18,an19,an20,an21,an22" shardingColumn="shard_key" function="func_enum"></shardingTable>
        <shardingTable name="shard_table_b" shardingNode="an1,an2,an3,an4,an5,an6,an7,an8,an9,an10,an11,an12,an13,an14,an15,an16,an17,an18,an19,an20,an21,an22" shardingColumn="shard_key" function="func_enum"></shardingTable>
	</schema>
    <shardingNode name="an1" dbGroup="Hostname1" database="test_dc1"></shardingNode>
    <shardingNode name="an2" dbGroup="Hostname1" database="test_dc2"></shardingNode>
    <shardingNode name="an3" dbGroup="Hostname1" database="test_dc3"></shardingNode>
    <shardingNode name="an4" dbGroup="Hostname1" database="test_dc4"></shardingNode>
    <shardingNode name="an5" dbGroup="Hostname1" database="test_dc5"></shardingNode>
    <shardingNode name="an6" dbGroup="Hostname1" database="test_dc6"></shardingNode>
    <shardingNode name="an7" dbGroup="Hostname1" database="test_dc7"></shardingNode>
    <shardingNode name="an8" dbGroup="Hostname1" database="test_dc8"></shardingNode>
    <shardingNode name="an9" dbGroup="Hostname2" database="test_dc9"></shardingNode>
    <shardingNode name="an10" dbGroup="Hostname2" database="test_dc10"></shardingNode>
    <shardingNode name="an11" dbGroup="Hostname2" database="test_dc11"></shardingNode>
    <shardingNode name="an12" dbGroup="Hostname2" database="test_dc12"></shardingNode>
    <shardingNode name="an13" dbGroup="Hostname2" database="test_dc13"></shardingNode>
    <shardingNode name="an14" dbGroup="Hostname2" database="test_dc14"></shardingNode>
    <shardingNode name="an15" dbGroup="Hostname2" database="test_dc15"></shardingNode>
    <shardingNode name="an16" dbGroup="Hostname2" database="test_dc16"></shardingNode>
    <shardingNode name="an17" dbGroup="Hostname3" database="test_dc17"></shardingNode>
    <shardingNode name="an18" dbGroup="Hostname3" database="test_dc18"></shardingNode>
    <shardingNode name="an19" dbGroup="Hostname3" database="test_dc19"></shardingNode>
    <shardingNode name="an20" dbGroup="Hostname3" database="test_dc20"></shardingNode>
    <shardingNode name="an21" dbGroup="Hostname3" database="test_dc21"></shardingNode>
    <shardingNode name="an22" dbGroup="Hostname3" database="test_dc22"></shardingNode>
    <function name="func_enum" class="Enum">
        <property name="mapFile">partition-enum.txt</property>
        <property name="defaultNode">11</property>
        <property name="type">1</property>
    </function>
</dble:sharding>
```

* **steps：**    
    step1.  
insert into shard_table_a values (1,'5101','5101'),(2,'5100','5101');
insert into shard_table_b values (1,'5101','5101'),(2,'5100','5101');
insert into shard_table_a values (3,'5104','5104');

    step2.
explain
select a.id,a.filed_a,b.filed_b
from shard_table_a a
left join shard_table_b b on a.id = b.id and b.shard_key = '5104'
where a.shard_key = '5104'
limit 10;

    step3.
explain
select a.id,a.filed_a,b.filed_b
from shard_table_a a
inner join shard_table_b b on a.id = b.id and b.shard_key = '5104'
where a.shard_key = '5104'
union all
select a.id,a.filed_a,b.filed_b
from shard_table_a a
inner join shard_table_b b on a.id = b.id and b.shard_key = '5104'
where a.shard_key = '5104'
limit 10;

* **expect result：**  
    1.the whole sql statement should be routed to sharding node: <shardingNode name="an1" dbGroup="Hostname1" database="test_dc1"></shardingNode>
* **real result：**  
    1.
+-----------------+---------------+------------------------------------------------------------------------------------------------------------------------------+
| SHARDING_NODE   | TYPE          | SQL/REF                                                                                                                      |
+-----------------+---------------+------------------------------------------------------------------------------------------------------------------------------+
| an1_0           | BASE SQL      | select `a`.`id`,`a`.`shard_key`,`a`.`filed_a` from  `shard_table_a` `a` where `a`.`shard_key` = '5104' ORDER BY `a`.`id` ASC |
| merge_1         | MERGE         | an1_0                                                                                                                        |
| shuffle_field_1 | SHUFFLE_FIELD | merge_1                                                                                                                      |
| an1_1           | BASE SQL      | select `b`.`id`,`b`.`shard_key`,`b`.`filed_b` from  `shard_table_b` `b` where `b`.`shard_key` = '5104' ORDER BY `b`.`id` ASC |
| merge_2         | MERGE         | an1_1                                                                                                                        |
| shuffle_field_3 | SHUFFLE_FIELD | merge_2                                                                                                                      |
| join_1          | JOIN          | shuffle_field_1; shuffle_field_3                                                                                             |
| limit_1         | LIMIT         | join_1                                                                                                                       |
| shuffle_field_2 | SHUFFLE_FIELD | limit_1                                                                                                                      |
+-----------------+---------------+------------------------------------------------------------------------------------------------------------------------------+
9 rows in set (0.00 sec)
    2.
+-----------------+---------------+------------------------------------------------------------------------------------------------------------------------------+
| SHARDING_NODE   | TYPE          | SQL/REF                                                                                                                      |
+-----------------+---------------+------------------------------------------------------------------------------------------------------------------------------+
| an1_0           | BASE SQL      | select `a`.`id`,`a`.`shard_key`,`a`.`filed_a` from  `shard_table_a` `a` where `a`.`shard_key` = '5104' ORDER BY `a`.`id` ASC |
| merge_1         | MERGE         | an1_0                                                                                                                        |
| shuffle_field_1 | SHUFFLE_FIELD | merge_1                                                                                                                      |
| an1_1           | BASE SQL      | select `b`.`id`,`b`.`shard_key`,`b`.`filed_b` from  `shard_table_b` `b` where `b`.`shard_key` = '5104' ORDER BY `b`.`id` ASC |
| merge_2         | MERGE         | an1_1                                                                                                                        |
| shuffle_field_4 | SHUFFLE_FIELD | merge_2                                                                                                                      |
| join_1          | JOIN          | shuffle_field_1; shuffle_field_4                                                                                             |
| shuffle_field_2 | SHUFFLE_FIELD | join_1                                                                                                                       |
| an1_2           | BASE SQL      | select `a`.`id`,`a`.`shard_key`,`a`.`filed_a` from  `shard_table_a` `a` where `a`.`shard_key` = '5104' ORDER BY `a`.`id` ASC |
| merge_3         | MERGE         | an1_2                                                                                                                        |
| shuffle_field_5 | SHUFFLE_FIELD | merge_3                                                                                                                      |
| an1_3           | BASE SQL      | select `b`.`id`,`b`.`shard_key`,`b`.`filed_b` from  `shard_table_b` `b` where `b`.`shard_key` = '5104' ORDER BY `b`.`id` ASC |
| merge_4         | MERGE         | an1_3                                                                                                                        |
| shuffle_field_7 | SHUFFLE_FIELD | merge_4                                                                                                                      |
| join_2          | JOIN          | shuffle_field_5; shuffle_field_7                                                                                             |
| limit_1         | LIMIT         | join_2                                                                                                                       |
| shuffle_field_6 | SHUFFLE_FIELD | limit_1                                                                                                                      |
| union_all_1     | UNION_ALL     | shuffle_field_2; shuffle_field_6                                                                                             |
| shuffle_field_3 | SHUFFLE_FIELD | union_all_1                                                                                                                  |
+-----------------+---------------+------------------------------------------------------------------------------------------------------------------------------+
19 rows in set (0.00 sec)

* **supplements：**  
    1.The result set returned is correct, but if shard_ table_ a and shard_ table_b are vary large, dble will consume too much CPU and memory resources.
   so,In my opinion, if multiple sharding tables are join(only left join and unin all statement) with the same sharding key, the whole SQL statement should be routed to the correct sharding database,like "inner join"

**Comment by Dinosauria** [comment]
Verified in 5.7.21-dble-9.9.9.9-05c27a5f80bddd88d332b2157524f25dad725376-20210524070924
![image](https://user-images.githubusercontent.com/17309012/119652037-35909780-be58-11eb-9acb-00869a726122.png)
