### ISSUE TITLE
'/*!dble:sql=select 1;*/call proc_test();' ,dble hangs

### ISSUE THREAD

**Issue by zhunina** [actiontech/dble#246]
```
mysql> /*!dble:sql=select 1;*/call proc_test();

```

**Comment by yanhuqing666** [comment]
1.don't add ';'    
2.use "/** !dble: */" for mysql   and "/** #dble: */"  for mybatis   
3.As of MySQL 5.7.7, the mysql client always passeshints to the server, regardless of whether this option is given. To ensure that hints are not stripped if you are using an older version of the mysql client with a version of the server that understands hints, invoke mysql with the --comments option.

**Comment by yexiaoli88** [comment]
verified on dble version: 5.6.29-dble-9.9.9.9-a0cd8d1a73a121acfc7f9ff917d02c52eec7ba32-20190117062756

**Comment by yexiaoli88** [comment]
auto_test position:sql_cover/special/hint.feature line443
