### ISSUE TITLE
mysqldump的导出文件用dble导入时,导入线程显示mdl锁

### ISSUE THREAD

**Issue by jiang-hao-01** [actiontech/dble#2485]
* **dble version：** 2.19.01.0
* **preconditions ：**  
在dble下的两个数据库show processlist都会看到mdl锁，初步分析是dump文件中有lock table write操作，而dble多线程导入时，会被lock table write的线程锁住。
* **configs：** 

**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  
* **expect result：**  
    1.
* **real result：**  
    1.
* **supplements：**  
    1.

**Comment by Dinosauria** [comment]
@jiang-hao-01 你好，这个问题在2.19.01.0版本确实可以复现，但是在目前最新的released版本 3.21.02版本已无此问题，建议通过升级dble来解决问题
测试版本 
5.6.29-dble-2.19.01.0-303221e9e77e00d7741629e15f8053e4fa196de3-20190228085303  问题仍存在
5.7.21-dble-3.21.02.99-2c790c9bd7ad21f77d4c8662fcf1a80d1cf9d35b-20210707094917  问题已不存在
