### ISSUE TITLE
Mysql8.0主键如果使用降序索引,在 MetaHelper.initTableMeta 阶段会报错.

### ISSUE THREAD

**Issue by Jack2222-luck** [actiontech/dble#2560]
* **dble version：**  
* 5.7.11-dble-3.20.10.99-cdc0923be854d91a0f942a9027bef1454057bde3-20201203102538
* **preconditions ：**  
no

* **steps：**    
    step1.  使用MYSQL8.0,主键降序索引新特性,建表时,在 MetaHelper.initTableMeta 阶段会报错.

* **sharding.xml：**

   `<shardingTable name="tb_enum_sharding" shardingNode="dn1,dn2" sqlMaxLimit="200" function="func_enum" shardingColumn="code"/>`

* **expect result：**  
    1.建表SQL如下
CREATE TABLE `tb_enum_sharding` (
  `id` int(11) NOT NULL,
  `code` int(11) NOT NULL COMMENT 'code',
  `content` varchar(250) NOT NULL,
  PRIMARY KEY (`id` DESC) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8
* **报错日志：**  
    WARN [complexQueryExecutor1] (com.actiontech.dble.meta.table.MetaHelper.initTableMeta(MetaHelper.java:60)) - sql[CREATE TABLE `tb_enum_sharding` (
  `id` int(11) NOT NULL,
  `code` int(11) NOT NULL COMMENT 'code',
  `content` varchar(250) NOT NULL,
  PRIMARY KEY (`id` DESC) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8] parser error:
com.alibaba.druid.sql.parser.ParserException: syntax error, expect RPAREN, actual DESC pos 159, line 5, column 21, token DESC
* **supplements：**  
    1.主要的原因是druid解析主键的时候报错,不能识别带了降序标志 **PRIMARY KEY (`id` DESC)** 的主键信息而导致报错.

**Comment by yanhuqing666** [comment]
looks like fixed by druid 1.2.x， you can try to use 3.21.02.0

**Comment by quexiuping** [comment]
verified on 3.21.02,create table successed.
