### ISSUE TITLE
load data would lost connection when transaction timeout

### ISSUE THREAD

**Issue by LavieZhou** [actiontech/dble#2787]
* **dble version：2.19.03/lts**  
* **preconditions ：**  
CREATE TABLE `test` (
  `id` int(11) DEFAULT NULL,
  `name` varchar(200) DEFAULT NULL
)
* **configs：** 
test1.txt
1,a
2,b
3,c
4,d
5,e
6,f
7,g
8,h
**schema.xml**  

```
 <table name="test" dataNode="dn1,dn2" rule="rule_common_hash"/>


```

**rule.xml**  

```
 <tableRule name="rule_common_hash">
        <rule>
            <columns>id</columns>
            <algorithm>func_common_hash</algorithm>
        </rule>
    </tableRule>
 <function name="func_common_hash" class="Hash">
        <property name="partitionCount">2</property>
        <property name="partitionLength">1</property>
    </function>


```

**server.xml**  

```
<property name="sqlExecuteTimeout">2</property>

```

* **steps：**    
    step1.  
set autocommit=0;
/\*!dble:datanode=dn1\*/select * from test;
select sleep (3);
load data local infile "./test1.txt" into table test fields terminated by "," lines terminated by "\n";
* **expect result：**  
    1.Transaction error, need to rollback.Reason:[ errNo:1023 Connection {DataHost[127.0.0.1:3306],Schema[db1],threadID[27]} was closed ,reason is [sql timeout]]
* **real result：**  
    1.Lost connection to MySQL server during query
* **supplements：**  
    1.

**Comment by yanhuqing666** [comment]
update to new version
