### ISSUE TITLE
update/insert/delete exeuted successfully in MySQL but DBLE return sql timeout in singlenode scenario

### ISSUE THREAD

**Issue by LavieZhou** [actiontech/dble#2788]
* **dble version：dble-2.19.03/lts**  
* **preconditions ：**  
CREATE TABLE test (
id int(11) DEFAULT NULL,
name varchar(200) DEFAULT NULL
)
insert into test values(1,"a");
* **configs：** 

**schema.xml**  

```
<table name="test" dataNode="dn1,dn2" rule="rule_common_hash"/>

```

**rule.xml**  

```
 <tableRule name="rule_common_hash">
        <rule>
            <columns>id</columns>
            <algorithm>func_common_hash</algorithm>
        </rule>
    </tableRule>
 <function name="func_common_hash" class="Hash">
        <property name="partitionCount">2</property>
        <property name="partitionLength">1</property>
    </function>


```

**server.xml**  

```
<property name="sqlExecuteTimeout">1</property>

```

* **steps：**    
    step1.  set breakpoint in MySQLConnectionHandler.java:158
    step2. execute "update test set name="b" where id =1;"
    step3. Connection {DataHost[127.0.0.1:3306],Schema[db2],threadID[44]} was closed ,reason is [sql timeout]
* **expect result：**  
    1. mysql> select * from test;
+------+------+
| id   | name |
+------+------+
|    1 | a   |
+------+------+

* **real result：**  
    1.mysql> select * from test;
+------+------+
| id   | name |
+------+------+
|    1 | b    |
+------+------+

* **supplements：**  
    1.

**Comment by dcy10000** [comment]
'sqlExecuteTimeout' property use to guarantee that SQL will not hang for too long.
If the SQL execute time > 'sqlExecuteTimeout', the connection will be closed because of 'SQL timeout'.

If a connection is closed because of network problems, we can't know whether this SQL executes ok or not.
Similarly, if a connection is closed because of SQL timeout,  we can't know too.

**Comment by LavieZhou** [comment]
Another test  scenario :
  step1. insert into test values (2,“a”),(2,"b");
  step2.start a transaction and excute “select * from test where id =2 for update” in MySQL.
  step3. execute "update test set name ="er" where id=2" in dble
             dble return ：mysql> update test set name="er" where id =2;
ERROR 1023 (HY000): Connection {DataHost[127.0.0.1:3306],Schema[db1],threadID[16]} was closed ,reason is [sql timeout]
  step4.  execute "commit" in mysql
  step5.  execute "select * from test " in dble
             mysql> select * from test;
                        +------+------+
                        | id   | name |
                        +------+------+
                        |    2 | er   |
                        |    2 | er   |
                        |    1 | a    |
                        +------+------+
                        3 rows in set (0.01 sec)

   I found  mysql data was changed but return error for user.

**Comment by dcy10000** [comment]
Same reason.
timeout != error

**Comment by dcy10000** [comment]
This isn't a bug.
You can increase the sqlExecuteTimeout if you don't want receive sql timeout.

**Comment by LavieZhou** [comment]
return a sql time for user but mysql changed sucessfully that can't accept .
and when sql timeout dble obviously  send a com_quit to mysql ,why it doesn't work.
![58916B651AEB360F959A3FE2F3CB52B0](https://user-images.githubusercontent.com/46223149/126603497-a75f5d94-28c6-46f6-93a7-761d07a88a28.jpg)

**Comment by yanhuqing666** [comment]
com_quit != rollback

**Comment by dcy10000** [comment]
Even if you directly connect Mysql. You also can receive errors because of other reasons(e.g. network problems).In these scenes, you can't know MySQL changed or not, either.



Mysql processes packet one by one. com_quit packet can't be processed when the connection is hanging by another query.

**Comment by LavieZhou** [comment]
Exclude network problem，in second scenes, during the sql (update test set name ="er" where id=2" )wait for lock release ,the connection was closed due to sql timeout , shoudn't be rollabck the sql？

**Comment by dcy10000** [comment]
1. non-transaction SQL can't be rollback.
2. No matter receive what kind of exception，you should check where the problem is. For timeout, you should check and ensure consistency by yourself.

**Comment by LavieZhou** [comment]
In this scenes,can dble  close the front connection to tell user should handle  again because the result of this sql is unknown?

**Comment by LavieZhou** [comment]
In this scenes,can dble  close the front connection to tell user should handle  again because the result of this sql is unknown?

**Comment by dcy10000** [comment]
The close front connection operation doesn't represent this status of SQL is unknown.
 

We send an error packet to the front connection, you can check this.

Like this:
ERROR 1023 (HY000): Connection {DataHost[127.0.0.1:3306],Schema[db1],threadID[16]} was closed ,reason is [sql timeout]



If the error code is 1023, it means that some connections need to be closed because of some exceptions.
Then，SQL timeout is one of the exceptions, you can locate it by check the detailed error message.

**Comment by LavieZhou** [comment]
Thanks for your carefully answers
