### ISSUE TITLE
load data batch mode problem

### ISSUE THREAD

**Issue by lenovore** [actiontech/dble#2791]
* **dble version：**  3.21.02.1
* **mysql version：**  8.0.19
* **preconditions ：**  
no
* **configs：** 
**sharding.xml**  

```
 <schema name="testdb" shardingNode="dn1">
         <shardingTable name="s_order" shardingNode="dn$1-4" function="func_jumpHash_int" shardingColumn="id">
            <childTable name="s_order_item" joinColumn="seller_order_id" parentColumn="id"/>
         </shardingTable>
    </schema>

<shardingNode name="dn$1-4" dbGroup="dbGroup1" database="dble$1-4"/>

<function name="func_jumpHash_int" class="jumpStringHash">
        <property name="partitionCount">4</property>
        <property name="hashSlice">0:20</property>
    </function>
```
* **steps：**    
1. aso.txt has 3600W rows
2. bootstrap.conf 
-DenableBatchLoadData=1 
-DmaxRowSizeToFile=500000
3. exec mysql -P8066 -e"load data infile 'aso.txt' into table s_order;"

* **expect result：**  
    1.import data
* **real result：**  
   1. files are generated in the temp/files directory, this is no problem
    
![图片](https://user-images.githubusercontent.com/29646774/126258799-1f041540-5fd6-41c4-a4d4-016a183acd61.png)

    2. Then the front-end and back-end sessions have been in sleep state, and the data has not been imported
![1](https://user-images.githubusercontent.com/29646774/126258553-ebbbe059-5ea7-4b7c-b5be-021095b29407.png)
![2](https://user-images.githubusercontent.com/29646774/126258556-b0be5b51-c436-4ff4-a627-b8574fa0a86a.png)

    3. there is no error messages in the dble log or mysql log

**Comment by jndxcaiwei** [comment]
Could you provide the sql about creating table and the test file？

**Comment by lenovore** [comment]
[t.zip](https://github.com/actiontech/dble/files/6845617/t.zip)
only 2 rows test data are provided

**Comment by lenovore** [comment]
i opened the general_log of mysql and found out that ‘load data local ’was executed
i didn’t add ‘local’ when i executed it, why did dble add it?
![图片](https://user-images.githubusercontent.com/29646774/126266792-3c22f6a9-e371-4902-b424-7982eca163f6.png)

**Comment by lenovore** [comment]
load data batch mode does not reuse connections，a new connection is created every time a batch is completed
![图片](https://user-images.githubusercontent.com/29646774/126298168-6e82bfb0-a5cb-4900-ba61-84dddb9cd87e.png)

**Comment by ylinzhu** [comment]
> 奇怪的是，不是批量执行的，而且文件都是在temp/file目录下生成的，为什么load数据还是用原来的文件aso.txt？



> i opened the general_log of mysql and found out that ‘load data local ’was executed
> i didn’t add ‘local’ when i executed it, why did dble add it?
> ![图片](https://user-images.githubusercontent.com/29646774/126266792-3c22f6a9-e371-4902-b424-7982eca163f6.png)
> 
> by the way, dble and mysql and exec load data are on the same machine



> i found the problem. mysql is configured with local_infile=0. when local_infile=1 is set, the import is normal, but why is there no error message returned on the dble side?
> ![图片](https://user-images.githubusercontent.com/29646774/126267575-ec890eca-272c-4c7a-bcd4-8ae055d7f118.png)

**Comment by ylinzhu** [comment]
1. 

> i found the problem. mysql is configured with local_infile=0. when local_infile=1 is set, the import is normal, but why is there no error message returned on the dble side?
> ![图片](https://user-images.githubusercontent.com/29646774/126267575-ec890eca-272c-4c7a-bcd4-8ae055d7f118.png)

use mysql client hava error message : ERROR 1148: The used command is not allowed with this MySQL version ,use navicat 12 the same error is reported. What client and version are you using

**Comment by ylinzhu** [comment]
> load data batch mode does not reuse connections，a new connection is created for next batch every time when current batch is completed
> ![图片](https://user-images.githubusercontent.com/29646774/126298168-6e82bfb0-a5cb-4900-ba61-84dddb9cd87e.png)

We need each connection to be responsible for its own commit  or rollback. So there's no reuse

**Comment by ylinzhu** [comment]
> the strange thing is, isn't it executed in batches, and the files are all generated in the temp/file directory, why the load data still uses the original file aso.txt?

We did not modify the sql, the files used are in the temp/file directory.

**Comment by jndxcaiwei** [comment]
Steps to reproduce：
1. set one backend mysql's ( which used by table for loading data )local_infile=off  &&  set load_data_batch=on;
2. mysql client connect to dble , load data:
![image](https://user-images.githubusercontent.com/70261656/126433485-b527ce6d-b22d-4a3c-a236-6b4cd89de1b0.png)
3. navicat12 connect to dble, load data:
![image](https://user-images.githubusercontent.com/70261656/126433545-4c2a3c6b-55e9-4b6f-92c8-23e81ada09a6.png)

both types connect to dble all give the prompt information，and other backend mysql's  data ( local_infile=on ) used by table for loading data all have  successfully import

**Comment by lenovore** [comment]
> 
> 
> > i found the problem. mysql is configured with local_infile=0. when local_infile=1 is set, the import is normal, but why is there no error message returned on the dble side?
> > ![图片](https://user-images.githubusercontent.com/29646774/126267575-ec890eca-272c-4c7a-bcd4-8ae055d7f118.png)
> 
> use mysql client hava error message : ERROR 1148: The used command is not allowed with this MySQL version ,use navicat 12 the same error is reported. What client and version are you using？

i use this command: mysql -P8066 -e"load data infile 'aso.txt' into table s_order;"   and did not enter the interactive.
mysql client version is 10.3.24-MariaDB

**Comment by ylinzhu** [comment]
> > > i found the problem. mysql is configured with local_infile=0. when local_infile=1 is set, the import is normal, but why is there no error message returned on the dble side?
> > > ![图片](https://user-images.githubusercontent.com/29646774/126267575-ec890eca-272c-4c7a-bcd4-8ae055d7f118.png)
> > 
> > 
> > use mysql client hava error message : ERROR 1148: The used command is not allowed with this MySQL version ,use navicat 12 the same error is reported. What client and version are you using？
> 
> i use this command: mysql -P8066 -e"load data infile 'aso.txt' into table s_order;" and did not enter the interactive.
> mysql client version is 10.3.24-MariaDB

dble fails to load data and send rollback， will have error message: rollback error connection closed. Real errors are sent to the client.You can use the mysql client and try it

**Comment by lenovore** [comment]
ok,tks!

**Comment by jndxcaiwei** [comment]
by the way, the version of dble you used may  come across a hang bug when  you use load data batch mode，and this bug has fixed in the next version to be released.

**Comment by lenovore** [comment]
maybe my situation is what you said
