### ISSUE TITLE
The transcation fail problem

### ISSUE THREAD

**Issue by boying52** [actiontech/dble#2819]
* **dble version：**  3.21.02.1 and master brance

When the concurrency is high, the same method of the application repeatedly executes the insert or update statement that starts the transaction, and an error is reported. The application rollback succeeds, but the data is still commited to the database.

configs:
bootstrap.cnf
user.xml
db.xml
dble.log
The above infomation has been submited to the technician。

**Comment by LUAgam** [comment]
okay, this is an issue and will be fixed

**Comment by boying52** [comment]
The first time we test this commit，but problem still rising...., transaction still fail rollback

**Comment by LUAgam** [comment]
> The first time we test this commit，but problem still rising...., transaction still fail rollback

confirm whether the version contains the submitted content

**Comment by boying52** [comment]
we confirm the fix/02-1298branch and  3.21.06.99/lts branch has been fixed。
