### ISSUE TITLE
Partition rule "Hash" ( PartitionByLong ) may have a greater interger space than 1024

### ISSUE THREAD

**Issue by Lordess** [actiontech/dble#285]
Phenonmenon
=========

"Hash" class in rule.xml is redirected to `com.actiontech.dble.route.function.PartitionByLong`, which uses `com.actiontech.dble.route.util.PartitionUtil` for routing.

With comments inside, it seems that `PartitionUtil` wants to limit its sharding space into a [0,1024] interger space. 

It will do check when it is initializing: 

1. get the dot product of `partitionCount` array and `partitionLength` array 

> dot product :=
> { partitionCount_1, partitionCount_2, ... , partitionCount_n } · { partitionLength_1, partitionLength_2, ... , partitionLength_n }

2. compare the limit and the dot product.

``` Java
partitionLength = ai[ai.length - 1];
/* other statments */
if (partitionLength > MAX_PARTITION_LENGTH) {
    throw new RuntimeException("error,check your partitionScope definition.MAX(sum(count*length[i]) must be less then 1024 ");
}
```

**But**, the limit here is not 1024, but 2880. So, a setting like `partitionCount[] = {1} ; paritiontLength[] = {2880}` is runnable. Though the case is against the design.

``` Java
private static final int MAX_PARTITION_LENGTH = 2880;
```

How to Repeat
=========

Start your dble, which has "Hash" tables, with settings belows, you will find dble works. Though this is against its design goal.

``` xml
<function name="your_function_name" class="Hash" >
    <property name="partitionCount">1</property>
    <property name="partitionLength">2880</property>
</function>
```

Fix Suggestion
=========

Change the value of MAX_PARTITION_LENGTH in `PartitionUtil` with 1024.

``` Java
private static final int MAX_PARTITION_LENGTH = 1024;
```

**Comment by yanhuqing666** [comment]
we will fix the error tip "error,check your partitionScope definition.MAX(sum(count*length[i]) must be less then 2880"
