### ISSUE TITLE
Plugin execution not covered by lifecycle configuration( something about pom.xml )

### ISSUE THREAD

**Issue by Lordess** [actiontech/dble#297]
Phenonmenon
======

When I importted the release of project into Eclipse, I had errors belows. They stopped Eclipse from importting it.

Description|Resource|Path|Location|Type
-----------|--------|----|--------|-----
Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-compiler-plugin:3.6.2:testCompile (execution: default-testCompile, phase: test-compile)|pom.xml|/dble-2.17.08.1-tag|line 306|Maven Project Build Lifecycle Mapping Problem
Plugin execution not covered by lifecycle configuration: org.codehaus.mojo:buildnumber-maven-plugin:1.3:create-timestamp (execution: default, phase: validate)|pom.xml|/dble-2.17.08.1-tag|line 593|Maven Project Build Lifecycle Mapping Problem

They seems to be matters about maven build lifecycle. And I found `testCompile` and `create-timestamp` cannot be mapping correctly.

![lifecycle_of_dble](https://user-images.githubusercontent.com/14990623/31800720-6af429e0-b575-11e7-877e-7394d9e0e0ce.png)

As a comparison, mycat in Eclipse has such lifecycle mapping.

![lifecycle_of_mycat](https://user-images.githubusercontent.com/14990623/31801004-b4c5bf6e-b577-11e7-860e-858d82e73c93.png)

My environment are:

* Win7 x64
* JDK 1.8
* Eclipse Neon3 4.6.3 + Maven 3.3.9(Embedded)
* DBLE 2.17.08.1
* MyCat 1.6.5

How to Repeat
=============

Import the project in eclipse as:

File -> Import -> Maven -> Existing Maven Projects

Fix Suggestions
===============

I think this is not a bug, but something about ease of use. Hence, here I have two workarounds.

1. Workaround 1

Modified the pom.xml before importting.

``` xml
<pluginExecution>
	<pluginExecutionFilter>
		<groupId>org.apache.maven.plugins</groupId>
		<artifactId>maven-compiler-plugin</artifactId>
		<versionRange>[3.1,)</versionRange>
		<goals>
			<goal>compile</goal>
      <!-- add testCompile here -->
			<goal>testCompile</goal>
		</goals>
	</pluginExecutionFilter>
	<action>
		<ignore></ignore>
	</action>
</pluginExecution>

...

<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>buildnumber-maven-plugin</artifactId>
    <version>1.3</version>
    <executions>
        <execution>
            <phase>validate</phase>
            <goals>
                <!-- here we replace create-timestamp with create -->
                <!--
                <goal>create-timestamp</goal>
                -->
                <goal>create</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
        <timestampFormat>yyyyMMddHHmmss</timestampFormat>
    </configuration>
</plugin>
```

2. Workaround 2

Hope your guys can give a guide to config the lifecycle.

**Comment by yanhuqing666** [comment]
m2e  is a little weak.
 
![A1](https://user-images.githubusercontent.com/16715575/31807879-2bdddfde-b5a3-11e7-8141-4a4f623546a3.png)

![a2](https://user-images.githubusercontent.com/16715575/31807948-83c533fa-b5a3-11e7-9fe2-89b12f2d4d2e.png)

**Comment by Lordess** [comment]
Grateful for your response.

Okay, I will try a standard Maven at first. But I wonder you dont have the question with your eclipse?

**Comment by yanhuqing666** [comment]
You can just IGNORE the error and build project using maven commend.

**How to ignore:**

1.Just click the link “Mark goal ... as ignored in Eclipse Build in ....” as my pictures above

**OR:**

2.Open Windows -> Preferences-> Maven -> Lifecycle Mapping->Open workspace lifecycle mappings metadata
![lifecycle](https://user-images.githubusercontent.com/16715575/31858148-e864bc60-b722-11e7-807f-cee65c06eafa.png)

add seeting like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<lifecycleMappingMetadata>
  <pluginExecutions>
    <pluginExecution>
      <pluginExecutionFilter>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-checkstyle-plugin</artifactId>
        <versionRange>2.17</versionRange>
        <goals>
          <goal>check</goal>
        </goals>
      </pluginExecutionFilter>
      <action>
        <ignore />
      </action>
    </pluginExecution>
    <pluginExecution>
      <pluginExecutionFilter>
        <groupId></groupId>
        <artifactId></artifactId>
        <versionRange></versionRange>
        <goals>
          <goal></goal>
        </goals>
      </pluginExecutionFilter>
      <action>
        <ignore />
      </action>
    </pluginExecution>
    <pluginExecution>
      <pluginExecutionFilter>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <versionRange>3.6.2</versionRange>
        <goals>
          <goal>testCompile</goal>
        </goals>
      </pluginExecutionFilter>
      <action>
        <ignore />
      </action>
    </pluginExecution>
    <pluginExecution>
      <pluginExecutionFilter>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>buildnumber-maven-plugin</artifactId>
        <versionRange>1.3</versionRange>
        <goals>
          <goal>create-timestamp</goal>
        </goals>
      </pluginExecutionFilter>
      <action>
        <ignore />
      </action>
    </pluginExecution>
  </pluginExecutions>
</lifecycleMappingMetadata>

```

**SUGGESTION:**

I suggest using Intellij IDEA (Community). I think it's a capable and ergonomic IDE for JAVA

**Comment by Lordess** [comment]
Your lifecycle mapping works and the errors are gone.

I heard a lot about IntelliJ IDEA, but its community edition lisence limits users work on open source projects only.  Well, I may stick to the free Eclipse for saving money LoL.

Now I still have something wrong with the Eclipse with your solution. It cannot create indexes for the source files at all. I will keep on. If I have any progress, I will be back.

**Comment by yanhuqing666** [comment]
> It also can be used for Commercial development.

The community edition of IntelliJ is available under the Apache2.0 license, which means you can use it for whatever purposes you want, as long as you follow the terms of the Apache license.
