### ISSUE TITLE
Log4j arbitrary code execution vulnerability fix request

### ISSUE THREAD

**Issue by lostmaniac** [actiontech/dble#2987]
Is there any related vulnerability repair plan, thank you

**Comment by yanhuqing666** [comment]
https://github.com/actiontech/dble/commit/bb1add38bc316f1bba90692bc8cc1549f70d404e

**Comment by lostmaniac** [comment]
Upgrade to 2.15.0 does not fix it, you need to upgrade to 2.15.0-rc2

**Comment by yanhuqing666** [comment]
> Upgrade to 2.15.0 does not fix it, you need to upgrade to 2.15.0-rc2

Where is the source of this conclusion？

**Comment by larry-zhang** [comment]
![log4j2](https://user-images.githubusercontent.com/4012952/145529876-617a4680-47f5-462f-b3f2-c49feb3b1fd8.png)
The first "Added features" is "no longer enables lookups within message text by default". So, 2.15.0 is a safe version.
BTW, "rc" is "release candidate", so , rc1 and rc2 are prior to the final release.

**Comment by larry-zhang** [comment]
> Upgrade to 2.15.0 does not fix it, you need to upgrade to 2.15.0-rc2

versions with "rc" are release candidates.

**Comment by yanhuqing666** [comment]
“prior to this release Log4j would automatically resolve Lookups contained in the message or its parameters in the
Pattern Layout. This behavior is no longer the default and must be enabled by specifying %msg{lookup}.
* The JNDI Lookup has been restricted to only support the java, ldap, and ldaps protocols by default. LDAP also no
longer supports classes that implement the Referenceable interface and restricts the Serializable classes to the
Java primitive classes by default and requires an allow list to be specified to access remote LDAP servers.

The Log4j 2.15.0 API, as well as many core components, maintains binary compatibility with previous releases.”
