### ISSUE TITLE
SQL parser can not tell the difference of '~id =1' and '~(id  =1)'

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#302]
Steps:   
  use dble to exec the sql " select * from suntest where ~ id = 1;" ,4 result
  find the record mysql node exec the same sql one by one every result is 0 result
Reason:  
  Druid has some error in parse '~',wait new druid version to release
  [https://github.com/alibaba/druid/pull/2056](url)

**Comment by sunsun314** [comment]
wait until update the  druid import in dble

**Comment by FlyingMao** [comment]
**verified version：**
 5.6.29-dble-9.9.9.9-359645c-20181029082136

**Comment by FlyingMao** [comment]
**for tester：**
suggest autotest position: sqls/select/expression.sql (reference line 62、64)
