### ISSUE TITLE
where条件分片字段未加别名时，语句路由不正确

### ISSUE THREAD

**Issue by bjddd192** [actiontech/dble#3063]
* **dble version：**  
* actiontech/dble:3.21.10.0
* **preconditions ：**
* 官方镜像  
* **steps：**    
    step1.  执行语句：SELECT * FROM testdb.tb_enum_sharding  a where code in (10010)
* **expect result：**  
    1. 只路由分片所在节点
* **real result：**  
    1. 路由了全部节点
* **supplements：**  
    1. 路由多个节点会带来性能损失，期待对这种语句也能精准路由

**Comment by dcy10000** [comment]
影响版本>=3.21.02，引入的commit 号 6c5402d2fae2d472088c3fd47059625cdacb97db 


临时解决方案：不用表别名
