### ISSUE TITLE
Lost connection to MySQL server

### ISSUE THREAD

**Issue by lenovore** [actiontech/dble#3132]
* **dble version：**  3.21.10.0 
* **configs：** 

**bootstrap.cnf**  

```
-DidleTimeout=600000

```
* **steps：**    
Execute a slow sql longer than 600s(the actual execution time is 1200s)
    
* **expect result：**  
    1. get data
* **real result：**  
    1. after sql execution exceeds 600 seconds, dble re-establishes a backend connection and starts executing the slow sql again. at this time, there are 2 same sqls being executed in the backend. when the first sql execution is completed, an error message is returned: Lost connection to MySQL server
    2. dble.log has a warn message: WARN [complexQueryExecutor87] (com.actiontech.dble.backend.mysql.nio.handler.MultiNodeQueryHandler.connectionClose(MultiNodeQueryHandler.java:214)) - backend connect client closed or timeout killed, conn info:MySQLResponseService ...
    3. but everything is ok when change idleTimeout bigger than 1200000.

**Comment by yanhuqing666** [comment]
We  will try to reproduce the problem

**Comment by KlawzZ** [comment]
Reproduced successfully
**dble version:** :dble-3.21.10.0-97a3b6d73a49cb374020f930c59f82746220b424-20211119064810
**bootstrap.cnf**: -DidleTimeout=6000
**steps：** execute sql: select sleep(7);
As long as the execution time is longer than the idleTimeout , the above phenomenon will be reproduced

**Comment by wenyh1** [comment]
From the [doc](https://actiontech.github.io/dble-docs-cn/1.config_file/1.02_bootstrap.cnf.html), the introduction to the 'idleTimeout' in bootstrap.cnf is
![idletimeout](https://user-images.githubusercontent.com/44251917/155496095-08d92431-c2e0-4b3b-87d2-c27e0e0330f3.jpeg)

Is not really an idle connection timeout.
Solution：increase its value.
By the way，We  will consider renaming  'idleTimeout'.
