### ISSUE TITLE
mysql-connector-java-v8.0.x 连不上dble服务

### ISSUE THREAD

**Issue by apollo47** [actiontech/dble#3138]
mysql-connector-java-v8.0.x 连不上dble（v3.21.06)服务，报错：

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class

Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).

使用较低版本mysql-connector-java-v5.1.x可以连上。

**Comment by PanternBao** [comment]
refer: https://github.com/actiontech/dble/discussions/3070

**Comment by yanhuqing666** [comment]
no response， so close it
