### ISSUE TITLE
Druid can't discriminate between "set session tx_variables,xxx" and "set tx_variables,xxx"

### ISSUE THREAD

**Issue by sevenFH** [actiontech/dble#316]
As titled.

**Comment by ditdb** [comment]
见alibaba/druid #2116

**Comment by FlyingMao** [comment]
**verified version:**
5.6.29-dble-9.9.9.9-359645c-20181029082136

**Comment by FlyingMao** [comment]
**for tester:**
suggest autotest position: sqls/select/bug.sql (reference line 214)
