### ISSUE TITLE
update语句中，分片键使用`符号包围，不能正常路由

### ISSUE THREAD

**Issue by xhailiang** [actiontech/dble#3160]
* **dble version：**  
* 3.21.10.1
* **preconditions ：**  
usr_id为分片键
* **configs：** 

**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  update t18_order set ord_sts='9X' where `usr_id`=9999999 and `ID`=999999999;
    usr_id 被 ` 符号引用
* **expect result：**  
    1.命中路由
explain update t18_order set ord_sts='9X' where `usr_id`=9999999 and `ID`=999999999 \G
SHARDING_NODE: dn13
         TYPE: BASE SQL
      SQL/REF: update t18_order set ord_sts='9X' where  `usr_id`=9999999 and `ID`=999999999
* **real result：**  
* 广播了
    explain update t18_order set ord_sts='9X' where `usr_id`=9999999 and `ID`=999999999 \G
*************************** 1. row ***************************
SHARDING_NODE: dn1
         TYPE: BASE SQL
      SQL/REF: update t18_order set ord_sts='9X' where `usr_id`=9999999 and `ID`=999999999
*************************** 2. row ***************************
................................省略dn2-dn17
................................
*************************** 18. row ***************************
SHARDING_NODE: dn18
         TYPE: BASE SQL
      SQL/REF: update t18_order set ord_sts='9X' where `usr_id`=9999999 and `ID`=999999999
* **supplements：**  
    1.

**Comment by dcy10000** [comment]
影响版本>=3.21.02，引入的issue号 https://github.com/actiontech/dble/issues/2152
临时解决方案：不要用`符号

**Comment by wangjuan-action** [comment]
verified version：
5.7.21-dble-3.21.10.99-c87a0806f42c3c106b49be3bdd84348d87cc0c40-20220309052451
5.7.21-dble-3.21.06.99-39054a4576d526dae95b1711da031723ddc19f89-20220309052343
5.7.21-dble-3.21.02.99-39e08a50878fcec64c71b9103b4c40d1feba87a1-20220309052944
