### ISSUE TITLE
数据库表字段使用smallInt情况下返回的数据出错

### ISSUE THREAD

**Issue by TommyZC** [actiontech/dble#3175]
* **dble version：2.19.03\lts and later**  
* **preconditions ：
```
CREATE TABLE `test3` (
  `id` int(10) NOT NULL,
  `userid` smallint(3) DEFAULT NULL,
  `name` char(5) DEFAULT NULL,
  `nn` year(4) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB

insert into test3 values('1','105','name',2022),('2','105','name2',2023);
```
* **configs：** 
none

* **steps：**    
```
        Class.forName("com.mysql.jdbc.Driver");
        Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:8066/test?
useServerPrepStmts=true", "root", "123456");

        PreparedStatement stmt = conn.prepareStatement("select id,userid,nn from test3 where id=?");
        stmt.setInt(1, 1);

        ResultSet rs = stmt.executeQuery();
        while (rs.next()) {
            System.out.println(rs.getString(1));
            System.out.println(rs.getShort(2));
            System.out.println(rs.getShort(3));
        }
```
* **expect result：**  
```
1
105
2022
```
* **real result：**  
```
1
12337
12338
```
* **supplements：**  
    1. 目前定位到问题在com.actiontech.dble.net.mysql.BinaryRowDataPacket.java中的read()函数，从rowDataPk中获取到的values值是49和50，在convert中按getShort()方法对byte数组(长度为1)做按位与操作得到的结果也是49和50，最终返回结果是49和50

**Comment by yanhuqing666** [comment]
You need to use 105 not '105' to avoid. It is a number but not a string.
 And we will try to reproduce and fix

**Comment by TommyZC** [comment]
这是分析的最新进展：
1. 修改com.actiontech.dble.util.ByteUtil.java中的getShort()方法，当byte数组长度为1时，使用parseShort()方法对byte数组做转换，发现返回的结果是正确的，判断是getShort()方法中对长度为1的byte数组的解析有误。
2. 当数据库的表字段是smallInt unsigned情况下，存在返回的byte数组长度大于2的情况，在getShort()方法中没有实现，因此返回数据错误。

**Comment by TommyZC** [comment]
> 
尝试了一下，使用insert into test6 values(4,105,'name4');插入数据，返回结果还是出错

**Comment by jndxcaiwei** [comment]
Verified version：5.7.21-dble-9.9.9.9-3d3612c9b31c2798b782b07066bc4615253920d4-20220321060316
