### ISSUE TITLE
当分片字段传入’‘时（where id = ''），路有结果为广播语句。

### ISSUE THREAD

**Issue by ClippedWings-renzy** [actiontech/dble#3218]
* **dble version：**  
* 2.19.03/lts
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```
table=bugtest11 rule=Stringhash datanode="dn0,dn1"

dn0--->dh0---->db
dn1--->dh1---->db

未配置默认分片
```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  
explain select * from bugtest11 where id ='';
   step2.
explain select* from bugtest11 where id is null;
* **expect result：**  
step1.
 预期应该是dn0或者dn1
step2.
预期报错
* **real result：**  
step1.
  dn0和dn1
广播下发

step2.
结果为某个分片的路由结果
* **supplements：**  
    1.

**Comment by LUAgam** [comment]
第一个问题2.20.04及以上版本修复
第二个sql不是问题，druid解析器能正确解析该语句

**Comment by Dinosauria** [comment]
Verified in 5.6.29-dble-2.19.03.4-2148288128c3bb4a5c41eac6739b366fffdd31d5-20220413084129
验证结果：
id is sharding key：
![origin_img_v2_9f459250-1514-4309-aaa3-5bcd91c2706g](https://user-images.githubusercontent.com/17309012/163163849-e10a7d2b-7306-4ef0-a6ae-6ca44a2e65a0.jpg)
复现情况：
Stable reproducibility in version 5.6.29-dble-2.19.03.3-121abfae75b396328029d901e7c43634479f9fe2-20200608115828 ，
The test result of the int-sharding key are as follows:
![origin_img_v2_9fc04982-7845-4a0f-8b37-0684c44361fg](https://user-images.githubusercontent.com/17309012/163164808-b54f8c98-6c0d-4038-90c0-0d49a7d5e3a3.jpg)
