### ISSUE TITLE
[Improvement] Refine the scope of effect of the reload configuration

### ISSUE THREAD

**Issue by LUAgam** [actiontech/dble#3298]
Refine the scope of effect of the reload configuration

**Comment by Dinosauria** [comment]
Verfied in 5.7.21-dble-9.9.9.9-eb2075516306ecdaa656a7da5cd232607d03aa31-20220812020255

**Comment by LUAgam** [comment]
associated documents:
https://actiontech.github.io/dble-docs-cn/history/develop/2.Function/2.001_manager_dble_information.html 
https://actiontech.github.io/dble-docs-cn/history/develop/2.Function/2.19_reload_diff.html
