### ISSUE TITLE
MultiNodeSelectHandler cause hang

### ISSUE THREAD

**Issue by 13611582598** [actiontech/dble#3444]
dble version： 3.21.10.3 ， 3.21.10.10 

dble 心跳异常无法连接后端数据库 ：
* java.io.IOException: the  [dbInstance[x.x.x.x:13316] can't reach. Please check the dbInstance status

[dble_jstack.log](https://github.com/actiontech/dble/files/9836519/dble_jstack.log)

**Comment by dcy10000** [comment]
原因是当下发的分片数大于线程数。外加MultiNodeSelectHandler用了阻塞队列，资源相互争抢导致了线程死锁。

**Comment by wjl1619** [comment]
verified on version：5.7.21-dble-9.9.9.9-1c1878895bfb85238fe002bf1d013d03b001b062-20221117013530
