### ISSUE TITLE
The java.specification.maintenance.version parameter of the JDK version is not supported

### ISSUE THREAD

**Issue by Huashusu** [actiontech/dble#3450]
* **dble version：3.22.07.0**  
* **preconditions ：**  
java version: jdk-8u341 or Other versions that support the java.specification.maintenance.version parameter.
* **configs：** 

**cluster.cnf**  

```
Same as cluster_template.cnf
```

**bootstrap.cnf**  

```
Same as bootstrap_template.cnf
```
**db.xml**  

```
Same as db_template.xml
```

**user.xml**  

```
Same as user_template.xml.
Modify only ip1, ip2, your_user, your_psw
```

**sharding.xml**  

```
Same as sharding_template.xml
```

* **steps：**    
    Start dble，command `bin/dble start`

* **real result：**  
```
STATUS | wrapper  | 2022/10/31 13:41:26 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2022/10/31 13:41:26 | Java Service Wrapper Community Edition 64-bit 3.5.40
STATUS | wrapper  | 2022/10/31 13:41:26 |   Copyright (C) 1999-2019 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2022/10/31 13:41:26 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2022/10/31 13:41:26 | 
STATUS | wrapper  | 2022/10/31 13:41:26 | Launching a JVM...
INFO   | jvm 1    | 2022/10/31 13:41:26 | Java HotSpot(TM) 64-Bit Server VM warning: UseCMSCompactAtFullCollection is deprecated and will likely be removed in a future release.
INFO   | jvm 1    | 2022/10/31 13:41:26 | Java HotSpot(TM) 64-Bit Server VM warning: CMSFullGCsBeforeCompaction is deprecated and will likely be removed in a future release.
INFO   | jvm 1    | 2022/10/31 13:41:26 | Listening for transport dt_socket at address: 8088
INFO   | jvm 1    | 2022/10/31 13:41:27 | WrapperManager: Initializing...
INFO   | jvm 1    | 2022/10/31 13:41:28 | These properties in bootstrap.cnf or bootstrap.dynamic.cnf are not recognized: java.specification.maintenance.version
STATUS | wrapper  | 2022/10/31 13:41:30 | <-- Wrapper Stopped
```

**Comment by wenyh1** [comment]
Currently, JDK parameters are supported internally in the DBLE source code： [SystemProperty.java](https://github.com/actiontech/dble/blob/master/src/main/java/com/actiontech/dble/util/SystemProperty.java)

As mentioned in [JDK link](https://bugs.openjdk.org/browse/JDK-8285497)，`java.specification.version`  updated to `java.specification.maintenance.version` in higher JDK versions

The `java.specification.maintenance.version`JDK param is not currently supported in DBLE，so startup failed.

You can bypass the [JDK link](https://bugs.openjdk.org/browse/JDK-8285497), mentioned in the JDK version, and start the DBLE successfully.

**Comment by wenyh1** [comment]
remark：bind inner issue 2021
