### ISSUE TITLE
项目卡死CPU跑满，日志出现大量exception

### ISSUE THREAD

**Issue by zeroxxmmbm** [actiontech/dble#3495]
dble version：3.20.10.2
![_MPA955KTX~)IUW8(G(_GD2](https://user-images.githubusercontent.com/32122056/203754707-8e140ae7-10ce-4716-98e4-ff338a33f7c8.png)
可能引发的起因是我用SQL查询了一段语句 但是忘记加上关联条件 等待10多秒后 发现等比较久有问题 语句操作查询中断  联表查询10来万的数据

**Comment by ylinzhu** [comment]
this will be fixed in the new version, as will previous versions

**Comment by wangjuan-action** [comment]
verified version：
5.7.21-dble-3.20.10.99-bf7b08e83488235a8a6ef9fd8aad66b0fa6087ba-20221209071350
5.7.21-dble-9.9.9.9-3db67a2ce8926b4f1dbc77c13229ecdccfa33dab-20221208033029
