### ISSUE TITLE
Deadlock by ’reload @@config_all‘ with high concurrency insertion

### ISSUE THREAD

**Issue by zhunina** [actiontech/dble#369]
[js1.log](https://github.com/actiontech/dble/files/1529938/js1.log)

**Comment by zhunina** [comment]
reload @@metadata has the same problem as titles

**Comment by yanhuqing666** [comment]
the commit 15996dc771126153d299d508f9ba06831e5428b6 should be releated #369

**Comment by zhunina** [comment]
fixed
