### ISSUE TITLE
Dble hangs when xa is opened /closed back and forth with set autocommit=0

### ISSUE THREAD

**Issue by zhunina** [actiontech/dble#385]
```
mysql> set autocommit=0;
Query OK, 0 rows affected (0.00 sec)

mysql> set xa=1;
Query OK, 0 rows affected (0.00 sec)

mysql> commit;
Query OK, 0 rows affected (0.00 sec)

mysql> set xa=0;
Query OK, 0 rows affected (0.01 sec)

mysql> select @b;
+------+
| @b   |
+------+
| NULL |
+------+
1 row in set (0.03 sec)

mysql> set xa=1;
Query OK, 0 rows affected (0.01 sec)

mysql> set @b=8;
Query OK, 0 rows affected (0.00 sec)

mysql> rollback;
```

Results: dble hanged by roolback

**Comment by yanhuqing666** [comment]
In transaction (begin  or set autocommit =0)，changing XA status should response error after sql sending to mysql node . 
For example:
case 1:
set autocommit =0;
select @b;
set xa =1;(Error)
set @b =8;
rollback;
 
case 2:
begin; 
select @b;
set xa =1;(Error)
set @b =8;
rollback;
 
 
case 3:
set autocommit =0;
set xa =1;
select @b;
set @b =8;
rollback;
 
case 4:
begin; 
set xa =1;
select @b;
set @b =8;
rollback;

**Comment by zhunina** [comment]
fixed
