### ISSUE TITLE
sqlSlowTime配置未生效

### ISSUE THREAD

**Issue by joer1900** [actiontech/dble#3875]
* **dble version：3.23.08.0**  
**bootstrap.cnf**  
-DsqlSlowTime=2000

慢查询阈值配置并未生效，查看代码发现写入慢查询sql queue之前并未判断sqlSlowTime该配置，只判断了开关，实际开启慢查询日志，将会导致了所有的sql都会写入slowlogs/slow-query.log文件中。

<img width="972" alt="image" src="https://github.com/actiontech/dble/assets/30944767/1ca91c98-85e0-40df-9187-1e2f41519c80">

之前的版本（3.22.11.1）是没问题的
<img width="846" alt="image" src="https://github.com/actiontech/dble/assets/30944767/0dc3b22f-a668-4d69-882b-32c6160c0474">

**Comment by wenyh1** [comment]
get, 确实存在此问题；
会尽快安排修复。
