### ISSUE TITLE
quick experience dble with docker

### ISSUE THREAD

**Issue by wweir** [actiontech/dble#444]
Hi, I have written a dockerfile for dble demo, so that we can quick experience dble in this way:
```bash
docker pull wweir/dble-demo
docker run -it --name=dble -p 3306:3306 -p 8066:8066 wweir/dble-demo
```
If you wanna know the detail of this dockerfile, please check [dockerhub](https://hub.docker.com/r/wweir/dble-demo/)

**Comment by yanhuqing666** [comment]
new version see pr #927 ， and [doc](https://github.com/actiontech/dble-docs-cn/blob/master/0.overview/0.4_dble_quick_start_docker.md)

**Comment by yexiaoli88** [comment]
quick-start success with docker

**Comment by yanhuqing666** [comment]
@sunsun314  doc to do:
1.keep doc of not using docker-compose
2.add doc that use docker-compose.yml
3.add doc to show how to use loccl config to start  docker of dble

**Comment by sunsun314** [comment]
https://github.com/actiontech/dble-docs-cn/blob/develop/0.overview/0.5_dble_start_docker_compose.md

**Comment by yexiaoli88** [comment]
verified on 2019/2/20
