### ISSUE TITLE
Error multi-table query which has several or-clause

### ISSUE THREAD

**Issue by zhunina** [actiontech/dble#462]
schema info from TPCH 

SQL19:
select
        sum(l_extendedprice* (1 - l_discount)) as revenue
from
        lineitem,
        part
where
        (
                p_partkey = l_partkey
                and p_brand = 'Brand#12'
                and p_container in ('SM CASE', 'SM BOX', 'SM PACK', 'SM PKG')
                and l_quantity >= 1 and l_quantity <= 1 + 10
                and p_size between 1 and 5
                and l_shipmode in ('AIR', 'AIR REG')
                and l_shipinstruct = 'DELIVER IN PERSON'
        )
        or
        (
                p_partkey = l_partkey
                and p_brand = 'Brand#23'
                and p_container in ('MED BAG', 'MED BOX', 'MED PKG', 'MED PACK')
                and l_quantity >= 10 and l_quantity <= 10 + 10
                and p_size between 1 and 10
                and l_shipmode in ('AIR', 'AIR REG')
                and l_shipinstruct = 'DELIVER IN PERSON'
        )
        or
        (
                p_partkey = l_partkey
                and p_brand = 'Brand#34'
                and p_container in ('LG CASE', 'LG BOX', 'LG PACK', 'LG PKG')
                and l_quantity >= 20 and l_quantity <= 20 + 10
                and p_size between 1 and 15
                and l_shipmode in ('AIR', 'AIR REG')
                and l_shipinstruct = 'DELIVER IN PERSON'
        );

**Comment by yexiaoli88** [comment]
**Issue verified by manually**

 **version: 5.6.29-dble-2.18.06.0-20180608074928**
 **prepare tables:**

        mysql> drop table if exists student;
        Query OK, 0 rows affected, 1 warning (0.14 sec)

        mysql> drop table if exists teacher;
        Query OK, 0 rows affected, 1 warning (0.11 sec)

        mysql> create table student(id int unsigned not null,name varchar(20) not null,class 
        varchar(20) not  null ,subject varchar(20) not null, score int unsigned not null,
        primary key (id))default charset=utf8;
        Query OK, 0 rows affected (0.14 sec)

       mysql> create table teacher(id int unsigned not null,name varchar(20) not null,classname 
       varchar(20)  not null,primary key (id))default charset=utf8;
       Query OK, 0 rows affected (0.13 sec)

       mysql> insert into student values(1,'ZHANGSAN','class1','Math',70), 
       (2,'ZHANGSAN','class1','English',55),(3,'LISI','class1','Math',90),
       (4,'LISI','class1','English',80), (5,'WANGWU','class2','Math',85),
       (6,'WANGWU','class2','English',65);
       Query OK, 6 rows affected (0.01 sec)
       Records: 6  Duplicates: 0  Warnings: 0

       mysql> insert into teacher values(1,'zhou','class1'),(2,'xu','class2');
       Query OK, 2 rows affected (0.01 sec)
       Records: 2  Duplicates: 0  Warnings: 0

**execute sql**:

    mysql> select s.name,s.class,s.score from student s,teacher t where (s.class = t.classname and 
    t.name='wangwu' ) or (s.class = t.classname and s.name='LISI' and s.score >85) 
    or (s.class=t.classname  and t.name ='xu' and s.score <70);
    +--------+--------+-------+
     | name   | class  | score |
    +--------+--------+-------+
     | LISI   | class1 |    90 |
     | WANGWU | class2 |    65 |
    +--------+--------+-------+
    2 rows in set (0.01 sec)
