### ISSUE TITLE
Error when having-clause has subquery

### ISSUE THREAD

**Issue by zhunina** [actiontech/dble#463]
schema-info from TPCH

SQL 11

select
        ps_partkey,
        sum(ps_supplycost * ps_availqty) as value
from
        partsupp,
        supplier,
        nation
where
        ps_suppkey = s_suppkey
        and s_nationkey = n_nationkey
        and n_name = 'GERMANY'
group by
        ps_partkey having
                sum(ps_supplycost * ps_availqty) > (
                        select
                                sum(ps_supplycost * ps_availqty) * 0.0001000000
                        from
                                partsupp,
                                supplier,
                                nation
                        where
                                ps_suppkey = s_suppkey
                                and s_nationkey = n_nationkey
                                and n_name = 'GERMANY'
                )
order by
        value desc;

```
mysql> select
    ->         ps_partkey,
    ->         sum(ps_supplycost * ps_availqty) as value
    -> from
    ->         partsupp,
    ->         supplier,
    ->         nation
    -> where
    ->         ps_suppkey = s_suppkey
    ->         and s_nationkey = n_nationkey
    ->         and n_name = 'GERMANY'
    -> group by
    ->         ps_partkey having
    ->                 sum(ps_supplycost * ps_availqty) > (
    ->                         select
    ->                                 sum(ps_supplycost * ps_availqty) * 0.0001000000
    ->                         from
    ->                                 partsupp,
    ->                                 supplier,
    ->                                 nation
    ->                         where
    ->                                 ps_suppkey = s_suppkey
    ->                                 and s_nationkey = n_nationkey
    ->                                 and n_name = 'GERMANY'
    ->                 )
    -> order by
    ->         value desc;
ERROR 1003 (HY000): Function argument not found:( SELECT SUM(ps_supplycost * ps_availqty) * 0.0001000000 FROM partsupp, supplier, nation WHERE ps_suppkey = s_suppkey         AND s_nationkey = n_nationkey   AND n_name = 'GERMANY' )
```

**Comment by yexiaoli88** [comment]
**hang when executing sql with having-clause which has subquery in dble:
version: 5.6.29-dble-2.18.06.0-20180608074928**

**step 1:prepare tables:**

      mysql> drop table if exists student;
      Query OK, 0 rows affected, 1 warning (0.14 sec)

      mysql> drop table if exists teacher;
      Query OK, 0 rows affected, 1 warning (0.11 sec)

      mysql> create table student(id int unsigned not null,name varchar(20) not null,class varchar(20) not 
      null ,subject varchar(20) not null, score int unsigned not null,primary key (id))default charset=utf8;
      Query OK, 0 rows affected (0.14 sec)

      mysql> create table teacher(id int unsigned not null,name varchar(20) not null,classname varchar(20) 
      not null,primary key (id))default charset=utf8;
      Query OK, 0 rows affected (0.13 sec)

      mysql> insert into student values(1,'ZHANGSAN','class1','Math',70), 
      (2,'ZHANGSAN','class1','English',55),(3,'LISI','class1','Math',90),(4,'LISI','class1','English',80), 
      (5,'WANGWU','class2','Math',85),(6,'WANGWU','class2','English',65);
      Query OK, 6 rows affected (0.01 sec)
      Records: 6  Duplicates: 0  Warnings: 0

      mysql> insert into teacher values(1,'zhou','class1'),(2,'xu','class2');
      Query OK, 2 rows affected (0.01 sec)
      Records: 2  Duplicates: 0  Warnings: 0

**step 2:  execute sql with having-clause has subquery in dble  ------hang**

       mysql> select avg(s.score),s.name from student s,teacher t where t.classname =s.class and t.name = 
       'zhou' group by s.name having avg(s.score)>(select sum(s.score)/count(s.subject) from student s);

**step 3: execute sql in mysql** 

       mysql> select avg(s.score),s.name from student s,teacher t where t.classname =s.class and t.name = 
       'zhou' group by s.name having avg(s.score)>(select sum(s.score)/count(s.subject) from student s);
       +--------------+------+
        | avg(s.score) | name |
       +--------------+------+
        |      85.0000 | LISI |
        +--------------+------+
       1 row in set (0.00 sec)
**step 4:execute sql with having-clause has no  subquery in dble**
   
     mysql> select avg(s.score),s.name from student s,teacher t where t.classname =s.class and t.name = 
     'zhou' group by s.name having avg(s.score)>74;
     +--------------+------+
     | AVG(s.score) | name |
    +--------------+------+
    |      85.0000 | LISI |
    +--------------+------+
   1 row in set (0.01 sec)


 log:

      com.actiontech.dble.plan.common.exception.MySQLOutPutException: join node mergebuild 
      exception! 
     at com.actiontech.dble.backend.mysql.nio.handler.builder.JoinNodeHandlerBuilder
     .mergeBuild(JoinNodeHandlerBuilder.java:74) ~[dble-2.18.06.0.jar:?]
        at com.actiontech.dble.backend.mysql.nio.handler.builder.BaseHandlerBuilder.build
     (BaseHandlerBuilder.java:104) ~[dble-2.18.06.0.jar:?]
        at com.actiontech.dble.backend.mysql.nio.handler.builder.HandlerBuilder.getBuilder
      (HandlerBuilder.java:64) ~[dble-2.18.06.0.jar:?]
        at com.actiontech.dble.backend.mysql.nio.handler.builder.HandlerBuilder.buildNode
      (HandlerBuilder.java:58) ~[dble-2.18.06.0.jar:?]
        at com.actiontech.dble.backend.mysql.nio.handler.builder.HandlerBuilder.build
       (HandlerBuilder.java:70) ~[dble-2.18.06.0.jar:?]
        at com.actiontech.dble.server.NonBlockingSession.executeMultiResultSet
      (NonBlockingSession.java:378) [dble-2.18.06.0.jar:?]
        at com.actiontech.dble.server.NonBlockingSession.access$000(NonBlockingSession.java:62)
        [dble-2.18.06.0.jar:?]
        at com.actiontech.dble.server.NonBlockingSession$1.run(NonBlockingSession.java:424)
        [dble-2.18.06.0.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
        Caused by: com.actiontech.dble.plan.common.exception.MySQLOutPutException: can not execute 
        empty rrss!
        at com.actiontech.dble.backend.mysql.nio.handler.query.impl.MultiNodeMergeHandler.<init> 
         (MultiNodeMergeHandler.java:58) ~[dble-2.18.06.0.jar:?]
        at com.actiontech.dble.backend.mysql.nio.handler.builder.BaseHandlerBuilder.buildMergeHandler
        (BaseHandlerBuilder.java:394) ~[dble-2.18.06.0.jar:?]
        at com.actiontech.dble.backend.mysql.nio.handler.builder.JoinNodeHandlerBuilder.mergeBuild
        (JoinNodeHandlerBuilder.java:72) ~[dble-2.18.06.0.jar:?]
        ... 10 more

**Comment by yexiaoli88** [comment]
**Verified on  version: 5.6.29-dble-2.18.06.0-20180619072937**

     mysql> select avg(s.score),s.name from student s,teacher t where t.classname =s.class 
                 and t.name ='zhou' group by s.name having avg(s.score)>
                 (select sum(s.score)/count(s.subject) from student s);
    +--------------+------+
     | AVG(s.score) | name |
    +--------------+------+
     |      85.0000 | LISI |
    +--------------+------+
    1 row in set (0.27 sec)
