### ISSUE TITLE
MySQLdb driver sends the following sqls in sequence get "Lost connection xxx" 

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#473]
version:5.6.29-dble-2.18.02.0-dev-20180321063015

sqls:
```mysql
#!share_conn_1
begin;
select * from sbtest1 order by id for update;
#!share_conn_2
begin;
update sbtest1 set pad=22 where id=1;/*hang*/
#!share_conn_1
commit;
#!share_conn_2
update sbtest1 set pad=22 where id=2;
```
execute sequence:
#!share_conn_1
```python
>>> import MySQLdb
>>> conn = MySQLdb.connect('172.100.0.2', 'test', 'test', 'mytest',8066, autocommit=True)
>>> cur=conn.cursor()
>>> cur.execute('begin')  #step1
0L
>>> cur.execute('select * from sbtest1 order by id for update;')  #step2
6L
>>> cur.execute('commit;')  #step5
0L
```
#!share_conn_2
```python
>>> import MySQLdb
>>> conn = MySQLdb.connect('172.100.0.2', 'test', 'test', 'mytest',8066, autocommit=True)
>>> cur=conn.cursor()
>>> cur.execute('begin')  #step3
0L
>>> cur.execute('update sbtest1 set pad=22 where id=1;/*hang*/')    #step4
1L
>>> cur.execute('update sbtest1 set pad=22 where id=2;')    #step6
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query')
```

dble related log:
[dble.log](https://github.com/actiontech/dble/files/1832820/dble.log)

the error does not occur when use mysql-client do the very same thing

**Comment by yanhuqing666** [comment]
There are two problems here:
1. "for update/lock in share mode" lost when the query is complex. In this case,limit should not add to rewritten SQL.
2. "Lost connection to MySQL server during query", usually it's a package error.

**Comment by sunsun314** [comment]
the #!share_conn_2 is caused by   Python mysql connection,the sql 'update sbtest1 set pad=22 where id=1;/*hang*/' be Recognized as ‘update sbtest1 set pad=22 where id=1’ & ‘/*hang*/’

**Comment by irene-coming** [comment]
version:5.6.29-dble-2.18.02.0-20180412113912

```mysql
#!sql_thread_1
delete from sbtest1;
insert into sbtest1 values(1,1,1,1),(2,2,2,2),(3,3,3,3),(4,4,4,4),(5,5,5,5),(6,6,6,6);
begin;
select * from sbtest1 order by id lock in share mode;
#!sql_thread_2
begin;
update sbtest1 set pad=22 where id=1/*zhj1*/;
#!sql_thread_1
rollback /*zhj2*/;
#!sql_thread_2
update sbtest1 set pad=22 where id=2/*zhj3*/;
```
sql_thread_1 means session 1,  sql_thread_2 means session 2.

the "rollback /*zhj2*/;" route to only 1 sharding of 4, so the line "update sbtest1 set pad=22 where id=1/*zhj1*/;" is always locked even rollback executed over;

![image](https://user-images.githubusercontent.com/6801133/39175703-926c15d2-47dd-11e8-822f-b071c0d3a64b.png)

**Comment by yanhuqing666** [comment]
move last comment to #533
