### ISSUE TITLE
If backend connection is broken or lost,front connection should report error,not just disconnect

### ISSUE THREAD

**Issue by yanhuqing666** [actiontech/dble#531]
the error msg should contains backend connection info,like host,port and user

**Comment by yexiaoli88** [comment]
**ger err msg as expected when excuting sql afer mysql server stoped:**

    java.io.IOException: the data source[10.186.19.75:3306] can't reached, please check the dataHost

**Comment by yexiaoli88** [comment]
**get err msg as expected when excuting sql after mysql server stoped:**

  java.io.IOException: the data source[10.186.19.75:3306] can't reached, please check the dataHost
