### ISSUE TITLE
reload hang when ZK is used for cluster

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#541]
when use ZK to group a dble cluster,the reload will hang

**Comment by yexiaoli88** [comment]
reload success when mulitiple dble and ZK on three different machines.
![machine](https://user-images.githubusercontent.com/39580715/40775395-8db0dae8-64fa-11e8-9141-def6548b4a8f.png)

but the issue still exists on docker environment:
when reload @@config;   -->success
when reload @@config_all;   -->hang
![docker](https://user-images.githubusercontent.com/39580715/40775407-94ac7802-64fa-11e8-86af-c691826207e7.png)

**Comment by yexiaoli88** [comment]
**verified on   version: 5.6.29-dble-2.18.06.0-20180620065910**
