### ISSUE TITLE
Complex query get error when column name is uppercase

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#542]
mysql> select Customer.id from Customer left join xtest on xtest.name  = customer.name;   
ERROR 4004 (42S22): column Customer.id not found

**Comment by yexiaoli88** [comment]
pre-condition: set mysql lower_case_tables_name = 1 (case insensitive)

**case1:** 

- add  table name to schema.xml with lowercase only

       <table name="test_a" dataNode="dn1,dn2" type="global"/>
       <table name="test_b" dataNode="dn1,dn2" type="global"/>

- excuting complex sql with uppercase 

         mysql> select test_A.name,TEST_b.gender from test_a left join test_b on test_a.name=test_b.name 
         order by test_a.id;
         +------+--------+
         | name | gender |
         +------+--------+
          | aaa  | female |
          | bbb  | female |
          | ccc  | male   |
          +------+--------+
         3 rows in set (0.01 sec)

 **case2:**

- add  table name to schema.xml with lowercase and uppercase

      <table name="TesT_f" dataNode="dn1" type="global"/>

- excuting complex sql with uppercase

          mysql> select TEST_f.name,test_b.gender from test_f left join test_b on TesT_f.name=test_b.name 
          order by test_B.id;
          +------+--------+
           | name | gender |
          +------+--------+
           | ddd  | male   |

**case3:**

-  add  table name to schema.xml with uppercase only

          <table name="TEST_E" dataNode="dn1" type="global"/>

- excuting complex sql with uppercase

           mysql> select TESt_E.name,TEST_b.gender from test_E left join test_b on test_E.name=test_b.name 
           order by test_B.id;
           +------+--------+
           | name | gender |
           +------+--------+
           | ddd  | male   |
           | bbb  | female |
           +------+--------+
