### ISSUE TITLE
return error when excuting select because of there's table name with uppercase in schema.xml

### ISSUE THREAD

**Issue by yexiaoli88** [actiontech/dble#553]
**pre-condition**:mysql set lower_case_table_names=0 (case sensitive)
**step1**:add table name with uppercase in schema.xml
              _table name="Test_c" dataNode="dn1,dn2" type="global"_
**step2**:create table in TESTDB

**step3**:excute select sql

**result:**
MySQL [TESTDB]> select * from Test_c;
ERROR 1064 (HY000): Index: 0, Size: 0

**Comment by sunsun314** [comment]
commit 28ed8934b1ae2e07c8bd07a075e50c35d996bccc fixed
