### ISSUE TITLE
when datahost‘s balance is 0,read host will not create connection for heartbeat and so on.

### ISSUE THREAD

**Issue by yanhuqing666** [actiontech/dble#557]
When datahost‘s balance is 0,readhost will be ignore when load schema.xml.   
It is just left for HA flag.

**Comment by yexiaoli88** [comment]
**Verified**
step 1: set schema.xml as follows:
 
    <dataHost balance="0" maxCon="1000" minCon="10" name="localhost1" switchType="1" 
      slaveThreshold="100">
        <heartbeat>select user()</heartbeat>
        <writeHost host="hostM1" url="10.186.19.75:3306" password="123" user="test">
        <readHost host="hostS1" url="10.186.30.160:3306" password="123" user="test" />
        </writeHost>
    </dataHost>

step2:execute -- select * from a_test; in dble

step3:execute -- show processlist; in mysql on server 10.186.30.160

     MySQL [(none)]> show processlist;
    +----+------+-----------+------+---------+------+----------+------------------+
     | Id | User | Host      | db   | Command | Time | State    | Info             |
    +----+------+-----------+------+---------+------+----------+------------------+
     |  3 | root | localhost | NULL | Query   |    0 | starting | show processlist |
    +----+------+-----------+------+---------+------+----------+------------------+
    1 row in set (0.00 sec)
