### ISSUE TITLE
when execute ddl failed, the table's metadata is locked, but it should not

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#564]
version: 5.6.29-dble-2.18.06.0-20180615064937

steps:

1. config a table in schema.xml, say named hash_table

2. execute ddl to dble:
mysql> create table hash_table (id int, data varchar(10));
Query OK, 0 rows affected (0.12 sec)
mysql> create table hash_table (id int, data varchar(10));
ERROR 1050 (42S01): Table 'hash_table' already exists

3. then execute manager cmd 'reload @@config_all':
mysql> reload @@config_all;
ERROR 1003 (HY000): Reload config failure.The reason is There is other session is doing DDL

expect: if ddl execute failed, the related metadata should not be locked

**Comment by yexiaoli88** [comment]
**verified in version: 5.6.29-dble-2.18.06.0-20180619072937**
