### ISSUE TITLE
View logic change

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#573]
When create view in dble,the view info may successfully load into dble memory but write into file or Ucore error  
Now the logic changed to: if repository write failed,the whole sql failed

**Comment by FlyingMao** [comment]
**Verified -- version: 5.6.29-dble-9.9.9.9-8870722-20180725060632**   

step 1:execute create view in dble
```
mysql> create view view_test as select * from sbtest2;
Query OK, 0 rows affected (0.15 sec)
```
step 2:modify the permissions of the viewConf file to read-only
```
chmod 444 viewConf
```
step3:execute alter view in dble
```
mysql> alter view view_test as select * from sbtest2 where id =6;
ERROR 1999 (HY000): SCHEMA[mytest], TABLE[view_test] is doing DDL
```

**Comment by sunsun314** [comment]
Has bug when the update sql is same sql

**Comment by FlyingMao** [comment]
verified version:5.6.23-dble-9.9.9.9-c3a7aae-20180829052545
