### ISSUE TITLE
expect [help xx] sql syntax to be supported

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#575]
version: 5.6.29-dble-9.9.9.9-20180621092251

At present, help syntax is not supported, for example:
```mysql
mysql> help select;
ERROR 1149 (HY000): Unsupported command
mysql> help create ;
ERROR 1149 (HY000): Unsupported command
```

**Comment by yanhuqing666** [comment]
dble's SQL Statement Syntax is not as same as MySQL, so we can't just send help to a rondom datanode.    
Just read documents of MySQL and DBLE for now
