### ISSUE TITLE
there should be an exception handing when the value of <property> set is not in candidate values in configuration files

### ISSUE THREAD

**Issue by yexiaoli88** [actiontech/dble#579]
For example (segment from server.xml):
```
<user name="user">
        <property name="password">123</property>
        <property name="schemas">TESTDB</property>
        <property name="usingDecrypt">3</property>
  </user>

```
The candidate values of "usingDecrypt" are '0' and '1', so there should be some exception handing when we set it as '3'.

**Comment by yexiaoli88** [comment]
server.xml:
``` 
<property name="charset">utf-8</property>
```
show @@backend;
```
MySQL [(none)]> show @@backend;
ERROR 1105 (HY000): java.lang.NullPointerException
```
error caused by "utf-8" is illegal

**Comment by yanhuqing666** [comment]
If these properties in server.xml is illegal，dble will use the default value and leave warnning in the log .  
useGlobleTableCheck  
sequnceHandlerType  
useSqlStat  
useCompression  
charset  
txIsolation   
recordTxn  
bufferUsagePercent  
frontSocketNoDelay   
backSocketNoDelay  
usingAIO  
checkTableConsistency  
useCostTimeStat  
useThreadUsageStat  
usePerformanceMode  
enableSlowLog

**Comment by yanhuqing666** [comment]
add need check rule.xml /schema.xml

**Comment by yexiaoli88** [comment]
相关issue ：http://10.186.18.21/universe/ushard/issues/136

**Comment by irene-coming** [comment]
test blocked for:
replace boolean type expect value 1/0 with true/false, dryrun get:
![image](https://user-images.githubusercontent.com/6801133/50335706-1da9e080-0547-11e9-9187-06593f7c3fb0.png)
problem:
1. user can't tell which property's true/false coursed the error, expect could
2. there are many other boolean 1/0 replaced by true/false,  dryrun gives only 1 error, expect all errors can be seen at one time if possible, not: fixing one then dryrun to see next one .

**Comment by irene-coming** [comment]
verified on version:5.6.29-dble-2.18.12.0-9fdecff1efb443a4dbdcd1f642be1141431965ea-20190108042852
autotest for part server.xml system node: server_system_value_valid.feature
