### ISSUE TITLE
Change the interface of  BackendConnection

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#607]
BackendConnections in dble usually close without quit packet ,mysql will log the issue with 'Got error communication packet' ,it may cause disk room wast.  
So cancel the quit interface in BackendConnection,and  move it into close function ,call the quit function before channel.close()

**Comment by yanhuqing666** [comment]
add how to repeat

**Comment by sunsun314** [comment]
In version 18.06 heartbeat will close the connection after job finished,so error 'Aborted connection 58 to db: 'unconnected' user: 'root' host: 'dble-host'' can be found in error-log

**Comment by FlyingMao** [comment]
verified version:5.6.29-dble-9.9.9.9-b223cfb-20180806030551
