### ISSUE TITLE
illegal  "create " syntax execute success

### ISSUE THREAD

**Issue by yexiaoli88** [actiontech/dble#622]
**dble version：version: 5.6.23-dble-9.9.9.9-617502e-20180803062203**

* **steps：**    
    step1.  create table in dble without column
   ```
   mysql> create table test_global;
  Query OK, 0 rows affected (0.52 sec)
   ```
* **expect result：**  
    1. query return error
* **real result：**  
    1. query return ok

/label ~BUG

**Comment by irene-coming** [comment]
verified on dble:5.6.29-dble-9.9.9.9-df5cb6285bac0e16098461d039d47b93ebd7483d-20200106061843
