### ISSUE TITLE
DryRun command for reload test

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#629]
It 's quite usual reload @@config_all return error,Because the config file is long and complicated.  
We try to provide a new command 'dry-run' for test config before reload   
**Usage**:  dryrun
**Check Item**:
    Whether the config file is legal  or not
    Any  configuration information is redundant
    Is all the backend Mysql Instance is available
    Was all the database needed be created

**Comment by yexiaoli88** [comment]
verified on version: 5.6.23-dble-9.9.9.9-e8d20a7-20180827072114

**Comment by sunsun314** [comment]
add schema check for user & lowerCase or UpperCase BUG fix

**Comment by yexiaoli88** [comment]
verified on version: 5.6.23-dble-9.9.9.9-4bb0734-20180828041814
