### ISSUE TITLE
JMX may fail without com.sun.management.jmxremote.host with Java 8

### ISSUE THREAD

**Issue by Lordess** [actiontech/dble#664]
* **dble version:**  

  2.18.09 in developing (master branch)

* **preconditions:**  

  * JVM 8
  * java.net.preferIPv4Stack=false(default) in wrapper.conf
  * host is UNKNOWN to name service ( e.g. host named "ALOHA" , but dont have "ALOHA“ reocord in both /etc/hosts and DNS servers
  * enabled JMX in wrapper.conf
  * do NOT have set  com.sun.management.jmxremote.host for JMX in wrapper.conf

* **configs:** 

  does not matter server.xml, schema.xml or rule.xml

* **steps:** 

    step1.  Remove your host record in /etc/hosts and wipe out dns cache. Do ping( e.g. `ping -c3 ALOHA`) and find it failed for validation. 
    step2. Start dble in normal way will get it stopped from booting. Found JMX failed to start and resulted in JVM quit.

![default](https://user-images.githubusercontent.com/14990623/44527979-f79c3d00-a71a-11e8-8279-3a0c4610442f.png) 

* **analysis:**

  For JVM 8, in default, IPv6 in favor of IPv4. And, this difference, may cause JVM_GetHostName() doesnt work as well as in IPv4 mode.

``` java
Inet6AddressImpl.getLocalHostName()
    at impl.getLocalHostName()
    at InetAddress.getLocalHost()
    at JMXServiceURL()
    at exportMBeanServer()
    ...
```

* **suggestion:**

  Add -Dcom.sun.management.jmxremote.host=127.0.0.1 for work aroud.

**Comment by FlyingMao** [comment]
verified version:5.6.29-dble-9.9.9.9-dc2f715-20180824075539
