### ISSUE TITLE
backend conns killed in an distribution transaction, commit may hang and the thread will be occupied

### ISSUE THREAD

**Issue by yanhuqing666** [actiontech/dble#676]
* **dble version：**  
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```
<table name="sharding_two_node" dataNode="dn1,dn2" rule="two_node_hash"/>

```

**rule.xml**  

```
<tableRule name="two_node_hash">
		<rule>
			<columns>id</columns>
			<algorithm>two_node_hash</algorithm>
		</rule>
	</tableRule>
<function name="two_node_hash" class="Hash">
		<property name="partitionCount">2</property>
		<property name="partitionLength">512</property>
	</function>

```

**server.xml**  

```
<property name="processorExecutor">1</property>
<property name="processors">1</property>
<property name="backendProcessors">1</property>
<property name="backendProcessorExecutor">1</property>

```

* **steps：**    
    step1.   
```
mysql> begin;
Query OK, 0 rows affected (0.00 sec)

mysql> delete from sharding_two_node where id in(511,530);//  distribution transaction 
Query OK, 0 rows affected (0.02 sec)
```

    step2.   
in manager port，execute ：  
`show @@backend;`

find a `MYSQLID` that the value of column `BORROWED` is true 

just connect the MySQL， kill  MYSQLID

    step3. 
return the session in step1，execute ：  
`commit; `
* **expect result：**  
    1. return error
* **real result：**  
    1. hang
* **supplements：**  
    1.

/label ~BUG

**Comment by yexiaoli88** [comment]
verified on version: 5.6.29-dble-9.9.9.9-6912b0c-20180828095441
