### ISSUE TITLE
charset of group_concat is not correct

### ISSUE THREAD

**Issue by yanhuqing666** [actiontech/dble#679]
* **dble version：**  
* **preconditions ：**  
CREATE TABLE `sharding_two_node` (
  `id` int(11) NOT NULL,
  `c_flag` char(255) DEFAULT NULL,
  `c_decimal` decimal(16,4) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
* **configs：** 

**schema.xml**  

```
<schema name="testdb" sqlMaxLimit="100" >
		<table name="sharding_two_node" dataNode="dn1,dn2" rule="two_node_hash"/>
</schema>
```
 
**rule.xml**  

```
<tableRule name="two_node_hash">
		<rule>
			<columns>id</columns>
			<algorithm>two_node_hash</algorithm>
		</rule>
</tableRule>
<function name="two_node_hash" class="Hash">
		<property name="partitionCount">2</property>
		<property name="partitionLength">512</property>
</function>
```
 
 

* **steps：**    
    step0. mysql -uuser -ppassword -P 8066 -Dtestdb 
     step1. set names utf8;
    step2.  insert into sharding_two_node values(18,'美国',20.0),(530,'中国',20.0);
    step3. select c_decimal,group_concat(c_flag)  from sharding_two_node where c_decimal =20 group by c_decimal;
* **expect result：**  
    1. step3:
```
+-----------+------------------------------------------------------+
| c_decimal | GROUP_CONCAT(sharding_two_node.c_flag SEPARATOR ',') |
+-----------+------------------------------------------------------+
|   20.0000 | 美国,中国                                            |
+-----------+------------------------------------------------------+
1 row in set (0.43 sec)
```
* **real result：**  
    1.
```
+-----------+------------------------------------------------------+
| c_decimal | GROUP_CONCAT(sharding_two_node.c_flag SEPARATOR ',') |
+-----------+------------------------------------------------------+
|   20.0000 | ??,??                                                |
+-----------+------------------------------------------------------+
1 row in set (0.02 sec)
```
* **supplements：**  
    1.

/label ~BUG

**Comment by irene-coming** [comment]
on dble commit version：18e8b31.
pls pay attention to character_set_connection: latin1 in following query:
```mysql
mysql> show variables like 'char%';
+--------------------------+----------------------------------+
| Variable_name            | Value                            |
+--------------------------+----------------------------------+
| character_set_client     | utf8                             |
| character_set_connection | latin1                           |
| character_set_database   | latin1                           |
| character_set_filesystem | binary                           |
| character_set_results    | utf8                             |
| character_set_server     | latin1                           |
| character_set_system     | utf8                             |
| character_sets_dir       | /usr/local/mysql/share/charsets/ |
+--------------------------+----------------------------------+
```

if query 
```mysql
set names utf8
```
before step1, query will get expect result, else step2 will still get the wrong error as real result before. 

ps: do "set names utf8" between step1 and step2 also get the wrong error as real result before.

**Comment by irene-coming** [comment]
verified on version: 5.6.29-dble-2.18.09.1-2b298cd-20180904021034

the problem described in https://github.com/actiontech/dble/issues/679#issuecomment-418049065 moved to
https://github.com/actiontech/dble/issues/689
