### ISSUE TITLE
Join Error when the join Key contain value null

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#681]
* **dble version：**  lastest
* **preconditions ：**  
* **configs：** 

**schema.xml**  

```
<?xml version="1.0"?>
<!DOCTYPE dble:schema SYSTEM "schema.dtd">
<dble:schema xmlns:dble="http://dble.cloud/">

    <schema name="TESTDB">
        <!-- auto sharding by id (long) -->
        <table name="table_a" dataNode="node_db00,node_db01" rule="sharding-by-hash2"/>
        <table name="table_b" dataNode="node_db00,node_db01" rule="sharding-by-hash2"/>
        <table name="table_c" dataNode="node_db00,node_db01" rule="sharding-by-hash2"/>
    </schema>
    <!-- <dataNode name="dn1$0-743" dataHost="localhost1" database="db$0-743"
        /> -->
    <dataNode name="node_db00" dataHost="localhost1" database="db1"/>
    <dataNode name="node_db01" dataHost="localhost1" database="db2"/>
    <dataHost name="localhost1" maxCon="1000" minCon="10" balance="0" switchType="1" slaveThreshold="100">
        <heartbeat>show slave status</heartbeat>
        <!-- can have multi write hosts -->
        <writeHost host="hostM1" url="localhost:3306" user="root"
                   password="123456">
        </writeHost>
    </dataHost>
</dble:schema>
```

**rule.xml**  

default config

**server.xml**  

default config

* **steps：**    
create table and insert data into this case
mysql> select * from table_a;
+------+------+
| id   | aa   |
+------+------+
|    1 | 123  |
+------+------+

mysql> select * from table_b;
+------+------+
| id   | bb   |
+------+------+
|    2 | 111  |
|    2 | 123  |
|    2 | NULL |
+------+------+
select * from table_a a,table_b b where a.aa = b.bb;
* **expect result：**  
+------+------+------+------+
| id   | aa   | id   | bb   |
+------+------+------+------+
|    1 | 123  |    2 | 123  |
+------+------+------+------+
* **real result：**  
  Empty set (0.32 sec)

/label ~BUG

**Comment by yanhuqing666** [comment]
#634  #600 #140

**Comment by irene-coming** [comment]
verified on version 5.6.29-dble-2.18.09.1-2b298cd-20180904021034
