### ISSUE TITLE
[feature]check @@metadata

### ISSUE THREAD

**Issue by yanhuqing666** [actiontech/dble#708]
## Background
check @@metadata after reload @@metadata to confirm the table structure。

## Design
* * `check @@metadata`
    * return the datetime of last reload @@metadata（or the datetime of last reload @@config_all or init time）  

*  * `check full @@metadata` ,and suppert these filter: 
      * `where schema=? and table=?`
      * `where schema=?`
      * `where reload_time=?`,`where reload_time>=?`,`where reload_time<=?`
      * `where reload_time is null`
      * `where consistent_in_data_nodes=0`
      * `where consistent_in_data_nodes = 1`
      * `where consistent_in_memory=0`
      * `where consistent_in_memory = 1`
      * If no where, retrun all results.

  * `check full @@metadata` result like this:

schema|table|reload_time|table_structure|consistent_in_data_nodes|consistent_in_memory
--|--|--|--|--|--
schema|table|2018-09-18 11:01:04| CREATE TABLE table`(.....|1|1

**column table_structure is just like the format of `show create table`**

**Comment by irene-coming** [comment]
append above management commands to show @@help ?

**Comment by FlyingMao** [comment]
**verified version:**
5.6.29-dble-9.9.9.9-ea3eaeb-20180929033800
