### ISSUE TITLE
new check item in Dryrun

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#712]
Add table meta check in dryrun ,check if the table has been created   
Add ucore connect check ,check if Dble can connect to ucore

**Comment by yexiaoli88** [comment]
verified on version: 5.6.23-dble-9.9.9.9-2a7e068-20180921021116

**Comment by yexiaoli88** [comment]
verified on version: 5.6.29-dble-9.9.9.9-97c7758-20181017071207
testlink : http://10.186.18.20:888/testlink/linkto.php?tprojectPrefix=DMP&item=testcase&id=DMP-965
