### ISSUE TITLE
query "SELECT * FROM (SELECT 1, 2, 3) AS t1;" got error:No dataNode found

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#716]
* **dble version：**  
5.6.29-dble-9.9.9.9-287a2f4-20180921052651
* **preconditions ：**  
reference: https://dev.mysql.com/doc/refman/8.0/en/join.html
> A table_subquery is also known as a derived table or subquery in the FROM clause. See Section 13.2.11.8, “Derived Tables”. Such subqueries must include an alias to give the subquery result a table name, and may optionally include a list of table column names in parentheses. A trivial example follows:
SELECT * FROM (SELECT 1, 2, 3) AS t1;

* **steps：**    
    step1.  execute query with dble business port
```mysql
mysql> SELECT * FROM (SELECT 1, 2, 3) AS t1;
ERROR 1046 (HY000): No dataNode found ,please check tables defined in schema:mytest
mysql> explain SELECT * FROM (SELECT 1, 2, 3) AS t1;
ERROR 1105 (HY000): java.lang.NullPointerException
```
* **expect result：**  
    1. step1 query success
* **real result：**  
    1. step1 query fail
* **supplements：**  
    1.

/label ~BUG

**Comment by yexiaoli88** [comment]
verified on version: 5.6.29-dble-9.9.9.9-21b7b82-20180925034029
