### ISSUE TITLE
multi-query with ddl may need sync context

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#743]
* **dble version：**  
5.6.29-dble-9.9.9.9-153cf8b-20180928075325
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```
        <schema name="mytest" sqlMaxLimit="100" dataNode="dn5">
                <table name="aly_test" dataNode="dn1,dn2,dn3,dn4" rule="hash-four" />
        </schema>
        <dataNode name="dn1" dataHost="172.100.9.5" database="db1" />
        <dataNode name="dn2" dataHost="172.100.9.6" database="db1" />
        <dataNode name="dn3" dataHost="172.100.9.5" database="db2" />
        <dataNode name="dn4" dataHost="172.100.9.6" database="db2" />
        <dataNode name="dn5" dataHost="172.100.9.5" database="db3" />
```

* **steps：**    
    step1.  run ./multiQuery.o

source file and compile see autotest directory:
autotest/dble/tree/master/drivers/c_mysql_api/multi-queries
 
* **expect result：**  
    1.print multi resultsets:
        0 rows affected
        More results exist
        0 rows affected
        More results exist
        0 rows affected
        More results exist
        0 rows affected
        More results exist
        1 rows affected
        More results exist
        1 rows affected
        More results exist
        0 rows affected
* **real result：**  
    1.  print multi resultsets:
        0 rows affected
        More results exist
        0 rows affected
        More results exist
        0 rows affected
        More results exist
Could not get next result

* **supplements：**  
    1. dble log segment

![image](https://user-images.githubusercontent.com/6801133/46241833-0e0c7700-c3f2-11e8-885e-2b18cb3bf6d0.png)

/label ~BUG

**Comment by yanhuqing666** [comment]
9acdbb8a18a960735c84ba19f2f70da5b26633c2 not for #734 but #743

**Comment by irene-coming** [comment]
verified on version: 5.6.29-dble-9.9.9.9-9acdbb8-20180929073705
autotest:mysql_multi_queries.cpp
