### ISSUE TITLE
sql syntax [lock table ... write] cannot be parsed by druid

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#744]
* **dble version：** 
 5.6.29-dble-9.9.9.9-153cf8b-20180928075325

* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```
<table dataNode="dn1,dn2,dn3,dn4" name="aly_test" rule="hash-four" />
```

* **steps：**    
    step1.  execute query with dble business port
```mysql
mysql> lock table aly_table write;
ERROR 1064 (HY000): sql syntax error, no terminated. IDENTIFIER
```
* **expect result：**  
    1. step1,  support lock table ... write
* **real result：**  
    1.lock table ... write got syntax error
* **supplements：**  
    1.

/label ~BUG

**Comment by FlyingMao** [comment]
**verified version:**   5.6.29-dble-9.9.9.9-359645c-20181029082136

**Comment by FlyingMao** [comment]
#788
