### ISSUE TITLE
MaxCon do not work when the concurrent number increase rapidly

### ISSUE THREAD

**Issue by Lennon925** [actiontech/dble#745]
* **dble version：**  Release 2.18.09.0

**schema.xml**  

```
<dble:schema xmlns:dble="http://dble.cloud/">

    <schema name="dble_testdb" dataNode="dn1">
    </schema>

    <dataNode name="dn1" dataHost="localhost1" database="testdb"/>

    <dataHost name="localhost1" maxCon="100" minCon="50" balance="0" switchType="1" slaveThreshold="100">
        <heartbeat>select user()</heartbeat>
  
        <writeHost host="hostS1" url="10.151.95.14:3306" user="root" password="123456"/>

    </dataHost>
</dble:schema>

```

* **real result：**  
    INFO   | jvm 1    | 2018/10/08 14:48:02 | java.io.IOException: Can't get variables from data node
INFO   | jvm 1    | 2018/10/08 14:48:02 | 	at com.actiontech.dble.DbleServer.pullVarAndMeta(DbleServer.java:288)
INFO   | jvm 1    | 2018/10/08 14:48:02 | 	at com.actiontech.dble.DbleServer.startup(DbleServer.java:438)
INFO   | jvm 1    | 2018/10/08 14:48:02 | 	at com.actiontech.dble.DbleStartup.main(DbleStartup.java:41)
INFO   | jvm 1    | 2018/10/08 14:48:02 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2018/10/08 14:48:02 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO   | jvm 1    | 2018/10/08 14:48:02 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2018/10/08 14:48:02 | 	at java.lang.reflect.Method.invoke(Method.java:498)
INFO   | jvm 1    | 2018/10/08 14:48:02 | 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:240)
INFO   | jvm 1    | 2018/10/08 14:48:02 | 	at java.lang.Thread.run(Thread.java:748)

As I know, when I set schema.xml like above, mycat is ok. but dble is not,it can't start and log as above.

**Comment by yanhuqing666** [comment]
“Can't get variables from data node” ，
Please check if you can connect mysql `<writeHost host="hostS1" url="10.151.95.14:3306" user="root" password="123456"/>`  from your dble server machine

**Comment by Lennon925** [comment]
> “Can't get variables from data node” ，
> Please check if you can connect mysql `<writeHost host="hostS1" url="10.151.95.14:3306" user="root" password="123456"/>` from your dble server machine

Thanks for your reply. you are right. but another bug: 
I set maxCon = 100 and in my app I start 200 threads to do something about database, I found that mysql connection count is above 100. MaxCon didn't prevent threads to connect mysql.
In mycat， there is the same bug too.

**Comment by sunsun314** [comment]
Please describe the detail of your test case,mainly the way to observe the mysql connection

**Comment by Lennon925** [comment]
> Please describe the detail of your test case,mainly the way to observe the mysql connection

Hi Sunsun,

1. Set maxcon = 100 like schema.xml above.
2.Write some code to connect dble to create 200 thread to do something about database operations.
3.using command “show processlist” to observe mysql connection in mysql command line client.

my python code is like this:
`import MySQLdb
import thread
import time

def insert_data(threadName):
    try:
        db = MySQLdb.connect("10.184.159.224", "root", "123456", "dble_testdb", port=8066, charset='utf8' )
        cursor = db.cursor()
        sql = """INSERT INTO TB_ITEM(ID,TITLE) VALUES ('123456', 'Lennon')"""
        cursor.execute(sql)
        db.commit()
    except Exception,err:
        print err
    
    time.sleep(600)
    db.close()


for num in range(0,200):
    thread.start_new_thread(insert_data,(num,))

time.sleep(600)`

**Comment by Lennon925** [comment]
You can also see dble log and will notice that extra connections were created.

**Comment by Lennon925** [comment]
Before I tested with dble, I used mycat and I found that it's not thread-safe when mycat creates connections with mysql. My friend suggested my to try  dble.  Unfortunately, it seems that there is  the same bug with mycat. I want to know whether dble team can fix this bug.

**Comment by sunsun314** [comment]
The maxCon problem was reproduced in my test machine,we may fix the problem in future release version

**Comment by Lennon925** [comment]
> The maxCon problem was reproduced in my test machine,we may fix the problem in future release version

How long will dble team fix this bug?

**Comment by Lennon925** [comment]
> It would take one or two version if we finish discussing the risk of the change,otherwise we would write on this issue if we decide not fix it
> The main difficult is that we must keep the Dble stable,it may takes lots of testing effort

Do  you have some documents about how to install dble by building source code? I want to fix this bug as soon as possible and to use dble.

**Comment by sunsun314** [comment]
Only maven is needed to build the Dble. I would fix it in some branch in one or two days,but it may not release for a long time

**Comment by Lennon925** [comment]
> Only maven is needed to build the Dble. I would fix it in some branch in one or two days,but it may not release for a long time

Could you tell me the branch you will fix this issue on so that after you finish, I can download branch source code to build a temp version and use it?

**Comment by sunsun314** [comment]
https://github.com/actiontech/dble/tree/issue-745
The code is only tested by myself,still waiting for review

**Comment by Lennon925** [comment]
> https://github.com/actiontech/dble/tree/issue-745
> The code is only tested by myself,still waiting for review

this branch is disappear?

**Comment by sunsun314** [comment]
The change have been merged into master

**Comment by Lennon925** [comment]
> The change have been merged into master

It seems not to get fixed correctly. I downloaded the latest master source code and built, after that I used tar.gz in target folder to test. the behavior is still wrong. My configuration files are as below.
`<schema name="dble_testdb" dataNode="dn1">
    </schema>

    <dataNode name="dn1" dataHost="localhost1" database="testdb"/>

    <dataHost name="localhost1" maxCon="100" minCon="20" balance="0" switchType="1" slaveThreshold="100">
        <heartbeat>select user()</heartbeat>
        <writeHost host="hostS1" url="10.151.95.14:3306" user="root" password="123456"/>
    </dataHost>`

and my python codes as below:
`def insert_data(threadName):
    try:
        db = MySQLdb.connect("10.184.159.224", "root", "123456", "dble_testdb", port=8066, charset='utf8' )
        cursor = db.cursor()
        sql = """INSERT INTO TB_ITEM(ID,TITLE) VALUES ('123456', 'Lennon')"""
        cursor.execute(sql)
        db.commit()
    except Exception,err:
        print err
    
    time.sleep(600)
    db.close()


for num in range(0,200):
    thread.start_new_thread(insert_data,(num,))

time.sleep(600)`

**Comment by sunsun314** [comment]
I tested it with JDBC,I will try to test it with Python later

**Comment by Lennon925** [comment]
> I tested it with JDBC,I will try to test it with Python later

I think getConnection this function in PhysicalDatasource file is not thread-safe.

**Comment by sunsun314** [comment]
I tested it with python script,the mysql connections number sames to be right ,I tested with script below  
Maybe you should update your local code?
`
import thread,time,MySQLdb

def insert_data(threadName):
    try:
      print str(threadName)+"is connecting"
      db = MySQLdb.connect("192.168.2.166", "root", "123456", "testdb", port=8066, charset='utf8' )
      cursor = db.cursor()
      sql = """insert into table_a set id = 1"""
      cursor.execute(sql)
      db.commit()
    except Exception,err:
      print "error "+str(err)
    time.sleep(600)
    db.close()

if __name__ == "__main__":
    for num in range(0, 200):
        thread.start_new_thread(insert_data,(num,))

    time.sleep(6000)
`

**Comment by sunsun314** [comment]
I use connectionCount and createNewCount() to count the connection, it's not necessary to set the getConnection() synchronized(this reduce the query performance too much,and would not solve the problem)

**Comment by Lennon925** [comment]
> I tested it with python script,the mysql connections number sames to be right ,I tested with script below
> Maybe you should update your local code?
> `
> import thread,time,MySQLdb
> 
> def insert_data(threadName):
> try:
> print str(threadName)+"is connecting"
> db = MySQLdb.connect("192.168.2.166", "root", "123456", "testdb", port=8066, charset='utf8' )
> cursor = db.cursor()
> sql = """insert into table_a set id = 1"""
> cursor.execute(sql)
> db.commit()
> except Exception,err:
> print "error "+str(err)
> time.sleep(600)
> db.close()
> 
> if **name** == "**main**":
> for num in range(0, 200):
> thread.start_new_thread(insert_data,(num,))
> 
> ```
> time.sleep(6000)
> ```
> `

I  downloaded the master source code and rebuilt again. It didn't work. My build command is as follow:
mvn install -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dmaven.wagon.http.ssl.ignore.validity.dates=true.

I used tar.gz file in dble/target folder to test and after running python codes, there are 44 failed connections instead of 100. And mysql connections count is 154. So I think it's still wrong.

I did saw your changeset in my local codes about createNewCount() function. I think my local codes are the latest.

**Comment by Lennon925** [comment]
> I use connectionCount and createNewCount() to count the connection, it's not necessary to set the getConnection() synchronized(this reduce the query performance too much,and would not solve the problem)

Even though I set maxCon = 10, I start 200 threads to run there are still 186 connections on mysql and only 11 thread error info in console.

Anything wrong with me?

**Comment by Lennon925** [comment]
In addtion, there is no logs in dble/log folder when dble server is running.

**Comment by Lennon925** [comment]
Maybe the installer I generated is not correct because I can't connect dble when I used another schema name. But python code can connect previous schema. I think dble environment on my linux is dirty. But I removed dble folder and copy the latest to linux, restart dble using command "dble start", it didn't work. 

could you tell me the way you generate installer using master source code and how to clean the previous dble?

**Comment by sunsun314** [comment]
....... you may connected to your previous Dble server,use ps -ef |grep dble and try to kill it.Than start a new one with lastest version.

**Comment by Lennon925** [comment]
> ....... you may connected to your previous Dble server,use ps -ef |grep dble and try to kill it.Than start a new one with lastest version.

You are right. This morning I tested again and it's right. Thanks for your reply. You are so great and nice.

**Comment by yexiaoli88** [comment]
verified on version: 5.6.29-dble-9.9.9.9-533a13c-20181009064153
