### ISSUE TITLE
 Multiple statements add view create/drop support and ErrorPacket packetId fix

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#746]
Add create/drop view support into multiple statements   
Fix a problem that the ErrorPacket packetId is always 1

**Comment by irene-coming** [comment]
verified on dble version:
5.6.29-dble-9.9.9.9-785f12e-20181012083335

1,add view create/drop support has verfied
2,ErrorPacket packetId always 1 verified by manual:
tcpdump to view err packet id
