### ISSUE TITLE
dble does not support reserved words as table name or column name even use backtick (`)

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#753]
* **dble version：**
5.6.29-dble-9.9.9.9-533a13c-20181009064153
 
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```
<table name="select" dataNode="dn1,dn2,dn3,dn4" type="global"/>
<table name="drop" dataNode="dn1,dn2,dn3,dn4" rule="hash-four"/>
```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  execute sqls with dble business port:
```mysql
mysql> create table `select` (id int);
ERROR 5316 (HY000): CREATE TABLE OK, BUT GENERATE METADATA FAILED
mysql>
mysql>
mysql> drop table if exists `drop`;
Query OK, 0 rows affected, 1 warning (0.02 sec)

mysql> create table .drop(`order` int, `add` int);
ERROR 1064 (HY000): error DOT table
mysql>
mysql>
mysql> create table mytest.drop(`order` int, `add` int);
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'drop(`order` int, `add` int)' at line 1
```

step2.execute sqls with mysql directly
```mysql
mysql> create table .drop(`order` int, `add` int);
Query OK, 0 rows affected (0.04 sec)

mysql> drop table .drop ;
Query OK, 0 rows affected (0.01 sec)

mysql> create table mytest.drop(`order` int, `add` int);
Query OK, 0 rows affected (0.01 sec)

```
* **expect result：**  
    1.step1 get same feedback with step2
* **real result：**  
    1. step1 get different  feedback with step2
* **supplements：**  
    1.

/label ~BUG

**Comment by irene-coming** [comment]
testing sqls FYI:
```mysql
use `schema`;
drop table if exists `drop`;
create table .drop(`order` int, `add` int);
insert into `drop`(order, add) values(1,1);
insert into `drop`(`order`, `add`) values(1,1);
insert into .drop(drop.order, drop.add) values(1,1);
insert into .drop(.drop.order, .drop.add) values(1,1);
insert into .drop(schema.drop.order, schema.drop.add) values(1,1);
select order from .drop;
select `order` from .drop;
select drop.order from schema.drop;
select schema.drop.order from .drop;
select drop.order from .drop order by add;
select drop.order from .drop order by `add`;
select drop.order from .drop order by drop.add;
select drop.order from .drop order by .drop.add;
select schema.drop.order from schema.drop order by schema.drop.add;
show tables from schema;
show tables from `schema`;
explain select `order`, drop.order, .drop.order, schema.drop.order from schema.drop, .drop;
```

**Comment by irene-coming** [comment]
and config reserved words as table name in schema.xml may make metadata load failed

**Comment by FlyingMao** [comment]
### Error when system function name is used as table name
_ps: The table used below is a no_sharding table_

**steps**
execute create in dble:
```
create table MAX (i int);
```
**expect result:**
```
mysql> create table MAX (i int);
Query OK, 0 rows affected (0.38 sec)
```
 **real result:**
```
mysql> create table MAX (i int);
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'MAX (i int)' at line 1
```

**Comment by FlyingMao** [comment]
#798

**Comment by Baofengqi** [comment]
This way of specifying tables is not supported by druid, like .drop.

**Comment by irene-coming** [comment]
> 1. This way of specifying tables is not supported by druid, like .drop.
> 2. When the way of specifying tables or filed is like schema.drop.order, dble replace `schema.` with empty string, so drop.order is push down.  we can instead use schema.`drop`.`order`.
> 3. MAX as table name is associated with sql_mode.

- [ ] 1. is passed
- [ ] 2. create table mytest.drop(`order` int, `add` int); is still failed in dble, the dble.log like:
(use schema1 replace mytest in testing)
```log
    392 2020-02-04 03:15:31.929  INFO [complexQueryExecutor5] (com.actiontech.dble.singleton.DDLTraceManager.updateConnectionStatus(DDLTraceManager.java:40)) - [DDL][5] MySQ        LConnection status update : backendId = 7 mysqlId = 592 CONN_EXECUTE_ERROR
    393 2020-02-04 03:15:31.929  INFO [complexQueryExecutor3] (com.actiontech.dble.singleton.DDLTraceManager.updateConnectionStatus(DDLTraceManager.java:40)) - [DDL][5] MySQ        LConnection status update : backendId = 9 mysqlId = 591 CONN_EXECUTE_ERROR
    394 2020-02-04 03:15:31.929  INFO [complexQueryExecutor5] (com.actiontech.dble.singleton.DDLTraceManager.updateConnectionStatus(DDLTraceManager.java:40)) - [DDL][5] MySQ        LConnection status update : backendId = 21 mysqlId = 28226 CONN_EXECUTE_ERROR
    395 2020-02-04 03:15:31.929  INFO [complexQueryExecutor2] (com.actiontech.dble.singleton.DDLTraceManager.updateConnectionStatus(DDLTraceManager.java:40)) - [DDL][5] MySQ        LConnection status update : backendId = 24 mysqlId = 28224 CONN_EXECUTE_ERROR
    396 2020-02-04 03:15:31.929  WARN [complexQueryExecutor2] (com.actiontech.dble.server.NonBlockingSession.handleSpecial(NonBlockingSession.java:1130)) - DDL execute faile        d or Session closed, Schema[schema1],SQL[create table schema1.drop(`order` int, `add` int)]errorInfo:{
    397    1 -> MySQLConnection host=172.100.9.5, port=3306, schema=db2
    398    2 -> MySQLConnection host=172.100.9.5, port=3306, schema=db1
    399    3 -> MySQLConnection host=172.100.9.6, port=3306, schema=db1
    400    4 -> MySQLConnection host=172.100.9.6, port=3306, schema=db2
    401 }
```
supplements:
create table schema1.drop(`order` int, `add` int); can success in both 2 dble backend dataHosts
ps another problem @sunsun314 : the WARN log of the DDL seems lack key info about: errorInfo
- [ ] 3. is passed

**Comment by Baofengqi** [comment]
> > 1. This way of specifying tables is not supported by druid, like .drop.
> > 2. When the way of specifying tables or filed is like schema.drop.order, dble replace `schema.` with empty string, so drop.order is push down.  we can instead use schema.`drop`.`order`.
> > 3. MAX as table name is associated with sql_mode.
> 
> * [x]  1. is passed
> * [ ]  2. create table mytest.drop(`order` int, `add` int); is still failed in dble, the dble.log like:
>   (use schema1 replace mytest in testing)
> 
> ```sql
> mysql> create table schema1.drop(`order` int, `add` int);
> ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'drop(`order` int, `add` int)' at line 1
> ```
> 
> ```
>     392 2020-02-04 03:15:31.929  INFO [complexQueryExecutor5] (com.actiontech.dble.singleton.DDLTraceManager.updateConnectionStatus(DDLTraceManager.java:40)) - [DDL][5] MySQ        LConnection status update : backendId = 7 mysqlId = 592 CONN_EXECUTE_ERROR
>     393 2020-02-04 03:15:31.929  INFO [complexQueryExecutor3] (com.actiontech.dble.singleton.DDLTraceManager.updateConnectionStatus(DDLTraceManager.java:40)) - [DDL][5] MySQ        LConnection status update : backendId = 9 mysqlId = 591 CONN_EXECUTE_ERROR
>     394 2020-02-04 03:15:31.929  INFO [complexQueryExecutor5] (com.actiontech.dble.singleton.DDLTraceManager.updateConnectionStatus(DDLTraceManager.java:40)) - [DDL][5] MySQ        LConnection status update : backendId = 21 mysqlId = 28226 CONN_EXECUTE_ERROR
>     395 2020-02-04 03:15:31.929  INFO [complexQueryExecutor2] (com.actiontech.dble.singleton.DDLTraceManager.updateConnectionStatus(DDLTraceManager.java:40)) - [DDL][5] MySQ        LConnection status update : backendId = 24 mysqlId = 28224 CONN_EXECUTE_ERROR
>     396 2020-02-04 03:15:31.929  WARN [complexQueryExecutor2] (com.actiontech.dble.server.NonBlockingSession.handleSpecial(NonBlockingSession.java:1130)) - DDL execute faile        d or Session closed, Schema[schema1],SQL[create table schema1.drop(`order` int, `add` int)]errorInfo:{
>     397    1 -> MySQLConnection host=172.100.9.5, port=3306, schema=db2
>     398    2 -> MySQLConnection host=172.100.9.5, port=3306, schema=db1
>     399    3 -> MySQLConnection host=172.100.9.6, port=3306, schema=db1
>     400    4 -> MySQLConnection host=172.100.9.6, port=3306, schema=db2
>     401 }
> ```
> 
> supplements:
> create table schema1.drop(`order` int, `add` int); can success in both 2 dble backend dataHosts
> ps another problem @sunsun314 : the WARN log of the DDL seems lack key info about: errorInfo
> 
> * [x]  3. is passed

You can use "create table mytest.\`drop\`(order int, add int)" instead. dble replace `mytest.` with empty string, so "create table \`drop\`(order int, add int)"  is push down. Otherwise, "create table drop(order int, add int)"  is push down.

**Comment by wjl1619** [comment]
verified on version: 5.6.29-dble-2.19.11.0-14d0361ecc08d84098a04090b8db7d66aa4801f1-20200211074123
