### ISSUE TITLE
Dble can't start with upper case dataNode when mysql is in lower_case_table_name=1

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#754]
* **dble version：**  2.18.09 release
* **preconditions ：**  

* **configs：** 

**schema.xml**  

```
<!DOCTYPE dble:schema SYSTEM "schema.dtd">
<dble:schema xmlns:dble="http://dble.cloud/">
    <schema name="TESTDB" dataNode='DN1'>
        <table name="table_a" dataNode="DN1,dn2" rule="sharding-by-hash2"/>
        <table name="aly_test" dataNode="DN1,dn2" rule="sharding-by-hash2"/>
        <table name="table_b" dataNode="DN1,dn2" rule="sharding-by-hash2"/>
        <table name="table_c" dataNode="DN1,dn2" rule="sharding-by-hash2">
            <childTable name="table_d" joinKey="id" parentKey="id" primaryKey="id"/>
        </table>
    </schema>
    <schema name="testxxx" dataNode="DN1"/>
    <dataNode name="DN1" dataHost="localhost1" database="db1"/>
    <dataNode name="dn2" dataHost="localhost1" database="db2"/>
    <dataNode name="dn3" dataHost="localhost1" database="db3"/>
    <dataNode name="dn4" dataHost="localhost1" database="db4"/>
    <dataHost balance="0" maxCon="20" minCon="5" name="localhost1" switchType="-1" slaveThreshold="100">
        <heartbeat>show slave status</heartbeat>
        <writeHost host="hostM1" url="10.186.24.37:3306" password="123456" user="root">
        	</writeHost>
    </dataHost>
</dble:schema>


```

* **steps：**    
Backend mysql set lower_case_table_names = 1   
use dataNode with name upper case
start dble
* **expect result：**  
start dble success
* **real result：**  
com.actiontech.dble.config.util.ConfigException: SelfCheck### schema dataNode[dn1] is empty!
	at com.actiontech.dble.config.ServerConfig.selfChecking0(ServerConfig.java:431)
	at com.actiontech.dble.config.ServerConfig.reviseLowerCase(ServerConfig.java:372)
	at com.actiontech.dble.DbleServer.reviseSchemas(DbleServer.java:241)
	at com.actiontech.dble.DbleServer.pullVarAndMeta(DbleServer.java:261)
	at com.actiontech.dble.DbleServer.startup(DbleServer.java:423)
	at com.actiontech.dble.DbleStartup.main(DbleStartup.java:29)

/label ~BUG

**Comment by yexiaoli88** [comment]
verified on version: 5.6.29-dble-2.18.10.0-6367e10-20181012031734
