### ISSUE TITLE
"select id, -sum(c_decimal) [as] c2 from aly_test group by id order by c2 desc;" got "field not found:-SUM(c_decimal)"

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#758]
* **dble version：**  
5.6.29-dble-2.18.10.0-0a33274-20181012083619
* **preconditions ：**  
no
* **configs：** 
**schema.xml**  

```
<table name="aly_test" dataNode="dn1,dn2,dn3,dn4" rule="hash-four" />
```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1. execute queries with dble:
```mysql
mysql> create table aly_test(id int, c_decimal float);
Query OK, 0 rows affected (0.01 sec)
mysql> select -sum(c_decimal) c_alias from aly_test order by c_alias;
ERROR 1003 (HY000): field not found:-SUM(c_decimal)

``` 
* **expect result：**  
    1. step1, select query success
* **real result：**  
    1.  select query fail
* **supplements：**  
    1.

/label ~BUG

**Comment by yexiaoli88** [comment]
verified on version: 5.6.29-dble-2.18.10.0-6367e10-20181012031734

**Comment by yexiaoli88** [comment]
verified on version: 5.6.29-dble-2.18.10.0-c683b99-20181015051308
