### ISSUE TITLE
expect a way to know whether the config property value is same with the real in working value

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#759]
dble version:5.6.29-dble-2.18.10.0-0a33274-20181012083619

Some times, after several times change to config file, I can not tell whether the config value is the one in working. 
so, I expect a way to know config property's in working value

**Comment by irene-coming** [comment]
Ways to get part of config info (provided by [tiger.yan]( https://github.com/yanhuqing666)):
startup time: show @@time.startup
check server.xml property in system node:  show @@sysparam
whitelist: show @@white
schema names in  schema.xml： show @@database
datasource in schema.xml：show @@datasource
datanode in schema.xml： show @@datanode

table info of special schema: show @@dataNodes where schema=? and table=?;
table sharding info: show @@algorithm where schema=? and table=?;

**Comment by Baofengqi** [comment]
add manager command:
show @@user
show @@user.privilege

modify manager command:
show @@datasource

**Comment by Baofengqi** [comment]
update doc : https://github.com/actiontech/dble-docs-cn/blob/develop/2.Function/2.1_manager_cmd/2.1.03_show.md
