### ISSUE TITLE
manager user's connection num may exceed maxCon limit

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#761]
* **dble version：**  
5.6.29-dble-2.18.10.0-c683b99-20181015051308

* **steps：**    
        + step1:           create a btrace script like below:
 ```
package com.actiontech.dble.btrace.script;

import com.sun.btrace.BTraceUtils;
import com.sun.btrace.annotations.BTrace;
import com.sun.btrace.annotations.OnMethod;
import com.sun.btrace.annotations.ProbeClassName;
import com.sun.btrace.annotations.ProbeMethodName;


@BTrace(unsafe = true)
public final class BtraceClusterDelay {

    @OnMethod(
            clazz = "com.actiontech.dble.net.FrontendUserManager",
            method = "countDown"
    )
    public static void countDown(@ProbeClassName String probeClass, @ProbeMethodName String probeMethod) throws Exception {
        BTraceUtils.print("get into countDown ");
        BTraceUtils.print(" for order __________________________ ");
        Thread.sleep(10000L);
    }
}
```
        +step2 use btrace to trace a dble instance
        +step3 use more then one client to create at least 2 connection to dble
        +step4 execute kill @@connection to kill a connection
        +step5 close their connection,wait for about 20s
        + step6 try to create frontConnection more than maxCon
* **expect result：**  
      frontEndConnection can not more than maxCon
* **real result：**  
      frontEndConnection can be more than maxCon

/label ~BUG

**Comment by wjl1619** [comment]
can't replicate on dble version: 5.6.29-dble-9.9.9.9-10ce90a-20181101120727

**Comment by wjl1619** [comment]
verified on version: 5.6.29-dble-9.9.9.9-10ce90a-20181101120727
