### ISSUE TITLE
myid.properties only one zkUrl is available

### ISSUE THREAD

**Issue by kwengelie** [actiontech/dble#766]
* **dble version：**  
5.6.29-dble-2.18.09 release
* **steps：**    
    start dble with myid.properties  ipAddress=10.186.24.112:2181,10.186.24.113:2181
* **expect result：**  
   connection zk success
* **real result：**  
     Background exception was not retry-able or retry gave up java.net.UnknownHostException: 127.0.0.1:2181: invalid IPv6 address
	at java.net.InetAddress.getAllByName(InetAddress.java:1169)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
/label ~BUG

**Comment by yexiaoli88** [comment]
verified on version：5.6.29-dble-9.9.9.9-7955560-20181206052945

testlink位置：http://10.186.18.20:888/testlink/linkto.php?tprojectPrefix=dble&item=testcase&id=dble-911
