### ISSUE TITLE
dble parses empty column for int to NULL while mysql parses to 0 in [load data ...] query

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#768]
* **dble version：**  
5.6.29-dble-2.18.10.0-c683b99-20181015051308

* **preconditions ：**  
no
* **configs：** 

**schema.xml**  
```
<table dataNode="dn1,dn2,dn3,dn4" name="test" rule="hash-four" />
```
* **steps：**    
    step1.  create file 'file1.txt' and fill contents in both dble and mysql seperately:
```
1,a,,
2,b,2,2
3,c,,3
4,d,4,
5,,5,5
6,e,6
```
    step2. execute sqls in both dble and mysql seperately
```mysql
create table test(id int, c1 char(5), c2 int, c3 int);
load data local infile './file1.txt' into table test fields terminated by ',' lines terminated by '\n';
select * from test order by id;
```
    step3.dble and mysql results : 
![image](https://user-images.githubusercontent.com/6801133/47147221-5982b880-d300-11e8-97ad-cc94596f6c2d.png)
![image](https://user-images.githubusercontent.com/6801133/47147280-7ae3a480-d300-11e8-9eb0-3b5f3d12ac74.png)

* **expect result：**  
    1. step3 dble get same result with mysql
* **real result：**  
    1. step3 dble get different result with mysql as marked in above pictures
* **supplements：**  
    1.mysql load data... warnings:
![image](https://user-images.githubusercontent.com/6801133/47147413-c302c700-d300-11e8-87c9-3c54b67e8c5d.png)

/label ~BUG

**Comment by yanhuqing666** [comment]
can not reproduce

**Comment by irene-coming** [comment]
can not reproduce
