### ISSUE TITLE
dble parses empty line different with mysql in [load data ...] query

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#769]
* **dble version：**  
5.6.29-dble-2.18.10.0-c683b99-20181015051308
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```
<table dataNode="dn1,dn2,dn3,dn4" name="test" rule="hash-four" />
```

* **steps：**    
    step1.  create file 'file1.txt' and fill contents in both dble and mysql seperately:
```
1,a,,
2,b,2,2
3,c,,3
4,d,4,
5,,5,5
6,e,6
(empty line here)
```
    step2. execute sqls in both dble and mysql seperately
```mysql
create table test(id int, c1 char(5), c2 int, c3 int);
load data local infile './file1.txt' into table test fields terminated by ',' lines terminated by '\n';
select * from test order by id;
```
    step3.dble and mysql results : 
![image](https://user-images.githubusercontent.com/6801133/47148057-3c4ee980-d302-11e8-9621-3add9685abfc.png)
![image](https://user-images.githubusercontent.com/6801133/47148097-5ee10280-d302-11e8-8679-011b6a1edf0c.png)

* **expect result：**  
    1. step3 dble get same result with mysql
* **real result：**  
    1. step3 dble get different result with mysql as marked in above pictures
* **supplements：**  
  1.mysql load data... warnings:
![image](https://user-images.githubusercontent.com/6801133/47148154-80da8500-d302-11e8-8e5e-8096d709f501.png)

  2.there are another bug in the resultset which prompted in issue https://github.com/actiontech/dble/issues/768

/label ~BUG

**Comment by wjl1619** [comment]
verified on version: 5.6.29-dble-9.9.9.9-0e46f01-20181106093320
Now it wil give an error message if loading file contains empty line: ERROR 1136 (HY000): row data can't not calculate a sharding value,Partition column is empty in line ''
