### ISSUE TITLE
Close the session while doing DDL, the DDL lock may not be removed

### ISSUE THREAD

**Issue by yanhuqing666** [actiontech/dble#797]
* **dble version：**  dble-2.18.10.0-6cbccd3-20181020142155
* **preconditions ：**  
```

CREATE TABLE `sharding_two_node` (
  `id` int(11) NOT NULL,
  `c_flag` char(255) DEFAULT NULL,
  `c_decimal` decimal(16,4) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

```
* **configs：** 

**schema.xml**  

```
<table name="sharding_two_node" rule="two_node_hash" dataNode="dn1,dn2"></table>

```
* **steps：**    
    step1.  

start btrace using [unsafe mode](https://blogs.oracle.com/sundararajan/btrace-unsafe-mode) :
```
{$btracePath}/bin/btrace `{pidof java}` {$scriptPath}/Test.java  

```
btrace script(Test.java):
```
package com.actiontech.dble.btrace.script;

import com.sun.btrace.BTraceUtils;
import com.sun.btrace.annotations.BTrace;
import com.sun.btrace.annotations.OnMethod;
import com.sun.btrace.annotations.ProbeClassName;
import com.sun.btrace.annotations.ProbeMethodName;

@BTrace(unsafe = true)
public final class Test {
    private Test() {

    }
    @OnMethod(
            clazz = "com.actiontech.dble.meta.ProxyMetaManager",
            method = "addMetaLock"
    )
    public static void sleepWhenAddMetaLock(@ProbeClassName String probeClass, @ProbeMethodName String probeMethod) throws Exception {
        BTraceUtils.print("get into addMetaLock,start sleep ");
        BTraceUtils.print(" __________________________ ");
        Thread.sleep(30000L);
        BTraceUtils.print("sleep end ");
        BTraceUtils.print(" __________________________ ");
    }
}
```
   step2. open session 1 and execute `truncate table  sharding_two_node`
   step3. see btrace log shows `get into addMetaLock,start sleep` and close session 1 in 30 seconds.
   step4. after btrace shows `sleep end`,open session 2 and and execute `truncate table  sharding_two_node`

* **expect result：**  
    1. step4 return ok.
* **real result：**  
    1. step4 return `ERROR 4006 (HY000): SCHEMA[testdb], TABLE[sharding_two_node] is doing DDL`
* **supplements：**  
    1.

/label ~BUG

**Comment by FlyingMao** [comment]
**verified version：** 5.6.29-dble-9.9.9.9-b3d9d8d-20181123074828

**Comment by FlyingMao** [comment]
1. The ddl lock cannot be released when the session is closed after `select 1`
2. Inconsistent table structure when the session is closed after `select 1`

**Comment by FlyingMao** [comment]
**verified version：** 5.6.29-dble-9.9.9.9-3b1f9f9-20181127080214

**Comment by FlyingMao** [comment]
**reopen version：** 5.6.29-dble-9.9.9.9-06d1f9a203c576becf5f5bc2565b722cd981a5b3-20181224034323

**Comment by FlyingMao** [comment]
**verified version：** 5.6.29-dble-9.9.9.9-d696cf476c9e2c030b07458f02a2aa1d5bacbc18-20181227020937
