### ISSUE TITLE
[select * from sharding_two_node where id  is null] gets lost connection ...

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#800]
* **dble version：**  
5.6.29-dble-9.9.9.9-88bdad5-20181030102646

* **preconditions：** 
table sharding_two_node is correctly created

* **configs：** 

**schema.xml**  

```
<table name="sharding_two_node" primaryKey="id" dataNode="dn1,dn2" rule="hash-two" />
```

* **steps：**    
    step1. execute sql with dble
![image](https://user-images.githubusercontent.com/6801133/47895050-2401d180-dea1-11e8-93c4-ffb54a60d7ce.png)

 **expect result：**  
    1. query success
* **real result：**  
    1. query failed
* **supplements：**  
    1. this bug is accidental, expect developer can give an efficient way to test, thx~

the developer suggest:
1. insert a null value to the above table's sharing column(which also is primary key in schema.xml), 
2. then "select xxx from sharding_two_node where id is null" will reproduce the bug

/label ~BUG

**Comment by FlyingMao** [comment]
**verified version:** 5.6.29-dble-9.9.9.9-475ffa1-20181121114114
