### ISSUE TITLE
get "recycle time out" when try to commit a session

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#808]
* **dble version：**  
2.18.09 release
5.6.29-dble-2.18.10.0-6cbccd3-20181020142155
* **schema.xml**  

```
<table name="xtest" dataNode="dn1,dn2" rule="hash-two" primaryKey="id"/>
<table name="ntest" dataNode='dn2' />
```
* **steps：**    

    step1. prepare table with query in dble:
    ```mysql
    create table ntest(id int,name varchar(33));
    create table xtest(id int,name varchar(33));
    ```
    step2. prepare data with query in dble:
    ```mysql
    insert into ntest set id = 1;
    insert into xtest set id = 1;
    ```
    step3. prepare data with MySQLdb driver to dble:
```python
import MySQLdb
conn=MySQLdb.connect('172.100.9.1','test','111111','mytest',8066,autocommit=True)
cur=conn.cursor()
def my_insert():
    for i in range(900,1000):
        cur.execute("insert into xtest set id={0}".format(i))

my_insert()
```

    step4. start btrace to trace the dble, BtraceClusterDelay.java download here, 

[BtraceClusterDelay.java.txt] 
(https://github.com/actiontech/dble/files/2551951/BtraceClusterDelay.java.txt)
    (remove the postfix .txt by yourself)
    

> ./btrace dble-pid BtraceClusterDelay.java
   
 step5. execute query in dble:
```mysql
mysql> start transaction; -- verify "begin;" and "set autocommit=0;"
Query OK, 0 rows affected (0.00 sec)

mysql> select a.id from xtest a,ntest b where a.id = b.id;
+------+
| id   |
+------+
|    1 |
+------+
1 row in set (0.62 sec)

mysql> commit;
ERROR 1105 (HY000): recycle time out
```
* **expect result：**  
 step5 "commit" gives success
* **real result：**  
step5 "commit" gives error

* **supplement: **
explain from developer zhengfang.sun:
trx commit handler has no way to setting "running" to false.
/label ~BUG

**Comment by FlyingMao** [comment]
**verified version:** 5.6.29-dble-2.18.10.1-cb392c3-20181106093917
