### ISSUE TITLE
MySQL Workbench 8.0 connect to dble failed, but it connect to MySQL 5.7.13 successfully

### ISSUE THREAD

**Issue by wjl1619** [actiontech/dble#819]
* **dble version：**  
 5.6.29-dble-9.9.9.9-0e46f01-20181106093320
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  use MySQL Workbech 8.0 to connect dble
* **expect result：**  
    1.connect successfully
* **real result：**  
    1.connect failed
* **supplements：**  
    1.maybe it caused by  not supports the caching_sha2_password authentication plugin, details please check the attachment file.

/label ~BUG

**Comment by wjl1619** [comment]
[workbench直连mysql5.7抓包.txt](https://github.com/actiontech/dble/files/2565531/workbench.mysql5.7.txt)

note: please change the extention name as .pcapng before you open the above file

**Comment by yanhuqing666** [comment]
https://dev.mysql.com/doc/internals/en/connection-phase-packets.html#packet-Protocol::AuthSwitchRequest

**Comment by wjl1619** [comment]
verified on dble version: 5.6.29-dble-9.9.9.9-c53c3f7-20181116022818

ps: now the issue comes from workbench 8.0 client itself: the TestConnection button
