### ISSUE TITLE
 It will show wrong table schema and duplicate table names on the table list after we click the 'design table' 

### ISSUE THREAD

**Issue by wjl1619** [actiontech/dble#824]
* **dble version：**  
5.6.29-dble-9.9.9.9-614d735-20181112061135
* **preconditions ：**  
install navicat 12.1.9 for Windows
* **configs：** 
* **steps：**    
    step1. connect to dble
    step2. double click the table 'tbl_test3'(display right table schema for this time) 
    step3. right click the table 'tbl_test3' and select 'design table'(display wrong table schema this time, coz it displays the schema of table 'aly_test')
    step4. refresh the table list, then display the duplicate table name 'aly_test' 
* **expect result：**  
    1.display the right table schema and don't show the duplicate table name on the table list
* **real result：**  
    1.display one table's schema for another and show duplicate table name on the table list
* **supplements：**  
    1.
![navicat_display issue](https://user-images.githubusercontent.com/44627441/48388721-5a5b0e80-e735-11e8-8fc9-d5e94808455e.png)

/label ~BUG

**Comment by sunsun314** [comment]
It's because the navicat  use show table status like 'table_name' ,but dble will return all table status and ignore the like condition

**Comment by wjl1619** [comment]
verified on version:5.6.29-dble-9.9.9.9-f7691ca-20181217021055
