### ISSUE TITLE
Can not reflect view under view list after creating the view correctly

### ISSUE THREAD

**Issue by wjl1619** [actiontech/dble#825]
* **dble version：**  
5.6.29-dble-9.9.9.9-614d735-2018111206113
* **preconditions ：**  
install vavicat 12.1.9 for windows
* **configs：** 

**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  execute the sql: create view view_test as select id,name from aly_test
* **expect result：**  
    1.create right and reflect on the view list after refresh
* **real result：**  
    1.create right but not reflect on the view list after refresh
* **supplements：**  
    1.

/label ~BUG

**Comment by Baofengqi** [comment]
GUI Client send the following statement to query views : SHOW FULL TABLES WHERE Table_type = 'VIEW' .  In current version of dble, result of this statement doesn't include view.
