### ISSUE TITLE
for data type float, dble and mysql may get different results

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#843]
dble version: 5.6.29-dble-9.9.9.9-08136d5-20181106070356

![image](https://user-images.githubusercontent.com/6801133/48747132-348db680-ecad-11e8-8368-ce97f0eb8817.png)

resolution: dble will not deal such case at present, and will give instruction in docs.

**Comment by sunsun314** [comment]
https://github.com/actiontech/dble-docs-cn/blob/master/3.SQL_Syntax/3.10_func_and_operators.md#3108-aggregate-group-by-functions

doc update

**Comment by irene-coming** [comment]
doc verified
