### ISSUE TITLE
Missing administrative commands to view backend locks

### ISSUE THREAD

**Issue by FlyingMao** [actiontech/dble#858]
For example, It takes a long time to execute ddl. In this process, the front-end connection is forcibly closed, and the back-end ddl lock still exists. At this time, an administrative command is needed to see the lock.

**Comment by yanhuqing666** [comment]
#887

**Comment by yanhuqing666** [comment]
#888

**Comment by yexiaoli88** [comment]
related issue #887 and 888 have been created
