### ISSUE TITLE
global table union with none global table get unexpect unreadable error:ERROR 1105 (HY000): Index: 2, Size: 2

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#860]
* **dble version：**  
5.6.29-dble-9.9.9.9-3b1f9f9-20181127080214
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```xml
<schema dataNode="dn5" name="mytest" sqlMaxLimit="100">
  <table dataNode="dn1,dn2,dn3,dn4" name="aly_test" rule="hash-four"/>
  <table dataNode="dn1,dn2,dn3,dn4" name="test" type="global"/>
</schema>

```
**server.xml**  

```xml
<system>
<property name="useGlobleTableCheck">1</property>
</system>
<user name="test_user">
    <property name="password">111111</property>
    <property name="schemas">mytest,testdb</property>
    <privileges check="true">
        <schema name="mytest" dml="0000">
            <table name="aly_test" dml="1111"/>
            <table name="aly_order" dml="0010"/>
        </schema>
    </privileges>
</user>

```
* **steps：**    
step1.  prepare table with dble:
```mysql
create table aly_test(id int, name varchar(5));
create table test(id int, name varchar(5));
```
step2.execute sql with dble:
```mysql
mysql> select * from mytest.aly_test union select * from mytest.test;
ERROR 1105 (HY000): Index: 2, Size: 2
```
step3. execute sql with dble:
```mysql
mysql> alter table test drop column name;
Query OK, 0 rows affected (0.07 sec)
```
step4. execute sql with dble:
```mysql
mysql> select * from aly_test union select * from test;
ERROR 1064 (HY000): The statement DML privilege check is not passed, sql:SELECT *
FROM aly_test
UNION
SELECT *
FROM test
```
* **expect result：**  
   - [x] 1.step2 union success
   - [x] 2.step4 error message  needn't divide into multiple lines
* **real result：**  
    1.step2 union failed
    2.step4 error message occupies multiple lines
* **supplements：**  
    1.autotest already: server_privileges.feature 985c7f5c866f8aa72e71ba7ad3947e3262fda886

/label ~BUG

**Comment by yanhuqing666** [comment]
step2，Can not reproduce
step4， fixed

**Comment by FlyingMao** [comment]
**verified version：** 5.6.29-dble-9.9.9.9-77a57794fbf089f75a76f7c977d47eac5c327b5d-20190102070438
