### ISSUE TITLE
Unsupported statement SAVEPOINT

### ISSUE THREAD

**Issue by wbshen** [actiontech/dble#877]
* **dble version：** 
dble-2.18.09.0-533a13c7
 
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  
~

**rule.xml**  
~

**server.xml**  
~

* **steps：**    
    step1.  execute sql with dble
```
mysql> SAVEPOINT active_record_1;
ERROR 1047 (HY000): Unsupported statement SAVEPOINT active_record_1
```
* **real result：**  
    1. dble  does not support the statement `SAVEPOINT`

* **supplements：**  
    1.

/label ~BUG

**Comment by yanhuqing666** [comment]
we know and will not support

**Comment by Baofengqi** [comment]
savepoint : https://dev.mysql.com/doc/refman/8.0/en/savepoint.html

todo:doc-it

**Comment by wjl1619** [comment]
verified on version: 5.6.29-dble-9.9.9.9-6f61afd798465e9650313bcb1d40b9a1325e287a-20190813105935
