### ISSUE TITLE
For dble management command "kill",now it will response "OK" while killing a connection id that does not exists.

### ISSUE THREAD

**Issue by wjl1619** [actiontech/dble#882]
* **dble version：**  
5.6.29-dble-9.9.9.9-3eb26a6-20181210020901
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  exec : show @@connection;
    step2. exec：kill @@connection 4.
* **expect result：**  
    1.It should response with error message .
* **real result：**  
    1.It will exec success and response "OK"
![image](https://user-images.githubusercontent.com/44627441/49780044-e158d200-fd47-11e8-9687-3bb867da0509.png)

* **supplements：**  

/label ~BUG

**Comment by Baofengqi** [comment]
doc it：https://github.com/actiontech/dble-docs-cn/blob/master/2.Function/2.1_manager_cmd/2.1.05_kill.md

**Comment by wjl1619** [comment]
verified on version: 5.6.29-dble-9.9.9.9-0cd1e42ff677c59e17e251a3b84c8201356e9f58-20181229081733
