### ISSUE TITLE
can not identify the same table name in sub query and  got error "column test_shard.id not found"

### ISSUE THREAD

**Issue by wjl1619** [actiontech/dble#884]
* **dble version：**  
5.6.29-dble-9.9.9.9-ed53a23-20181210110536
* **preconditions ：**  
exec the sqls:
drop table if exists test_shard;
create table test_shard (id int(11) primary key,R_REGIONKEY float,R_NAME varchar(50),t datetime,b bool)DEFAULT CHARSET=UTF8;
insert into test_shard (id,R_REGIONKEY,R_NAME,t,b) values (1,1, 'a string','2012/12/31 11:30:45',0),(2,2, 'a string','2012/12/31 11:30:45',0),(5,5, 'a string','2018/12/03 11:30:45',0);

* **configs：** 

**schema.xml**  

```
<schema name="mytest" sqlMaxLimit="100" dataNode="dn5">
        <table name="sharding_one_1" primaryKey="id" dataNode="dn1" />
                <table name="sharding_one_2" primaryKey="id" dataNode="dn1" />
                <table name="a_two" primaryKey="id" dataNode="dn1,dn2" rule="hash-two" />
        <table name="a_three" primaryKey="id" dataNode="dn1,dn2,dn3" rule="hash-three" />
        <table name="three_sharding_t1" primaryKey="id" dataNode="dn1,dn2,dn3" rule="hash-three-step10" />

                <!--固定Hash分区(string)-->
        <table name="fixed_patch_uniform_string" dataNode="dn1,dn2,dn3,dn4" rule="fixed_uniform_string_rule" />
        <table name="fixed_patch_nonuniform_string" dataNode="dn1,dn2,dn3" rule="fixed_nonuniform_string_rule" />

        <!--枚举方式分区-->
        <table name="enum_patch_integer" dataNode="dn1,dn2,dn3,dn4" rule="enum_integer_rule"/>
                <table name="enum_patch_string" dataNode="dn1,dn2,dn3,dn4" rule="enum_string_rule"/>

                <!--数字范围分区-->
                <table name="range_patch" dataNode="dn1,dn2,dn3,dn4" rule="range_rule" />

        <!--按日期分区-->
                <table name="date_patch" dataNode="dn1,dn2,dn3,dn4" rule="date_rule" />
                <table name="date_patch_default" dataNode="dn1,dn2,dn3,dn4" rule="date_default_rule" />

                <!--全局表-->
                <table name="global_table1" primaryKey="id" type="global" dataNode="dn1,dn2,dn3,dn4" />
                <table name="global_table2" primaryKey="id" type="global" dataNode="dn1,dn2,dn3,dn4" />
                <table name="global_table3" primaryKey="id" type="global" dataNode="dn1,dn2" />
                <table name="test_global" dataNode="dn1,dn2,dn3,dn4" type="global"/>

                <!-- 取模 -->
                <table name="aly_test" dataNode="dn1,dn2,dn3,dn4" rule="hash-four" />
                <table name="aly_order" dataNode="dn1,dn2,dn3,dn4" rule="hash-four" />
                <table name="a_manager" primaryKey="id" dataNode="dn1,dn2,dn3,dn4" rule="hash-four" />
                <table name="mytest_auto_test1" dataNode="dn1,dn2,dn3,dn4" rule="hash-four" primaryKey="R_REGIONKEY" autoIncrement="true"/>
                <table name="test_shard" dataNode="dn1,dn2,dn3,dn4" rule="hash-four"/>


```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  exec the sqls:
select * from test_shard;
select * from test_shard where exists(select * from test_shard where id=1||id=3);
explain SELECT select * from test_shard where exists(select * from test_shard where id=1||id=3);
* **expect result：**  
    1.exec success
* **real result：**  
    1.select * from test_shard where exists(select * from test_shard where id=1||id=3);-->ERROR 4004 (42S22): column test_shard.id not found
    2.explain select * from test_shard where exists(select * from test_shard where id=1||id=3);-->ERROR 1105 (HY000): column test_shard.id not found

* **supplements：**  
    1.
![image](https://user-images.githubusercontent.com/44627441/49786203-efb1e880-fd5d-11e8-83f6-9ee8c6bf6688.png)

/label ~BUG

**Comment by FlyingMao** [comment]
**verified version：** 5.6.29-dble-9.9.9.9-53ddf3e-20181214052815

**Comment by FlyingMao** [comment]
**for tester：**
sqls/bugs/bug.sql（line:232）   features/sql_cover/sql.feature
