### ISSUE TITLE
error when join cross databases

### ISSUE THREAD

**Issue by yexiaoli88** [actiontech/dble#886]
* **dble version： 5.6.29-dble-9.9.9.9-79933e5-20181211102340**  
* **preconditions ：**  
lower_case_table_names =1
* **configs：** 

**schema.xml**  

```
       <schema dataNode="dn5" name="mytest" sqlMaxLimit="100">
                <table dataNode="dn1,dn2,dn3,dn4" name="test" type="global"/>
        </schema>

        <schema name="DBTEST">
        <table name="Test_Table" dataNode="dn1,dn2,dn3,dn4" rule="hash-four"/>
        </schema>


```
* **steps：**    
    step1.  execute in dble 
```
mysql> use mytest;
Database changed   
mysql> select t1.id from dbtest.test_table t1 left join test t2 on t1.id=t2.id;
ERROR 4004 (42S22): column t1.id not found


```
* **expect result：**  
    1. query success
* **real result：**  
    1.query failed
* **supplements：**  
    1. auto_test position:lower_case_table_names.feature --line66-68

/label ~BUG

**Comment by yexiaoli88** [comment]
verified on version: 5.6.29-dble-9.9.9.9-fa53a6f-20181212091929

**Comment by FlyingMao** [comment]
**verified version：** 5.6.29-dble-9.9.9.9-53ddf3e-20181214052815
