### ISSUE TITLE
dble manager has not a way to view in-processing ddl

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#887]
* **dble version：**  
5.6.29-dble-9.9.9.9-3eb26a6-20181210020901

* **expect result：**  
    1. provide a way to view in-processing ddl

**Comment by Baofengqi** [comment]
add management command：show @@ddl

**Comment by yanhuqing666** [comment]
add it in show @@help #852

**Comment by yanhuqing666** [comment]
https://github.com/actiontech/dble-docs-cn/blob/develop/2.Function/2.1_manager_cmd/2.1.03_show.md#21344---show-ddl

**Comment by yexiaoli88** [comment]
#949

**Comment by yexiaoli88** [comment]
verified on version: 5.6.23-dble-9.9.9.9-66ff63a4377428e48842cb16e1662e40e315c1b4-20190124074908
