### ISSUE TITLE
dble manager has not a way to kill in-processing ddl but expect

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#888]
dble version:
5.6.29-dble-9.9.9.9-3eb26a6-20181210020901

**Comment by yanhuqing666** [comment]
add it in show @@help #852

**Comment by yanhuqing666** [comment]
doc need update @Baofengqi

**Comment by yexiaoli88** [comment]
function already has been verified on dble version 5.6.23-dble-9.9.9.9-d52a65fafdd1cbf36151f7d51a37f08d055dcb84-20190219080310

**Comment by Baofengqi** [comment]
doc updated

**Comment by yexiaoli88** [comment]
verified on version 5.6.23-dble-9.9.9.9-c3445b55c3e57110427b5b0862a56411fd9f96b7-20190221102958
