### ISSUE TITLE
"sqlMaxLimit" is invalid for non-sharding table

### ISSUE THREAD

**Issue by yexiaoli88** [actiontech/dble#890]
* **dble version: 5.6.29-dble-9.9.9.9-79933e5-20181211102340**  

* **configs：** 

**schema.xml**  

```
        <schema dataNode="dn1" name="mytest" sqlMaxLimit="3">
            <table dataNode="dn1,dn3" name="test_table" type="global"/>
        </schema>

```

* **steps：**    
 step1.  execute in dble
```
mysql> create table test(id int);
Query OK, 0 rows affected (0.29 sec)

mysql> insert into test values(1),(2),(3),(4);
Query OK, 4 rows affected (0.07 sec)
```
step 2: query in dble
```
mysql> select * from test;
+------+
| id   |
+------+
|    1 |
|    2 |
|    3 |
|    4 |
+------+
4 rows in set (0.00 sec)
```
* **expect result：**  
    1.step2 should return 3 rows
* **real result：**  
    1.step2 returns 4rows
* **supplements：**  
    1.auto_test postion:schema_attribute.feature --line21-24

/label ~BUG

**Comment by yanhuqing666** [comment]
todo：   
1. review "sqlMaxLimit" logic
2. refactor 
3. added to doc

**Comment by wjl1619** [comment]
verified on version: 5.6.29-dble-9.9.9.9-f21f8f0c11b13c8b6c9c90268f6c3983f5dc12aa-20190812080631

**Comment by sunsun314** [comment]
https://github.com/actiontech/dble-docs-cn/blob/develop/1.config_file/1.02_schema.xml.md

**Comment by wjl1619** [comment]
verified on version: 5.6.29-dble-9.9.9.9-9864433926e5278eb808962846064a3dd9722741-20190830092240
