### ISSUE TITLE
system param "maxCon" is invalid for manager user

### ISSUE THREAD

**Issue by yexiaoli88** [actiontech/dble#891]
* **dble versionversion: 5.6.29-dble-9.9.9.9-79933e5-20181211102340：**  

**server.xml**  

```

 <system>
           <property name="useGlobleTableCheck">1</property>
           <property name="processors">1</property>
          <property name="processorExecutor">1</property>
          <property name="maxCon">1</property>
     </system>

     <user name="root">
          <property name="password">111111</property>
          <property name="manager">true</property>
     </user>
     <user name="test">
          <property name="password">123</property>
          <property name="schemas">mytest</property>
     </user>
```

* **steps：**    
    step1.   use "test" connects dble --success
    step2.   use "test" connects dble in the other mysql client --return err:Access denied for user 'test',too many connections for dble server
   step 3: use "root" connects dble -success
* **expect result：**  
    1.step 3 should return error like as step2
* **real result：**  
    1.step 3 success
* **supplements：**  
    1.aut0_test postion:server.feature --line 345

/label ~BUG

**Comment by sunsun314** [comment]
https://github.com/actiontech/dble-docs-cn/blob/master/1.config_file/1.3_server.xml.md  
doc update

**Comment by irene-coming** [comment]
doc verified
