### ISSUE TITLE
MySQL GUI and MySQL driver testing 

### ISSUE THREAD

**Issue by wjl1619** [actiontech/dble#907]
1. GUI
  1.1 MySQL Workbench 8.0  --tested
  1.2 Navicat Premium 12  --tested
  1.3 MySQL Query Browser 1.1.20  --tested
  1.4 DBeaver 5.2.4  --tested
2. Sql support
  2.1 Connector/Python 2.1  --client side is done,  manager part will ignore
  2.2 Connector/J 5.1.35 5.1.39 --done
  2.3 Connector/Net 6.10 --done
  2.4 Connector/C++ 1.1 -- done
3. Driver API -- done by xiaoli

**Comment by guihouchang** [comment]
GUI HeidiSql not supportted~
