### ISSUE TITLE
[select count(distinct id),pad from test_shard group by pad] got "ERROR 1003 (HY000):Merge thread error..."

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#916]
* **dble version：**  
5.6.24-dble-9.9.9.9-0cd1e42ff677c59e17e251a3b84c8201356e9f58-20181229081733
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```
<schema name="mytest" sqlMaxLimit="100" >
        <table name="test_shard" dataNode="dn1,dn2,dn3,dn4" rule="hash-four"/>
</schema>
```

**rule.xml**  

```
```

**server.xml**  

```


```

* **steps：**    
    step1.  execute sql with dble 
```mysql
mysql> use mytest
Database changed
mysql> CREATE TABLE test_shard(`id` int(10) unsigned NOT NULL,`k` int(10) unsigned NOT NULL DEFAULT '0',`c` char(120),`pad` int(11) NOT NULL,PRIMARY KEY (`id`),UNIQUE KEY (`k`))DEFAULT CHARSET=UTF8;
Query OK, 0 rows affected (0.17 sec)
mysql> insert into test_shard values(1,1,'id1',1),(2,2,'id2',2),(3,3,'id3',3),(4,4,'id4',4),(5,5,'id5',1),(6,6,'id6',2),(7,7,'id7',3),(8,8,'$id8$',4),(9,9,'test',3),(10,10,'中',3),(11,11,'i_',4),(12,12,'_g',5),(13,13,'y_u',6),(14,14,'20%',14),(15,15,'a_1',15),(16,16,16,-1),(0,0,0,0),(17,17,'new*\n*line',17),(18,18,'a',18);
Query OK, 19 rows affected (0.03 sec)
mysql> select count(distinct id),pad from test_shard group by pad;
ERROR 1003 (HY000): Merge thread error, Index: 1, Size: 1
mysql>
```
* **expect result：**  
    1. 'select count(distinct id),pad from test_shard group by pad' query success
* **real result：**  
    1. query failed
* **supplements：**  
    1.autotest already
sqls/select/select.sql

/label ~BUG

**Comment by irene-coming** [comment]
verifier attention:

 - [ ] need to verify https://github.com/actiontech/dble/issues/889

**Comment by FlyingMao** [comment]
**verified version:** 5.6.29-dble-9.9.9.9-61be3b260ee1a279e672e56805508c3cd115a639-20190102095816
