### ISSUE TITLE
drop `view` failed when using keyword as view name

### ISSUE THREAD

**Issue by FlyingMao** [actiontech/dble#920]
* **dble version：** 
5.6.29-dble-9.9.9.9-c7d9bfa336cc4dbc2d039e3387bfd80c180c5499-20190104110721 
* **preconditions ：**  
```
drop table if exists test_shard;
CREATE TABLE test_shard(`id` int(10) unsigned NOT NULL,`k` int(10) unsigned NOT NULL DEFAULT '0',`c` char(120),`pad` int(11) NOT NULL,PRIMARY KEY (`id`),UNIQUE KEY (`k`))DEFAULT CHARSET=UTF8;
insert into test_shard values(1,1,'id1',1),(2,2,'id2',2),(3,3,'id3',3),(4,4,'id4',4),(5,5,'id5',1),(6,6,'id6',2),(7,7,'id7',3),(8,8,'$id8$',4),(9,9,'test',3),(10,10,'中',3),(11,11,'i_',4),(12,12,'_g',5),(13,13,'y_u',6),(14,14,'20%',14),(15,15,'a_1',15),(16,16,16,-1),(0,0,0,0),(17,17,'new*\n*line',17),(18,18,'a',18);
create view `select` as select * from test_shard;
```
* **configs：** 

**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  drop view in dble
```
drop view `select`;
```
* **expect result：**  
    1. drop view successed
* **real result：**  
    1.
```
mysql> drop view `select`;
ERROR 1051 (HY000):  Unknown table '`select`'
```
* **supplements：**  
    1. for tester：
This issue is already included in the autotest：sqls/syntax/reserved_words.sql(line: 984)

/label ~BUG

**Comment by yexiaoli88** [comment]
**verified on dble version:  5.6.29-dble-9.9.9.9-5c8cb18839da19645362e7b19b0249b46163f32e-20190110082402**
