### ISSUE TITLE
Add config for incrementColumn table 

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#933]
dble in previous versions can only auto_Increment primary key ,now the increment column can be set with config "incrementColumn" in table config,when the incrementColumn is not set and primaryKey is set,primary key column can still auto increase

**Comment by FlyingMao** [comment]
**verified version** 5.6.29-dble-9.9.9.9-187ade3f39ac09f6d59e689d914dd53bfc077a55-20190228023030
