### ISSUE TITLE
[CREATE TABLE test1(id int, data1 int,data2 int,data3 int as (data1+data2) stored);] hang

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#936]
* **dble version：**  
5.6.29-dble-9.9.9.9-6eb8120084a386b9e05115f5f8f0f53a34adfb55-20190118042625
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```
 <table dataNode="dn1,dn2,dn3,dn4" name="test1" type="global" />
```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  execute sql with dble:
```mysql
mysql> CREATE TABLE test1(id int, data1 int,data2 int,data3 int as (data1+data2) stored);
```
step2. wait step1 until sql time out,login dble manager port:
```mysql
mysql> reload @@config_all;
ERROR 1003 (HY000): Reload config failure.The reason is There is other session is doing DDL
CREATE TABLE test1 (
	id int,
	data1 int,
	data2 int,
	data3 int AS (data1 + data2) SORTED,
	_dble_op_time bigint DEFAULT NULL COMMENT 'field for checking consistency'
)
mysql> kill @@ddl_lock where schema=schema1 and table=test1;
Query OK, 0 rows affected (0.00 sec)
ddl lock that exists is removed successfully!
mysql> reload @@config_all;                                
Query OK, 1 row affected (0.15 sec)
Reload config success
```
* **expect result：**  
   

- [x] 1,step1, query gets error like(because druid parser does not support at present ):
```
ERROR 1064 (HY000): syntax error, error in :'ta2) SORTED)', expect RPAREN, actual IDENTIFIER pos 83, line 1, column 77, token IDENTIFIER SORTED
```
- [ ]  2. step2, if client connection is released(any reason, including timeout), ddl in dble should be released 
* **real result：**  
    1.step1, query hang
   2.step2, ddl lock in dble not released after step1 sql timeout
* **supplements：**  
    1.sharding table has no such problem
    2.dble.log segment:
![image](https://user-images.githubusercontent.com/6801133/51371319-d0fcf980-1b34-11e9-8d95-382df882a5c6.png)

4. autotest already at create_table_definition.sql

/label ~BUG

**Comment by wjl1619** [comment]
1.also hang for executing the sql: 
```sql
 alter table test1 add $ boolean;
```
2.replicate steps:execute the following sqls step by step:
```sql
create table test1(a int(4));
alter table test1 add 01a boolean;
alter table test1 drop column sharding_4_t1.01a;
alter table test1 add `011` boolean;
alter table test1 add $ boolean;
```
3.real result:
hang for 30 mins，and got error:
![image](https://user-images.githubusercontent.com/44627441/51520086-c48ede80-1e5d-11e9-88e4-d1ba65a881af.png)

**Comment by sunsun314** [comment]
The resaon is that dble will parse the sql again after the DDL been executed,and the sql may be changed during route, and the druid may parse the sql error in the second time

**Comment by yexiaoli88** [comment]
verified on dble  version: 5.6.29-dble-9.9.9.9-b83955577d2f5f3555ac6f1254e9c5edb69cefb4-20190129042006
