### ISSUE TITLE
The union result is inconsistent with MySQL when `unsigned column union  negative number`

### ISSUE THREAD

**Issue by FlyingMao** [actiontech/dble#952]
* **dble version：**  
5.6.29-dble-9.9.9.9-21e353f171b56ddd0397c334849938deb8f71f30-20190122041603
* **preconditions ：**  
```
drop table if exists  test1;
CREATE TABLE  test1(`id` int(10) unsigned NOT NULL,`k` int(10) unsigned NOT NULL DEFAULT '0',`c` char(120),`pad` int(11) NOT NULL,PRIMARY KEY (`id`),UNIQUE KEY (`k`))DEFAULT CHARSET=UTF8;
insert into  test1 values(1,1,'id1',1),(2,2,'id2',2),(3,3,'id3',3),(4,4,'id4',4),(5,5,'id5',1),(6,6,'id6',2),(7,7,'id7',3),(8,8,'$id8$',4),(9,9,'test',3),(10,10,'中',3),(11,11,'i_',4),(12,12,'_g',5),(13,13,'y_u',6),(14,14,'20%',14),(15,15,'a_1',15),(16,16,16,-1),(0,0,0,0),(17,17,'new*\n*line',17),(18,18,'a',18);
insert into  test1(id,k,pad) values(19,19,19);
```
* **configs：** 

**schema.xml**  

```
<schema name="schema1" sqlMaxLimit="100">
		<table name="test1" dataNode="dn1,dn2,dn3,dn4" rule="hash-four" />
	</schema>

```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.   execute select query in dble
```
select id from  test1 union SELECT '-1';
```
* **expect result：**  
    1. as mysql result
```
mysql> select id from  test1 union SELECT -1;
+----+
| id |
+----+
|  0 |
|  1 |
|  2 |
|  3 |
|  4 |
|  5 |
|  6 |
|  7 |
|  8 |
|  9 |
| 10 |
| 11 |
| 12 |
| 13 |
| 14 |
| 15 |
| 16 |
| 17 |
| 18 |
| 19 |
+----+
20 rows in set (0.00 sec)

```
* **real result：**  
    1.
```
mysql> select id from  test1 union SELECT '-1';
+----+
| id |
+----+
| -1 |
| 0  |
| 1  |
| 10 |
| 11 |
| 12 |
| 13 |
| 14 |
| 15 |
| 16 |
| 17 |
| 18 |
| 19 |
| 2  |
| 3  |
| 4  |
| 5  |
| 6  |
| 7  |
| 8  |
| 9  |
+----+
21 rows in set (0.01 sec)

```
* **supplements：**  
    1.

**for tester**
dble/sqls/sqls_util/syntax/union.sql(line:65、92、93、95、101、102、108、133、136)
/label ~BUG

**Comment by yanhuqing666** [comment]
delay

**Comment by sunsun314** [comment]
In MySQL 5.7.13 or later the -1 missing can not be reproduced. 
As for union order, MySQL do not committed to normal union result  
https://dev.mysql.com/doc/refman/8.0/en/union.html
As look through the MySQL source code, the normal union result order follow rules below:
+ the result order by sql-union-part order
+ in every part of the uion it follow order like the part sql it self(e.g. order by explicit rule or primary key order)

**Comment by sunsun314** [comment]
As a result, the dble do not need to change to fit the MySQL phenomenon

**Comment by FlyingMao** [comment]
close reason: The basic reason is the difference between different versions of MySQL
