### ISSUE TITLE
For no-sharding table, got error while executing sql "show columns in test1"

### ISSUE THREAD

**Issue by wjl1619** [actiontech/dble#958]
* **dble version：**  
5.6.29-dble-9.9.9.9-21e353f171b56ddd0397c334849938deb8f71f30-20190122041603
* **preconditions ：**  
no
* **steps：**    
    step1.  execute the sqls
```sql
create table test1 (ID int(11),R_REGIONKEY int(11) primary key,R_NAME varchar(50),R_COMMENT varchar(50));
show columns in test1;
```
* **expect result：**  
    1.show correct columns for test1 
* **real result：**  
    1.got error: ERROR 1064 (HY000): java.sql.SQLSyntaxErrorException: syntax error, error in :'umns in test1 from schema1', expect IN, actual IN pos 15, line 1, column 13, token IN

* **supplements：**  
    1.
![image](https://user-images.githubusercontent.com/44627441/51817829-6d7a8500-2307-11e9-908b-7d2afe6387b5.png)

/label ~BUG

**Comment by sunsun314** [comment]
https://actiontech.github.io/dble-docs-cn/3.SQL_Syntax/3.5_DAL/3.5.2_SHOW.html  
as the doc shows, the show COLUMNS  ***From*** is only allowed because of druid limit

**Comment by wjl1619** [comment]
verified on dble version: 5.6.29-dble-9.9.9.9-2c240dda40d1ed03c20d5c8415c5916c88f53491-20190215032215
