### ISSUE TITLE
for no-sharding table, got wrong result while executing sql "SELECT CURRENT_USER() union select id from  test1"

### ISSUE THREAD

**Issue by wjl1619** [actiontech/dble#960]
* **dble version：**  
5.6.29-dble-9.9.9.9-21e353f171b56ddd0397c334849938deb8f71f30-20190122041603
* **preconditions ：** 
create table named test1: 
```sql
drop table if exists  test1;
CREATE TABLE  test1(`id` int(10) unsigned NOT NULL,`k` int(10) unsigned NOT NULL DEFAULT '0',`c` char(120),`pad` int(11) NOT NULL,PRIMARY KEY (`id`),UNIQUE KEY (`k`))DEFAULT CHARSET=UTF8;
insert into  test1 values(1,1,'id1',1),(2,2,'id2',2),(3,3,'id3',3),(4,4,'id4',4),(5,5,'id5',1),(6,6,'id6',2),(7,7,'id7',3),(8,8,'$id8$',4),(9,9,'test',3),(10,10,'中',3),(11,11,'i_',4),(12,12,'_g',5),(13,13,'y_u',6),(14,14,'20%',14),(15,15,'a_1',15),(16,16,16,-1),(0,0,0,0),(17,17,'new*\n*line',17),(18,18,'a',18);
```
* **configs：** 

**schema.xml**  

```xml
	<schema name="schema1" sqlMaxLimit="100" dataNode="dn5">
	</schema>
        <dataNode name="dn5" dataHost="172.100.9.5" database="db3" />
        <dataHost name="172.100.9.5" maxCon="1000" minCon="10" balance="0" switchType="1"  slaveThreshold="100">
		<heartbeat>select user()</heartbeat>
		<writeHost host="hostM1" url="172.100.9.5:3306" user="test1"
				   password="111111">
		</writeHost>
	</dataHost>
```

**server.xml**  

```xml
<user name="test1">
		<property name="password">111111</property>
		<property name="schemas">schema1,schema2,schema3</property>
	</user>
```

* **steps：**    
    step1.  SELECT CURRENT_USER() union select id from  test1
* **expect result：**  
    1.show with correct resultset
* **real result：**  
    1.
![image](https://user-images.githubusercontent.com/44627441/51824421-27c8b700-231d-11e9-9056-98a7e1b9ec13.png)
There are two issues here:
1.the column name should be CURRENT_USER() rather than USER()，so maybe dble execte with "select USER()" instead of "select CURRENT_USER()" here.
2.dble only return the result of "SELECT USER()" but not union the resultset from "select id from  test1"

* **supplements：**  
1.Exeute the sql :
```sql
(SELECT CURRENT_USER()) ;
```
The result is:
![image](https://user-images.githubusercontent.com/44627441/51825443-bcccaf80-231f-11e9-9d06-ae4d983d8334.png)
Expect result here should be 'test1@XXX' but not 'test@XXX'

2.For sql "SELECT DATABASE() union select id from  test1;", we got the similar issues.
    

/label ~BUG
located in auto_test: dble/features/sql_cover/special/sql_nosharding.feature,, dble/sqls/sqls_util/syntax/union.sql (line 278,280)

**Comment by sunsun314** [comment]
The issue can be divided into two parts  
i.  user() and current_user() should has some difference  
ii. function like user() version() should can be use in complex query ,such as union or other case  
So the case should be verified with both feature

**Comment by wjl1619** [comment]
verified on version: 5.6.29-dble-9.9.9.9-a5727fff47f373bed0d4ae67eedf1063261f5570-20190724064350
