### ISSUE TITLE
query with 2 "in subquery" with global table may get error "ERROR 4004 (42S22): column autoalias_tt.autoalias_scalar not found"

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#961]
* **dble version：**  
5.6.29-dble-9.9.9.9-f2ee68f267caf5c53371cb68de2068998b363b72-20190128080033
* **preconditions ：**  
table tt is a table in schema's default node
* **configs：** 

**schema.xml**  

```
                <table dataNode="dn1,dn2,dn3,dn4" name="test" type="global" />
```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  execute queries with dble:
```
mysql> create table tt(id int);
Query OK, 0 rows affected (0.01 sec)

mysql> insert into tt values(1),(2),(3),(4);
Query OK, 4 rows affected (0.00 sec)

mysql> create table test(id int, k int);                       
Query OK, 0 rows affected (0.08 sec)

mysql> insert into test values(1,1),(2,2),(3,3),(null,null);
Query OK, 4 rows affected (0.02 sec)
```
step2.execute queries with dble:
```
mysql> select * from test where k=1 and k in (select id from tt) and id in (select id from tt);
ERROR 4004 (42S22): column autoalias_tt.autoalias_scalar not found
```

* **expect result：**  
    1.step2 query success
* **real result：**  
    1.step2 query got error
* **supplements：**  
    1.sharding table has no such problem

/label ~BUG

**Comment by yexiaoli88** [comment]
verified on dble version: 5.6.29-dble-9.9.9.9-b83955577d2f5f3555ac6f1254e9c5edb69cefb4-20190129042006

**Comment by yexiaoli88** [comment]
auto_test position: sql/sqls_mixed/select/join_global_sharding.sql
