### ISSUE TITLE
For global table, in select ...where... syntax, now not support "schema.table.column" in where clause 

### ISSUE THREAD

**Issue by wjl1619** [actiontech/dble#964]
* **dble version：**  
5.6.29-dble-9.9.9.9-b83955577d2f5f3555ac6f1254e9c5edb69cefb4-20190129042006
* **preconditions ：**  
```sql
drop table if exists test1;
drop table if exists schema3.test3;
CREATE TABLE test1(`id` int(10) unsigned NOT NULL,`t_id` int(10) unsigned NOT NULL DEFAULT '0',`name` char(120) NOT NULL DEFAULT '',`pad` int(11) NOT NULL,PRIMARY KEY (`id`),KEY `k_1` (`t_id`))DEFAULT CHARSET=UTF8;
CREATE TABLE schema3.test3(`id` int(10) unsigned NOT NULL,`m_id` int(10) unsigned NOT NULL DEFAULT '0',`name` char(120) NOT NULL DEFAULT '',`pad` int(11) NOT NULL,PRIMARY KEY (`id`),KEY `k_1` (`m_id`))DEFAULT CHARSET=UTF8;
```
* **configs：** 

**schema.xml**  

```xml
<schema name="schema1" sqlMaxLimit="100">
		<table name="global_4_t1" dataNode="dn1,dn2,dn3,dn4" type="global" />
		<table name="test1" dataNode="dn1,dn2,dn3,dn4" type="global" />
	</schema>
<schema name="schema3" sqlMaxLimit="100" dataNode="dn5">
		<table name="test3" dataNode="dn1,dn2,dn3,dn4" type="global" />
	</schema>
```

**server.xml**  

```xml
<user name="test">
		<property name="password">111111</property>
		<property name="schemas">schema1,schema2,schema3</property>
	</user>
```

* **steps：**    
    step1.  execute the sql:
```sql
select schema3.test3.id,schema3.test3.pad from test1 join schema3.test3 where test1.pad=schema3.test3.pad;
```
* **expect result：**  
    1.execute correctly and return right result
* **real result：**  
mysql> select schema3.test3.id,schema3.test3.pad from test1 join schema3.test3 where test1.pad=schema3.test3.pad;
ERROR 1003 (HY000): Unknown column 'schema3.test3.pad' in 'where clause'
mysql> explain select schema3.test3.id,schema3.test3.pad from test1 join schema3.test3 where test1.pad=schema3.test3.pad;
+-----------+----------+---------------------------------------------------------------------------------------------------+
| DATA_NODE | TYPE     | SQL/REF                                                                                           |
+-----------+----------+---------------------------------------------------------------------------------------------------+
| dn1_0     | BASE SQL | select `test3`.`id`,`test3`.`pad` from  `test1` join  `test3` where test1.pad = schema3.test3.pad |
| merge_1   | MERGE    | dn1_0                                                                                             |
+-----------+----------+---------------------------------------------------------------------------------------------------+

* **supplements：**  
    1.

/label ~BUG
located in auto_test: dble/features/sql_cover/special/sql_global.feature,  dble/sqls/special_global/select/join.sql (line 17)

**Comment by FlyingMao** [comment]
#965

**Comment by wjl1619** [comment]
verified on version:  5.6.29-dble-9.9.9.9-2c240dda40d1ed03c20d5c8415c5916c88f53491-20190215032215
