### ISSUE TITLE
Error when `create table BIT_XOR (i int)`

### ISSUE THREAD

**Issue by FlyingMao** [actiontech/dble#972]
* **dble version：**  
5.6.29-dble-9.9.9.9-f2ee68f267caf5c53371cb68de2068998b363b72-20190128080033
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  
```
create table BIT_XOR (i int);
```
* **expect result：**  
    1.
```
mysql> create table BIT_XOR (i int);
Query OK, 0 rows affected (0.00 sec)
```
* **real result：**  
    1.
```
mysql> create table BIT_XOR (i int);                                                                                                                
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'BIT_XOR (i int)' at line 1

```
* **supplements：**  
    1. dble explain result:
```
mysql> explain create table BIT_XOR (i int);
+-----------+----------+------------------------------+
| DATA_NODE | TYPE     | SQL/REF                      |
+-----------+----------+------------------------------+
| dn5       | BASE SQL | create table BIT_XOR (i int) |
+-----------+----------+------------------------------+
1 row in set (0.00 sec)
```
**for tester:**
in auto_test:dble/sqls/sqls_mixed/syntax/identifiers.sql(line:55)
/label ~BUG

**Comment by yanhuqing666** [comment]
when SQL_MODE contains 'IGNORE_SPACE',mysql will report  SQL syntax problem

**Comment by yanhuqing666** [comment]
https://github.com/actiontech/dble-docs-cn/blob/master/4.Protocol/4.2_Connecting.md
