### ISSUE TITLE
For no-sharding table, got incorrect result while executing " select id,data from test1 where id is null;" after executing "set @@sql_auto_is_null=on;" in one session

### ISSUE THREAD

**Issue by wjl1619** [actiontech/dble#978]
* **dble version：**  
5.6.29-dble-9.9.9.9-b83955577d2f5f3555ac6f1254e9c5edb69cefb4-20190129042006
* **preconditions ：**  
```sql
drop table if exists test1;
create table test1(id int primary key auto_increment,data varchar(10));
insert into test1 (data) values ('aaa');
set @@sql_auto_is_null=on;
select @@sql_auto_is_null;
insert into test1 (data) values ('bbb');
```
* **configs：** 

**schema.xml**  

```xml
	<schema name="schema1" sqlMaxLimit="100" dataNode="dn5">
	</schema>
        <dataHost name="172.100.9.5" maxCon="1000" minCon="10" balance="0" switchType="1"  slaveThreshold="100">
		<heartbeat>select user()</heartbeat>
		<writeHost host="hostM1" url="172.100.9.5:3306" user="test"
				   password="111111">
		</writeHost>
	</dataHost>
```

* **steps：**    
    step1.  
```sql
select id,data from test1 where id is null;
```
* **expect result：**  
    1.
mysql> select id,data from test1 where id is null;
+----+------+
| id | data |
+----+------+
|  2 | bbb  |
+----+------+
1 row in set (0.00 sec)

* **real result：**  
    1.
mysql> select id,data from test1 where id is null;
Empty set (0.00 sec)
* **supplements：**  
    1.general_log for dn5:
2019-01-31T10:11:32.514233Z 2630 Query  set @@sql_auto_is_null=on
2019-01-31T10:11:40.845521Z 2627 Query  select user()
2019-01-31T10:11:41.234792Z 2632 Query  select @@sql_auto_is_null
2019-01-31T10:11:48.118019Z 2635 Query  insert into test1 (data) values ('bbb')
2019-01-31T10:11:50.845420Z 2627 Query  select user()
2019-01-31T10:11:54.516670Z 2629 Query  select id,data from test1 where id is null
2019-01-31T10:12:00.845470Z 2627 Query  select user()

/label ~BUG
located in auto_test: dble/features/sql_cover/special/sql_nosharding.feature, dble/sqls/sqls_util/syntax/set_server_var_util.sql (line 26)

**Comment by yanhuqing666** [comment]
https://github.com/actiontech/dble-docs-cn/blob/master/5.Limit/5.2_other_limit.md

**Comment by FlyingMao** [comment]
**verified version:** dble-2.19.01.0-303221e9e77e00d7741629e15f8053e4fa196de3-20190228085303
