### ISSUE TITLE
`CREATE TABLE` statement with `PARTITION` clause raise an error when logic table doesn't exists

### ISSUE THREAD

**Issue by tankilo** [actiontech/dble#983]
https://actiontech.github.io/dble-docs-cn/3.SQL_Syntax/3.1_DDL/3.1.1_DDL&Table_Syntax.html 看到ddl语法

```
mysql> create table customer_test(customer_id int (11),name varchar (60),province varchar (60),age Decimal (21),register_date date) PARTITION by hash(customer_id) PARTITIONS 4;
ERROR 1146 (42S02): Table 'testdb.customer_test' doesn't exist in the config of schema
```

应该DDL去schema和物理分库增加这个表的，但是现在反而报没有。

**Comment by sunsun314** [comment]
check your schema.xml config file & read the config doc with patient  
I guess the problem is you did not define this table in config file

**Comment by tankilo** [comment]
> check your schema.xml config file & read the config doc with patient
> I guess the problem is you did not define this table in config file

Thanks for your reply. But what I mean to say is that if i use `CREATE TABLE` statement with `PARTITION` clause,  obviously I know there is no related `table` tags in  schema.xml and I want dble to create that logic table for me, such like creating table tag in schemal.xml with the information i provide in the CREATE TABLE sql.

The current logic of the code  is only suitable for  `CREATE TABLE` statement **without** `PARTITION` clause, which means logic table exists but there are no physical tables on partions . In this situation, DBLE will route the sql to all the partions of the logic table.

**Comment by sunsun314** [comment]
Well,DDL doc may be little confusing.  
The `PARTITION` in `create table syntax` means you can create physical tables with `PARTITION` optimization.  
This feature is the solution of the request "Split table in single dataNode"(Which referred to by users many times in the community) .
And the feature  you mention may be implement in the future(obviously in other way).
We would not implement this functionality using standard SQL syntax to avoid misunderstanding in use.

**Comment by tankilo** [comment]
Understood! Thanks~
