### ISSUE TITLE
Add version attribute in rule/schema/server.xml to help to identify config version

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#986]
Well,when the dble-server be upgraded in some customer's environment ，there may be some errors occur because the config attribute has changed when the dble version changes.  They may confused about what version the config file is and how to change to latest version config.   
So we decide to add a version  attribute in rule/schema/server.xml to help the user to identify the config version.DBLE would not stop user use outdated config ,only notify user with warning logs and dryrun results

**Comment by wjl1619** [comment]
verified on dble version: 5.6.29-dble-9.9.9.9-e3b87339fe8b0d59538c27c01771ded840355091-20190220091638
