### ISSUE TITLE
For global table, the isolation level REPEATABLE READ not work fine

### ISSUE THREAD

**Issue by wjl1619** [actiontech/dble#989]
* **dble version：**  
5.6.29-dble-9.9.9.9-b83955577d2f5f3555ac6f1254e9c5edb69cefb4-20190129042006
* **preconditions ：**  
```sql
drop table if exists test1;
CREATE TABLE test1(`id` int(10) unsigned NOT NULL,`k` int(10) unsigned NOT NULL DEFAULT '0',`c` char(120) NOT NULL DEFAULT '',`pad` int(11) NOT NULL,PRIMARY KEY (`id`),UNIQUE KEY (`k`));
```
* **configs：** 

**schema.xml**  

```xml
	<schema name="schema1" sqlMaxLimit="100">
		<table name="test1" dataNode="dn1,dn2,dn3,dn4" type="global" />
	</schema>
```
* **steps：**    
    step1.  execute the following sqls in two different sessions:
```sql
#*******************REPEATABLE READ****单节点****commit*********************
#!share_conn_1
SET @@session.autocommit = ON;
delete from test1;
set session transaction isolation level REPEATABLE READ;
begin;
select * from test1;
#!share_conn_2
SET @@session.autocommit = ON;
set session transaction isolation level REPEATABLE READ;
begin;
insert into test1 values(1,1,1,1);
select * from test1;
#!share_conn_1
select * from test1;
#!share_conn_2;
commit;
#!share_conn_1
select * from test1;
```

* **expect result：**  
mysql> select * from test1;
Empty set (0.00 sec)

* **real result：**  
mysql> select * from test1;
+----+---+---+-----+---------------+
| id | k | c | pad | _dble_op_time |
+----+---+---+-----+---------------+
|  1 | 1 | 1 |   1 | 1550114903755 |
+----+---+---+-----+---------------+
1 row in set (0.00 sec)

* **supplements：**  
    1.

/label ~BUG
located in auto_test: dble/features/sql_cover/special/sql_global.feature, dble/sqls/sqls_util/transaction/trx_isolation.sql (line 22)

**Comment by wjl1619** [comment]
not work fine for line 136 in file dble/sqls/sqls_util/transaction/trx_isolation.sql

**Comment by yanhuqing666** [comment]
> not work fine for line 136 in file dble/sqls/sqls_util/transaction/trx_isolation.sql

fixed

**Comment by wjl1619** [comment]
verified on dble version: 5.6.29-dble-9.9.9.9-2c240dda40d1ed03c20d5c8415c5916c88f53491-20190215032215
