### ISSUE TITLE
use incorrect decoder to decode non-ASCII sharding column for utf8mb4 before routing

### ISSUE THREAD

**Issue by Lordess** [actiontech/dble#995]
* **dble version：**
2.18.12.0 and earlier

* **preconditions ：**
1. shards by a column which has non-ASCII characters (such as Chinese characters etc.)
2. character_set_client is utf8mb4 ( and utf8 with Oracle's MySQL J connector 5.1.13 and later when you set )

* **configs：** 

**schema.xml**

```
<schema name="testdb">
    <table name="sharding_table" rule="hash-by-carNum" dataNodes="dn1,dn2" />
</schema>
```

**rule.xml**

```
<tableRule name="hash-by-carNum" >
    <rule>
        <columns>carNum</columns>
        <algorithms>hash-into-two</algorithm>
    </rule>
</tableRule>

<function name="hash-into-two" class="Hash">
    <property name="partitionCount">2</property>
    <property name="partitionLength">512</property>
</function>
```

**server.xml**

```
<system>
    <!- 
          This setting will make Oracle's MySQL J connector(5.1.13 and later) send "SET NAMES utf8mb4" 
          to dble, even "characterEncoding=utf8" in the connection string.
     ->
    <property name="charset">utf8mb4</property>
</system>
```

* **steps：**
   step1. Execute following commands in Bash
``` sh
export LC_CTYPE=zh_CN.utf8
sql="EXPLAIN INSERT INTO sharding_table(carNum) VALUES ('京A00000')\G"
```
   step2. Execute following commands in Bash and remember its 'DATA_NODE' value( which data node would the SQL be sent to )
``` sh
mysql -h $dble_ip -P 8066 -u $dble_user -p $dble_pass  -e "$sql" \
--default-character-set=utf8 \
testdb
```
   step3. Execute following commands in Bash and remember its 'DATA_NODE' value( which data node would the SQL be sent to )
``` sh
mysql -h $dble_ip -P 8066 -u $dble_user -p $dble_pass  -e "$sql" \
--default-character-set=utf8mb4 \
testdb
```
   step4. Compare 'DATA_NODE' from step2 and step3.
* **expect result：**
    1. 'DATA_NODE's are same.
* **real result：**
    1. 'DATA_NODE' is different to each other.
* **supplements：**
    1. If you write a JDBC with Oracle's MySQL connector mentioned above, whether you set characterEncoding "utf8" or "utf8mb4" in the connection string, you will always get the same 'DATA_NODE' from step3.

/label ~BUG

**Comment by Lordess** [comment]
* **analysis：**
    The map CHARSET_TO_JAVA from src/main/java/io/dble/backend/mysql/CharsetUtil.java has incorrectly set the mapping between MySQL's utf8mb4 character set and Java's MacCentralEurope character set.
``` java
CHARSET_TO_JAVA.put("utf8mb4", "MacCentralEurope");
```

**Comment by yexiaoli88** [comment]
verified on version: 5.6.29-dble-2.18.12.0-9fdecff1efb443a4dbdcd1f642be1141431965ea-20190108042852

**Comment by yanhuqing666** [comment]
1.If you use a string column as sharding column and client use utf8mb4,you must need re-sharding data.
2. For JDBC 5.1.47 ,8.0.13 or later version ,Jdbc will change utf8 to utf8mb4, so if you use them, you also need to re-sharding data.
see mysql docs https://dev.mysql.com/doc/relnotes/connector-j/5.1/en/news-5-1-47.html

**Comment by yexiaoli88** [comment]
auto_test postion: features/func_test/cfg_test/charset.feature  Scenario#2
